PAIRS = [
("Kumar is a critic who wrote about suicide, that is, about a serious social problem.", "कुमार आलोचक है जिसने आत्महत्या अर्थात् एक गंभीर सामाजिक समस्या के बारे में लिखा।"),
("Users were angry because the sponsored programme was shown to them.", "उपयोगकर्ताओं को गुस्सा आया क्योंकि प्रायोजित कार्यक्रम उन्हें दिखाया गया।"),
("These people said that the politician was passing through the city.", "इन्होंने कहा कि राजनीतिज्ञ शहर से गुजरता हुआ आया था।"),
("After the rocket launch, the team reached the control room.", "रॉकेट प्रक्षेपण के बाद टीम नियंत्रण कक्ष में पहुंची।"),
("The publications honoured the runner-up of the competition.", "प्रकाशनों ने प्रतियोगिता के उपविजेता का सम्मान किया।"),
("The continental climate has many special features, as the gods' stories also say.", "महाद्वीपीय जलवायु की कई विशेषताएँ हैं और देवताओं की कथाएँ भी यही कहती हैं।"),
("The submarine is a dynamic machine that reduces emissions.", "पनडुब्बी एक गतिशील मशीन है जो उत्सर्जन कम करती है।"),
("Human rights are an important topic in the points the lawyer raised.", "मानवाधिकार उन बिंदुओं में एक महत्वपूर्ण विषय है जो वकील ने उठाए।"),
("The federation sold its properties after the legislative debate.", "महासंघ ने विधायी बहस के बाद अपनी संपत्तियों को बेच दिया।"),
("His bowling is short-term luck, but his abortion-related views were decisive for the party.", "उसकी गेंदबाजी अल्पकालिक किस्मत है, पर गर्भपात पर उसके विचार पार्टी के लिए निर्णायक थे।"),
("The south-eastern holder of the title is a nationalist leader.", "दक्षिणपूर्वी क्षेत्र का धारक एक राष्ट्रवादी नेता है।"),
("His poems reflect the pain of society and have been approved.", "उसकी कविताओं में समाज का दर्द प्रतिबिंबित होता है और उन्हें अनुमोदित किया गया है।"),
("These creations of the legislature show an intellectual and theoretical depth.", "विधायिका की ये कृतियाँ बौद्धिक और सैद्धांतिक गहराई दिखाती हैं।"),
("The derivation of the word is explained in the dictionary's terminology.", "शब्द की व्युत्पत्ति शब्दावली की किताब में समझाई गई है।"),
("The fraud was found in statistical reports and the vertical chart.", "धोखाधड़ी सांख्यिकीय रिपोर्टों और ऊर्ध्वाधर चार्ट में पाई गई।"),
("She is studying postgraduate courses, and the regulation has changed for them.", "वह स्नातकोत्तर पाठ्यक्रम पढ़ रही है और उनके लिए विनियमन बदल गया है।"),
("Copies of the book were sent to a disabled student for continuity of study.", "किताब की प्रतियां विकलांग छात्र को पढ़ाई की निरंतरता के लिए भेजी गईं।"),
("His debut was a revival of old music, and it was rebuilt with care.", "उसका पदार्पण पुराने संगीत का पुनरुद्धार था और इसे पुनर्निर्मित किया गया।"),
("There is a variation in the front part of the building, as the criminal saw.", "इमारत के अग्रभाग में भिन्नता है, जैसा अपराधी ने देखा।"),
("Manufacturing and financing of the factory are both difficult tasks.", "कारखाने का विनिर्माण और वित्तपोषण दोनों कठिन काम हैं।"),
("The destructive coup showed that the rulers lacked excellence.", "विनाशकारी तख्तापलट ने दिखाया कि शासकों में उत्कृष्टता नहीं थी।"),
("The whole family read the reviews and discussed the ideology.", "पूरे कुटुंब ने समीक्षाएँ पढ़ीं और विचारधारा पर चर्चा की।"),
("An archipelago and an editorial were both in the newspaper today.", "आज अख़बार में द्वीपसमूह और संपादकीय दोनों थे।"),
("The telecom company has a virtual office, and the rule was absorbed there.", "दूरसंचार कंपनी का आभासी कार्यालय है, और वहाँ नियम अवशोषित हो गया।"),
("The resurrection of the old village and the synthesis of ideas surprised everyone.", "पुराने गाँव के पुनरुत्थान और विचारों के संश्लेषण ने सबको चौंका दिया।"),
("The acting head and the destroyer ship reached the port together.", "कार्यवाहक प्रमुख और विध्वंसक जहाज़ साथ बंदरगाह पहुंचे।"),
("The opposition party leader met the pregnant woman and asked about methods.", "विपक्षी दल के नेता ने गर्भवती महिला से मिलकर विधियों के बारे में पूछा।"),
("The functional model of the intermediate class got many presentations.", "कार्यात्मक मॉडल को मध्यवर्ती कक्षा की कई प्रस्तुतियों में दिखाया गया।"),
("He is committed to his work, and this commitment is clear to all.", "वह अपने काम के प्रति प्रतिबद्ध है और यह प्रतिबद्धता सबको साफ़ दिखती है।"),
("The designation and the manuscript were kept in the library.", "पदनाम और पांडुलिपि पुस्तकालय में रखे गए थे।"),
("The armoured vehicle was managed by his girlfriend's brother.", "बख्तरबंद गाड़ी को उसकी प्रेमिका का भाई प्रबंधित करता था।"),
("He gave justification for the infected area and immunity of the people.", "उसने संक्रमित इलाके के लिए औचित्य दिया और लोगों की प्रतिरक्षा के बारे में बताया।"),
("Every entry is boxing news, and boxing is popular in this state.", "हर प्रविष्टि मुक्केबाजी की खबर है और मुक्केबाजी इस राज्य में लोकप्रिय है।"),
("An interstate road and the great queen's monarchy are in the book.", "अंतरराज्यीय सड़क और महारानी की राजशाही उस किताब में हैं।"),
("Archaeology is her subject, and she was awarded for her work.", "पुरातत्व उसका विषय है और उसे अपने काम के लिए पुरस्कृत किया गया।"),
("These creations were praised, and after deliberation they received approval.", "इन कृतियों की प्रशंसा हुई और विचारविमर्श के बाद उन्हें अनुमोदन मिल गया।"),
("The armoury was full, and the bowler stood near the arsenal.", "शस्त्रागार भरा हुआ था और गेंदबाज उसके पास खड़ा था।"),
("The aligned plans and the new investigation were configured by the engineer.", "इंजीनियर ने संरेखित योजनाओं और अन्वेषण का नया विन्यास तैयार किया।"),
("The task was executed, and posthumous honour was given to the soldier.", "काम निष्पादित किया गया और सैनिक को मरणोपरांत सम्मान दिया गया।"),
("There is mutual trust, and the administered region is peaceful.", "पारस्परिक विश्वास है और प्रशासित क्षेत्र शांत है।"),
("In the latter half of the film, the abuse of power is shown.", "फ़िल्म के उत्तरार्ध में सत्ता का दुर्व्यवहार दिखाया गया है।"),
("The utility of this product has increased among investors.", "इस उत्पाद की उपयोगिता निवेशकों के बीच बढ़ गई है।"),
("A by-election was held, and he ignored the advice of everyone.", "उपचुनाव हुआ और उसने सबकी सलाह को नजरअंदाज किया।"),
("He lives on the Mediterranean coast and studies the concentration of salt.", "वह भूमध्यसागरीय तट पर रहता है और नमक की सांद्रता का अध्ययन करता है।"),
("The scheduled meeting will be led by a lecturer.", "अनुसूचित बैठक का नेतृत्व एक व्याख्याता करेंगे।"),
("The demonstrators went to the police, and statistics show the crowd grew.", "प्रदर्शनकारियों ने पुलिस से बात की और सांख्यिकी बताती है कि भीड़ बढ़ गई।"),
("The hostage was freed, and the refined plan worked well.", "बंधक को छुड़ा लिया गया और परिष्कृत योजना अच्छी तरह चली।"),
("The speaker said that the thing said was removed from the list.", "वक्ता ने कही हुई बात को सूची से हटाई गई बताया।"),
("A leftist writer and the whole continent were part of the story.", "एक वामपंथी लेखक और पूरा महाद्वीप उस कहानी का हिस्सा थे।"),
("The theorem is regulated by a function, and the horizontal line is regulated too.", "प्रमेय एक फलन से बंधा है और क्षैतिज रेखा विनियमित भी है।"),
("Carbon is organic, and the warship is a big machine.", "यह कार्बनिक पदार्थ है और युद्धपोत एक बड़ी मशीन है।"),
("The feminist leader called for a boycott in the discussions.", "नारीवादी नेता ने चर्चाओं में बहिष्कार की अपील की।"),
("The correspondent spoke to the followers and the refugees.", "संवाददाता ने अनुयायियों और शरणार्थियों से बात की।"),
("The nineteenth-century unveiling of the statue was an incredible event.", "उन्नीसवीं सदी में मूर्ति का अनावरण एक अविश्वसनीय घटना थी।"),
("The crashed plane caused an objection to be raised, nominal though it was.", "दुर्घटनाग्रस्त विमान पर आपत्ति उठाई गई, हालाँकि वह नाममात्र थी।"),
("Please come along with them; the mercury was pushed away, so go.", "कृपया उनके समेत आइए; पारा धकेल दिया गया, अब जाएं।"),
("Pregnancy needs care, and acoustic music helps the mind.", "गर्भावस्था में देखभाल चाहिए और ध्वनिक संगीत मन को सुकून देता है।"),
("The politicians were adventurous, and their release was celebrated.", "राजनेताओं ने साहसिक कदम उठाया और उनकी रिहाई का जश्न मनाया गया।"),
("Lime is used in the architecture of the old temple.", "पुराने मंदिर के वास्तुशिल्प में चूना इस्तेमाल हुआ है।"),
("Fungus grew on the illustrated book, and the sister on the left was sad.", "सचित्र किताब पर कवक उग गया और बाई ओर बैठी बहन उदास थी।"),
("The intoxicating drink is harmful, and he joins the pieces carefully.", "नशीली चीज़ हानिकारक है और वह टुकड़ों को सावधानी से जोड़ते हैं।"),
("The irregular work and the stuck car made him feel hopeless.", "अनियमित काम और फंस गई गाड़ी से वह निराश हो गया।"),
("Concepts are explained here, and poems are also included in the poetry book.", "यहाँ अवधारणाओं को समझाया गया है और कविताएँ भी इसमें शामिल हैं।"),
("The disappointing result of the telephone meeting was disputed.", "दूरभाष बैठक का निराशाजनक नतीजा विवादित था।"),
("He explained with accuracy how metabolism works.", "उसने सटीकता से समझाया कि चयापचय कैसे काम करता है।"),
("The intrusion by the veteran player shocked the famous team's mechanics.", "दिग्गज खिलाड़ी की घुसपैठ से यांत्रिकी पर काम करने वाली टीम हैरान रह गई।"),
("The plant grew well, and its follower called it notorious.", "पादप अच्छी तरह उगा और उसके अनुयायी ने उसे कुख्यात कहा।"),
("Give an explanation, because you are under the influence of intoxication, he said, and increase the work.", "वह बोला, स्पष्टीकरण दो, क्योंकि तुम नशे में हो, और बढ़ाना काम को।"),
("The establishment has rivalry and competition, so the guns were kept hidden.", "प्रतिष्ठान में प्रतिद्वंद्विता है, इसलिए बंदूकें छिपाकर रखी गईं।"),
("A naked statue and the availability of water were discussed.", "एक नग्न मूर्ति और पानी की उपलब्धता पर चर्चा हुई।"),
("Cognitive skills matter, and they play their roles well.", "संज्ञानात्मक कौशल मायने रखते हैं और वे अपनी भूमिका अच्छे से निभाते हैं।"),
("The star of the film and the printing press were both famous.", "फ़िल्म का सितारा और मुद्रण की मशीन दोनों मशहूर थे।"),
("The Lord forgave the sorrow, and the regret was great over the killings.", "प्रभु ने क्षमा किया, और हत्याओं पर खेद बहुत गहरा था।"),
("The playwright is a fanatic of prose, and the killers are arrested.", "नाटककार गद्य का कट्टर प्रेमी है और हत्यारे पकड़े गए।"),
("The geometry article was written by the late teacher.", "ज्यामिति का आलेख दिवंगत शिक्षक ने लिखा था।"),
("The communist front launched projects, and the acid was kept safe.", "साम्यवादी मोर्चा ने परियोजनाएं शुरू कीं और अम्ल सुरक्षित रखा गया।"),
("Repetition is needed in the best memoir, which is secular.", "बेहतरीन संस्मरण में पुनरावृत्ति की ज़रूरत है, जो धर्मनिरपेक्ष है।"),
("A molecule is tiny, and the indirect refugee help was displaced.", "अणु बहुत छोटा होता है और शरणार्थी की अप्रत्यक्ष मदद विस्थापित हो गई।"),
("The ammunition was displaced, and the certification took time.", "गोलाबारूद विस्थापित हो गया और प्रमाणन में समय लगा।"),
("Satire is a musical art, and this rectangular hall is large.", "व्यंग्य एक कला है, संगीतमय शाम चली और यह आयताकार हॉल बड़ा है।"),
("All the women writers praised the colony's triangular park.", "समस्त लेखिका ने उपनिवेश के त्रिकोणीय पार्क की प्रशंसा की।"),
("The magnitude of mutation is a five-member committee's subject.", "परिमाण और उत्परिवर्तन पांच सदस्यीय समिति का विषय है।"),
("The ballot was famous, and the delegation was received well.", "मतपत्र विख्यात था और प्रतिनिधिमंडल का स्वागत अच्छा हुआ।"),
("The alphabet is consistent, and one and a half hours were enough.", "वर्णमाला संगत है और डेढ़ घंटा काफ़ी था।"),
("Manipulation spoiled relations, and the replica was a gift.", "हेरफेर ने नाते बिगाड़ दिए और प्रतिकृति एक उपहार थी।"),
("His captaincy was praised at dawn when the nephew-in-law's sister was there.", "उसकी कप्तानी की तारीफ़ हुई, पौ फटते ही भांजी वहाँ थी।"),
("Squeezing the lemon, he put on a sock and watched the myna.", "निचोड़ना नींबू था, उसने मोज़ा पहना और मैना को देखा।"),
("Pushing the cart is hard; oh, the nameless man left.", "ठेलना गाड़ी कठिन है; ओह, अनाम आदमी चला गया।"),
]
