PAIRS = [
("Children's vaccination and regular health checkups are very important.", "बच्चों का टीकाकरण और सतत स्वास्थ्य जाँच बहुत महत्वपूर्ण है।"),
("The pages of the old book have many layers of dust.", "पुरानी किताब के पन्नों पर धूल की कई परतों जमी हैं।"),
("He started pulling the rope and dragging the heavy boxes.", "वह भारी बक्सों को खींचने और रस्सी खींचने लगा।"),
("Teachers say sexuality education should be given at the right age.", "शिक्षक मानने हैं कि कामुकता की शिक्षा सही उम्र में दी जानी चाहिए।"),
("The obsolete machine was removed and the thorns were cleared from the yard.", "अप्रचलित मशीन हटा दी गई और आँगन से कांटे साफ़ किए गए।"),
("A tower stands on the fort and the explorer is climbing it.", "किले पर बुर्ज खड़ा है और खोजकर्ता उस पर चढ़ रहा है।"),
("Dozens of graves are found near the old village.", "पुराने गाँव के पास दर्जनों कब्रों मिली हैं।"),
("He played his role well, but the company went bankrupt.", "उसने अपनी भूमिका अच्छी तरह निभाया, पर कंपनी दिवालिया हो गई।"),
("There was no place for burying them, so they chose another land.", "उन्हें दफनाने के लिए जगह नहीं थी, इसलिए दूसरी जमीन चुनी गई।"),
("Those moments of joy stay with us forever, said the ruling leader.", "सत्तारूढ़ नेता ने कहा कि क्षणों की खुशी हमेशा साथ रहती है।"),
("The magical foolish quartet entertained everyone at the fair.", "जादुई चौकड़ी ने मेले में सबका मनोरंजन किया, किसी मूर्ख की तरह नहीं।"),
("The retrospective exhibition showed lakes and mountains from earlier years.", "पूर्वव्यापी प्रदर्शनी में पुराने वर्षों की झीलें और पहाड़ दिखाए गए।"),
("The varieties of fruit differ, and the statements of leaders also differ.", "फलों की किस्मों अलग हैं और नेताओं के बयानों भी अलग हैं।"),
("The disintegrated empire became a worldwide topic of discussion.", "विघटित साम्राज्य विश्वव्यापी चर्चा का विषय बन गया।"),
("Write down the addresses and then watch a film.", "पते लिख लो और फिर एक चलचित्र देखो।"),
("The man from Bihar wrote a will for his property.", "बिहारी आदमी ने अपनी संपत्ति के लिए वसीयत लिखी।"),
("I want to order food and also avoid mumbling.", "मुझे खाना मंगवाना है और बड़बड़ाना भी बंद करना है।"),
("A cockroach and a moth were both flying in the kitchen.", "रसोई में तिलचट्टा और पतंगा दोनों घूम रहे थे।"),
("The young boy likes sniffing flowers and pushing the swing.", "तरुण लड़के को फूल सूँघना और झूला धकेलना पसंद है।"),
("Spreading seeds is easy; the constellation is visible tonight.", "बीज बिखेरना आसान है; आज रात तारामंडल साफ़ दिख रहा है।"),
("The monetary policy has a claimant, and the future is uncertain.", "मौद्रिक नीति पर एक दावेदार है और भावी स्थिति अनिश्चित है।"),
("The pills and the torso model are kept in the doctor's room.", "गोलियों और धड़ का मॉडल डॉक्टर के कमरे में रखे हैं।"),
("A vibration was felt, and the effectiveness of the plan was doubted.", "कंपन महसूस हुआ और योजना की प्रभावशीलता पर शक किया गया।"),
("There is healthy competition among the players on the Indian subcontinent.", "उपमहाद्वीप के खिलाड़ियों में स्वस्थ स्पर्धा है।"),
("Eternal truth is what she believes and also respects.", "शाश्वत सत्य वही है जिसे वह मानती है।"),
("There are many complications, and the boxer is training hard.", "जटिलताओं बहुत हैं और मुक्केबाज कड़ी मेहनत कर रहा है।"),
("Racism is wrong, and the subdistrict office is closed today.", "नस्लवाद गलत है और उपज़िला कार्यालय आज बंद है।"),
("The transformed town and the prophet's teachings are famous.", "रूपांतरित शहर और पैगंबर की शिक्षाएँ प्रसिद्ध हैं।"),
("The destruction caused great excitement and anger among the people.", "विध्वंस से लोगों में बड़ी उत्तेजना और गुस्सा फैल गया।"),
("The waterfalls are beautiful, and she reaches home late in the evening.", "झरनों बहुत सुंदर हैं और वह शाम को देर से घर पहुंचती है।"),
("Follow the instructions, because socialism is the topic of today's lecture.", "निर्देशों का पालन करो, क्योंकि आज का विषय समाजवाद है।"),
("He sends a letter and keeps the tradition alive.", "वह चिट्ठी भेजता है और परम्परा को जीवित रखता है।"),
("The previous chapter lacked clarity and the vagueness confused everyone.", "पिछला अध्याय स्पष्ट नहीं था और अस्पष्टता ने सबको उलझा दिया।"),
("The mediator spoke with the daughter of the family.", "मध्यस्थ ने परिवार की पुत्री से बात की।"),
("The donor was excited and the soldier was also excited.", "दाता उत्तेजित था और सेनानी भी बहुत खुश था।"),
("The freedom fighter lived in the rooms of the old fort.", "सेनानी पुराने किले के कक्षों में रहता था।"),
("A bacterium causes disease, and the director general warned the public.", "जीवाणु बीमारी फैलाता है, ऐसा महानिदेशक ने जनता को चेताया।"),
("The junior officer sang a song, and the song was loved.", "कनिष्ठ अधिकारी ने गान गाया और सबको पसंद आया।"),
("Bankruptcy hurt the business, and blood circulation matters for health.", "दिवालियापन से व्यापार को चोट लगी और परिसंचरण स्वास्थ्य के लिए जरूरी है।"),
("Throw the garbage in the bin; this is a logical rule.", "कचरे को डिब्बे में डालो; यह एक तार्किक नियम है।"),
("The tribunal gave a verdict, and the propagandist protested.", "न्यायाधिकरण ने फैसला सुनाया और प्रचारक ने विरोध किया।"),
("The beautiful atmosphere of the hills changes the weather.", "पहाड़ों का खूबसूरत वायुमंडल मौसम बदल देता है।"),
("There was a deviation in the route, so catching the thief was hard.", "रास्ते में विचलन था, इसलिए चोर को पकड़ना कठिन था।"),
("Since it rained, he made a strike on the paper and left.", "चूँकि बारिश हुई, इसलिए उसने कागज़ पर प्रहार किया और चला गया।"),
("What was said in the meeting about the wells was clear.", "बैठक में जो कहे गए, कुओं के बारे में स्पष्ट थे।"),
("He cut the wood with a saw, and the work is illegal.", "उसने आरा से लकड़ी काटी, पर यह काम गैरकानूनी है।"),
("Terrestrial animals live on land, and Kumari is their guide.", "स्थलीय जीव जमीन पर रहते हैं और कुमारी उनकी मार्गदर्शक है।"),
("Contributors and the astrology teacher came to the event.", "योगदानकर्ता और ज्योतिष के शिक्षक कार्यक्रम में आए।"),
("The dissatisfied workers asked for communism in a meeting.", "असंतुष्ट मज़दूरों ने सभा में साम्यवाद की चर्चा की।"),
("Accordingly, the tragedy shook the entire country.", "तदनुसार, इस त्रासदी ने पूरे देश को हिला दिया।"),
("Numerical data and the marginal profit were discussed.", "संख्यात्मक आँकड़ों और सीमांत लाभ पर चर्चा हुई।"),
("There is a hole in the wall, and an asteroid is far away.", "दीवार में छिद्र है और क्षुद्रग्रह बहुत दूर है।"),
("The councillors removed the names and the inflation worried them.", "पार्षदों ने नाम हटाए और मुद्रास्फीति ने उन्हें चिंतित किया।"),
("The prosecutor said the imagined story is not evidence.", "अभियोजक ने कहा कि कल्पित कहानी सबूत नहीं है।"),
("The legislature met on Friday, and Venus shone brightly.", "विधानमंडल की बैठक शुक्रवार को हुई और शुक्र ग्रह चमक रहा था।"),
("The warrior held a spear and won many titles.", "योद्धा ने भाला पकड़ा और कई खिताबों को जीता।"),
("Architects made copies of the plans on the lower floor.", "वास्तुकारों ने निचला मंज़िल पर योजनाओं की प्रतियाँ बनाईं।"),
("Algae grow in ponds, and your kindness is a favour.", "शैवाल तालाबों में उगते हैं और आपका अनुग्रह एक एहसान है।"),
("Data retrieval is easy, but the shop is expensive.", "पुनर्प्राप्ति आसान है, पर यह दुकान महंगा सामान बेचती है।"),
("Encoded messages were sent after the expulsion of the officer.", "कूटबद्ध संदेश अधिकारी के निष्कासन के बाद भेजे गए।"),
("Removing the stain is hard; speak in local dialects instead.", "दाग हटाना कठिन है; बोलियों में बात करो।"),
("Humanities students found an old coin.", "मानविकी के छात्रों को एक पुराना सिक्का मिला।"),
("The complaints and the innings of the match were discussed.", "शिकायतों और मैच की पारियों पर चर्चा हुई।"),
("The biennial fair brings castes together as communities.", "द्विवार्षिक मेला विभिन्न जातियाँ को एक साथ लाता है।"),
("Perform your duty and keep a pure heart.", "अपना कर्तव्य निभा और विशुद्ध मन रखो।"),
("Democrats worked on surfaces and the manuscripts in the library.", "लोकतंत्रवादियों ने पुस्तकालय में सतहों और पांडुलिपियों पर काम किया।"),
("The crafted story needs some adjustment and a plural form.", "गढ़ा हुआ किस्सा समायोजन और बहुवचन रूप माँगता है।"),
("Publishers signed contracts, but the town was ruined.", "प्रकाशकों ने अनुबंधों पर हस्ताक्षर किए, पर शहर तबाह हो गया।"),
("The surface of the lake shows toxicity from chemicals.", "झील की पृष्ठीय परत में रसायनों की विषाक्तता दिखती है।"),
("The gymnasium and the livestock farm are near the road.", "व्यायामशाला और पशुधन का बाड़ा सड़क के पास हैं।"),
("The shapes are magnetic, and the council approved them.", "आकृतियों चुम्बकीय हैं और परिषद् ने उन्हें मंजूरी दी।"),
("The unanimous decision cleaned the spots and stains.", "सर्वसम्मत फैसले से धब्बे साफ़ किए गए।"),
("I had a dream that I paid the coefficient fee.", "मैंने स्वप्न देखा कि मैंने गुणांक का शुल्क अदा किया।"),
("The synagogue is bright with light and a patch of green.", "आराधनालय आलोक से भरा है और वहाँ हरा पैच है।"),
("Be aware that the facing direction is oriented to the east.", "अवगत रहो कि यह उन्मुख दिशा पूर्व की ओर है।"),
("The spheres and the nucleus were drawn in the book.", "गोलों और नाभिक के चित्र किताब में बनाए गए।"),
("The teacher appreciated the creation, and she praised it.", "शिक्षक ने सृष्टि की सराहा और उसकी प्रशंसा की।"),
("A vegetarian friend ate two and a half rotis.", "शाकाहारी दोस्त ने ढाई रोटियाँ खाईं।"),
("The mountainous region benefited from the new road.", "पर्वतीय क्षेत्र नई सड़क से लाभान्वित हुआ।"),
("Volcanic craters are pits that are reasonable to study.", "ज्वालामुखीय गड्ढों का अध्ययन तर्कसंगत है।"),
("Read the bats' story, and absorption was explained.", "बल्ले की कहानी पढ़ें और अवशोषण समझाया गया।"),
("The accused was acquitted, and the intersection was closed.", "आरोपी बरी हो गया और प्रतिच्छेदन बंद था।"),
("An evolutionist showed a scenic view and gave a kick to the ball.", "विकासवादी ने दर्शनीय दृश्य दिखाया और गेंद को लात मारी।"),
("Linguistics studies language, and the arms of the wrestler were strong.", "भाषाविज्ञान भाषा का अध्ययन करता है, और बाहों में ताकत थी।"),
("Integrity is important, and the fifth challenge is tough.", "अखंडता महत्वपूर्ण है और पाँचवाँ चुनौतीपूर्ण है।"),
("The warships and hydropower projects were shown on television.", "युद्धपोतों और पनबिजली परियोजनाओं को टीवी पर दिखाया गया।"),
("She knows that the rumour is baseless; actually it is false.", "वह जानती है कि अफवाह निराधार है, वस्तुत झूठी है।"),
("A suffix is added to words, and the corpses were found.", "प्रत्यय शब्दों में जुड़ता है; शवों की पहचान हुई।"),
("Corporations and collections were examined by the committee.", "समिति ने निगमों और संग्रहों की जाँच की।"),
("The hostile attitude and the bound prisoners worried us.", "शत्रुतापूर्ण रवैये और बंधे कैदियों ने हमें चिंतित किया।"),
("Disorders in riders and the supply of ration are being treated.", "विकारों का इलाज चल रहा है, सवारों को रसद मिल रही है।"),
("He collided with the wall, and the promoter created an uproar.", "वह दीवार से टकरा गया और प्रवर्तक ने हंगामा किया।"),
("Their dominance ended, and where is the group now?", "उनका वर्चस्व खत्म हुआ; अब मंडली कहां है?"),
("Immutable laws and responsibilities must be respected.", "अपरिवर्तनीय नियमों और जिम्मेदारियों का सम्मान करना चाहिए।"),
("The infamous shop is economical, but I have a fear.", "बदनाम दुकान किफायती है, पर मुझे आशंका है।"),
("The chapters were read, and a push started the grand launch.", "अध्यायों को पढ़ा गया और धक्का देकर शुभारंभ हुआ।"),
("The radius of the circle and the lists are on the board.", "त्रिज्या और सूचियों बोर्ड पर लिखी हैं।"),
("The empowered women laughed at the foolish argument.", "सशक्त महिलाओं ने मूर्खतापूर्ण बहस पर हँसी उड़ाई।"),
("Algebra is hard, and the Marxist's paradox puzzled him.", "बीजगणित कठिन है और मार्क्सवादी के विरोधाभास ने उसे उलझाया।"),
("A rightist leader and an editor discussed the distortion.", "दक्षिणपंथी नेता और संपादकों ने विकृति पर बात की।"),
("Institutions and herbs are featured in this exhibition.", "इस प्रदर्शनी में प्रतिष्ठानों और जड़ीबूटियों को दिखाया गया।"),
("Accounting classes and a doll are in the shop.", "लेखांकन की कक्षाएँ और गुड़िया दुकान में हैं।"),
("International talks need understanding and redevelopment plans.", "अन्तरराष्ट्रीय वार्ता में जानना और पुनर्विकास योजनाएँ जरूरी हैं।"),
("Fusion and vowels are topics in the science and language class.", "संलयन और स्वरों पर विज्ञान और भाषा की कक्षा में बात हुई।"),
("The begum was projected as a leader, and estimates changed.", "बेगम प्रक्षेपित नेता थीं और अनुमानों में बदलाव आया।"),
("He stole the file, and the MPs called a commentator.", "उसने फ़ाइल चुरा ली और सांसदों ने टिप्पणीकार को बुलाया।"),
("The siblings and the interception of the call surprised us.", "भाईबहन और कॉल के अवरोधन ने हमें चौंका दिया।"),
("Deaths occurred and sizes changed; the sick were helped.", "मौतें हुईं, आकारों में बदलाव आया; ग्रस्त लोगों की मदद की गई।"),
("At the workplace, the plants and factories are modern.", "कार्यस्थल पर संयंत्रों और कारखाने आधुनिक हैं।"),
("The factions were bound by an ordinance on formats.", "गुटों पर अध्यादेश लागू था, प्रारूपों के बारे में।"),
("Priests drew a diagram for the full-length film preview.", "पुजारियों ने पूर्णलंबाई फ़िल्म के पूर्वावलोकन के लिए आरेख बनाया।"),
("Synonym and advisors, mammals too, were discussed.", "पर्याय, सलाहकारों और स्तनधारियों पर चर्चा हुई।"),
("The importance of the coastline was told by the co-author.", "सहलेखक ने तटरेखा का महत्त्व बताया।"),
("The promises were tremendous; she raised her eyes and said the slogan.", "वादे जबरदस्त थे; उसने आंखें उठाईं और नारा लगाया।"),
("Gardening, emulsion, and friendly directors were in the article.", "लेख में बागवानी, पायस और मैत्रीपूर्ण निर्देशकों की चर्चा थी।"),
("The hemisphere and the teachings of the orbital class were useful.", "गोलार्ध और शिक्षाओं के साथ कक्षीय पाठ उपयोगी था।"),
("A one-day match and a barrier made inability visible.", "एकदिवसीय मैच में अवरोध ने अक्षमता दिखा दी।"),
("The cottage industry and minorities, edited by the writer, were liked.", "कुटीर उद्योग और अल्पसंख्यकों पर सम्पादन अच्छा लगा।"),
("The data figure was contaminated, so it was erased.", "आंकड़ा दूषित था, इसलिए उसे मिटा दिया गया।"),
]
