PAIRS = [
("The vice-chancellor spoke about the accidents on the highway.", "कुलपति ने राजमार्ग पर हुई दुर्घटनाओं के बारे में बात की।"),
("Extraction of minerals and the brave knights are described in the book.", "किताब में निष्कर्षण और शूरवीरों का वर्णन किया गया है।"),
("The doctor said that the childbirth would be easy.", "डॉक्टर ने कहा कि प्रसव आसान होगा।"),
("Realism in literature differs from the confederation of states.", "साहित्य में यथार्थवाद परिसंघ से अलग विषय है।"),
("The Jat farmer read a theological book.", "जाट किसान ने एक धर्मशास्त्रीय किताब पढ़ी।"),
("The justice and the lead metal were both in the museum.", "न्यायमूर्ति और सीसा दोनों संग्रहालय में थे।"),
("The soldiers carried weapons and ammunition for the war.", "सैनिक युद्ध के लिए आयुध लेकर चल रहे थे।"),
("My niece likes a bilateral agreement between the two countries.", "मेरी भतीजी को दोनों देशों के बीच द्विपक्षीय समझौता पसंद है।"),
("The relatives of the dead mourned their wishes and the heirs.", "मृतकों के रिश्तेदारों ने उनकी इच्छाओं और उत्तराधिकारियों को याद किया।"),
("The reinforcement of the bridge emerged as an unwilling plan.", "पुल का सुदृढीकरण एक अनिच्छुक योजना के रूप में उभरी।"),
("The exploitation of forests by an undefeated king was wrong.", "अपराजित राजा द्वारा जंगलों का दोहन गलत था।"),
("The indicator showed the conviction of the accused.", "संकेतक ने आरोपी की दोषसिद्धि दिखाई।"),
("The maulana explained the physical constant to the students.", "मौलाना ने विद्यार्थियों को स्थिरांक समझाया।"),
("The majority lives near the birthplace of the poet.", "बहुसंख्यक लोग कवि के जन्मस्थान के पास रहते हैं।"),
("The brothers and sisters were accused of treason.", "भाईबहनों पर राजद्रोह का आरोप लगाया गया।"),
("The responsible officer opposed the dictatorship.", "उत्तरदायी अधिकारी ने तानाशाही का विरोध किया।"),
("The emperor studied jurisprudence in the northeastern city.", "बादशाह ने उत्तरपूर्वी शहर में न्यायशास्त्र का अध्ययन किया।"),
("The guidelines for hemp and plants were published today.", "भांग और वनस्पतियों के दिशानिर्देशों को आज प्रकाशित किया गया।"),
("Hereditary diseases and homosexuality were discussed at the shrine.", "धाम में वंशानुगत बीमारियों और समलैंगिकता पर चर्चा हुई।"),
("The watershed remained unchanged, and the bleeding stopped.", "जलविभाजक अपरिवर्तित रहा और रक्तस्राव रुक गया।"),
("The satellites showed a bloody scene to the defendant.", "उपग्रहों ने प्रतिवादी को खूनी दृश्य दिखाया।"),
("The will was recovered from the peripheral office.", "वसीयतनामा परिधीय कार्यालय से पुनर्प्राप्त किया गया।"),
("Many Hindus got big chances to speak.", "हिंदुओं को बोलने के बड़ी मौकों पर अवसर मिले।"),
("The lease and the submarines were part of the agreement.", "पट्टा और पनडुब्बियों का ज़िक्र समझौते में था।"),
("The armies stationed at the bases stayed on high ground.", "अड्डों पर तैनात सेनाएँ ऊंचा स्थान चुनकर रुकीं।"),
("The voices of the people echoed, and Madan revealed a secret.", "आवाज़ों की गूंज थी और मदन ने रहस्योद्घाटन किया।"),
("The snake bought a security bond and a standard measure.", "नाग ने प्रतिभूति और मापदंड के बारे में सुना।"),
("Traditional amphibian studies are respectable and experimental.", "परंपरागत उभयचर अध्ययन सम्मानजनक और प्रायोगिक हैं।"),
("They decided to hand over the work to the organizers.", "उन्होंने काम आयोजकों को सौंपने का फैसला किया।"),
("Stuck in the atrocity, they asked for transparency.", "अत्याचार में फंसे लोगों ने पारदर्शिता की माँग की।"),
("Neglect of the devotees led to a speech or address.", "भक्तों की अनदेखी के कारण संबोधन देना पड़ा।"),
("The battles were innovative, and the ivory was a symbol of barbarity.", "लड़ाइयों में अभिनव तरीके थे और हाथीदांत बर्बरता का प्रतीक था।"),
("He could not control the integer and the rectangle.", "वह पूर्णांक और आयत पर काबू नहीं रख सका।"),
("The notability of the glossary and attachment to it grew.", "कोश की उल्लेखनीयता और उससे लगाव बढ़ गया।"),
("To earn money, the idol-worshipper will keep working.", "कमाने के लिए मूर्तिपूजक काम करता रहेगा।"),
("The married man will keep a seventh-floor flat.", "शादीशुदा आदमी सातवां फ्लैट रखेंगे।"),
("Developmental stagnation and feminism were topics in the class.", "विकासात्मक ठहराव और नारीवाद कक्षा के विषय थे।"),
("The gazette lists letters and counterparts.", "राजपत्र में वर्णों और समकक्षों की सूची है।"),
("The independent candidate trusted the expenses and surveys.", "निर्दलीय उम्मीदवार को खर्चों और सर्वेक्षणों पर यकीन था।"),
("The transferred land is reflected in the fountains of the park.", "हस्तांतरित भूमि पार्क के फव्वारे में परिलक्षित है।"),
("Madness and passion drove the species to extinction.", "पागलपन और आवेश ने प्रजातियां खत्म कर दीं।"),
("The coordinator discussed ethnicity at the gateway.", "संयोजक ने प्रवेशद्वार पर जातीयता पर चर्चा की।"),
("Intimate and proportional results came from the laboratories.", "प्रयोगशालाओं से अंतरंग और आनुपातिक परिणाम आए।"),
("The situation became worse, and the implication is clear.", "स्थिति बदतर हो गई और निहितार्थ स्पष्ट है।"),
("Independence is quite a multinational concern.", "स्वतन्त्रता एकदम बहुराष्ट्रीय चिंता है।"),
("The rent was low, and the separation was difficult.", "किराये कम थे और पृथक्करण कठिन था।"),
("Eligibility and presentations will be judged tomorrow.", "पात्रता और प्रस्तुतियाँ कल परखी जाएँगी।"),
("The islander was shocked and the decomposition began.", "द्वीपवासी सदमे में था और अपघटन शुरू हो गया।"),
("Encroachment and the ovary were topics of the lecture.", "अतिक्रमण और अंडाशय व्याख्यान के विषय थे।"),
("Their beliefs about mental illness are to be repeated.", "उनके विश्वासों और मनोरोग के बारे में बातें दोहराने की ज़रूरत है।"),
("The cells and the shareholders were equal in the sermon.", "कोशिकाएँ और शेयरधारकों की बातें समतुल्य थीं।"),
("The unused folk tales were told in the sermon.", "अप्रयुक्त लोककथाओं को प्रवचन में सुनाया गया।"),
("Applied science and the timeline were not effective.", "अनुप्रयुक्त विज्ञान और समयरेखा अप्रभावी थीं।"),
("The waves rushed back, and the edge was upside down.", "तरंगों की धार उल्टा हो गई थी।"),
("The immigrants practiced archery in the unfortunate village.", "अप्रवासियों ने दुर्भाग्यपूर्ण गाँव में तीरंदाजी की।"),
("The working subfamily is interactive and evergreen.", "कामकाजी उपपरिवार संवादात्मक और सदाबहार है।"),
("The demographic attractions are viable.", "जनसांख्यिकीय आकर्षणों को व्यवहार्य माना गया।"),
("The plot of land was for the twelfth archer.", "भूखंड बारहवीं तीरंदाज के लिए था।"),
("Not at all, well, the indicator shows efficiency.", "बिलकुल नहीं, ख़ैर, सूचक कार्यक्षमता दिखाता है।"),
("The sect and the transmission were referred to in the report.", "रिपोर्ट के हवाले से सम्प्रदाय और प्रेषण का ज़िक्र हुआ।"),
("The prefix is in legends, said the old man.", "बूढ़े ने कहा कि उपसर्ग किंवदंतियों में है।"),
("The contracted artworks belong to the mistress.", "अनुबंधित कलाकृतियाँ मालकिन की हैं।"),
("The injuries in the pargana were funded by zinc.", "परगना की चोटें जस्ता से वित्तपोषित थीं।"),
("The songs have medical, ideal themes.", "गानों में चिकित्सीय और आदर्शों के विषय हैं।"),
("The landscapes were shown to the graduates and guardians.", "परिदृश्यों को स्नातकों और संरक्षकों को दिखाया गया।"),
("The subject matter of prostitution is sensitive.", "विषयवस्तु और वेश्यावृत्ति संवेदनशील मुद्दे हैं।"),
("My brother-in-law has long hair and is unmarried.", "बहनोई के लम्बे बाल हैं और वे अविवाहित हैं।"),
("Creativity and atoms are linked in the lesson.", "रचनात्मकता और परमाणुओं का संबंध पाठ में है।"),
("The spots and the last page were secondary.", "धब्बों और अन्तिम पन्ने द्वितीयक थे।"),
("Go for a walk, mentioned the engineering teacher.", "अभियांत्रिकी शिक्षक ने घूम आने का जिक्र किया।"),
("The crusade and the surah were mentioned by the colonists.", "धर्मयुद्ध और सूरा का उल्लेख उपनिवेशवादियों ने किया।"),
("The subtitle was made by an eccentric person.", "उपशीर्षक एक सनकी आदमी ने बनाया।"),
("The situation is clear, and solutions are needed.", "हालात गंभीर हैं और समाधानों की ज़रूरत है।"),
("The seeds are one-sided and inevitable.", "बीजों की बात एकतरफा और अपरिहार्य है।"),
("The tenant found it existing, and the lease was signed.", "किरायेदार को घर विद्यमान मिला और उसे पाये की तरह रखा।"),
("Tucker made a special contribution in the corners.", "टकर ने कोनों में विशेषयोगदान दिया।"),
("The miners found an egg with a periodic design.", "खनिकों को सामयिक चिह्न वाला अंडा मिला।"),
("Provinces made excuses about photography.", "प्रदेशों ने छायांकन के बहाने बनाए।"),
("The perennial duties and obligations are important.", "बारहमासी दायित्वों का पालन ज़रूरी है।"),
("The wolves, however, stayed in the cages.", "भेड़िये तथापि पिंजरे में ही रहे।"),
("It is noteworthy that customs follow the following.", "गौरतलब है कि रीतिरिवाजों का पालन निम्नानुसार होता है।"),
("There are many varieties, and the candidate was a liar.", "किस्में कई हैं और प्रत्याशी झूठा था।"),
("The sensory co-production was a maneuver.", "संवेदी सहनिर्माण एक पैंतरेबाज़ी थी।"),
("The hired non-governmental workers are crushing the weeds.", "भाड़े के गैरसरकारी लोग घास को कुचल रहे हैं।"),
("The subspecies and the directors had angular loans.", "उपप्रजाति पर निदेशकों ने ऋणों की बात की।"),
("The servants are fond of the angular building.", "सेवकों को कोणीय इमारत का शौकीन माना जाता है।"),
("Recommendations are innate, said the leader.", "नेता ने कहा कि सिफारिशों की जन्मजात समझ चाहिए।"),
("Saurabh lives on the ground floor, and initiatives continue.", "सौरभ भूतल पर रहता है और पहलों पर काम चल रहा है।"),
("Styles and good fortune are in the story.", "शैलियाँ और सौभाग्य इस कहानी में हैं।"),
("Friction occurs while she drives incomplete machines.", "घर्षण होता है जब वह अपूर्ण मशीन चलाती है।"),
("The viceroy had structured tuberculosis data.", "वायसराय के पास संरचित तपेदिक का डेटा था।"),
("Producers called the rascal a villain.", "उत्पादकों ने बदमाश को खलनायक कहा।"),
("The lighthouse and fighting were shown, and crore of rupees spent.", "प्रकाशस्तंभ दिखाया गया और लड़ना मना था, करोड़ रुपये खर्च हुए।"),
("The activation of the wards was uncontrolled.", "वार्डों का सक्रियण अनियंत्रित था।"),
("The vector and medicines are in the lesson.", "सदिश और दवाएं पाठ में हैं।"),
("The abbot was suicidal, and generalized rules were written on inscriptions.", "मठाधीश आत्मघाती था और सामान्यीकृत नियम शिलालेखों पर लिखे थे।"),
]
