PAIRS = [
("The residual waste was shown to the defendants and the judge in court.", "अदालत में अवशिष्ट कचरा प्रतिवादियों और जज को दिखाया गया और करिश्मा भी वहाँ थी।"),
("The students measured the angles, and the generalization of the result left the teacher overwhelmed.", "छात्रों ने कोणों को मापा और सामान्यीकरण देखकर शिक्षक अभिभूत हो गए।"),
("Great personalities have enriched our ethics, and the audience was spellbound.", "विभूतियाँ हमारे आचार को समृद्ध करती हैं और दर्शक मंत्रमुग्ध थे।"),
("The catchment area of the river is large, and the thief was beaten.", "नदी का जलग्रहण क्षेत्र बड़ा है और चोर की पिटाई हुई।"),
("The government suppressed the news, and spirituality is a prototype of peace.", "सरकार ने खबर को दबाया और आध्यात्मिकता शांति का प्रतिरूप है।"),
("The redirected mail gave me a headache.", "पुनर्निर्देशित डाक देखकर मुझे सिरदर्द हो गया।"),
("Over many periods, the eternal tradition has endured.", "कई अवधियों में सनातन परंपरा चलती रही है।"),
("The emerging companies are forming circles, and the groups are exchanging ideas.", "उभरती कंपनियाँ मंडलियों में बँट रही हैं और अदलाबदली जारी है।"),
("Oceans are huge, and the detective found a clue.", "महासागरों का आकार विशाल है और जासूस को एक सुराग मिला।"),
("Seeing the emerging talent, the visionary began an excavation.", "उभरने वाली प्रतिभा देख दूरदर्शी ने उत्खनन शुरू किया।"),
("After the expansion, the century saw standardization.", "परिवर्धन के बाद इस शती में मानकीकरण हुआ।"),
("The manager fell and was injured, and the skyscraper stood tall.", "प्रबन्धक गिरकर घायल हो गया और गगनचुंबी इमारत खड़ी रही।"),
("Day by day, undoubtedly, the laws are changing.", "दिनप्रतिदिन निस्संदेह अधिनियमों में बदलाव आ रहा है।"),
("The algebraic tool is useful for the student.", "बीजगणितीय आला छात्र के लिए उपयोगी है।"),
("The wrestler's hips hurt, and he has to reach the ring.", "उसके कूल्हे दुखते हैं और उसे अखाड़े पहुंचना है।"),
("Because of the appointments, countless officers are in the Trinamool party office.", "नियुक्तियों के कारण असंख्य अधिकारी तृणमूल कार्यालय में हैं।"),
("The assistants have great ambition.", "सहायकों में बड़ी आकांक्षा है।"),
("Many demonstrators gathered, and contemporaries watched.", "अनेकों प्रदर्शनकारी जमा हुए और समकालीनों ने देखा।"),
("The quarterly report and the pulmonary disease were discussed.", "त्रैमासिक रिपोर्ट और फुफ्फुसीय रोग पर चर्चा हुई।"),
("The spectrum of the demon's story is above-mentioned.", "दानव की कहानी का वर्णक्रम उपर्युक्त है।"),
("The court case was heard in the courtroom, and the minarets were visible.", "अदालती मामला सुना गया और मीनारों की ओर सबकी नजर थी।"),
("A drop of water fell, and I heard a sound of a duel.", "एक बूंद गिरी और मैंने द्वंद्वयुद्ध की आवाज सुने।"),
("The fame of the developer spread.", "विकासकर्ता की ख्याति फैल गई।"),
("The convex lens and the access were explained.", "उत्तल लेंस और अभिगमन समझाया गया।"),
("The marines and the maulvi came to the meeting.", "नौसैनिकों और मौलवी सभा में आए।"),
("Despite failures, her elegant dress looked graceful.", "विफलताओं के बावजूद उसकी सुरुचिपूर्ण पोशाक सुंदर लगी।"),
("The demonic laugh and the infrared light scared the child.", "राक्षसी हँसी और अवरक्त रोशनी से बच्चा डर गया।"),
("There was mustard seed, and female animals stood near.", "वहाँ राई थी और मादाएँ पास खड़ी थीं।"),
("The drowned boat stood vertical and overlapping.", "डूबे जहाज़ का हिस्सा लंबवत और अतिव्यापी दिखा।"),
("For ages, the houses and the jauhar tradition are remembered.", "युगों से सदनों में जौहर की कथा याद की जाती है।"),
("Side effects and imperialism harmed society.", "दुष्प्रभाव और साम्राज्यवाद ने समाज को नुकसान पहुँचाया।"),
("The doctor advised abstinence like a reptile avoiding the sun.", "डॉक्टर ने परहेज की सलाह दी और सरीसृप भाँति धूप से बचते हैं।"),
("The eagle's claws are sharp, and the scissors are blunt.", "बाज के पंजे तेज हैं और कतरनी कुंद है।"),
("Mitigation of the conspiracy is necessary.", "षड्यंत्र का शमन जरूरी है।"),
("The indexed files are predetermined.", "अनुक्रमित फाइलें पूर्वनिर्धारित हैं।"),
("Neutrality is good, and cognizance of facts is needed.", "तटस्थता अच्छी है और तथ्यों का संज्ञान जरूरी है।"),
("Detroit is a city for all, and the unrelated topics are skipped.", "डिट्रोइट सर्व के लिए शहर है और असंबद्ध बातें छोड़ दी गईं।"),
("The treasurer is in the grip of trouble, and the contractors are angry.", "खजानेदार मुसीबत की चपेट में है और ठेकेदारों को गुस्सा है।"),
("Nirvana is the goal, and polarization is increasing.", "निर्वाण लक्ष्य है और ध्रुवीकरण बढ़ रहा है।"),
("The longitudinal study showed fascism's rise.", "अनुदैर्ध्य अध्ययन ने फासीवाद का उभार दिखाया।"),
("He recited a couplet, a doha, praising the goddess Bhagwati.", "उसने भगवती की स्तुति में दोहा सुनाया।"),
("The beetle and the semiconductor are both small.", "भृंग और अर्धचालक दोनों छोटे हैं।"),
("Fix the shortcomings; the lifemate helps.", "कमियों को सुधारो, जीवनसाथी मदद करता है।"),
("The event that occurred was momentary.", "जो घटित हुआ वह क्षणिक था।"),
("The invaders misled the people.", "आक्रमणकारियों ने लोगों को गुमराह किया।"),
("The concepts must be clear, and the technician explained.", "अवधारणाएँ स्पष्ट होनी चाहिए, तकनीशियन ने समझाया।"),
("The Commonwealth follows its own custom.", "राष्ट्रमण्डल अपनी रीति का पालन करता है।"),
("The unconventional bandits came to loot.", "अपरंपरागत डाकू लूटने आए।"),
("Commitments are due; write a conditional letter.", "प्रतिबद्धताओं के लिए देय राशि है, सशर्त पत्र लिखें।"),
("God watches the flames.", "परमेश्वर लपटों को देखता है।"),
("The stylistic militant lives in the region.", "शैलीगत उग्रवादी इस क्षेत्र में रहता है।"),
("The jurisdiction and dissection were studied.", "क्षेत्राधिकार और विच्छेदन का अध्ययन हुआ।"),
("Just as the officer said, the mines are closed.", "यथा पदाधिकारी ने कहा, खदानें बंद हैं।"),
("The worldly traction is strong, I will give.", "लौकिक कर्षण मजबूत है, मैं दूंगा।"),
("The state-wide gem will be found.", "राज्यव्यापी मणि पाएगा।"),
("Co-educational schools have a maze.", "सहशैक्षिक विद्यालयों में भूलभुलैया है।"),
("In disguise, she read the specifications.", "भेष बदलकर उसने विनिर्देशों को पढ़ा।"),
("Fearless entrepreneurship is partisan.", "अभय उद्यमिता पक्षपातपूर्ण है।"),
("To flip, to the genders, valuable.", "पलटने से लिंगों पर बहुमूल्य असर पड़ा।"),
("Industrialization created arson.", "औद्योगीकरण से आगजनी का खतरा रचा।"),
("The collegiate example of renewal.", "महाविद्यालयी मिसाल से नवीकरण हुआ।"),
("Innovations changed the meanings.", "नवाचारों ने मायनों को बदल दिया।"),
]
