PAIRS = [
("He made an offering of his devotion, and his faith remained unbroken.", "उसने अपनी भक्ति अर्पित की और उसकी आस्था अक्षुण्ण रही।"),
("The interpreter explained the sequence of events to the guests.", "दुभाषिया ने मेहमानों को पूरा घटनाक्रम समझाया।"),
("The lamp was lit, and the old custom continued in the workshops.", "दीपक प्रज्वलित हुआ और कार्यशालाएं पुराने चलन के साथ चलती रहीं।"),
("With a humble plea, he made a request to the elders.", "उसने विनती करके बड़ों से सहायता मांगी।"),
("Frequency is measured in hertz, and thunder rumbled in the sky.", "आवृत्ति हर्ट्ज में नापी जाती है और आसमान में गड़गड़ाहट हुई।"),
("The advocates questioned the attacker in court.", "अधिवक्ताओं ने अदालत में आक्रमणकारी से पूछताछ की।"),
("Those who do the work check the pelvis bone carefully.", "श्रोणि की हड्डी की जांच करनेवाले लोग ध्यान से देखते हैं।"),
("The delayed propellant finally reached the laboratory.", "विलंबित प्रणोदक आखिरकार प्रयोगशाला में पहुंचा।"),
("His involvement in the scam was proven, so no dealings remained with him.", "घोटाले में उसकी संलिप्तता साबित हुई, इसलिए उससे कोई लेनादेना नहीं रहा।"),
("To lure customers, a misunderstanding was created in the archival record.", "ग्राहकों को लुभाने के लिए अभिलेखीय रिकॉर्ड में गलतफहमी पैदा की गई।"),
("The hymns were so striking that they made the whole village cry.", "भजनों की प्रस्तुति इतनी हड़ताली थी कि सारा गांव रो पड़ा।"),
("The young men, who received high titles, were of a superior rank.", "उपाधियाँ पाने वाले युवकों की कोटि बहुत ऊंची थी।"),
("Dive into the river, he told them.", "उसने कहा कि नदी में डुबो और तैरो।"),
("Coming out, the lords felt the consciousness of the soil.", "निकलकर प्रभुओं ने मृदा और चैतन्य का अनुभव किया।"),
("The vein shows the proper reality of the body.", "शिरा शरीर का समुचित यथार्थ दिखाती है।"),
("The devotee found the place joyful.", "श्रद्धालु को वह स्थान बहुत आनंददायक लगा।"),
("The long descriptive talk was a collection of sermons.", "लम्बा व्याख्यात्मक भाषण उपदेशों का संग्रह था।"),
("The chains on the road were remarkable.", "सड़क पर पड़ी जंजीरों की बनावट विलक्षण थी।"),
("The documentation was ready, and the recommendation arrived.", "प्रलेखन तैयार था और अनुशंसा भी आ गई।"),
("The shrine's rising fame draws crowds.", "दरगाह की उभरता हुआ नाम भीड़ को खींचता है।"),
("The gunman spoke about vaccines and myths.", "बंदूकधारी टीकों और मिथकों के बारे में बोला।"),
("Empires feared missing out, and a sensation spread.", "साम्राज्यों को चूकने का डर था और हर जगह सनसनी फैल गई।"),
("Modernity and infrastructure have changed our lives.", "आधुनिकता और अवसंरचना ने हमारा जीवन बदल दिया।"),
("A fly sat on the yeast.", "मक्खी खमीर पर आकर बैठ गई।"),
("The half projectile fell among the goods.", "अर्ध प्रक्षेप्य सामानों के बीच जा गिरा।"),
("The biologist laughed at the ridiculous contributors' list.", "जीववैज्ञानिक योगदानकर्ताओं की हास्यास्पद सूची पर हंसा।"),
("The captured spy was the millionaire's martyrdom, they said.", "पकड़ी गई जासूस करोड़पति की शहादत का कारण बनी।"),
("The father loves balls, which were looted.", "बाप को गेंदें पसंद हैं, जिन्हें किसी ने लूटा।"),
]
