#!/usr/bin/env python3
"""Batch ID-05: Culinary, Domestic & Material Culture (250 sentences).
File: data/phrases29.json, IDs: p29s001..p29s250.
Themes: दाल, घी, तेल, थाली, रोटी, नमक, घड़ा, म्यान, तलवार, कंगन, तराजू.
"""
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parent))
from gen_batches_pipeline import process_batch

PAIRS = [
    # 1-30: दाल, भात, चावल, खिचड़ी (Lentils, Rice, Porridge)
    ("The cunning trickster realized that his trick will not work here", "चालाक धोखेबाज़ समझ गया कि यहाँ उसकी दाल नहीं गलेगी"),
    ("The clever detective suspected that something was fishy in the matter", "चतुर जासूस को तुरंत समझ आ गया कि दाल में कुछ काला है"),
    ("The unwelcome neighbor was poking his nose into our personal conversation", "बिन बुलाया पड़ोसी हमारी बातचीत में दाल भात में मूसलचंद बन रहा था"),
    ("The poor clerk worked hard every day just to earn simple food", "गरीब मुंशी केवल दाल रोटी कमाने के लिए दिन रात मेहनत करता था"),
    ("The stubborn rebel did not listen and made his own separate plans", "हठी विद्रोही ने किसी की न सुनी और अपनी अलग खिचड़ी पकाई"),
    ("The kind mother prepared hot lentils and fresh rice for the guests", "स्नेही माँ ने भूखे अतिथियों के लिए गरम दाल और ताज़ा चावल बनाए"),
    ("The greedy landlord will take away even the poor farmer simple bread", "लालची ज़मींदार गरीब किसान की रूखी सूखी दाल रोटी भी छीन लेगा"),
    ("The wise grandmother cooked light porridge for the sick child yesterday", "समझदार दादी ने कल बीमार बच्चे के लिए हल्की खिचड़ी पकाई थी"),
    ("The diligent cook is boiling fragrant basmati rice in the copper pot", "मेहनती रसोइया ताँबे के बड़े बर्तन में सुगंधित बासमती चावल उबाल रहा है"),
    ("The hungry traveler ate the delicious lentils with immense joy and gratitude", "भूखे मुसाफिर ने बड़े चाव और कृतज्ञता के साथ स्वादिष्ट दाल खाई"),
    ("The arrogant merchant thought nobody could challenge his authority in the town", "घमंडी व्यापारी सोचता था कि नगर में उसके सामने किसी की दाल नहीं गल सकती"),
    ("The careful accountant noticed a small error and smelled something fishy immediately", "सतर्क मुनीम ने बहीखाते में गड़बड़ी देखकर तुरंत भांप लिया कि दाल में कुछ काला है"),
    ("The little girl was happily mixing warm yellow lentils with boiled rice", "छोटी बालिका उबले चावल के साथ पीली गरम दाल खुशी से मिला रही थी"),
    ("The temple priests distributed holy food and sweet rice among the pilgrims", "मंदिर के पुजारियों ने तीर्थयात्रियों के बीच पवित्र भोजन और मीठे चावल बाँटे"),
    ("The honest laborer will always remain satisfied with his honest bread", "ईमानदार मजदूर हमेशा अपनी मेहनत की सूखी दाल रोटी से संतुष्ट रहेगा"),
    ("The foolish conspirators were secretly cooking up a dangerous plot inside", "मूर्ख षड्यंत्रकारी बंद कमरे में बैठकर गुप्त रूप से कोई भयानक खिचड़ी पका रहे थे"),
    ("The village elder advised the quarrelsome youths to share their daily meals", "गाँव के मुखिया ने झगड़ालू युवकों को मिल बाँटकर दाल रोटी खाने की सलाह दी"),
    ("The fragrant steam was rising slowly from the earthen pot of spiced lentils", "मसालेदार दाल की मिट्टी की हाँडी में से धीमी सुगंधित भाप उठ रही थी"),
    ("The clever lawyer proved that the forged documents had something wrong in them", "चतुर वकील ने अदालत में सिद्ध कर दिया कि जाली दस्तावेज़ में दाल में काला है"),
    ("The tired soldiers sat around the campfire and shared simple hot rice", "थके हुए सैनिकों ने अलाव के पास बैठकर सादा गरम भात आपस में बाँटा"),
    ("The humble ascetic refused the royal feast and accepted only dry grains", "विनम्र तपस्वी ने राजसी भोजन ठुकरा दिया और केवल रूखी दाल रोटी स्वीकार की"),
    ("The mischievous boy spilled the bowl of lentils on the clean floor", "शरारती बालक ने साफ़ फर्श पर दाल से भरा कटोरा गिरा दिया"),
    ("The faithful servant served warm lentil soup to his ailing old master", "वफादार सेवक ने अपने बीमार वृद्ध स्वामी को गरम दाल का सूप पिलाया"),
    ("The village woman was carefully winnowing the dried lentils in the courtyard", "ग्रामीण महिला आँगन में बैठकर सूखी दाल को सूप से साफ़ कर रही थी"),
    ("The proud officer realized soon that his threats would not succeed here", "घमंडी अधिकारी को जल्द अहसास हो गया कि यहाँ उसकी हेकड़ी की दाल नहीं गलेगी"),
    ("The old shopkeeper weighed two kilograms of yellow lentils on the scales", "बूढ़े दुकानदार ने तराजू पर दो किलो पीली दाल सावधानी से तौली"),
    ("The festive family enjoyed fried savories along with rich lentil curry", "त्योहार पर पूरे परिवार ने पूरियों के साथ स्वादिष्ट दाल का आनंद लिया"),
    ("The suspicious guard checked every cart to see if anything was amiss", "सतर्क पहरेदार ने हर गाड़ी की जाँच की ताकि कोई दाल में काला न रहे"),
    ("The generous king opened the granary to provide free rice to everyone", "उदार राजा ने सभी भूखे नागरिकों को मुफ्त चावल देने के लिए अन्न भंडार खोल दिया"),
    ("The simple village meal of lentils and bread gave them immense strength", "दाल और रोटी के सादे ग्रामीण भोजन ने उन्हें यात्रा के लिए भरपूर ताकत दी"),

    # 31-65: घी, तेल, मक्खन (Ghee, Oil, Butter - Idioms & Metaphors)
    ("The prosperous merchant was living in luxury with blessings from all sides", "नए व्यापार में सफलता मिलने से व्यापारी की पाँचों उँगलियाँ घी में थीं"),
    ("The overjoyed citizens lit lamps of clarified butter to celebrate the victory", "सेना की भारी जीत की खुशी में नगरवासियों ने घी के दिए जलाए"),
    ("The cruel instigator added fuel to the fire during the violent quarrel", "दुष्ट उपद्रवी ने भड़कते झगड़े में कड़वे बोल बोलकर आग में घी डाल दिया"),
    ("The poor clerk worked like a mill ox from morning till night", "गरीब बाबू दफ्तर में सुबह से शाम तक कोल्हू के बैल की तरह पिसता था"),
    ("The cunning flatterer knew how to butter up the powerful minister skillfully", "चालाक चापलूस जानता था कि बड़े मंत्री की चिकनी चुपड़ी बातें बनाकर मक्खन कैसे लगाना है"),
    ("The grandmother poured pure golden butter over the hot wheat bread", "दादी ने गरम गेहूँ की रोटी पर शुद्ध पीला मक्खन प्यार से लगाया"),
    ("The dishonest oilman was mixing cheap substance with pure mustard oil", "बेईमान तेली शुद्ध सरसों के तेल में सस्ती मिलावट कर रहा था"),
    ("The mother applied cooling herbal oil to the forehead of the boy", "माँ ने बालक के माथे पर जड़ी बूटियों वाला ठंडा तेल धीरे से लगाया"),
    ("The brave warrior was confident that his prosperity would continue to flourish", "साहसी योद्धा को पूरा विश्वास था कि उसकी मेहनत से पाँचों उँगलियाँ घी में रहेंगी"),
    ("The joyful family will light earthen lamps with fragrant butter on Diwali", "प्रसन्न परिवार दीपावली की पावन रात को सुगंधित घी के दीये जलाएगा"),
    ("The provocative speech of the wicked leader poured oil over burning hatred", "दुष्ट नेता के भड़काऊ भाषण ने जलती नफरत की आग में घी का काम किया"),
    ("The simple farmer worked tirelessly like an ox in the muddy sugarcane fields", "सीधा किसान कीचड़ भरे गन्ने के खेत में कोल्हू के बैल की तरह पसीना बहाता था"),
    ("The shrewd courtier used flattering words to gain favor from the emperor", "चतुर दरबारी ने बादशाह से जागीर पाने के लिए मीठी बातों का मक्खन लगाया"),
    ("The pure cow butter melted quickly on the freshly baked griddle bread", "तवे पर से उतरी गरम रोटी पर गाय का शुद्ध मक्खन तुरंत पिघल गया"),
    ("The old oil press was creaking loudly under the heavy wooden beam", "भारी लकड़ी के शहतीर के नीचे पुराना कोल्हू बहुत तेज़ आवाज़ कर रहा था"),
    ("The devotee poured fragrant sandalwood oil into the brass temple lamp", "भक्त ने मंदिर के पीतल के दीपक में सुगंधित चंदन का तेल डाला"),
    ("The lucky heir found unexpected treasure and enjoyed boundless good fortune", "अचानक गड़ा धन मिलने से उस भाग्यशाली युवक की पाँचों उँगलियाँ घी में हो गईं"),
    ("The victory of the young prince made everyone light lamps of joy", "राजकुमार की शानदार विजय का समाचार सुनकर प्रजा ने घी के दीये जलाए"),
    ("Do not utter harsh words and add fuel to this delicate family dispute", "कटु वचन बोलकर इस नाज़ुक पारिवारिक विवाद की आग में घी मत डालो"),
    ("The dedicated teacher worked like a patient mill ox to educate the village", "समर्पित अध्यापक ने गाँव के बच्चों को पढ़ाने में कोल्हू के बैल की तरह श्रम किया"),
    ("The greedy vendor charged extra money for the jar of pure butter", "लोभी दुकानदार ने शुद्ध मक्खन के डिब्बे के लिए ग्राहक से अधिक दाम माँगे"),
    ("The aromatic oil burned brightly through the dark stormy midnight hour", "सुगंधित तेल का दीपक उस तूफानी अंधेरी रात में लगातार जगमगाता रहा"),
    ("The wealthy contractor always ensures that his investments bring double profit", "धनी ठेकेदार हमेशा ऐसा सौदा करता है जिससे उसकी पाँचों उँगलियाँ घी में रहें"),
    ("The entire village will celebrate and light lamps when the soldier returns", "जब बहादुर सिपाही सुरक्षित घर लौटेगा तब पूरा गाँव घी के दिए जलाएगा"),
    ("His bitter taunt acted like oil on the blazing anger of the king", "उसके कड़वे ताने ने राजा के धधकते क्रोध में घी की आहुति का काम किया"),
    ("The weary laborer felt like a tired ox turning the heavy oil wheel", "थका हुआ मजदूर महसूस कर रहा था मानो वह कोल्हू का थका हुआ बैल हो"),
    ("The sweet aroma of simmering clarified butter filled the entire royal kitchen", "खौलते हुए शुद्ध घी की मीठी सुगंध से पूरा शाही भोजनालय महक उठा"),
    ("The traditional potter shaped earthen lamps to hold burning mustard oil", "पारंपरिक कुम्हार ने सरसों का तेल भरने के लिए मिट्टी के सुंदर दीये बनाए"),
    ("The ambitious merchant hoped that all his ventures would yield abundant wealth", "महत्वाकांक्षी व्यापारी चाहता था कि हर सौदे में उसकी पाँचों उँगलियाँ घी में रहें"),
    ("The jubilant crowd lit countless butter lamps along the holy river bank", "उत्साहित भीड़ ने पवित्र नदी के किनारे अनगिनत घी के दीपक प्रज्वलित किए"),
    ("Any unnecessary intervention will merely add oil to the rising conflict", "कोई भी अनुचित हस्तक्षेप केवल सुलगते विवाद की आग में घी ही डालेगा"),
    ("The exhausted clerk spent thirty years working like an uncomplaining mill ox", "थके हुए बाबू ने बिना शिकायत किए तीस साल कोल्हू के बैल की तरह काट दिए"),
    ("The traditional wrestlers massaged their strong muscles with pure mustard oil", "पारंपरिक पहलवानों ने अखाड़े में शुद्ध सरसों के तेल से अपने शरीर की मालिश की"),
    ("The generous grandmother always gave her grandchildren fresh bread with butter", "उदार दादी हमेशा अपने नाती पोतों को मक्खन लगी ताज़ा रोटियाँ खिलाती थीं"),
    ("The burning oil lamp cast long dancing shadows across the whitewashed wall", "जलते हुए तेल के दीये ने सफ़ेद दीवार पर लंबी नाचती हुई परछाइयाँ बना दीं"),

    # 66-100: रोटी, चूल्हा, तवा, कड़ाही (Bread, Hearth, Griddle, Pan)
    ("The selfish opportunist tried to bake his own bread in the riot", "स्वार्थी अवसरवादी ने दंगे के दौरान अपनी राजनीतिक रोटी सेकने की पूरी कोशिश की"),
    ("The poor widow had to struggle hard just to keep the hearth burning", "गरीब विधवा को घर का चूल्हा जलाने के लिए भी भारी मशक्कत करनी पड़ती थी"),
    ("The hot bread puffed up beautifully on the iron griddle over fire", "आग पर रखे लोहे के तवे पर गरम रोटी सुंदर रूप से फूल गई"),
    ("The delicious sweets were frying gently in the large brass cauldron", "पीतल की बड़ी कड़ाही में मीठे पकवान धीमी आँच पर तल रहे थे"),
    ("The greedy leader exploited the public distress to bake his own bread", "लालची नेता ने जनता की परेशानी का फायदा उठाकर अपनी निजी रोटी सेकी"),
    ("The hungry children gathered around the warm hearth on the winter night", "सर्द रात में भूखे बच्चे रसोई के गरम चूल्हे के चारों ओर जमा हो गए"),
    ("The mother was flipping thin wheat flatbreads skillfully on the hot griddle", "माँ गरम तवे पर गेहूँ की पतली रोटियाँ बड़ी निपुणता से उलट पलट रही थी"),
    ("The bubbling sweet syrup smelled delicious inside the deep iron pan", "गहरी लोहे की कड़ाही के अंदर खौलता हुआ मीठा शीरा बहुत महक रहा था"),
    ("Do not take advantage of their helplessness to serve your own selfish interest", "उनकी बेबसी का गलत लाभ उठाकर अपनी स्वार्थ की रोटी सेकना बंद करो"),
    ("The storm extinguished the firewood and the kitchen hearth went completely cold", "तूफान ने गीली लकड़ियाँ बुझा दीं और रसोई का चूल्हा पूरी तरह ठंडा पड़ गया"),
    ("The village baker took out fresh crispy loaves from the earthen oven", "गाँव के नानबाई ने मिट्टी के तंदूर से ताज़ा कुरकुरी रोटियाँ बाहर निकालीं"),
    ("The golden crisp fritters were taken out of the hot oil pan", "गरम तेल की कड़ाही में से सुनहरे कुरकुरे पकौड़े बाहर निकाल लिए गए"),
    ("The unprincipled politician will always look for opportunities to bake his bread", "सिद्धांतहीन नेता हमेशा ऐसा मौका ढूँढता है जहाँ वह अपनी रोटी सेक सके"),
    ("The poor family rejoiced when smoke finally rose from their kitchen hearth", "गरीब परिवार खुश हो गया जब कई दिन बाद उनके चूल्हे से धुआँ उठा"),
    ("The sound of kneading fresh flour echoed softly from the quiet kitchen", "शांत रसोई से ताज़ा आटा गूँथने की धीमी आवाज़ आ रही थी"),
    ("The heavy iron griddle was smoking hot before the batter was poured", "घोल डालने से पहले लोहे का भारी तवा धुएँदार गरम हो चुका था"),
    ("The clever broker made a huge commission and baked his golden bread", "चालाक दलाल ने भारी कमीशन बनाया और सौदे में अपनी शानदार रोटी सेक ली"),
    ("The old wooden spoon stirred the simmering porridge inside the brass pan", "पुरानी लकड़ी की करछुल ने पीतल की कड़ाही में पकती खीर को धीरे से चलाया"),
    ("The dedicated mother baked fresh bread for her children before sunrise", "कर्तव्यनिष्ठ माँ ने सूर्योदय से पहले उठकर अपने बच्चों के लिए ताज़ा रोटियाँ बनाईं"),
    ("The cold hearth of the ruined mansion told a sad tale of decline", "खंडहर बन चुकी हवेली के ठंडे चूल्हे ने पतन की दर्दनाक कहानी बयां की"),
    ("The wicked landlord tried to bake his bread while the peasants quarreled", "जब किसान आपस में लड़ रहे थे तब दुष्ट ज़मींदार अपनी रोटी सेकने लगा"),
    ("The fragrant hot bread made of millet tasted heavenly with fresh garlic", "बाजरे की ताज़ा गरम रोटी लहसुन की चटनी के साथ अत्यंत स्वादिष्ट लगती थी"),
    ("The sweet maker stirred boiling sugar syrup inside the wide copper cauldron", "हलवाई ने ताँबे की चौड़ी कड़ाही में उबलती चाशनी को लगातार हिलाया"),
    ("The hungry orphan looked longing at the steaming bread on the wooden table", "भूखे अनाथ बालक ने मेज़ पर रखी गरम भाप छोड़ती रोटी को ललचाई नज़रों से देखा"),
    ("The old grandmother sat near the glowing hearth to warm her hands", "बूढ़ी दादी अपने काँपते हाथ सेकने के लिए जलते चूल्हे के पास बैठ गईं"),
    ("The opportunistic agent tried to bake his bread out of the crisis", "अवसरवादी दलाल ने बड़े संकट में से भी अपनी रोटी सेकने का मार्ग ढूँढ लिया"),
    ("The golden wheat bread was soft as silk in the basket", "टोकरी में रखी सुनहरी गेहूँ की रोटी रेशम जैसी कोमल थी"),
    ("The brass cauldron shone brightly after the scullery maid cleaned it thoroughly", "दासी द्वारा अच्छी तरह माँजने के बाद पीतल की कड़ाही सोने जैसी चमक उठी"),
    ("The traveler asked for a loaf of bread and a cup of water", "थके हुए मुसाफिर ने एक रोटी और एक कटोरा पानी माँगा"),
    ("The hearth fire crackled merrily as dry oak branches burned bright", "सूखी लकड़ियाँ जलने से चूल्हे की आग सुखद आवाज़ के साथ धधक रही थी"),
    ("The selfish contractor used public funds to bake his private bread", "स्वार्थी ठेकेदार ने सरकारी धन का उपयोग करके अपनी निजी रोटी सेक ली"),
    ("The maiden patted the round dough balls into flat circles on stone", "युवती ने पत्थर की चौकी पर गोल लोइयों को थपथपाकर सुंदर रोटियाँ बनाईं"),
    ("The savory fried bread puffed up into golden balloons in hot oil", "गरम तेल में पड़ते ही स्वादिष्ट कचौरी सुनहरे गुब्बारे की तरह फूल गई"),
    ("The poor peasant worked hard to keep fire in his hearth every day", "गरीब किसान रोज़ अपने घर का चूल्हा जलाने के लिए खून पसीना बहाता था"),
    ("The cold metal griddle took long to heat over the damp twigs", "गीली टहनियों के ऊपर लोहे का ठंडा तवा गरम होने में बहुत समय ले रहा था"),

    # 101-140: नमक, मिर्च, मसाला (Salt, Chili, Spices - Idioms & Human Nature)
    ("The cruel enemy rubbed salt into the deep wounds of the captive", "क्रूर शत्रु ने बंदी योद्धा के गहरे घावों पर जले पर नमक छिड़क दिया"),
    ("The loyal servant proved true to the salt of his noble master", "वफादार सेवक ने अपने नेक स्वामी के नमक का हक पूरी ईमानदारी से अदा किया"),
    ("The treacherous traitor was completely unfaithful to his salt and nation", "विश्वासघाती देशद्रोही अपने देश और अन्नदाता के प्रति घोर नमकहराम निकला"),
    ("The boastful storyteller added unnecessary spice to his simple adventure story", "शेखीबाज़ कथावाचक ने अपनी सीधी सादी यात्रा की कहानी में मिर्च मसाला लगा दिया"),
    ("Do not rub salt into his grief by mocking his painful failure", "उसकी दुखद असफलता का उपहास उड़ाकर उसके दुखते घाव पर नमक मत छिड़को"),
    ("The faithful guard gave his life to honor the salt of the kingdom", "वफादार पहरेदार ने राज्य का नमक अदा करने के लिए अपना बलिदान दे दिया"),
    ("The honest soldier declared that he would never betray his salt", "ईमानदार सैनिक ने गर्व से कहा कि वह अपने मालिक का नमक कभी नहीं भूलेगा"),
    ("The gossiping woman added extra salt and pepper to the neighborhood rumor", "बातूनी महिला ने पड़ोस की सामान्य अफवाह में खूब मिर्च मसाला लगाकर सुनाया"),
    ("His mocking laughter felt like salt on the raw wounds of the defeated", "उसकी उपहास भरी हँसी पराजित खिलाड़ी के ताज़ा घाव पर नमक जैसी लगी"),
    ("The righteous warrior repaid the debt of his salt on the battlefield", "धर्मनिष्ठ योद्धा ने युद्ध के मैदान में अपने स्वामी के नमक का कर्ज चुकाया"),
    ("The disloyal treasurer proved unfaithful to the salt and robbed the vault", "बेईमान खज़ांची नमकहराम निकला और उसने शाही तिजोरी का धन चुरा लिया"),
    ("The dramatic journalist exaggerated the minor incident with hot spices", "नाटकबाज़ पत्रकार ने उस छोटी सी घटना में मिर्च मसाला लगाकर सनसनी फैला दी"),
    ("Sympathy is needed here rather than rubbing salt on their terrible loss", "उनके भारी नुकसान पर नमक छिड़कने के बजाय सच्ची सहानुभूति की आवश्यकता है"),
    ("The brave commander honored the salt of his ancestors with valor", "बहादुर सेनापति ने असीम वीरता दिखाकर अपने पूर्वजों के नमक का मान रखा"),
    ("The base betrayer forgot all past favors and turned against his benefactor", "नीच गद्दार ने सारे उपकार भुला दिए और नमकहरामी करके स्वामी के विरुद्ध हो गया"),
    ("The clever poet knows how to add literary spice to plain verse", "कुशल कवि जानता है कि साधारण कविता में भी सुंदर भावों का मसाला कैसे भरना है"),
    ("His harsh rebuke was like rubbing coarse salt into a weeping sore", "उसकी कठोर डांट बहते हुए घाव पर मोटा नमक मलने जैसी असहनीय थी"),
    ("The grateful peasant bowed low and praised the salt of the landlord", "कृतज्ञ किसान ने झुककर प्रणाम किया और दयालु ज़मींदार के नमक की प्रशंसा की"),
    ("The old general would rather die than act unfaithful to his royal salt", "वृद्ध सेनापति शाही नमक के प्रति बेईमानी करने के बजाय मरना अधिक पसंद करता"),
    ("The sensational newspaper added sensational spice to the plain legal verdict", "सनसनीखेज अखबार ने अदालत के सीधे फैसले में मिर्च मसाला जोड़कर खबर छापी"),
    ("Avoid making sarcastic remarks that rub salt on an open injury", "ऐसे व्यंग्य बाण मत चलाओ जो किसी के खुले घाव पर नमक छिड़कते हों"),
    ("The dedicated doctor treated the poor with dedication to honor his medical oath", "समर्पित चिकित्सक ने अपनी शपथ और नमक का मान रखकर गरीबों का इलाज किया"),
    ("History will always despise the traitor who was unfaithful to his bread", "इतिहास हमेशा उस गद्दार का तिरस्कार करेगा जिसने अपने देश के नमक से गद्दारी की"),
    ("She narrated the family quarrel with so much spice that everyone gathered", "उसने पारिवारिक विवाद की बात इतने मिर्च मसाले के साथ सुनाई कि भीड़ लग गई"),
    ("Your untimely criticism will only rub salt into his wounded pride", "तुम्हारी असमय आलोचना उसके आहत स्वाभिमान पर केवल नमक छिड़कने का काम करेगी"),
    ("The noble hostage refused to escape and remained true to his salt", "नेक बंधक ने भागने से इनकार कर दिया और अपने दिए वचन और नमक पर अडिग रहा"),
    ("The faithful servant swore upon the salt that he told the absolute truth", "वफादार नौकर ने अपने स्वामी के नमक की कसम खाकर पूरी सच्चाई बताई"),
    ("The witty comedian added humorous spice to his witty observations", "हास्य कलाकार ने अपने व्यंग्यात्मक विचारों में हास्य का तीखा मसाला मिला दिया"),
    ("His sudden dismissal rubbed salt into his already unbearable financial plight", "अचानक नौकरी छूटने से उसकी पहले से खराब माली हालत पर नमक छिड़क गया"),
    ("The brave clan fought fiercely to repay the debt of their feudal salt", "बहादुर कुल ने अपने सामंत के नमक का कर्ज चुकाने के लिए जी जान से लड़ाई लड़ी"),
    ("The corrupt officer proved false to his salt by taking public bribes", "भ्रष्ट अधिकारी ने जनता से रिश्वत लेकर अपने पद के नमक का अपमान किया"),
    ("The spicy curry had fragrant turmeric cumin and crushed red pepper", "मसालेदार तरकारी में सुगंधित हल्दी जीरा और पिसी हुई लाल मिर्च मिली थी"),
    ("Do not rub salt into the tears of the grieving mother with questions", "कठोर प्रश्न पूछकर शोकाकुल माँ के आँसुओं पर नमक मत छिड़को"),
    ("The honest watchman guarded the storehouse faithfully to honor his salt", "ईमानदार चौकीदार ने अपने नमक की लाज रखने के लिए गोदाम की सतर्क पहरेदारी की"),
    ("The mischievous boy spiced up the simple truth to frighten his sister", "शरारती लड़के ने अपनी बहन को डराने के लिए साची बात में मिर्च मसाला लगा दिया"),
    ("The pinch of pure rock salt brought out the taste of the fresh soup", "सेंधा नमक की एक चुटकी ने ताज़ा सूप के स्वाद को निखार दिया"),
    ("The old veteran reminded the young recruits to respect their soldierly salt", "पुराने सूबेदार ने नए रंगरूटों को सैनिक के नमक की गरिमा बनाए रखने की सीख दी"),
    ("The cunning impostor was proved unfaithful to the salt in open court", "भरी अदालत में साबित हो गया कि वह ढोंगी अपने मालिक के नमक का दगाबाज़ था"),
    ("The chef added ground aromatic spices to make the royal dish delicious", "प्रधान बावर्ची ने शाही व्यंजन को स्वादिष्ट बनाने के लिए पिसे मसाले मिलाए"),
    ("His insensitive comment rubbed salt into their freshly broken hearts", "उसकी असंवेदनशील टिप्पणी ने उनके टूटे हुए दिलों पर नमक छिड़कने का काम किया"),

    # 141-175: घड़ा, थाली, मटका, बर्तन, कटोरा (Pitcher, Platter, Bowl, Utensils)
    ("The measure of sins of the tyrant was full to the brim now", "अत्याचारी राजा के पाप का घड़ा अब पूरी तरह भर चुका था"),
    ("The unprincipled opportunist rolled around like a brinjal on a platter", "सिद्धांतहीन अवसरवादी नेता हमेशा थाली के बैंगन की तरह लुढ़कता रहता था"),
    ("The two corrupt clerks were scoundrels of the very same bag", "वे दोनों बेईमान बाबू वास्तव में एक ही थैली के चट्टे बट्टे निकले"),
    ("The cool water from the earthen pitcher quenched the thirst of travelers", "मिट्टी के घड़े के शीतल जल ने थके हुए यात्रियों की प्यास बुझाई"),
    ("When the measure of his misdeeds was full divine retribution struck him down", "जब उसके बुरे कर्मों का घड़ा भर गया तब ईश्वरीय न्याय ने उसे दंडित किया"),
    ("Nobody trusts a man who changes his loyalties like a rolling eggplant", "जो व्यक्ति थाली के बैंगन की तरह बात बदलता है उस पर कोई भरोसा नहीं करता"),
    ("The police arrested all five thieves who belonged to the same dishonest gang", "पुलिस ने पाँचों चोरों को पकड़ा जो एक ही थैली के चट्टे बट्टे थे"),
    ("The village maiden balanced two painted earthen pots gracefully on her head", "गाँव की युवती ने अपने सिर पर दो सुंदर मिट्टी के घड़े कुशलता से संभाले"),
    ("The arrogant ruler did not know that his cup of sins was overflowing", "अहंकारी शासक को पता नहीं था कि उसके पाप का घड़ा फूटने ही वाला है"),
    ("The fickle minister shifted his allegiance to whoever offered higher gold", "चंचल मंत्री थाली के बैंगन की तरह हमेशा उसी ओर झुकता था जहाँ अधिक धन हो"),
    ("Both the dishonest contractor and the greedy inspector were birds of feather", "बेईमान ठेकेदार और लालची निरीक्षक दोनों एक ही थैली के चट्टे बट्टे निकले"),
    ("The earthen water pitcher broke into many pieces upon the hard stone", "मिट्टी का पानी का घड़ा सख्त पत्थर पर गिरकर चकनाचूर हो गया"),
    ("Every sin adds a drop until the vessel of guilt overflows completely", "हर अपराध एक बूँद जोड़ता है जब तक कि पाप का घड़ा पूरी तरह न भर जाए"),
    ("A politician without ideology will roll like an eggplant on a flat dish", "बिना नीति का नेता हमेशा थाली के बैंगन की तरह इधर उधर डोलता रहेगा"),
    ("Do not expect justice from judges who are corrupt peers of the oppressor", "उन अधिकारियों से न्याय की उम्मीद मत रखो जो शोषक के साथ एक ही थैली के चट्टे बट्टे हैं"),
    ("The cool earthen pot kept the summer water cold and sweet naturally", "मिट्टी के मटके ने भीषण गर्मी में भी पानी को प्राकृतिक रूप से ठंडा और मीठा रखा"),
    ("Beware because when the cup of wickedness is full destruction comes swiftly", "सावधान रहो क्योंकि जब दुष्टता का घड़ा भर जाता है तब विनाश अचानक आता है"),
    ("The opportunist will praise the winner and roll over to the winning party", "अवसरवादी थाली के बैंगन की तरह हमेशा जीतने वाले दल की ओर लुढ़क जाता है"),
    ("All the conspirators in the fraud turned out to be chips of the same block", "धोखाधड़ी में शामिल सभी जालसाज़ एक ही थैली के चट्टे बट्टे साबित हुए"),
    ("The potter shaped a round clay pitcher on his spinning wooden wheel", "कुम्हार ने अपने घूमते हुए चाक पर मिट्टी का सुंदर गोल घड़ा तैयार किया"),
    ("The righteous sage warned the cruel tyrant that his cup was nearly full", "तपस्वी मुनि ने क्रूर राजा को चेतावनी दी कि उसके पापों का घड़ा भरने को है"),
    ("He has no firm opinion and wavers like a loose brinjal on a tray", "उसका कोई पक्का विचार नहीं है और वह थाली के बैंगन की तरह डगमगाता है"),
    ("The rival smugglers were secretly partners from the very same corrupt bag", "दिखावे के विरोधी तस्कर वास्तव में एक ही थैली के चट्टे बट्टे निकले"),
    ("The woman filled her brass pot with clear water from the village well", "महिला ने गाँव के कुएँ से अपने पीतल के घड़े में साफ़ पानी भरा"),
    ("When the measure of evil overflows the proud empire crumbles into dust", "जब अधर्म का घड़ा भर जाता है तब घमंडी साम्राज्य भी मिट्टी में मिल जाता है"),
    ("A reliable friend never acts like an untrustworthy eggplant on a platter", "सच्चा मित्र कभी थाली के बैंगन की तरह समय देखकर अपना रुख नहीं बदलता"),
    ("The two rival moneylenders were actually conspirators sharing the same bag", "दोनों साहूकार जनता को लूटने के लिए एक ही थैली के चट्टे बट्टे बने हुए थे"),
    ("The fragile earthen jar cannot withstand a heavy blow from an iron rod", "मिट्टी का नाज़ुक घड़ा लोहे की छड़ का भारी वार कभी सहन नहीं कर सकता"),
    ("His relentless crimes will soon fill the pot of his ruin to the brim", "उसके लगातार अपराध बहुत जल्द उसके विनाश का घड़ा भर देंगे"),
    ("A person without character behaves like a loose vegetable on a plate", "चरित्रहीन व्यक्ति संकट आते ही थाली के बैंगन की तरह पाला बदल लेता है"),
    ("All those corrupt officials are accomplices sharing the very same loot", "वे सभी भ्रष्ट अधिकारी जनता की गाढ़ी कमाई लूटने वाले एक ही थैली के चट्टे बट्टे हैं"),
    ("The farmer covered the mouth of the earthen water pot with a cloth", "किसान ने मिट्टी के मटके का मुँह साफ़ सूती कपड़े से बाँध दिया"),
    ("The vessel of his misdeeds broke and the truth came out in public", "उसके कुकर्मों का घड़ा फूट गया और सारा सच जनता के सामने आ गया"),
    ("Do not trust that slippery fellow who rolls about like a plate brinjal", "उस अविश्वसनीय व्यक्ति पर भरोसा मत करो जो थाली के बैंगन की तरह बदलता है"),
    ("The thieves and the corrupt watchman were partners of the very same purse", "चोर और बेईमान पहरेदार दोनों चोरी का माल बाँटने वाले एक ही थैली के चट्टे बट्टे थे"),

    # 176-215: लोहा, म्यान, तलवार, कंगन, आरसी (Iron, Sheath, Sword, Bangle, Mirror)
    ("The brave freedom fighters had to chew iron chickpeas during the revolt", "क्रांतिकारियों को स्वतंत्रता संग्राम के दौरान लोहे के चने चबाने पड़े थे"),
    ("Two sharp swords can never fit into a single leather scabbard", "दो शक्तिशाली प्रतिद्वंद्वी एक साथ नहीं रह सकते क्योंकि एक म्यान में दो तलवारें नहीं समातीं"),
    ("The obvious truth is self evident and needs no mirror to prove itself", "प्रत्यक्ष सत्य को प्रमाण की आवश्यकता नहीं होती क्योंकि हाथ कंगन को आरसी क्या"),
    ("The resolute hero accepted the iron challenge and stood firm like steel", "दृढ़निश्चयी नायक ने लोहा मान लिया और चट्टान की तरह अडिग खड़ा रहा"),
    ("The invading army had to chew iron chickpeas before capturing the mountain fort", "पहाड़ी किले पर अधिकार करने से पहले हमलावर सेना को लोहे के चने चबाने पड़े"),
    ("Two ambitious monarchs can never rule peacefully in the same royal court", "एक ही राजदरबार में दो महत्वाकांक्षी राजा नहीं टिक सकते क्योंकि एक म्यान में दो तलवारें नहीं रहतीं"),
    ("When the document clearly bears your signature what further evidence do you need", "जब दस्तावेज़ पर तुम्हारा हस्ताक्षर मौजूद है तो हाथ कंगन को आरसी क्या"),
    ("The foreign champion had to acknowledge the superior skill of the wrestler", "विदेशी पहलवान को भारतीय अखाड़े में हमारे पहलवान का लोहा मानना पड़ा"),
    ("The poor villagers made the greedy invaders chew bitter iron chickpeas", "साहसी ग्रामीणों ने अपनी भूमि की रक्षा करते हुए आक्रमणकारियों को लोहे के चने चबवा दिए"),
    ("Two proud queens could not share the palace as two blades reject one sheath", "दो घमंडी रानियाँ एक महल में नहीं रह सकतीं जैसे एक म्यान में दो तलवारें नहीं समातीं"),
    ("The evidence is crystal clear before everyone so no elaborate proof is required", "सच्चाई सबके सामने स्पष्ट है इसलिए हाथ कंगन को आरसी क्या की बात चरितार्थ होती है"),
    ("The entire empire acknowledged the matchless bravery of the young prince", "पूरे साम्राज्य ने युद्ध भूमि में युवा राजकुमार की अद्भुत वीरता का लोहा माना"),
    ("The mountain climbers had to endure severe hardship and chew iron grams", "बर्फीले पर्वत पर चढ़ते समय पर्वतारोहियों को लोहे के चने चबाने पड़े"),
    ("Two brilliant masters cannot manage one small workshop without rivalry", "एक छोटी कार्यशाला में दो बड़े उस्ताद नहीं रह सकते क्योंकि एक म्यान में दो तलवारें नहीं समातीं"),
    ("Look at the glowing result yourself because what is evident needs no glass", "सामने आए शानदार परिणाम को स्वयं देख लो क्योंकि हाथ कंगन को आरसी क्या"),
    ("The stubborn opponent finally acknowledged the invincible power of the army", "हठी विरोधी ने अंततः हमारी सेना की अजेय शक्ति का लोहा मान ही लिया"),
    ("The brave commander made the powerful enemy chew chickpeas of hard iron", "बहादुर सेनापति ने शक्तिशाली शत्रु सेना को युद्ध में लोहे के चने चबाने पर विवश कर दिया"),
    ("Two supreme commanders in a single army will only cause fatal confusion", "एक ही सेना में दो प्रधान सेनापति नहीं हो सकते क्योंकि एक म्यान में दो तलवारें नहीं समातीं"),
    ("Your outstanding victory is evident to all so why search for external proof", "तुम्हारी शानदार सफलता सबके सामने प्रत्यक्ष है और हाथ कंगन को आरसी क्या"),
    ("The great scholar made all learned critics acknowledge his profound wisdom", "विद्वान पंडित ने शास्त्रार्थ में सभी विद्वानों से अपने गहरे ज्ञान का लोहा मनवाया"),
    ("Passing that rigorous examination was like chewing chickpeas made of solid iron", "उस कठिन परीक्षा को पास करना किसी भी छात्र के लिए लोहे के चने चबाने जैसा था"),
    ("Peace was impossible between the two rival chieftains sharing the valley", "घाटी में दो विरोधी सरदारों के बीच शांति असंभव थी क्योंकि एक म्यान में दो तलवारें नहीं रहतीं"),
    ("The golden ornaments in the chest prove the wealth beyond all doubt", "तिजोरी में रखे सोने के आभूषण गवाही दे रहे हैं और हाथ कंगन को आरसी क्या"),
    ("The fierce gladiator made every challenger in the arena acknowledge his strength", "अखाड़े के हर लड़ाके को उस वीर योद्धा के बाहुबल का लोहा मानना पड़ा"),
    ("The pioneering explorers had to chew iron chickpeas in the arctic cold", "अंटार्कटिका की भीषण ठंड में खोजकर्ताओं को वास्तव में लोहे के चने चबाने पड़े थे"),
    ("Two ferocious tigers cannot inhabit the same rocky hill territory", "एक ही पहाड़ी गुफा में दो शिकारी बाघ नहीं रह सकते जैसे एक म्यान में दो तलवारें नहीं समातीं"),
    ("The visible injury on his arm proves that an assault occurred here", "हाथ पर लगा गहरा घाव खुद गवाही दे रहा है और हाथ कंगन को आरसी क्या"),
    ("Even the proudest conqueror had to acknowledge the spiritual power of the sage", "घमंडी विजेता को भी शांत तपस्वी की आत्मिक शक्ति का लोहा मानना पड़ा"),
    ("The small rebel militia made the royal battalions chew bitter iron chickpeas", "छोटे से विद्रोही दस्ते ने शाही पलटनों को घने जंगलों में लोहे के चने चबवा दिए"),
    ("Two greedy partners will soon destroy the business because of mutual rivalry", "दो लालची साझेदार व्यापार को चौपट कर देंगे क्योंकि एक म्यान में दो तलवारें नहीं समातीं"),
    ("The shining silver bangle on her wrist gleamed under the morning sunlight", "युवती की कलाई पर पहना हुआ चाँदी का सुंदर कंगन सुबह की धूप में चमक रहा था"),
    ("The ancient iron sword had sharp edges and an ornate golden hilt", "प्राचीन लोहे की तलवार की धार बहुत तेज़ थी और उसकी मूठ पर सोने की नक्काशी थी"),
    ("The honest mirror shows every wrinkle without bias or falsehood", "सच्चा दर्पण चेहरे की हर रेखा को बिना किसी पक्षपात के साफ़ दिखा देता है"),
    ("The blacksmith hammered the glowing red iron bar on the heavy anvil", "लोहार ने भारी निहाई पर रखकर लाल गरम लोहे की छड़ को हथौड़े से पीटा"),
    ("The skilled warrior drew his steel blade swiftly from the decorated scabbard", "कुशल योद्धा ने सुंदर नक्काशीदार म्यान से अपनी लोहे की तलवार बिजली की तरह निकाली"),
    ("The heavy iron lock on the treasury door was broken by the thieves", "तिजोरी के भारी लोहे के ताले को चोरों ने लोहे की सब्बल से तोड़ दिया"),
    ("The jeweller polished the antique silver mirror with a soft velvet cloth", "जौहरी ने मखमली कपड़े से प्राचीन चाँदी की आरसी को चमकने तक साफ़ किया"),
    ("The strong iron chains kept the fierce war elephant bound to the pillar", "मजबूत लोहे की जंजीरों ने मतवाले हाथी को पत्थर के खंभे से कसकर बाँध रखा था"),
    ("The mother gifted her daughter a pair of carved gold bangles for wedding", "माँ ने बेटी के विवाह के अवसर पर सोने के सुंदर नक्काशीदार कंगन उपहार में दिए"),
    ("The shining edge of the sword reflected the golden rays of the setting sun", "तलवार की चमकती धार पर ढलते हुए सूरज की सुनहरी किरणें नाच रही थीं"),

    # 216-250: तराजू, सुई, धागा, सिक्का, तिजोरी (Balance, Needle, Thread, Coin, Vault)
    ("The impartial judge held the scales of justice strictly in balance", "निष्पक्ष न्यायाधीश ने न्याय की तराजू को दोनों पलड़ों में बिल्कुल बराबर रखा"),
    ("The diligent tailor threaded the sharp steel needle with blue silk", "मेहनती दर्जी ने नुकीली सुई में नीले रेशम का बारीक धागा पिरोया"),
    ("The golden coin rolled across the polished marble floor of the palace", "सोने का चमकदार सिक्का राजमहल के चिकने संगमरमर के फर्श पर लुढ़क गया"),
    ("The honest merchant never tampered with the weights of his brass scales", "ईमानदार व्यापारी ने कभी अपने पीतल के तराजू के बाँटों में कोई हेराफेरी नहीं की"),
    ("The poor seamstress repaired the torn garments using a needle and thread", "गरीब दर्ज़िन ने सुई और धागे की सहायता से फटे हुए कपड़े की मरम्मत की"),
    ("The heavy iron safe protected the ancient jewels and royal treaties", "भारी लोहे की तिजोरी ने प्राचीन रत्नों और शाही संधियों को सुरक्षित रखा"),
    ("The silver coin jingled merrily in the leather pouch of the traveler", "यात्री की चमड़े की थैली में चाँदी का सिक्का सुखद आवाज़ के साथ खनका"),
    ("The clever thief tried to pry open the steel safe with an iron crowbar", "चालाक चोर ने लोहे की सब्बल से भारी तिजोरी को खोलने का असफल प्रयास किया"),
    ("A sharp needle can sew delicate garments that a heavy sword cannot touch", "जहाँ बारीक सुई का काम होता है वहाँ भारी तलवार कोई काम नहीं कर सकती"),
    ("The village elder weighed the grain carefully on the wooden balance", "गाँव के बुजुर्ग ने लकड़ी की तराजू पर अनाज को बड़ी सावधानी से तौला"),
    ("The fine cotton thread snapped under the sudden pull of the child", "बालक के अचानक खींचने से सूती कपड़े का बारीक धागा बीच में से टूट गया"),
    ("The king rewarded the honest servant with a bag of gold coins", "राजा ने ईमानदार सेवक को सोने के सिक्कों से भरी एक थैली पुरस्कार में दी"),
    ("The secret combination of the royal safe was known only to the minister", "शाही तिजोरी का गुप्त कोड केवल प्रधानमंत्री और कोषाध्यक्ष को ही पता था"),
    ("The tailor stitched the royal velvet robe with golden metallic threads", "दर्जी ने सुनहरे ज़री के धागों से राजा के मखमली चोगे की सुंदर सिलाई की"),
    ("The heavy balance tilted downward as more weight was added to one pan", "एक पलड़े में अधिक वजन रखने से भारी तराजू का काँटा नीचे झुक गया"),
    ("The copper coin had an image of a galloping horse carved upon it", "ताँबे के पुराने सिक्के पर दौड़ते हुए घोड़े का सुंदर चित्र अंकित था"),
    ("The blacksmith forged an unbreakable steel lock for the merchant safe", "लोहार ने व्यापारी की तिजोरी के लिए एक अटूट लोहे का ताला तैयार किया"),
    ("The embroidery artisan worked with needle and colored threads till dusk", "कशीदाकारी के कारीगर ने शाम तक रंगीन धागों और सुई से कपड़े पर बेलबूटे बनाए"),
    ("The honest shopkeeper balanced every transaction fairly on his scale", "ईमानदार दुकानदार ने तराजू के दोनों पलड़ों को हर ग्राहक के लिए समान रखा"),
    ("The ancient coins found in the earthen jar belonged to the Gupta empire", "मिट्टी के घड़े में से मिले प्राचीन सिक्के गुप्त साम्राज्य के काल के थे"),
    ("The seamstress searched the woven mat carefully for the dropped needle", "दर्ज़िन ने चटाई पर गिरी हुई बारीक सुई को बहुत ध्यान से ढूँढा"),
    ("The greedy usurer counted his shining coins inside the locked cellar", "लालची सूदखोर बंद तहखाने में बैठकर अपने चमकते सिक्के बार बार गिनता था"),
    ("The strong iron safe survived the devastating fire of the royal mansion", "हवेली में लगी भीषण आग के बाद भी लोहे की मजबूत तिजोरी सुरक्षित बची रही"),
    ("The young girl threaded the colorful glass beads onto a nylon cord", "छोटी लड़की ने नायलॉन के धागे में रंग बिरंगे काँच के मनके पिरोए"),
    ("The balance of truth will ultimately weigh every virtue and sin impartially", "सत्य की तराजू अंत में हर पुण्य और पाप को निष्पक्ष भाव से तौलेगी"),
    ("The sound of jingling coins attracted the attention of the highway robber", "खनकते सिक्कों की आवाज़ ने राजमार्ग के लुटेरे का ध्यान तुरंत अपनी ओर खींच लिया"),
    ("The master tailor used a silver thimble to push the needle through leather", "उस्ताद दर्जी ने चमड़े में सुई चुभाने के लिए चाँदी की अंगुश्ताना का उपयोग किया"),
    ("The banker deposited the precious royal pearls into the deep steel safe", "खज़ांची ने बहुमूल्य शाही मोतियों को लोहे की गहरी तिजोरी में सुरक्षित रख दिया"),
    ("The weaver spun fine cotton threads on the traditional wooden spinning wheel", "बुनकर ने लकड़ी के पारंपरिक चरखे पर सूत के बारीक धागे काते"),
    ("The antique bronze scale was displayed in the historical city museum", "ऐतिहासिक नगर के संग्रहालय में काँसे की प्राचीन तराजू को प्रदर्शित किया गया था"),
    ("A single gold coin was sufficient to purchase food for a whole month", "पूरे महीने का राशन खरीदने के लिए सोने का एक ही सिक्का काफी होता था"),
    ("The needle pierced the thick cloth and joined the two pieces together", "नुकीली सुई ने मोटे कपड़े को छेदकर दोनों टुकड़ों को मजबूती से जोड़ दिया"),
    ("The heavy safe was bolted firmly to the stone floor of the castle", "किले के पत्थर के फर्श पर भारी तिजोरी को लोहे के पेंचों से जकड़ा गया था"),
    ("The faithful servant returned the lost coin to its rightful owner", "वफादार सेवक ने गिरा हुआ सिक्का उसके असली मालिक को आदर सहित लौटा दिया"),
    ("Justice holds the balance evenly without fear favor or prejudice", "सच्चा न्याय बिना किसी भय या पक्षपात के तराजू को हमेशा सीधा रखता है"),
]

if __name__ == "__main__":
    process_batch(29, "p29s", PAIRS)
