#!/usr/bin/env python3
"""Batch VT-01: Habitual & Imperfective Aspects across All Persons (200 sentences).
File: data/phrases33.json, IDs: p33s001..p33s200.
Themes: Habitual aspect (-ता/-ती/-ते है/हैं/हूँ/हो), Past Habitual (-ता था/-ती थी/-ते थे), Future Habitual (-ता रहेगा/-ती रहेगी), Negative habitual (नहीं + stem).
Persons: मैं (m/f), तू (m/f), तुम (m/f), आप (m/f), वह (m/f), हम (m/f), वे (m/f).
"""
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parent))
from gen_batches_pipeline import process_batch

PAIRS = [
    # 1-35: मैं (First Person Singular - m & f, present/past/future habitual)
    ("I wake up early every morning and read classical books in the garden", "मैं हर सुबह जल्दी उठता हूँ और बगीचे में बैठकर पुरानी पुस्तकें पढ़ता हूँ"),
    ("I walk five kilometers daily along the bank of the quiet river", "मैं रोज़ शांत नदी के किनारे पाँच किलोमीटर पैदल चलती हूँ"),
    ("I always write detailed notes in my personal diary before going to bed", "मैं सोने से पहले अपनी निजी डायरी में हमेशा विस्तार से लिखता हूँ"),
    ("I drink warm cow milk with fragrant turmeric every evening after work", "मैं काम के बाद हर शाम हल्दी वाला गरम दूध पीती हूँ"),
    ("I study Sanskrit grammar diligently with the venerable temple scholar every weekend", "मैं हर सप्ताहांत विद्वान गुरुजी के साथ लगन से व्याकरण पढ़ता हूँ"),
    ("I never utter falsehood in front of the judge in the court", "मैं न्यायालय में न्यायाधीश के सामने कभी कोई झूठी बात नहीं बोलती"),
    ("I used to swim in the cool village pond during hot summer afternoons", "मैं गर्मियों की दोपहर में गाँव के ठंडे तालाब में तैरा करता था"),
    ("I used to weave fine cotton shawls on the old wooden handloom", "मैं पुराने करघे पर सूत की सुंदर शॉल बुना करती थी"),
    ("I used to visit the quiet mountain monastery during the annual rainy season", "मैं हर साल वर्षा ऋतु में उस शांत पहाड़ी आश्रम में जाया करता था"),
    ("I will always continue to speak the truth despite all difficult external pressures", "मैं सभी दबावों के बावजूद हमेशा केवल सत्य ही बोलता रहूँगा"),
    ("I will keep learning new musical ragas from my venerable classical music teacher", "मैं अपने गुरुजी से हमेशा नए शास्त्रीय राग सीखती रहूँगी"),
    ("I do not eat sweet confections because my doctor advised strict dietary restriction", "मैं मीठे पकवान नहीं खाता क्योंकि चिकित्सक ने परहेज़ की सख्त सलाह दी है"),
    ("I do not watch loud television broadcasts late in the quiet night hours", "मैं देर रात तक टीवी पर तेज़ आवाज़ वाले कार्यक्रम नहीं देखती"),
    ("I tend the fragrant rose plants in our family courtyard with great affection", "मैं पारिवारिक आँगन में खिले गुलाब के पौधों की बड़े प्यार से देखभाल करता हूँ"),
    ("I prepare warm herbal tea for my ailing grandmother every single morning", "मैं हर सुबह अपनी बीमार दादी के लिए गरम काढ़ा तैयार करती हूँ"),
    ("I practice classical archery in the open forest clearing before morning sunrise", "मैं सूर्योदय से पहले जंगल के मैदान में तीरंदाज़ी का अभ्यास करता हूँ"),
    ("I paint delicate landscape watercolors of the snowy Himalayan peaks during holidays", "मैं छुट्टियों में हिमालय की बर्फीली चोटियों के सुंदर चित्र बनाती हूँ"),
    ("I used to run across the green meadows with my pet dog happily", "मैं अपने पालतू कुत्ते के साथ हरे मैदानों में खुशी से दौड़ा करता था"),
    ("I used to sing folk songs with the village maidens during harvest", "मैं कटाई के समय गाँव की सहेलियों के साथ लोकगीत गाया करती थी"),
    ("I will continue to write honest historical chronicles for future generations to read", "मैं आने वाली पीढ़ियों के लिए निष्पक्ष इतिहास के पन्ने लिखता रहूँगा"),
    ("I will remain steadfast upon the sacred path of duty throughout my life", "मैं जीवन भर कर्तव्य के पावन मार्ग पर दृढ़ता से चलती रहूँगी"),
    ("I do not borrow money from greedy private moneylenders under any circumstances", "मैं किसी भी परिस्थिति में लालची साहूकारों से कर्ज़ नहीं लेता"),
    ("I do not waste precious morning hours in idle daydreams and procrastination", "मैं सुबह के अनमोल घंटों को व्यर्थ के आलस्य में नहीं गँवाती"),
    ("I teach arithmetic to the poor children of our neighborhood without charging fee", "मैं बिना कोई शुल्क लिए बस्ती के गरीब बच्चों को गणित पढ़ाता हूँ"),
    ("I bake fresh wheat bread on the iron griddle for my family", "मैं अपने परिवार के लिए लोहे के तवे पर ताज़ा रोटियाँ सेकती हूँ"),
    ("I used to ride my chestnut mare through the dense pine woodland", "मैं घने चीड़ के जंगल में अपनी भूरी घोड़ी दौड़ाया करता था"),
    ("I used to help my mother grind fresh spices on stone mortar", "मैं रसोई में सिलबट्टे पर मसाले पीसने में माँ की मदद किया करती थी"),
    ("I will always defend the rights of the weak in our village council", "मैं ग्राम सभा में निर्बलों के अधिकारों की रक्षा सदा करता रहूँगा"),
    ("I will keep lighting the evening lamp at the threshold of our cottage", "मैं अपनी कुटिया की देहरी पर शाम का दीपक सदा जलाती रहूँगी"),
    ("I do not harbor jealousy toward the legitimate success of my fellow peers", "मैं अपने साथियों की सच्ची सफलता पर मन में कोई द्वेष नहीं रखता"),
    ("I do not leave any work unfinished when the working day concludes peacefully", "मैं दिन समाप्त होने पर कोई भी काम अधूरा छोड़कर नहीं जाती"),
    ("I repair antique clockwork mechanisms with delicate steel tweezers and small magnifying glass", "मैं आवर्धक लेंस की सहायता से पुरानी घड़ियों के बारीक कलपुर्जे सुधारता हूँ"),
    ("I collect medicinal mountain roots from the high rocky slopes every autumn", "मैं हर पतझड़ में ऊँची पहाड़ी ढलानों से जड़ी बूटियाँ एकत्र करती हूँ"),
    ("I used to listen to the heroic legends told by my grandfather", "मैं अलाव के पास बैठकर दादाजी से वीरों की कहानियाँ सुना करता था"),
    ("I will always remember the valuable moral guidance given by my schoolmaster", "मैं अपने गुरुजी द्वारा दी गई उत्तम नैतिक शिक्षा को सदा याद रखती रहूँगी"),

    # 36-70: तू एवं तुम (Second Person Informal & Familiar - m & f)
    ("Thou speakest the truth fearlessly whenever injustice threatens the peaceful community", "तू अन्याय के सामने हमेशा बिना किसी डर के सच बोलता है"),
    ("Thou singest sweet devotional hymns in the temple every morning with pure devotion", "तू हर सुबह मंदिर में निर्मल भक्ति भाव से सुंदर भजन गाती है"),
    ("Thou usedst to run faster than the wind across the open pastures", "तू खुले मैदानों में हवा की गति से तेज़ दौड़ा करता था"),
    ("Thou usedst to weave colorful flower garlands for the festive village deities", "तू त्योहार के दिन देवताओं के लिए रंग बिरंगे फूलों की माला गूँथा करती थी"),
    ("Thou wilt continue to guide the wandering travelers through the dangerous mountain pass", "तू दुर्गम दर्रे में भटके हुए मुसाफिरों को रास्ता दिखाता रहेगा"),
    ("Thou wilt keep inspiring the timid youths with thy courageous and noble spirit", "तू अपनी अदम्य वीरता से डरपोक बालकों में नया साहस भरती रहेगी"),
    ("Thou dost not break thy sacred promise given to a trusting childhood companion", "तू अपने बचपन के सच्चे साथी को दिया गया वचन कभी नहीं तोड़ता"),
    ("Thou dost not neglect thy daily household chores even during festive celebrations", "तू त्योहार की खुशी में भी अपने घर के दैनिक काम नहीं भूलती"),
    ("You play the classical wooden flute with extraordinary sensitivity and melodic grace", "तुम लकड़ी की बांसुरी इतनी मधुर धुन में बजाते हो कि सब मुग्ध हो जाते हैं"),
    ("You write evocative Hindi poetry that touches the deepest core of human hearts", "तुम ऐसी सुंदर कविता लिखती हो जो हर संवेदनशील हृदय को छू लेती है"),
    ("You used to work together with the blacksmith in the noisy village smithy", "तुम गाँव की भट्टी में लोहार के साथ मिलकर कठिन परिश्रम किया करते थे"),
    ("You used to dance gracefully on stage during the annual spring festival celebrations", "तुम वसंत उत्सव के रंगारंग मंच पर बहुत सुंदर शास्त्रीय नृत्य किया करती थीं"),
    ("You will always uphold the moral prestige of your ancient ancestral family lineage", "तुम अपने कुल की मर्यादा और सम्मान की रक्षा सदा करते रहोगे"),
    ("You will keep tending the garden blossoms until spring returns to our valley", "तुम घाटी में नए वसंत के आने तक इन खिले फूलों की देखभाल करती रहोगी"),
    ("You do not lose your temper when faced with unfair and harsh provocations", "तुम अनुचित उकसावे के सामने भी अपना धैर्य और संयम कभी नहीं खोते"),
    ("You do not hide the truth from your parents under any circumstance whatever", "तुम किसी भी स्थिति में अपने माता पिता से कोई बात नहीं छिपातीं"),
    ("Thou risest before dawn and tillest the dry soil with thy wooden plow", "तू भोर होते ही उठकर अपने लकड़ी के हल से खेत जोतता है"),
    ("Thou milkest the gentle cows and churnest fresh butter in the earthen pot", "तू गाय का दूध दुहकर मिट्टी की हाँडी में ताज़ा मक्खन बिलोती है"),
    ("Thou usedst to fish along the quiet reed beds of the northern lake", "तू उत्तरी झील के किनारे बैठकर रोज़ मछलियाँ पकड़ा करता था"),
    ("Thou usedst to stitch delicate embroidery upon the velvet curtains of the palace", "तू मखमली पर्दों पर सुनहरे धागों से बारीक बेलबूटे काढ़ा करती थी"),
    ("Thou wilt shine like a steady beacon across the stormy waters of life", "तू जीवन के तूफानी समंदर में दिशा दिखाने वाले प्रकाश स्तंभ की तरह चमकता रहेगा"),
    ("Thou wilt keep defending the weak and helpless throughout thy honorable days", "तू अपने जीवन में हमेशा कमज़ोरों और दुखियों का सहारा बनती रहेगी"),
    ("Thou dost not envy the good fortune and prosperity of thy neighbors ever", "तू अपने पड़ोसियों की समृद्धि और उन्नति से मन में कभी नहीं जलता"),
    ("Thou dost not waste thy precious youth in idle and frivolous companionship", "तू अपना कीमती समय व्यर्थ की गपशप और आलस्य में नहीं गँवाती"),
    ("You cultivate healthy seasonal vegetables in your organic garden behind the house", "तुम अपने घर के पीछे वाले बगीचे में ताज़ा मौसमी सब्जियाँ उगाते हो"),
    ("You design beautiful architectural plans for modern sustainable and eco friendly homes", "तुम पर्यावरण के अनुकूल सुंदर और टिकाऊ घरों के नक्शे बनाती हो"),
    ("You used to study under the streetlamp when your house lacked electric light", "तुम बिजली न होने पर सड़क की बत्ती के नीचे बैठकर पढ़ा करते थे"),
    ("You used to make clay pottery vessels on the spinning traditional wooden wheel", "तुम चाक पर मिट्टी के सुंदर बर्तन और दीये बनाया करती थीं"),
    ("You will continue to excel in your medical studies at the central university", "तुम विश्वविद्यालय में अपनी चिकित्सा की पढ़ाई में हमेशा अव्वल आते रहोगे"),
    ("You will keep sharing your extensive knowledge with the younger generations of students", "तुम अपने ज्ञान का प्रकाश हमेशा नए विद्यार्थियों में बाँटती रहोगी"),
    ("You do not accept bribes while performing your administrative duties as public servant", "तुम सरकारी सेवा में रहते हुए कभी किसी से कोई अनुचित रिश्वत नहीं लेते"),
    ("You do not permit injustice to prevail in your court without firm challenge", "तुम अपनी आँखों के सामने कभी किसी निर्दोष के साथ अन्याय नहीं होने देतीं"),
    ("Thou walkest with righteous dignity through the dusty crowded avenues of the metropolis", "तू महानगर की भीड़ भरी गलियों में भी अपने स्वाभिमान के साथ चलता है"),
    ("Thou feedest the hungry stray animals outside thy doorstep every single dawn", "तू हर सुबह अपनी चौखट पर आने वाले बेजुबान पशुओं को खाना खिलाती है"),
    ("You maintain strict physical discipline and exercise daily in the traditional wrestling gymnasium", "तुम रोज़ सुबह पारंपरिक अखाड़े में जाकर कठिन शारीरिक व्यायाम करते हो"),

    # 71-105: आप (Second Person Formal/Honorific - m & f)
    ("You teach ancient philosophical texts with profound wisdom and scholarly patience", "आप प्राचीन दर्शन के ग्रंथों को अत्यंत गहरे ज्ञान और धैर्य से पढ़ाते हैं"),
    ("You manage the charitable hospital with remarkable administrative efficiency and deep compassion", "आप परोपकारी अस्पताल का संचालन अद्भुत कुशलता और सेवा भाव से करती हैं"),
    ("You used to advise the prime minister on critical matters of international diplomacy", "आप अंतरराष्ट्रीय मामलों पर प्रधानमंत्री को मूल्यवान कूटनीतिक सलाह दिया करते थे"),
    ("You used to lead the national symphony orchestra during grand international cultural festivals", "आप बड़े सांस्कृतिक समारोहों में राष्ट्रीय संगीत दल का सफल नेतृत्व किया करती थीं"),
    ("You will always remain a shining role model of integrity for all citizens", "आप देश के सभी नागरिकों के लिए सत्यनिष्ठा के आदर्श प्रेरणास्रोत बने रहेंगे"),
    ("You will keep guiding our research institute toward groundbreaking scientific discoveries and inventions", "आप हमारे शोध संस्थान को नई वैज्ञानिक उपलब्धियों की ओर लगातार ले जाती रहेंगी"),
    ("You do not compromise on the quality of education in your reputable academy", "आप अपनी प्रतिष्ठित अकादमी में शिक्षा की गुणवत्ता के साथ कोई समझौता नहीं करते"),
    ("You do not tolerate any financial corruption or dishonesty within your government department", "आप अपने प्रशासनिक विभाग में किसी भी प्रकार के भ्रष्टाचार को सहन नहीं करतीं"),
    ("You cultivate rare organic tea on your picturesque mountain estate in the east", "आप पूर्व के अपने सुंदर पहाड़ी बागान में दुर्लभ जैविक चाय की खेती करते हैं"),
    ("You write insightful commentaries on constitutional jurisprudence for the supreme national law journal", "आप राष्ट्रीय विधि पत्रिका के लिए संविधान के महत्वपूर्ण फैसलों पर टिप्पणी लिखती हैं"),
    ("You used to represent our sovereign republic as ambassador to historical European capitals", "आप यूरोपीय राजधानियों में हमारे देश के राजदूत के रूप में सेवा दिया करते थे"),
    ("You used to treat thousands of rural patients in remote inaccessible border villages", "आप सीमावर्ती दुर्गम गाँवों में जाकर हज़ारों निर्धन रोगियों की निःस्वार्थ सेवा किया करती थीं"),
    ("You will continue to inspire generations of young authors with your timeless prose", "आप अपने उत्कृष्ट लेखन से युवा लेखकों की नई पीढ़ियों को सदा प्रेरित करते रहेंगे"),
    ("You will keep fostering communal harmony through your cultural peace foundations and seminars", "आप अपने शांति सम्मेलनों के माध्यम से समाज में आपसी सद्भाव को बढ़ावा देती रहेंगी"),
    ("You do not yield to authoritarian pressure when upholding fundamental constitutional civil liberties", "आप नागरिकों के अधिकारों की रक्षा करते समय किसी तानाशाही दबाव के आगे नहीं झुकते"),
    ("You do not neglect the genuine welfare grievances of the humblest factory worker", "आप सबसे साधारण कारखाने के मजदूर की जायज़ समस्याओं की कभी अनदेखी नहीं करतीं"),
    ("You organize classical music concerts to preserve our intangible traditional artistic heritage", "आप हमारी अमूल्य शास्त्रीय संगीत परंपरा को सुरक्षित रखने के लिए सम्मेलन आयोजित करते हैं"),
    ("You supervise the archaeological excavations at the ancient Indus valley civilization site", "आप प्राचीन सिंधु घाटी सभ्यता के ऐतिहासिक स्थलों पर वैज्ञानिक उत्खनन का निर्देशन करती हैं"),
    ("You used to defend political dissidents without charging legal fees during turbulent times", "आप संकट के दौर में निर्दोष बंदियों के मुकदमे बिना कोई फीस लिए लड़ा करते थे"),
    ("You used to compose timeless classical poetry in the serene atmosphere of quiet hills", "आप शांत पहाड़ियों के सुरम्य वातावरण में बैठकर अमर शास्त्रीय काव्य रचा करती थीं"),
    ("You will always champion the cause of environmental conservation in our vulnerable river basin", "आप हमारी नदियों और वनों के संरक्षण के लिए हमेशा अग्रणी भूमिका निभाते रहेंगे"),
    ("You will keep mentoring young women scientists to break glass ceilings across academia", "आप विज्ञान के क्षेत्र में आगे बढ़ने वाली बालिकाओं का हमेशा मार्गदर्शन करती रहेंगी"),
    ("You do not endorse misleading commercial advertisements in your public scientific communication", "आप अपने वैज्ञानिक संवाद में कभी किसी भ्रामक विज्ञापन का समर्थन नहीं करते"),
    ("You do not permit partisan political bias to influence your objective editorial journalism", "आप अपनी निष्पक्ष पत्रकारिता में कभी किसी राजनीतिक दल का पक्षपात नहीं आने देतीं"),
    ("You build durable stone bridges connecting isolated mountain hamlets to regional markets", "आप सुदूर पहाड़ी गाँवों को बाज़ार से जोड़ने वाले मजबूत पुलों का निर्माण करते हैं"),
    ("You curate the priceless royal manuscript collection in the national central library archives", "आप राष्ट्रीय अभिलेखागार में दुर्लभ प्राचीन पांडुलिपियों के संग्रह की देखरेख करती हैं"),
    ("You used to command the elite mountain warfare brigade along the northern frontiers", "आप उत्तरी सीमा पर सेना की साहसी पर्वतीय टुकड़ी का गौरवशाली नेतृत्व किया करते थे"),
    ("You used to head the international human rights commission during delicate hostage negotiations", "आप अंतरराष्ट्रीय मानवाधिकार आयोग की प्रमुख के रूप में जटिल वार्ताओं का संचालन किया करती थीं"),
    ("You will continue to serve our university with unblemished scholarly distinction and wisdom", "आप अपनी अमूल्य विद्वता और ज्ञान से हमारे विश्वविद्यालय की प्रतिष्ठा सदा बढ़ाते रहेंगे"),
    ("You will keep promoting vernacular literature through your philanthropic publishing endowments and grants", "आप अपनी संस्था के माध्यम से लोक साहित्य के प्रचार प्रसार में सदैव योगदान देती रहेंगी"),
    ("You do not accept gifts from corporate lobbyists seeking special legislative tax exemptions", "आप कानून बनाते समय किसी भी व्यापारिक गुट से कोई अनुचित उपहार स्वीकार नहीं करते"),
    ("You do not compromise on the safety standards of passenger civil aviation aircraft", "आप यात्री विमानों के सुरक्षा नियमों के साथ कभी कोई छोटी सी लापरवाही नहीं होने देतीं"),
    ("You cultivate indigenous heirloom rice varieties to preserve biodiversity in our agriculture", "आप कृषि में विविधता बनाए रखने के लिए प्राचीन धान की किस्मों का संरक्षण करते हैं"),
    ("You conduct free medical surgeries for underprivileged children suffering from congenital heart disease", "आप जन्मजात हृदय रोग से पीड़ित गरीब बच्चों का मुफ्त ऑपरेशन करके नया जीवन देती हैं"),
    ("You embody the noble virtues of patience tolerance humility and deep selfless service", "आप अपने जीवन में धैर्य सहिष्णुता विनम्रता और निःस्वार्थ सेवा के पावन गुणों का साक्षात रूप हैं"),

    # 106-140: वह (Third Person Singular - m & f)
    ("He works tirelessly in the fields from sunrise until dusk to feed his family", "वह अपने परिवार का पेट भरने के लिए सुबह से शाम तक खेतों में पसीना बहाता है"),
    ("She teaches mathematics to high school students with great clarity and infinite patience", "वह हाई स्कूल के विद्यार्थियों को बहुत सरलता और असीम धैर्य से गणित पढ़ाती है"),
    ("He used to climb the rocky cliffs of the gorge to gather wild honey", "वह जंगली शहद इकट्ठा करने के लिए दर्रे की खतरनाक चट्टानों पर चढ़ा करता था"),
    ("She used to weave delicate silk patterns on the traditional wooden loom in village", "वह गाँव में पुराने लकड़ी के करघे पर रेशम के सुंदर नमूने बुना करती थी"),
    ("He will always remain loyal to the constitutional ideals of our democratic republic", "वह हमारे लोकतांत्रिक गणराज्य के पावन आदर्शों के प्रति सदा वफादार बना रहेगा"),
    ("She will keep striving until she achieves her lifelong ambition of becoming civil servant", "वह प्रशासनिक अधिकारी बनने का अपना सपना पूरा होने तक निरंतर प्रयास करती रहेगी"),
    ("He does not utter harsh or derogatory remarks against his opponents in debate", "वह वाद विवाद प्रतियोगिता में अपने विरोधियों के खिलाफ कभी कोई कटु शब्द नहीं बोलता"),
    ("She does not waste food and distributes leftovers to the hungry destitute people", "वह कभी भोजन व्यर्थ नहीं फेंकती और बचा हुआ खाना भूखों में बाँट देती है"),
    ("He rises at five every dawn to practice gymnastics in the municipal park", "वह हर सुबह पाँच बजे उठकर नगर के पार्क में व्यायाम का अभ्यास करता है"),
    ("She conducts scientific experiments on plant genetics in the university research greenhouse laboratory", "वह विश्वविद्यालय की प्रयोगशाला में पौधों के आनुवंशिक गुणों पर नए शोध करती है"),
    ("He used to herd cattle along the green banks of the river Yamuna", "वह यमुना के हरे कछारों में अपनी गायों और बछड़ों को चराया करता था"),
    ("She used to sing classical devotional bhajans at the ancient riverside marble temple", "वह नदी किनारे बने संगमरमर के प्राचीन मंदिर में शाम को भजन गाया करती थी"),
    ("He will continue to fight against social injustice through his fearless independent journalism", "वह अपनी निर्भीक और निष्पक्ष पत्रकारिता से सामाजिक बुराइयों के खिलाफ लड़ता रहेगा"),
    ("She will keep inspiring rural girls to pursue higher university education and sports", "वह गाँव की बेटियों को उच्च शिक्षा पाने और खेलों में भाग लेने के लिए प्रेरित करती रहेगी"),
    ("He does not bow before the arrogant threats of the local corrupt syndicate", "वह इलाके के भ्रष्ट दबंगों की खोखली धमकियों के आगे अपना सिर कभी नहीं झुकाता"),
    ("She does not charge medical consultation fees from poor destitute patients in hamlet", "वह गाँव के निर्धन और असहाय रोगियों से इलाज की कोई फीस नहीं लेती"),
    ("He sculpts realistic sandstone statues of historical heroes in his rustic suburban workshop", "वह अपनी कार्यशाला में बलुआ पत्थर से ऐतिहासिक वीरों की सजीव मूर्तियाँ बनाता है"),
    ("She translates ancient philosophical treatises from Sanskrit into simple accessible modern Hindi prose", "वह संस्कृत के गूढ़ दार्शनिक ग्रंथों का सरल और सुबोध हिंदी में अनुवाद करती है"),
    ("He used to deliver postal letters on bicycle to twenty distant mountain villages", "वह साइकिल पर बीस दुर्गम पहाड़ी गाँवों में चिट्ठियाँ पहुँचाया करता था"),
    ("She used to manage the family dairy farm with remarkable diligence and financial frugality", "वह बड़े अनुशासन और मितव्ययिता के साथ परिवार की पूरी डेयरी का काम संभालती थी"),
    ("He will always honor the sacrifices made by our freedom fighters with deep reverence", "वह स्वतंत्रता सेनानियों के अमर बलिदानों का हमेशा गहरे आदर के साथ स्मरण करता रहेगा"),
    ("She will keep preserving traditional herbal remedies inherited from her wise village grandmother", "वह अपनी दादी से सीखी हुई पारंपरिक जड़ी बूटियों की विद्या को सदा सुरक्षित रखेगी"),
    ("He does not participate in harmful communal rumors spread through unverified electronic messages", "वह अफ़वाहों और भ्रामक संदेशों पर भरोसा करके कभी किसी विवाद में भाग नहीं लेता"),
    ("She does not accept gifts from commercial contractors bidding for school textbook tenders", "वह पाठ्यपुस्तकों के ठेके देने के बदले किसी से कोई अनुचित उपहार नहीं लेती"),
    ("He trains stray street puppies into obedient and affectionate domestic companions for families", "वह सड़क के बेसहारा पिल्लों को पालकर उन्हें परिवारों के लिए वफादार साथी बनाता है"),
    ("She leads the village women cooperative bank with complete transparency and prudent accounting", "वह महिला सहकारी बैंक का संचालन पूरी पारदर्शिता और ईमानदारी के साथ करती है"),
    ("He used to sail the wooden fishing vessel through choppy coastal ocean waters", "वह तूफानी तटीय लहरों के बीच लकड़ी की मछली पकड़ने वाली नाव चलाया करता था"),
    ("She used to cultivate fragrant medicinal lavender flowers on the terraced hillside plots", "वह सीढ़ीदार पहाड़ी खेतों में सुगंधित लैवेंडर के फूलों की खेती किया करती थी"),
    ("He will continue to defend civil liberties before the highest judicial benches of republic", "वह देश की सर्वोच्च अदालतों में नागरिकों के अधिकारों की वकालत सदा करता रहेगा"),
    ("She will keep teaching digital literacy to elderly grandmothers in our rural community", "वह गाँव की बुजुर्ग महिलाओं को मोबाइल और कंप्यूटर चलाना हमेशा सिखाती रहेगी"),
    ("He does not neglect his daily morning physical fitness training even in winter", "वह कड़ाके की ठंड में भी अपने सुबह के व्यायाम को कभी नहीं छोड़ता"),
    ("She does not allow any student to feel neglected or discouraged in classroom", "वह अपनी कक्षा में किसी भी बालक को उपेक्षित या निराश महसूस नहीं होने देती"),
    ("He repairs broken agricultural diesel pumps for struggling farmers without taking monetary payment", "वह गरीब किसानों के खराब पड़े ट्यूबवेल के इंजन बिना पैसे लिए ठीक कर देता है"),
    ("She designs lightweight solar energy lamps for remote hamlets lacking electric grid access", "वह बिजली से वंचित बस्तियों के लिए सौर ऊर्जा से जलने वाले दीपक बनाती है"),
    ("He embodies the true spirit of quiet dedicated humble and uncomplaining hard work", "वह बिना किसी दिखावे के चुपचाप कर्तव्य निभाने वाले सच्चे कर्मयोगी का सजीव उदाहरण है"),

    # 141-170: हम (First Person Plural - m & f)
    ("We walk together through the pine forest every morning to breathe fresh air", "हम हर सुबह ताज़ा हवा लेने के लिए चीड़ के जंगल में सैर करते हैं"),
    ("We weave traditional cotton fabrics using natural vegetable dyes in our cooperative workshop", "हम अपनी सहकारी कार्यशाला में प्राकृतिक रंगों से सूती कपड़े तैयार करती हैं"),
    ("We used to study together under the great banyan tree in the village square", "हम गाँव के चौपाल वाले विशाल बरगद के नीचे एक साथ पढ़ा करते थे"),
    ("We used to sing patriotic anthems during national independence day school morning assemblies", "हम स्वतंत्रता दिवस पर स्कूल की प्रार्थना में देशभक्ति के गीत गाया करती थीं"),
    ("We will always stand united against any foreign aggression threatening our beloved motherland", "हम अपनी मातृभूमि की रक्षा के लिए विदेशी आक्रमण के सामने सदा एकजुट रहेंगे"),
    ("We will keep protecting the pristine biodiversity of our sacred Himalayan mountain rivers", "हम हिमालय की पावन नदियों और जंगलों की प्राकृतिक सुंदरता की सदा रक्षा करती रहेंगी"),
    ("We do not compromise on the high scientific ethical standards of medical research", "हम चिकित्सा शोध के उच्च नैतिक और वैज्ञानिक सिद्धांतों के साथ कोई समझौता नहीं करते"),
    ("We do not permit commercial builders to destroy our ancient heritage historical monuments", "हम अपने ऐतिहासिक स्मारकों को नुकसान पहुँचाने की किसी को अनुमति नहीं देतीं"),
    ("We cultivate organic wheat and mustard using traditional sustainable crop rotation farming methods", "हम अपनी उपजाऊ भूमि पर पारंपरिक तरीके से गेहूँ और सरसों की जैविक खेती करते हैं"),
    ("We manufacture handmade paper from discarded cotton rags and wild agricultural grass fibers", "हम पुराने कपड़ों और घास के रेशों से हस्तनिर्मित कागज़ बनाने का काम करती हैं"),
    ("We used to play football in the muddy village field during heavy monsoon rains", "हम बरसात के दिनों में कीचड़ भरे मैदान में खुशी से फुटबॉल खेला करते थे"),
    ("We used to enact historical dramatic plays during the annual autumn festival in town", "हम नगर के वार्षिक उत्सव के अवसर पर ऐतिहासिक नाटकों का मंचन किया करती थीं"),
    ("We will continue to advocate for universal quality healthcare for every impoverished rural citizen", "हम देश के हर निर्धन नागरिक को उत्तम स्वास्थ्य सेवा दिलाने के लिए संघर्ष करते रहेंगे"),
    ("We will keep training rural women in artisanal handicrafts and independent financial management", "हम गाँव की बहनों को आत्मनिर्भर बनाने के लिए हस्तशिल्प का प्रशिक्षण देती रहेंगी"),
    ("We do not engage in dishonest commercial practices or shortchanging in our family store", "हम अपनी पुश्तैनी दुकान में कभी किसी ग्राहक के साथ कोई बेईमानी नहीं करते"),
    ("We do not let petty sectarian disputes divide our historic composite cultural neighborhood", "हम आपसी सद्भाव और भाईचारे को किसी संकीर्ण विवाद से बिगड़ने नहीं देतीं"),
    ("We build affordable earthen houses using local sun dried mud bricks and thatch", "हम धूप में सुखाई गई मिट्टी की ईंटों से सस्ते और टिकाऊ मकान बनाते हैं"),
    ("We conduct free evening literacy classes for working street children across the city", "हम नगर के कामकाजी बच्चों के लिए शाम को मुफ्त पाठशाला का संचालन करती हैं"),
    ("We used to climb the high mountain passes to trade wool in Tibet", "हम सर्दियों से पहले ऊन का व्यापार करने के लिए ऊँचे दर्रों को पार किया करते थे"),
    ("We used to weave warm woolen blankets for the soldiers guarding freezing borders", "हम सीमा पर तैनात वीर जवानों के लिए गर्म ऊनी कंबल बुना करती थीं"),
    ("We will always uphold the secular democratic principles enshrined in our national constitution", "हम अपने संविधान में निहित धर्मनिरपेक्ष और लोकतांत्रिक मूल्यों की सदा रक्षा करते रहेंगे"),
    ("We will keep fighting for clean potable drinking water in all parched villages", "हम सूखे से प्रभावित हर गाँव में साफ़ पीने का पानी पहुँचाने का प्रयास करती रहेंगी"),
    ("We do not take recourse to violent means while conducting peaceful public protests", "हम अपने शांतिपूर्ण आंदोलनों में कभी किसी हिंसक रास्ते का सहारा नहीं लेते"),
    ("We do not conceal any audit records from public scrutiny in our organization", "हम अपनी संस्था के किसी भी वित्तीय हिसाब किताब को जनता से नहीं छिपातीं"),
    ("We plant ten thousand native fruit bearing saplings along highway margins every rainy season", "हम हर बरसात में राजमार्ग के दोनों ओर हज़ारों छायादार और फलदार वृक्ष लगाते हैं"),
    ("We run an animal rescue sanctuary for injured cows donkeys and abandoned horses", "हम घायल और बीमार बेजुबान पशुओं के उपचार के लिए आश्रय स्थल चलाती हैं"),
    ("We used to row heavy wooden cargo boats across the wide stormy river", "हम वर्षा ऋतु में उफनती नदी के पार भारी मालवाहक नावें चलाया करते थे"),
    ("We used to pick wild tea leaves on the misty slopes of Nilgiri", "हम नीलगिरि की धुंध भरी पहाड़ियों पर सुबह सुबह चाय की पत्तियाँ चुना करती थीं"),
    ("We will continue to champion the sacred cause of universal literacy and scientific temper", "हम समाज में वैज्ञानिक सोच और शिक्षा के प्रकाश को फैलाने का काम सदा करते रहेंगे"),
    ("We will keep preserving our mother tongue Hindi through rich cultural literature and education", "हम अपनी मातृभाषा हिंदी की सेवा और उसके साहित्य का संवर्धन सदा करती रहेंगी"),

    # 171-200: वे (Third Person Plural - m & f)
    ("They work with dedicated diligence in the iron foundries of the industrial city", "वे औद्योगिक नगर के लोहे के कारखानों में दिन रात कठिन परिश्रम करते हैं"),
    ("They design intricate handwoven silk sarees in the famous historic workshops of Varanasi", "वे काशी की ऐतिहासिक कार्यशालाओं में रेशम की बहुत सुंदर साड़ियाँ बुनती हैं"),
    ("They used to herd thousands of sheep across the high alpine Himalayan summer pastures", "वे गर्मियों में हज़ारों भेड़ों को लेकर हिमालय के ऊँचे चरागाहों में जाया करते थे"),
    ("They used to sing melodious harvest songs while cutting the golden wheat in spring", "वे वसंत में गेहूँ की कटाई करते समय खेत में मधुर लोकगीत गाया करती थीं"),
    ("They will always defend our territorial borders with supreme valor under all extreme weather", "वे हर विषम मौसम में देश की सीमाओं की रक्षा अदम्य वीरता के साथ करते रहेंगे"),
    ("They will keep illuminating the path of knowledge through their exemplary university teaching careers", "वे अपने उत्कृष्ट अध्यापन से छात्रों के जीवन को ज्ञान के प्रकाश से सदा आलोकित करती रहेंगी"),
    ("They do not yield to corrupt commercial inducements while awarding state infrastructure procurement contracts", "वे सरकारी ठेके देते समय किसी भी अनुचित आर्थिक प्रलोभन के आगे नहीं झुकते"),
    ("They do not discriminate against any patient on the grounds of creed or caste", "वे अस्पताल में इलाज करते समय किसी जाति या धर्म का कोई भेद नहीं करतीं"),
    ("They build sturdy ocean going vessels in the ancient shipyard on western coast", "वे पश्चिमी तट की पुरानी गोदी में समुद्र में चलने वाले बड़े जहाज़ बनाते हैं"),
    ("They manage the community watershed project to recharge groundwater reserves across the dry valley", "वे सूखी घाटी में जल संरक्षण के लिए चेकडैम और तालाबों का निर्माण करती हैं"),
    ("They used to brave heavy blizzards to deliver rations to remote mountain garrisons", "वे बर्फ़ीले तूफानों के बीच सीमा की चौकियों तक आवश्यक रसद पहुँचाया करते थे"),
    ("They used to embroider delicate golden threads on the wedding garments of royal brides", "वे राजसी वधुओं के परिधानों पर सोने के बारीक तारों से सुंदर कसीदाकारी किया करती थीं"),
    ("They will continue to preserve the authentic oral folk traditions of our tribal ancestors", "वे हमारे पूर्वजों की समृद्ध लोक संस्कृति और गीतों को सदा सुरक्षित रखते रहेंगे"),
    ("They will keep advocating for women equal inheritance rights in rural agricultural landholdings", "वे पैतृक भूमि में बेटियों के समान अधिकार के लिए कानूनी लड़ाई सदा लड़ती रहेंगी"),
    ("They do not compromise upon the structural safety norms of multi storey residential buildings", "वे आवासीय भवनों के निर्माण में सुरक्षा नियमों के साथ कभी कोई खिलवाड़ नहीं करते"),
    ("They do not let commercial interests pollute the sacred pristine mountain springs and streams", "वे प्राकृतिक झरनों और जल स्रोतों को किसी भी प्रकार से दूषित नहीं होने देतीं"),
    ("They forge unbreakable steel ploughshares and axes for agricultural laborers across the agrarian region", "वे पूरे कृषि क्षेत्र के किसानों के लिए मजबूत फाल और कुल्हाड़ियाँ बनाते हैं"),
    ("They research traditional medicinal plants to develop low cost botanical drugs for tropical fevers", "वे जड़ी बूटियों से सस्ती और अचूक दवाइयाँ विकसित करने के लिए निरंतर शोध करती हैं"),
    ("They used to cross the trackless desert with their heavily laden camel trading caravans", "वे माल से लदे ऊँटों के काफिले लेकर विशाल रेगिस्तान को पार किया करते थे"),
    ("They used to spin fine cotton yarn on hand spindles during the freedom struggle", "वे स्वतंत्रता संग्राम के दौरान चरखे पर सूत कातकर खादी के वस्त्र तैयार किया करती थीं"),
    ("They will always stand at the forefront of national scientific innovation and technological self reliance", "वे राष्ट्र की वैज्ञानिक प्रगति और आत्मनिर्भरता के अभियान में सदा अग्रणी भूमिका निभाते रहेंगे"),
    ("They will keep nurturing the young saplings until the hillside turns into lush forest", "वे पहाड़ी ढलानों पर नए पौधे लगाकर उन्हें घना जंगल बनाने का काम करती रहेंगी"),
    ("They do not abandon their duty even when facing severe threats from violent extremists", "वे उग्रवादियों की धमकियों के सामने भी अपने कर्तव्य पथ से कभी पीछे नहीं हटते"),
    ("They do not hoard essential life saving medicines to create artificial shortages in market", "वे बाज़ार में जीवन रक्षक दवाइयों की कृत्रिम किल्लत कभी पैदा नहीं होने देतीं"),
    ("They construct durable earthen dams to protect low lying villages from devastating seasonal floods", "वे निचले गाँवों को विनाशकारी बाढ़ से बचाने के लिए मजबूत बाँध बनाते हैं"),
    ("They educate illiterate adult women in evening community centers after exhausting daily farm work", "वे खेतों में दिन भर काम करने के बाद रात को अनपढ़ बहनों को पढ़ाती हैं"),
    ("They used to guard the mountain fortresses against hostile invaders with unyielding steadfast courage", "वे किले के फाटकों पर खड़े होकर दुश्मनों से अपनी मातृभूमि की रक्षा किया करते थे"),
    ("They used to paint vibrant frescoes on the interior walls of ancient cave temples", "वे गुफाओं के प्राचीन मंदिरों की दीवारों पर सुंदर और सजीव भित्तिचित्र बनाया करती थीं"),
    ("They will continue to uphold the highest judicial standards of constitutional integrity and fairness", "वे न्यायालय में निष्पक्ष न्याय और सत्य की गरिमा को सदा बनाए रखते रहेंगे"),
    ("They will keep inspiring the nation through their tireless pursuit of truth knowledge and service", "वे निःस्वार्थ सेवा ज्ञान और सत्य की साधना से पूरे समाज को सदा प्रेरणा देती रहेंगी"),
]

if __name__ == "__main__":
    process_batch(33, "p33s", PAIRS)
