#!/usr/bin/env python3
"""Batch ID-08: Classical, Literary & High Register Sayings (250 sentences).
File: data/phrases32.json, IDs: p32s001..p32s250.
Themes: गागर में सागर भरना, होनहार बिरवान के होत चीकने पात, दीपक तले अँधेरा, उल्टे बाँस बरेली को, पढ़े फारसी बेचे तेल, सौ सुनार की एक लोहार की, सत्यमेव जयते, वसुधैव कुटुम्बकम्.
"""
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parent))
from gen_batches_pipeline import process_batch

PAIRS = [
    # 1-35: गागर में सागर भरना (Conciseness, immense depth in few words)
    ("The great master poet expressed boundless philosophical depth in a single small couplet", "महाकवि ने अपने छोटे से दोहे में गागर में सागर भर दिया"),
    ("The brief diplomatic address contained immense wisdom and filled ocean into small pitcher", "संक्षिप्त भाषण में प्रधानमंत्री ने गागर में सागर भरने का कमाल कर दिखाया"),
    ("The classical miniature painting captured the entire grandeur of the royal court perfectly", "लघु चित्रकला के कलाकार ने छोटे से कैनवास पर गागर में सागर भर दिया"),
    ("In three simple sentences the wise sage explained the profound secret of existence", "तपस्वी ने तीन वाक्यों में जीवन का सार समझाकर गागर में सागर भर दिया"),
    ("A master writer knows how to pack ocean of meaning into few words", "कुशल लेखक थोड़े से शब्दों में गागर में सागर भरना अच्छी तरह जानता है"),
    ("The brilliant scientific formula summarized cosmic laws like an ocean in small jar", "वैज्ञानिक सूत्र ने ब्रह्मांड के नियमों को समेटकर गागर में सागर भर दिया"),
    ("The short poem described the profound agony of separation with touching brevity", "छोटी सी कविता ने विरह की गहरी वेदना को समेटकर गागर में सागर भर दिया"),
    ("The experienced lawyer summarized twenty volumes of evidence into one convincing argument", "वकील ने अपनी संक्षिप्त बहस में गागर में सागर भरकर न्यायाधीश को प्रभावित किया"),
    ("Bihari couplets are celebrated in Hindi literature for packing ocean into small pot", "कविवर बिहारी के दोहे गागर में सागर भरने के लिए साहित्य में अमर हैं"),
    ("The editorial column of the national newspaper captured public emotion in five paragraphs", "संपादकीय लेख ने देश की भावना को समेटते हुए गागर में सागर भर दिया"),
    ("A concise proverb can convey what hundred bulky volumes fail to explain", "एक छोटी सी कहावत गागर में सागर भरकर गहरा ज्ञान दे देती है"),
    ("The master architect designed a magnificent miniature palace within narrow garden grounds", "वास्तुकार ने छोटे से स्थान में सुंदर भवन बनाकर गागर में सागर भर दिया"),
    ("Her brief condolence letter brought immense comfort and filled ocean in small pitcher", "उसके संक्षिप्त पत्र ने शोक संतप्त परिवार के लिए गागर में सागर भर दिया"),
    ("The ancient aphorism holds profound spiritual illumination within four simple Sanskrit syllables", "प्राचीन सूत्र ने चार अक्षरों में गागर में सागर भरकर मोक्ष का मार्ग दिखाया"),
    ("The gifted orator explained complex economic policy to villagers with extraordinary succinctness", "वक्ता ने सीधे शब्दों में जटिल अर्थशास्त्र समझाकर गागर में सागर भर दिया"),
    ("This small handbook contains the essence of whole library like ocean in pot", "यह छोटी सी पुस्तिका पूरे पुस्तकालय का सार समेटकर गागर में सागर भरती है"),
    ("The brilliant satirist demolished the corrupt political regime with one devastating sharp epigram", "व्यंग्यकार ने एक तीखे जुमले में गागर में सागर भरकर सत्ता को हिला दिया"),
    ("With marvelous economy of words the story captures the tragedy of famine completely", "कहानीकार ने कम शब्दों में अकाल की विभीषिका समेटकर गागर में सागर भर दिया"),
    ("The summary statement at the conclusion of inquiry was truly masterly and complete", "जाँच समिति की अंतिम टिप्पणी ने पूरे मामले में गागर में सागर भर दिया"),
    ("The philosopher answered the complex metaphysical question with quiet brevity and grace", "दार्शनिक ने एक छोटे से दृष्टांत से गागर में सागर भरकर सबको चकित किया"),
    ("A true master artist requires no sprawling canvas to depict eternal human truth", "सच्चा कलाकार छोटी सी रचना में भी गागर में सागर भर देता है"),
    ("The tiny seed holds the memory of giant banyan tree within its core", "छोटा सा बीज अपने भीतर विशाल बरगद समेटकर गागर में सागर भरता है"),
    ("The brief preface to the epic poem outlined the entire mythological historical scope", "महाकाव्य की संक्षिप्त भूमिका ने पूरे ग्रंथ का गागर में सागर प्रस्तुत कर दिया"),
    ("Her three line haiku verse evoked the entire bittersweet melancholy of autumn leaves", "तीन पंक्तियों की कविता ने पतझड़ की उदासी समेटकर गागर में सागर भर दिया"),
    ("The brilliant strategist resolved the territorial crisis with one short and decisive letter", "कूटनीतिज्ञ ने एक संक्षिप्त संदेश भेजकर संकट में गागर में सागर भर दिया"),
    ("Proverbs are the refined jewels of language that pack boundless wisdom into grains", "कहावतें भाषा के वे रत्न हैं जो थोड़े में गागर में सागर भर देती हैं"),
    ("The insightful review captured both the glory and tragedy of the historical reign", "समीक्षक ने अपने छोटे से लेख में इतिहास का गागर में सागर प्रस्तुत किया"),
    ("He spoke only for five minutes yet illuminated the fundamental dispute completely", "पाँच मिनट के भाषण में वक्ता ने विवाद पर गागर में सागर भर दिया"),
    ("The master calligrapher expressed infinite spiritual yearning in one single golden stroke", "सुलेखक ने एक ही सुंदर अक्षर में अध्यात्म का गागर में सागर उड़ेल दिया"),
    ("A gifted tutor explains difficult geometry theorems with remarkable conciseness and clarity", "कुशल शिक्षक ने रेखागणित के जटिल प्रमेय में गागर में सागर भरकर समझाया"),
    ("The miniature carving on ivory displayed the entire celestial battle with astonishing detail", "हाथीदाँत की छोटी नक्काशी ने महाभारत के युद्ध का गागर में सागर दिखा दिया"),
    ("Her brief parting glance conveyed more love than twenty sentimental passionate speeches", "उसकी एक विदाई दृष्टि ने प्रेम के भावों में गागर में सागर भर दिया"),
    ("The epilogue of the novel brought every tangled narrative thread together with elegance", "उपन्यास के उपसंहार ने सभी कथा सूत्रों को समेटकर गागर में सागर भर दिया"),
    ("True literary genius consists in saying much with very few chosen words", "सच्ची साहित्यिक प्रतिभा वही है जो थोड़े शब्दों में गागर में सागर भर सके"),
    ("The ancient physician condensed pharmacology into thirty memorable rhythmic medical verses", "प्राचीन वैद्य ने आयुर्वेद के पूरे ज्ञान को श्लोकों में गागर में सागर बना दिया"),

    # 36-70: होनहार बिरवान के होत चीकने पात (Genius and destiny show in early signs)
    ("The child showed brilliant arithmetic skill proving that promising saplings have glossy leaves", "बालक की प्रतिभा देखकर सबने कहा कि होनहार बिरवान के होत चीकने पात"),
    ("From early childhood the future emperor displayed courage and generous leadership qualities", "बचपन से ही भावी राजा के लक्षण बता रहे थे कि होनहार बिरवान के होत चीकने पात"),
    ("The little girl sang classical melodies perfectly in her very first music lesson", "बालिका का पहला गायन सुनकर गुरुजी बोले कि होनहार बिरवान के होत चीकने पात"),
    ("His childhood curiosity and innovative inventions showed the future world renowned scientist", "बचपन के प्रयोगों ने साबित कर दिया कि होनहार बिरवान के होत चीकने पात"),
    ("The young apprentice mastered difficult wood carvings with effortless grace and precision", "युवा कारीगर के पहले काम ने दिखा दिया कि होनहार बिरवान के होत चीकने पात"),
    ("Even in primary school games the boy demonstrated extraordinary athletic stamina and speed", "प्राथमिक विद्यालय के खेल में ही दिख गया कि होनहार बिरवान के होत चीकने पात"),
    ("The tender sapling reveals the future shade of the giant tree very early", "पौधे की पहली कोपलें बता देती हैं कि होनहार बिरवान के होत चीकने पात"),
    ("From his youth the prince displayed profound compassion and wisdom toward all citizens", "युवावस्था के सद्गुणों ने सिद्ध कर दिया कि होनहार बिरवान के होत चीकने पात"),
    ("The young poet recited evocative verses that astonished the gathered assembly of scholars", "बालक की पहली कविता ने विद्वानों को दिखा दिया कि होनहार बिरवान के होत चीकने पात"),
    ("Her instinctive skill in horse riding surprised the veteran royal cavalry instructors completely", "सवारी में बालिका की निपुणता ने साबित किया कि होनहार बिरवान के होत चीकने पात"),
    ("The childhood sketches of the artist already showed astonishing mastery of light shadows", "बालक के पहले रेखाचित्रों ने बता दिया कि होनहार बिरवान के होत चीकने पात"),
    ("Early discipline and sharp intellect forecast the future eminence of the young scholar", "छात्र के शुरुआती अनुशासन ने दिखा दिया कि होनहार बिरवान के होत चीकने पात"),
    ("The little boy led his playmates with natural authority fairness and noble tact", "खेल में नेतृत्व देखकर बुजुर्गों ने कहा कि होनहार बिरवान के होत चीकने पात"),
    ("Her remarkable early courage during the village fire proved her future heroic nature", "साहसी बालिका के पहले कारनामे ने दिखा दिया कि होनहार बिरवान के होत चीकने पात"),
    ("From the beginning the young archer hit the bullseye with steady calm confidence", "निशानेबाज़ी के पहले अभ्यास से ही स्पष्ट था कि होनहार बिरवान के होत चीकने पात"),
    ("The child took apart clockwork toys and assembled them back with perfect accuracy", "यंत्र सुधारने में बालक की लगन ने साबित किया कि होनहार बिरवान के होत चीकने पात"),
    ("Early seeds of righteous conduct bloom into magnificent character during adult mature years", "बचपन के शुभ संस्कार ही बताते हैं कि होनहार बिरवान के होत चीकने पात"),
    ("The young debater outwitted university students with razor sharp logic and calm demeanor", "छात्र के पहले शास्त्रार्थ ने दिखा दिया कि होनहार बिरवान के होत चीकने पात"),
    ("His childhood generosity in sharing sweets foreshadowed his future role as great philanthropist", "बालक के बचपन के त्याग ने सिद्ध कर दिया कि होनहार बिरवान के होत चीकने पात"),
    ("The young flute player held the entire village spellbound with divine soulful melodies", "बांसुरी की पहली तान से ही सब जान गए कि होनहार बिरवान के होत चीकने पात"),
    ("The infant showed fearless curiosity toward wild animals in the forest hunting camp", "जंगल में बालक की निर्भीकता ने साबित कर दिया कि होनहार बिरवान के होत चीकने पात"),
    ("Her early mastery of multiple languages astounded foreign ambassadors visiting the imperial court", "भाषा सीखने की अद्भुत प्रतिभा देखकर सब बोले कि होनहार बिरवान के होत चीकने पात"),
    ("The boy repaired his father broken plow showing innate mechanical engineering talent early", "हल ठीक करने में बालक की समझ ने दिखा दिया कि होनहार बिरवान के होत चीकने पात"),
    ("From childhood the future general drew intricate battle tactical formations in the sand", "रेत पर युद्ध व्यूह बनाने वाले बालक के लक्षण थे कि होनहार बिरवान के होत चीकने पात"),
    ("Her compassionate nursing of wounded birds revealed her future destiny as a healer", "घायल पक्षियों की सेवा देखकर दादी बोलीं कि होनहार बिरवान के होत चीकने पात"),
    ("The young chess prodigy defeated the grand champion in twenty moves with smile", "शतरंज के खेल में बालक की चालों ने दिखा दिया कि होनहार बिरवान के होत चीकने पात"),
    ("Early diligence in morning studies forecasted his academic success at the royal academy", "प्रातःकाल की लगन देखकर पिता समझ गए कि होनहार बिरवान के होत चीकने पात"),
    ("The little girl defended her weaker classmate with fierce sense of natural justice", "न्याय की भावना देखकर शिक्षक ने कहा कि होनहार बिरवान के होत चीकने पात"),
    ("The first sculpture shaped by the apprentice showed signs of extraordinary artistic immortality", "पहली मूर्ति बनाते ही गुरु समझ गए कि होनहार बिरवान के होत चीकने पात"),
    ("His early calm under dangerous crisis marked him out as future crisis leader", "संकट में बालक का धैर्य देखकर सबने माना कि होनहार बिरवान के होत चीकने पात"),
    ("The young student read difficult Sanskrit commentaries with effortless intuitive ease and pleasure", "कठिन ग्रंथों को आसानी से पढ़ते देखकर गुरु बोले कि होनहार बिरवान के होत चीकने पात"),
    ("Her graceful first dance steps on stage forecasted her future international classical renown", "नृत्य के पहले घुंघरुओं ने बता दिया कि होनहार बिरवान के होत चीकने पात"),
    ("The child showed deep reverence toward books and learning from his earliest toddler days", "पुस्तकों के प्रति आदर देखकर सबने कहा कि होनहार बिरवान के होत चीकने पात"),
    ("The future statesman pacified neighborhood childhood disputes with remarkable wisdom and sweet patience", "झगड़े सुलझाने की कला ने दिखा दिया कि होनहार बिरवान के होत चीकने पात"),
    ("Signs of greatness appear in the cradle just as leaves shine on sapling", "पालने में ही वीर के लक्षण दिख जाते हैं जैसे होनहार बिरवान के होत चीकने पात"),

    # 71-105: दीपक तले अँधेरा (Darkness beneath lamp, ignorance close to source)
    ("The great education minister son failed all his basic school matriculation exams", "शिक्षा मंत्री का बेटा परीक्षा में फेल हो गया इसे कहते हैं दीपक तले अँधेरा"),
    ("The famous eye surgeon was completely blind to the cataract of his wife", "नेत्र विशेषज्ञ अपनी पत्नी की बीमारी न देख सका यह दीपक तले अँधेरा है"),
    ("The celebrated judge brother was caught red handed engaging in illegal black marketeering", "न्यायाधीश के घर में भाई की बेईमानी सचमुच दीपक तले अँधेरा साबित हुई"),
    ("The police station premises were looted by daring highway bandits at broad midnight", "थाने के ठीक सामने चोरी हो गई इसे कहते हैं दीपक तले अँधेरा"),
    ("The renowned priest daughter ran away with the notorious drunken village tavern keeper", "धर्मात्मा के घर में ऐसा अनर्थ होना वास्तव में दीपक तले अँधेरा दर्शाता है"),
    ("There is dense darkness right beneath the glowing brass lamp of the shrine", "मंदिर के जगमगाते दीये के ठीक नीचे दीपक तले अँधेरा साफ दिखाई देता है"),
    ("The wealthy banker family lived in miserable debt and bitter mutual recrimination privately", "धनी बैंकर के घर में कंगाली का माहौल होना दीपक तले अँधेरा कहलाता है"),
    ("The city light plant plunged into complete pitch darkness during the regional blackout", "बिजली घर के अपने ही परिसर में अंधेरा छाना दीपक तले अँधेरा है"),
    ("The great moral philosopher abused his domestic servants with shocking unbridled cruelty", "नीतिशास्त्र के शिक्षक का घर में क्रूर व्यवहार दीपक तले अँधेरा दिखाता है"),
    ("The famous detective could not discover that his personal driver was the burglar", "जासूस अपने ही चालक की चोरी न पकड़ सका यह दीपक तले अँधेरा हुआ"),
    ("The champion swimmer daughter drowned in two feet of garden swimming pool water", "तैराक की संतान का पानी में डूबना सचमुच दीपक तले अँधेरा की मिसाल है"),
    ("The author of bestselling health manuals suffered from chronic obesity and uncontrolled diabetes", "स्वास्थ्य पर पुस्तकें लिखने वाले का खुद बीमार रहना दीपक तले अँधेरा है"),
    ("The anti corruption officer was arrested for taking huge bribes in secret vault", "भ्रष्टाचार विरोधी अधिकारी का रिश्वत लेना दीपक तले अँधेरा की पराकाष्ठा है"),
    ("The renowned fire station caught fire and burned down before engines could respond", "अग्निशमन केंद्र में ही आग लग जाना हास्यास्पद दीपक तले अँधेरा साबित हुआ"),
    ("The scholar who taught Sanskrit grammar spoke crude abusive street slang at home", "व्याकरण के पंडित की घर में अशुद्ध भाषा दीपक तले अँधेरा दर्शाती है"),
    ("The grand royal library was infested with mice that devoured the precious manuscripts", "पुस्तकालय में ही चूहों द्वारा ग्रंथों का कतरना दीपक तले अँधेरा है"),
    ("The famous marriage counselor divorced his own third wife after bitter public litigation", "वैवाहिक सलाहकार का खुद तलाक लेना दीपक तले अँधेरा की दुखद कहानी है"),
    ("A lamp sheds illumination all around while its own pedestal remains in shadow", "दीपक चारों ओर उजाला देता है पर अपने नीचे दीपक तले अँधेरा रखता है"),
    ("The security guard house was broken into while he patrolled the perimeter wall", "चौकीदार के अपने ही घर में चोरी होना दीपक तले अँधेरा साबित हुआ"),
    ("The great preacher son became an atheist and ridiculed all sacred temple rituals", "उपदेशक की संतान का नास्तिक होना समाज के लिए दीपक तले अँधेरा बना"),
    ("The tax commissioner evaded paying local municipal property taxes for twenty long years", "कर अधिकारी का खुद कर चोरी करना घोर दीपक तले अँधेरा है"),
    ("The headmaster children were expelled for truancy and disruptive behavior in the classroom", "प्रधानाचार्य के बच्चों का स्कूल से निकाला जाना दीपक तले अँधेरा दिखाता है"),
    ("The environmental scientist dumped toxic plastic waste in his own backyard garden pond", "पर्यावरणविद द्वारा घर में कचरा फैलाना दीपक तले अँधेरा की मिसाल है"),
    ("The hospital chief medical officer died of preventable waterborne infection within the ward", "अस्पताल के निदेशक का संक्रमण से मरना दीपक तले अँधेरा की विडंबना है"),
    ("The royal watchtower was the only post that failed to spot invading armada", "पहरे की मुख्य मीनार से ही शत्रु का न दिखना दीपक तले अँधेरा था"),
    ("The master locksmith could not unlock his own front door when keys broke", "ताला बनाने वाले का अपने ही घर में बंद होना दीपक तले अँधेरा है"),
    ("The celebrated peace activist constantly quarreled with all his immediate next door neighbors", "शांति के मसीहा का पड़ोसियों से लड़ना दीपक तले अँधेरा दिखाता है"),
    ("The wealthy goldsmith daughter wore fake brass jewelry on her festive wedding day", "जौहरी की बेटी का नकली गहने पहनना सचमुच दीपक तले अँधेरा कहलाता है"),
    ("The great legal reformer was ignorant of basic municipal tenancy bylaws in village", "कानून के ज्ञाता का साधारण नियम न जानना दीपक तले अँधेरा साबित हुआ"),
    ("The temple treasurer was caught stealing the silver coins from the sacred charity box", "कोषाध्यक्ष का खुद दानपात्र से चोरी करना दीपक तले अँधेरा दर्शाता है"),
    ("The famous meteorologist was caught in sudden thunderstorm without coat or folding umbrella", "मौसम वैज्ञानिक का बिना छाते के भीगना दीपक तले अँधेरा की हास्यप्रद बात है"),
    ("The spiritual guru brother ran an illegal gambling den in the neighboring street", "गुरुजी के भाई का जुआघर चलाना सचमुच दीपक तले अँधेरा की घटना है"),
    ("The agricultural minister farm suffered drought while neighboring peasant fields were irrigated", "कृषि मंत्री के खेत का सूखा रहना दीपक तले अँधेरा साबित हुआ"),
    ("Ignorance dwelling closest to the fountain of knowledge is the saddest paradox", "ज्ञान के केंद्र के पास ही अज्ञान का होना दीपक तले अँधेरा कहलाता है"),
    ("The grand lighthouse keeper ship crashed upon the jagged rocks below his tower", "प्रकाश स्तंभ के नीचे ही जहाज का टकराना दीपक तले अँधेरा की त्रासदी है"),

    # 106-140: उल्टे बाँस बरेली को (Superfluous action, carrying coals to Newcastle)
    ("Exporting cheap timber to the dense forest country is like taking bamboo to Bareilly", "जंगल वाले देश में लकड़ी बेचना उल्टे बाँस बरेली को भेजने जैसा है"),
    ("Teaching basic arithmetic to the mathematics professor was carrying bamboo to Bareilly city", "गणित के विद्वान को गिनती सिखाना उल्टे बाँस बरेली को ले जाने जैसा था"),
    ("Offering simple clay lamps to the holy city of lights was completely superfluous", "रोशनी के शहर में दीये ले जाना उल्टे बाँस बरेली को भेजने जैसा मूर्खतापूर्ण है"),
    ("Selling woven silk fabrics in the weaver town was utter waste of trading effort", "बुनकरों के नगर में कपड़ा बेचना उल्टे बाँस बरेली को ले जाना साबित हुआ"),
    ("Bringing fresh water pitchers to the bank of the mighty overflowing Ganga river", "गंगा के किनारे पानी का घड़ा ले जाना उल्टे बाँस बरेली को भेजने जैसा है"),
    ("Gifting ordinary mangoes to the owner of five hundred fertile mango orchards", "बागवान को आम भेंट करना सचमुच उल्टे बाँस बरेली को ले जाने जैसा लगा"),
    ("Trying to lecture the supreme court chief justice on constitutional fundamental legal principles", "मुख्य न्यायाधीश को कानून सिखाना उल्टे बाँस बरेली को भेजने की हास्यास्पद बात है"),
    ("Taking coals to the mining valley is a proverbial instance of futile labor", "कोयले की खान में कोयला ले जाना उल्टे बाँस बरेली को भेजने जैसा व्यर्थ है"),
    ("Selling sweet sugarcane stalks to the bustling sugar refinery in the industrial zone", "चीनी मिल के मालिक को गन्ना बेचना उल्टे बाँस बरेली को ले जाना है"),
    ("Advising the seasoned veteran mountain guide on which narrow pass to cross safely", "पहाड़ी गाइड को रास्ता बताना उल्टे बाँस बरेली को भेजने जैसा निरर्थक है"),
    ("Offering sea salt to the coastal salt pan workers was greeted with mockery", "नमक के कारीगरों को नमक देना उल्टे बाँस बरेली को ले जाने जैसा लगा"),
    ("Carrying printed books to the ancient university library was an unnecessary commercial venture", "पुस्तकालय में सामान्य पुस्तकें बेचना उल्टे बाँस बरेली को भेजने जैसा था"),
    ("Selling hot fragrant tea in the lush hill slopes of famous tea plantations", "चाय के बागानों में चाय पत्ती बेचना उल्टे बाँस बरेली को ले जाना है"),
    ("Teaching swimming techniques to the agile dolphin or crocodile in the deep river", "मछली को तैरना सिखाना उल्टे बाँस बरेली को भेजने जैसा हास्यास्पद प्रयास है"),
    ("Offering ordinary gravel stones to the owner of rich diamond and emerald mines", "रत्नों के व्यापारी को कंकड़ भेंट करना उल्टे बाँस बरेली को ले जाना है"),
    ("Taking fresh cow milk to the pastoral village known for hundred dairy farms", "ग्वालों के गाँव में दूध बेचना उल्टे बाँस बरेली को भेजने जैसा व्यर्थ काम है"),
    ("Attempting to teach Sanskrit recitation to the venerable Varanasi temple scholars and priests", "काशी के पंडितों को संस्कृत पढ़ाना उल्टे बाँस बरेली को ले जाना कहलाता है"),
    ("Selling warm woolen blankets in the scorching midday heat of Thar desert summer", "रेगिस्तान की तपती दोपहर में कंबल बेचना उल्टे बाँस बरेली को ले जाना है"),
    ("Carrying rose perfumes to the famous perfume manufacturing historic capital of Kannauj", "कन्नौज में इत्र बेचना सचमुच उल्टे बाँस बरेली को भेजने की पुरानी मिसाल है"),
    ("Instructing the master goldsmith on how to solder delicate links of gold chain", "सुनार को गहने जोड़ना सिखाना उल्टे बाँस बरेली को ले जाने जैसा लगा"),
    ("Bringing common pottery jars to the village celebrated for master terracotta craft pottery", "कुम्हारों के गाँव में मटके बेचना उल्टे बाँस बरेली को भेजने जैसा व्यर्थ है"),
    ("Offering ordinary grain bags to the central state agricultural reserve granary storehouses", "अन्न के भंडार में एक बोरी अनाज ले जाना उल्टे बाँस बरेली को ले जाना है"),
    ("Advising the master shipwright on how to caulk the wooden hull of galleon", "नाव बनाने वाले को कील ठोकना सिखाना उल्टे बाँस बरेली को भेजने जैसा था"),
    ("Taking fresh fish to the bustling fishing harbor at the morning catch arrival", "मछुआरों की बस्ती में मछली बेचना उल्टे बाँस बरेली को ले जाने जैसा लगा"),
    ("Selling brass bells in the temple pilgrimage town famous for brass metal foundries", "पीतल के नगर में घंटियाँ बेचना उल्टे बाँस बरेली को भेजने का उदाहरण है"),
    ("Instructing the royal court poet on how to construct a sixteen syllable meter", "राजकवि को छंद शास्त्र सिखाना उल्टे बाँस बरेली को ले जाने जैसा दुस्साहस था"),
    ("Bringing palm leaves to the tropical palm grove along the southern coastal lagoon", "ताड़ के जंगल में ताड़ के पत्ते ले जाना उल्टे बाँस बरेली को भेजना है"),
    ("Teaching horse riding to the nomadic cavalry warrior born upon the saddle back", "घुड़सवार योद्धा को लगाम पकड़ना सिखाना उल्टे बाँस बरेली को ले जाना है"),
    ("Selling woven carpets in the historic Persian craft bazaar of ancient master weavers", "कालीन के बाज़ार में दरी बेचना उल्टे बाँस बरेली को भेजने जैसा साबित हुआ"),
    ("Taking firewood to the dense primeval pine forest on the high snowy ridge", "घने जंगल में सूखी लकड़ियाँ ले जाना उल्टे बाँस बरेली को ले जाना है"),
    ("Offering basic culinary cooking advice to the royal banquet master executive head chef", "प्रधान बावर्ची को तड़का लगाना सिखाना उल्टे बाँस बरेली को भेजने जैसा था"),
    ("Selling ice blocks to the native hunters living in the arctic igloo settlement", "बर्फ़ के देश में बर्फ़ बेचना उल्टे बाँस बरेली को ले जाने जैसा मूर्खतापूर्ण है"),
    ("Taking holy water drops to the sacred confluence of three great eternal rivers", "त्रिवेणी संगम पर जल ले जाना उल्टे बाँस बरेली को भेजने जैसा निरर्थक है"),
    ("Giving military archery advice to the greatest undefeated legendary warrior of the age", "महान धनुर्धर को तीर चलाना सिखाना उल्टे बाँस बरेली को ले जाना कहलाता है"),
    ("Do not engage in superfluous commercial ventures that carry bamboo to Bareilly markets", "ऐसे व्यापार में समय मत गँवाओ जो उल्टे बाँस बरेली को भेजने जैसा व्यर्थ हो"),

    # 141-175: पढ़े फारसी बेचे तेल (Underemployment, talent wasted)
    ("The brilliant postgraduate scholar was forced to work as a manual street sweeper", "उच्च शिक्षित विद्वान का झाड़ू लगाना दर्शाता है कि पढ़े फारसी बेचे तेल"),
    ("Holding a master degree in engineering he had to sell fried snacks daily", "इंजीनियरिंग करके पकोड़े बेचना सचमुच पढ़े फारसी बेचे तेल वाली विडंबना है"),
    ("The talented linguist could find no job and drove a hired auto rickshaw", "कई भाषाएं जानने वाले का रिक्शा चलाना पढ़े फारसी बेचे तेल जैसा दुखद है"),
    ("After studying classical literature for ten years he worked as a night watchman", "साहित्य पढ़कर चौकीदारी करना इस बात का प्रमाण है कि पढ़े फारसी बेचे तेल"),
    ("The qualified doctor had to manage a small village grocery shop for livelihood", "चिकित्सक की उपाधि लेकर परचून की दुकान चलाना पढ़े फारसी बेचे तेल की कहानी है"),
    ("Unemployment in the country forces educated youths into humiliating and menial labor daily", "बेरोजगारी के कारण नौजवानों का यह हाल है कि पढ़े फारसी बेचे तेल"),
    ("The accomplished pianist had to load heavy sacks of cement at railway depot", "प्रतिभाशाली संगीतकार का बोरी ढोना सचमुच पढ़े फारसी बेचे तेल की त्रासदी है"),
    ("He mastered complex theoretical physics and ended up working as an office peon", "भौतिकी के विद्वान का चपरासी बनना दर्शाता है कि पढ़े फारसी बेचे तेल"),
    ("A certified advocate was reduced to selling cheap plastic ballpoint pens on trains", "वकील का रेलगाड़ी में पेन बेचना इसी बात को सिद्ध करता है कि पढ़े फारसी बेचे तेल"),
    ("When talent finds no worthy scope high qualifications lead to selling mustard oil", "जब योग्यता का मान न हो तो विद्वान को भी पढ़े फारसी बेचे तेल करना पड़ता है"),
    ("The young mathematician had to work as a cashier at a fast food counter", "गणित के मेधावी छात्र का ढाबे पर बिल काटना पढ़े फारसी बेचे तेल की मिसाल है"),
    ("Having published three scholarly historical monographs he became an errand boy for politician", "इतिहासकार का नेताजी का झोला उठाना सचमुच पढ़े फारसी बेचे तेल की बात है"),
    ("The trained classical dancer was forced to sell vegetables in the vegetable market", "शास्त्रीय नृत्यांगना का सब्ज़ी बेचना दर्शाता है कि समाज में पढ़े फारसी बेचे तेल का दौर है"),
    ("High educational credentials bring no guarantee of suitable professional employment in difficult times", "डिग्री होने पर भी जब काम न मिले तो लोग कहते हैं कि पढ़े फारसी बेचे तेल"),
    ("The gold medalist in philosophy had to work as a petrol pump attendant", "दर्शनशास्त्र के स्वर्ण पदक विजेता का पेट्रोल भरना पढ़े फारसी बेचे तेल की विडंबना है"),
    ("He learned five classical European tongues and now sells second hand cheap shoes", "विदेशी भाषाएं सीखकर पुराने जूते बेचना सचमुच पढ़े फारसी बेचे तेल जैसा है"),
    ("The gifted sculptor was forced to crush gravel stones for modern highway construction", "मूर्तिकार का सड़क पर गिट्टी तोड़ना दिखाता है कि पढ़े फारसी बेचे तेल की स्थिति है"),
    ("A certified airline pilot was reduced to driving a heavy delivery freight truck", "विमान चालक का मालवाहक ट्रक चलाना पढ़े फारसी बेचे तेल की उदास कहानी है"),
    ("When national economic opportunities dry up educated intellectuals suffer underemployment and bitter penury", "आर्थिक संकट के समय विद्वानों को भी पढ़े फारसी बेचे तेल का दुख झेलना पड़ता है"),
    ("The scholar of ancient Sanskrit manuscripts had to hawk cheap plastic toys outside", "पांडुलिपियों के विशेषज्ञ का खिलौने बेचना पढ़े फारसी बेचे तेल का जीवंत उदाहरण है"),
    ("He studied international corporate trade laws and now distributes morning newspapers from bicycle", "अंतरराष्ट्रीय कानून पढ़कर अखबार बाँटना सचमुच पढ़े फारसी बेचे तेल की बात है"),
    ("The botanist had to prune private lawns for rich arrogant ignorant suburban homeowners", "वनस्पति विज्ञानी का घास काटना दिखाता है कि पढ़े फारसी बेचे तेल का क्या अर्थ है"),
    ("A trained marine biologist had to clean fish tanks in the local restaurant", "समुद्री जीवविज्ञानी का ढाबे के बर्तन माँजना पढ़े फारसी बेचे तेल की व्यथा है"),
    ("The qualified chemical engineer worked as a dishwasher in a greasy roadside diner", "रासायनिक अभियंता का जूठे बर्तन धोना पढ़े फारसी बेचे तेल का ज्वलंत प्रमाण है"),
    ("It is deeply tragic to see university graduates struggling in low wage jobs", "विश्वविद्यालय के स्नातकों को देखकर लगता है कि आज भी पढ़े फारसी बेचे तेल सच है"),
    ("The master calligrapher had to paint commercial billboards on the busy highway junction", "सुलेख के उस्ताद का विज्ञापन पोतना पढ़े फारसी बेचे तेल की दुखद दास्तान है"),
    ("He holds advanced degrees in archaeology and works as a cinema hall usher", "पुरातत्व के शोधार्थी का सिनेमा में टिकट जाँचना पढ़े फारसी बेचे तेल जैसा है"),
    ("The trained opera singer was forced to yell street slogans for political rallies", "गायक का नारों में गला फाड़ना सचमुच पढ़े फारसी बेचे तेल की पराकाष्ठा है"),
    ("When merit is ignored society witnesses countless pathetic spectacles of wasted precious potential", "प्रतिभा की उपेक्षा होने पर हर गली में पढ़े फारसी बेचे तेल का तमाशा दिखता है"),
    ("The gold medalist economist had to sell lottery tickets on the railway platform", "अर्थशास्त्री का लॉटरी का टिकट बेचना पढ़े फारसी बेचे तेल की दर्दनाक तस्वीर है"),
    ("He translated classical epics into modern prose and now types legal land affidavits", "महाकाव्यों के अनुवादक का कचहरी में अर्जी लिखना पढ़े फारसी बेचे तेल की मिसाल है"),
    ("The trained astronomer had to sell sunglasses on the dusty crowded pedestrian walkway", "खगोलशास्त्री का धूप के चश्मे बेचना दिखाता है कि कैसे पढ़े फारसी बेचे तेल होता है"),
    ("A skilled horologist who repaired antique clocks had to sell cheap quartz watches", "घड़ीसाज़ का फुटपाथ पर बैठना सचमुच पढ़े फारसी बेचे तेल का परिचायक है"),
    ("The agricultural scientist had to sell roasted corn on the crowded public beach", "कृषि वैज्ञानिक का भुट्टा भूनना इसी कड़वी सच्चाई को दर्शाता है कि पढ़े फारसी बेचे तेल"),
    ("May society value learning so no scholar ever has to sell crude oil", "शिक्षा का ऐसा मान हो कि किसी भी विद्वान को पढ़े फारसी बेचे तेल न कहना पड़े"),

    # 176-210: सौ सुनार की एक लोहार की (Hundred taps of goldsmith, one blow of blacksmith)
    ("The opponent made twenty petty arguments but the lawyer delivered one decisive counterattack", "विरोधी के बीस तर्कों पर वकील का एक ही जवाब भारी पड़ा जैसे सौ सुनार की एक लोहार की"),
    ("The weak boxer tapped constantly but the champion knocked him out with single punch", "पहलवान के हल्के मुक्कों के बाद विजेता का एक ही मुक्का पड़ा जैसे सौ सुनार की एक लोहार की"),
    ("After months of petty harassment the commander struck one devastating blow against rebellion", "छोटे हमलों के बाद सेनापति का एक ही वार निर्णायक साबित हुआ जैसे सौ सुनार की एक लोहार की"),
    ("The petty conspirators whispered for months but the emperor issued one final decree", "षड्यंत्रकारियों की महीनों की खुसर फुसर पर राजा का एक ही आदेश भारी पड़ा जैसे सौ सुनार की एक लोहार की"),
    ("He teased his brother hundred times but father arrived with one stern rebuke", "भाई की सौ शरारतों पर पिता की एक ही डांट भारी पड़ी जैसे सौ सुनार की एक लोहार की"),
    ("The delicate hammer taps shaped the ornament but the sledgehammer smashed the wall", "हल्की चोटों की तुलना में लोहार के भारी हथौड़े का वार भारी पड़ा जैसे सौ सुनार की एक लोहार की"),
    ("The minor critics published ten petty reviews but the master author silenced all", "आलोचकों की छोटी टिप्पणियों पर महान लेखक का एक ही लेख भारी पड़ा जैसे सौ सुनार की एक लोहार की"),
    ("A single resolute decision by leadership resolved years of endless bureaucratic delays completely", "सालों की फाइलों पर मंत्री का एक ही फैसला निर्णायक रहा जैसे सौ सुनार की एक लोहार की"),
    ("The little dog barked continuously but the tiger gave one terrifying deafening roar", "कुत्तों के लगातार भौंकने पर बाघ की एक ही दहाड़ भारी पड़ी जैसे सौ सुनार की एक लोहार की"),
    ("After endless petty skirmishes the heavy artillery strike finished the war in afternoon", "दिन भर की झड़पों के बाद तोप का एक ही गोला भारी पड़ा जैसे सौ सुनार की एक लोहार की"),
    ("The debtor gave fifty feeble excuses but the bank issued one legal notice", "कर्ज़दार के पचास बहानों पर बैंक का एक ही नोटिस भारी पड़ा जैसे सौ सुनार की एक लोहार की"),
    ("One powerful blow from the blacksmith anvil hammer is worth hundred goldsmith taps", "लोहार का एक ही घन सुनार की सौ हल्की चोटों पर भारी पड़ता है"),
    ("The teasing boy received one resounding slap from his older sister ending trouble", "लड़के की सौ शैतानियों पर बहन का एक ही थप्पड़ भारी पड़ा जैसे सौ सुनार की एक लोहार की"),
    ("The rival party spread hundred rumors but the leader delivered one truthful address", "सौ झूठी अफवाहों पर नेताजी का एक ही सच्चा भाषण भारी पड़ा जैसे सौ सुनार की एक लोहार की"),
    ("A single decisive military intervention broke the stubborn resistance of the rebel fortress", "सेना के एक ही साहसी हमले ने किले को झुका दिया जैसे सौ सुनार की एक लोहार की"),
    ("The stubborn tenant argued for hours until the police inspector arrived with warrant", "घंटों की बहस पर दरोगा की एक ही चेतावनी भारी पड़ी जैसे सौ सुनार की एक लोहार की"),
    ("One decisive stroke of the pen changed the historical destiny of twenty nations", "कलम की एक ही लकीर ने इतिहास बदल दिया जैसे सौ सुनार की एक लोहार की"),
    ("The little waves lapped the wooden pier but the tidal surge swept everything", "छोटी लहरों के बाद एक ही विशाल सुनामी सब बहा ले गई जैसे सौ सुनार की एक लोहार की"),
    ("His long series of sarcastic insults ended when champion challenged him to duel", "उसके सौ व्यंग्यों पर योद्धा की एक ही चुनौती भारी पड़ी जैसे सौ सुनार की एक लोहार की"),
    ("One clear direct question from the judge shattered the fabricated false defense narrative", "न्यायाधीश के एक ही सीधे सवाल ने झूठी गवाही तोड़ दी जैसे सौ सुनार की एक लोहार की"),
    ("The petty squabbling between factions ceased the moment the supreme chairman spoke firmly", "गुटों के छोटे विवादों पर अध्यक्ष का एक ही फैसला भारी पड़ा जैसे सौ सुनार की एक लोहार की"),
    ("The thief evaded fifty traps until the master tracker laid one inescapable snare", "चोर के सौ छलावों पर खोजी का एक ही फंदा भारी पड़ा जैसे सौ सुनार की एक लोहार की"),
    ("One massive rockfall blocked the canyon pass that fifty pickaxes could not clear", "पहाड़ से गिरी एक ही चट्टान ने दर्रा बंद कर दिया जैसे सौ सुनार की एक लोहार की"),
    ("The chatter of the assembly fell silent when the supreme emperor entered hall", "दरबारियों की सौ बातों पर सम्राट का एक ही संकेत भारी पड़ा जैसे सौ सुनार की एक लोहार की"),
    ("A single definitive scientific proof settled three centuries of continuous scholarly speculative debates", "वैज्ञानिक के एक ही प्रयोग ने सदियों की बहस खत्म कर दी जैसे सौ सुनार की एक लोहार की"),
    ("The petty gambler won ten small bets and lost his mansion in one", "छोटे सौ दांव जीतने के बाद एक ही बड़े दांव में सब हार गया जैसे सौ सुनार की एक लोहार की"),
    ("The child complained for hours until mother produced a single sweet golden jalebi", "घंटों के रोने पर माँ की एक ही जलेबी भारी पड़ी जैसे सौ सुनार की एक लोहार की"),
    ("One master stroke on the chess board trapped the opponent queen and king", "शतरंज की एक ही चाल ने बाज़ी पलट दी जैसे सौ सुनार की एक लोहार की"),
    ("The long diplomatic bickering ended when the treaty was signed with one stroke", "महीनों की वार्ताओं पर संधि का एक ही हस्ताक्षर भारी पड़ा जैसे सौ सुनार की एक लोहार की"),
    ("A single devastating artillery shell breached the thick outer stone defense battlements completely", "तोप का एक ही वार किले की दीवार गिराने के लिए काफी था जैसे सौ सुनार की एक लोहार की"),
    ("His fifty flattering letters were answered by one polite but firm refusal letter", "पचास चापलूसी भरे पत्रों पर एक ही साफ़ इनकार भारी पड़ा जैसे सौ सुनार की एक लोहार की"),
    ("The endless noisy chatter of the classroom stopped when the strict master coughed", "कक्षा के सौ शोरगुल पर शिक्षक की एक ही खाँसी भारी पड़ी जैसे सौ सुनार की एक लोहार की"),
    ("One decisive kick by the mule sent the annoying barking cur flying away", "गधे की एक ही दुलत्ती ने भौंकते कुत्ते को भगा दिया जैसे सौ सुनार की एक लोहार की"),
    ("A single historic speech ignited the spirit of national freedom across whole subcontinent", "एक ही ओजस्वी भाषण ने पूरे देश को जगा दिया जैसे सौ सुनार की एक लोहार की"),
    ("Quality and decisive power always triumph over petty repetitive inconsequential efforts and tricks", "सच्ची शक्ति का एक ही वार हमेशा दिखावे के सौ वारों पर भारी पड़ता है"),

    # 211-250: सत्यमेव जयते, वसुधैव कुटुम्बकम् एवं शास्त्रीय सूक्तियाँ (Classical Sanskrit Mottos & Aphorisms)
    ("Truth alone triumphs ultimately in the moral cosmos not falsehood and deceitful trickery", "सत्यमेव जयते नानृतम् अर्थात अंत में केवल सत्य की ही विजय होती है"),
    ("The whole world is one single loving family for the noble and magnanimous", "उदार चरितानां तु वसुधैव कुटुम्बकम् अर्थात सारा संसार ही एक परिवार है"),
    ("Excess in all human things must be avoided strictly according to ancient philosophy", "अति सर्वत्र वर्जयेत अर्थात किसी भी चीज़ की अति हमेशा हानिकारक होती है"),
    ("Non violence is the supreme moral duty and foundation of all noble ethics", "अहिंसा परमो धर्मः अर्थात जीवों पर दया और अहिंसा ही सबसे बड़ा धर्म है"),
    ("Mother and motherland are far superior even to the celestial delights of heaven", "जननी जन्मभूमिश्च स्वर्गादपि गरीयसी अर्थात मातृभूमि स्वर्ग से भी बढ़कर है"),
    ("Knowledge is that sublime treasure which bestows true spiritual liberation upon human soul", "सा विद्या या विमुक्तये अर्थात सच्ची विद्या वही है जो अज्ञान के बंधनों से मुक्ति दिलाए"),
    ("May all living beings be happy healthy and peaceful throughout the cosmic spheres", "सर्वे भवन्तु सुखिनः सर्वे सन्तु निरामयाः की पावन प्रार्थना हमारे ऋषियों ने की"),
    ("Duty performed without desire for selfish fruits leads to pure spiritual peace", "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन अर्थात फल की चिंता किए बिना केवल निष्काम कर्म करो"),
    ("Union of hearts and minds produces invincible collective strength in every human endeavor", "संघे शक्तिः कलियुगे अर्थात संगठन में ही इस युग में सबसे बड़ी शक्ति है"),
    ("The guest who arrives at the threshold must be revered as divine deity", "अतिथि देवो भव अर्थात घर आए मेहमान को ईश्वर का रूप मानकर सत्कार करो"),
    ("Lead us from darkness unto light and from mortality unto immortality forever", "तमसो मा ज्योतिर्गमय मृत्योर्मा अमृतं गमय की प्रार्थना ही मानव जाति का पथ प्रदर्शन करती है"),
    ("A life without righteousness is like a tree without roots in the storm", "धर्म हीन मनुष्य सींग और पूँछ के बिना पशु के समान माना गया है"),
    ("Greed is the root source of all sins vices and endless human suffering", "लोभः पापस्य कारणम् अर्थात लालच ही संसार के सभी पापों की असली जड़ है"),
    ("Patience and fortitude protect a human being amidst the fiercest storms of adversity", "धैर्य ही विपत्ति के समय मनुष्य का सबसे सच्चा और विश्वासपात्र मित्र होता है"),
    ("Charity given to the deserving without boast enriches both the giver and receiver", "पात्र को दिया गया गुप्त दान ही सबसे उत्तम और पुण्यकारी माना जाता है"),
    ("Learning is an unfailing friend when traveling through foreign strange and distant lands", "विदेश में विद्या ही मनुष्य की सबसे सच्ची और वफादार मित्र होती है"),
    ("True friendship requires neither flattering speech nor deceitful display of false wealth", "सच्ची मित्रता में किसी आडंबर या चापलूसी की कोई जगह नहीं होती"),
    ("The fragrance of noble character spreads against the wind across all ten directions", "उत्तम चरित्र की सुगंध हवा के विपरीत भी चारों दिशाओं में फैलती है"),
    ("Speech seasoned with truth and loving kindness is the supreme jewel of humanity", "सत्य और प्रिय वाणी ही मनुष्य का सबसे सुंदर और अनमोल आभूषण है"),
    ("He who conquers his own mind has conquered the entire three worlds easily", "जिसने अपने मन को जीत लिया उसने मानो पूरे संसार को जीत लिया"),
    ("Humility is the crowning ornament of profound wisdom and extensive scholarly erudition", "विद्या ददाति विनयं अर्थात सच्ची विद्या मनुष्य को स्वाभाविक विनम्रता प्रदान करती है"),
    ("Anger destroys intellect and delusion destroys the noble power of moral discernment", "क्रोध मनुष्य की बुद्धि को भ्रष्ट कर देता है और विवेक को नष्ट करता है"),
    ("Service rendered unto parents is the most sacred pilgrimage on this green earth", "माता पिता की सेवा ही संसार का सबसे पावन और फलदायी तीर्थ है"),
    ("The noble soul sees the joy and sorrow of others as his own", "आत्मवत् सर्वभूतेषु अर्थात दूसरों के सुख दुख को अपने समान समझना ही सज्जनता है"),
    ("Pride destroys great empires just as hidden termites devour giant wooden pillars", "अहंकार विशाल साम्राज्यों को भी वैसे ही खोखला कर देता है जैसे दीमक लकड़ी को"),
    ("Contentment is the purest nectar that bestows immortality upon the serene human heart", "संतोष ही वह अमृत है जो मनुष्य के हृदय को सच्चा सुख प्रदान करता है"),
    ("The spoken word cannot be recalled once it flies from the bow of tongue", "मुँह से निकला शब्द कमान से छूटे तीर की तरह वापस नहीं लौटता"),
    ("Righteous conduct is the highest knowledge and the most secure foundation of civilization", "आचारः परमो धर्मः अर्थात सदाचार ही मनुष्य का सबसे पहला और श्रेष्ठ धर्म है"),
    ("A learned scholar is revered in every land while king is honored locally", "स्वदेशे पूज्यते राजा विद्वान् सर्वत्र पूज्यते की प्राचीन उक्ति सर्वथा सत्य है"),
    ("Compassion toward the distressed is the supreme hallmark of a noble civilized spirit", "दीन दुखियों पर दया करना ही मानवता का सबसे उज्ज्वल और पावन लक्षण है"),
    ("May truth always guide the judicial tribunals and legislative assemblies of our republic", "हमारे न्यायालयों के ऊपर सत्यमेव जयते का पावन आदर्श वाक्य अंकित रहता है"),
    ("Our ancient sages taught that universal brotherhood embraces the whole terrestrial globe", "ऋषियों ने सिखाया कि वसुधैव कुटुम्बकम् की भावना से ही विश्व में शांति संभव है"),
    ("Avoid all extreme fanaticism because moderation in thought and action brings lasting peace", "अति सर्वत्र वर्जयेत का नियम अपनाकर ही जीवन में संतुलन और सौहार्द लाया जा सकता है"),
    ("Let noble thoughts come to us from every corner of the universe freely", "आ नो भद्राः क्रतवो यन्तु विश्वतः अर्थात हर दिशा से हमारे पास शुभ विचार आएँ"),
    ("The immortal motto of justice declares that truth alone triumphs over falsehood forever", "सत्यमेव जयते का अमर संदेश युगों युगों तक मानव चेतना को आलोकित करता रहेगा"),
]

if __name__ == "__main__":
    process_batch(32, "p32s", PAIRS)

MORE_PAIRS = [
    ("The pure moral light of truth pierces through the darkest clouds of deception", "सत्य का पावन प्रकाश छल कपट के घने बादलों को चीरकर बाहर आ जाता है"),
    ("Tolerance and mutual understanding build bridges between divergent cultures across the vast globe", "सहनशीलता और समझदारी विभिन्न संस्कृतियों के बीच शांति का पुल बनाती है"),
    ("The highest wisdom consists in treating every sentient being with boundless loving tenderness", "सभी प्राणियों के साथ दया और प्रेम का व्यवहार करना ही सबसे बड़ा ज्ञान है"),
    ("A society that honors scholars and artists attains enduring cultural and moral greatness", "विद्वानों और कलाकारों का सम्मान करने वाला समाज ही सच्चा गौरव प्राप्त करता है"),
    ("May peace prevail upon earth waters plants sky and within the hearts of humans", "समस्त पृथ्वी जल वनस्पति और मानव हृदयों में शांति की स्थापना हो"),
]
PAIRS.extend(MORE_PAIRS)
process_batch(32, "p32s", PAIRS)
