#!/usr/bin/env python3
"""Batch VT-03: Ergativity & Perfective Concord with ने (200 sentences).
File: data/phrases35.json, IDs: p35s001..p35s200.
Themes:
- Split Ergativity with ने (Past/Present/Past Perfect, Future Perfect)
- Object-Verb Agreement (unmarked object: masculine/feminine sg/pl)
- Differential Object Marking with को (भावे प्रयोग: invariable 3rd masc sg -ा)
- Ergative Exceptions: Transitive without ने (लाना, बोलना, भूलना) & Intransitive with ने (छींकना, खाँसना)
"""
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parent))
from gen_batches_pipeline import process_batch

PAIRS = [
    # 1-45: Unmarked Object Agreement (लड़के ने रोटी खाई, लड़की ने फल खाए, किसान ने फसल काटी)
    ("The hungry boy ate fresh wheat bread quickly with sweet cow milk", "भूखे लड़के ने मीठे दूध के साथ ताज़ा रोटी खाई"),
    ("The generous girl distributed sweet seasonal fruits among the poor children yesterday", "उदार लड़की ने कल गरीब बच्चों के बीच मीठे फल बाँटे"),
    ("The hardworking farmer harvested the golden wheat crop before the heavy rains", "मेहनती किसान ने भारी बारिश से पहले पकी हुई फसल काटी"),
    ("The master architect designed a magnificent royal palace near the mountain lake", "अनुभवी वास्तुकार ने पहाड़ी झील के पास एक भव्य महल बनाया"),
    ("The talented poetess composed an inspiring patriotic poem for the national celebration", "प्रतिभाशाली कवयित्री ने राष्ट्रीय पर्व के लिए एक ओजस्वी कविता रची"),
    ("The skilled carpenter crafted six sturdy wooden chairs for the new school", "कुशल बढ़ई ने नए विद्यालय के लिए लकड़ी की छह मजबूत कुर्सियाँ बनाईं"),
    ("The brave warrior wielded a heavy iron sword with astonishing martial dexterity", "वीर योद्धा ने युद्ध भूमि में लोहे की भारी तलवार चलाई"),
    ("The little sister read three fascinating historical novels during the summer vacation", "छोटी बहन ने गर्मियों की छुट्टियों में तीन ज्ञानवर्धक ऐतिहासिक उपन्यास पढ़े"),
    ("The honest merchant repaid all his outstanding business debts before the year ended", "ईमानदार व्यापारी ने साल खत्म होने से पहले अपने सारे कर्ज़ चुकाए"),
    ("The pious grandmother lit three sacred brass lamps before the household deity", "श्रद्धालु दादी ने कुलदेवता के सामने पीतल के तीन पावन दीपक जलाए"),
    ("The clever detective solved the intricate criminal mystery within two short days", "चतुर जासूस ने दो ही दिनों में चोरी की जटिल गुत्थी सुलझाई"),
    ("The diligent apprentice learned all thirty complex weaving patterns from his master", "लगनशील शिष्य ने अपने उस्ताद से बुनाई के सभी कठिन नमूने सीखे"),
    ("The village elder planted fifty shady banyan saplings along the dusty highway", "गाँव के बुजुर्ग ने राजमार्ग के किनारे पचास छायादार पौधे लगाए"),
    ("The experienced seamstress stitched a magnificent ceremonial silk coat for the prince", "अनुभवी दर्ज़िन ने राजकुमार के लिए एक बहुत सुंदर रेशमी चोगा सिला"),
    ("The thirsty traveler drank three bowls of cool water from the spring", "प्यासे मुसाफिर ने पहाड़ी झरने से ठंडा पानी पिया"),
    ("The young painter exhibited ten exquisite oil landscapes in the central gallery", "युवा चित्रकार ने कला दीर्घा में दस मनमोहक प्राकृतिक दृश्य प्रदर्शित किए"),
    ("The wise judge delivered a landmark historic ruling upholding fundamental constitutional equality", "न्यायाधीश ने नागरिकों की समानता की रक्षा करते हुए एक ऐतिहासिक फैसला सुनाया"),
    ("The dedicated mother baked fifty sweet festive pastries for the village gathering", "स्नेही माँ ने गाँव के उत्सव के लिए पचास मीठे पकवान बनाए"),
    ("The brave commander defended the mountain fortress against overwhelming hostile siege battalions", "बहादुर सेनापति ने शत्रु सेना के सामने पहाड़ी किले की सफल रक्षा की"),
    ("The schoolboy drew an accurate topographic map of India with colored pencils", "छात्र ने रंगीन पेंसिलों से भारत का एक बहुत सुंदर नक्शा बनाया"),
    ("The potter shaped twenty large earthen water jars on his spinning wheel", "कुम्हार ने अपने चाक पर पानी के बीस बड़े घड़े गढ़े"),
    ("The generous king opened the royal storehouses to distribute free grain rations", "उदार राजा ने अकाल के समय प्रजा के लिए अन्न के भंडार खोले"),
    ("The observant scout spotted the hidden rebel camp across the river valley", "सतर्क दूत ने नदी पार घने जंगल में विद्रोहियों की छावनी देखी"),
    ("The pious lady donated her ancestral silver jewelry to the municipal hospital", "धर्मात्मा महिला ने अपने पुश्तैनी चाँदी के गहने नगर के अस्पताल को दान दिए"),
    ("The courageous youth caught the venomous black cobra with his bare hands", "साहसी युवक ने अपने खाली हाथों से विषैला काला नाग पकड़ा"),
    ("The traditional goldsmith carved delicate floral designs upon the wedding necklace necklace", "पारंपरिक सुनार ने विवाह के सोने के हार पर बहुत सुंदर नक्काशी की"),
    ("The wise minister drafted a comprehensive trade treaty benefiting both sovereign nations", "बुद्धिमान मंत्री ने दोनों देशों के लाभ के लिए एक व्यापक व्यापारिक संधि तैयार की"),
    ("The young athlete broke the previous national running record by two seconds", "युवा धावक ने दो सेकंड के अंतर से पुराना राष्ट्रीय कीर्तिमान तोड़ा"),
    ("The caring nurse applied cooling herbal ointment to the inflamed burn wounds", "सेवाभावी नर्स ने जले हुए घावों पर ठंडक पहुँचाने वाला मरहम लगाया"),
    ("The diligent clerk recorded every single expenditure accurately in the ledger book", "ईमानदार मुनीम ने बहीखाते में एक एक पैसे का सही हिसाब लिखा"),
    ("The village blacksmith forged twenty sharp iron axes for the timber cutters", "गाँव के लोहार ने लकड़ी काटने वालों के लिए बीस कुल्हाड़ियाँ बनाईं"),
    ("The affectionate aunt bought two colorful silk sarees from the famous bazaar", "स्नेही मौसी ने बाज़ार से दो बहुत सुंदर रेशमी साड़ियाँ खरीदीं"),
    ("The brave girl rescued her little brother from the rushing flood waters", "साहसी बालिका ने उफनती नदी की धारा से अपने छोटे भाई की जान बचाई"),
    ("The celebrated musician composed a new classical symphony celebrating universal brotherhood harmony", "महान संगीतकार ने विश्व शांति के संदेश को समर्पित एक नया राग रचा"),
    ("The watchful shepherd protected his flock of sheep from the hungry wolves", "सतर्क गड़ेरिए ने अपनी भेड़ों को जंगल के भूखे भेड़ियों से बचाया"),
    ("The scholar translated the ancient Greek philosophical dialogue into modern Hindi prose", "विद्वान ने यूनानी दर्शन के प्राचीन संवाद का सरल हिंदी में अनुवाद किया"),
    ("The honest watchman discovered the broken lock before the burglars entered safe", "सतर्क चौकीदार ने चोरों के घुसने से पहले ही टूटा हुआ ताला देखा"),
    ("The kind grandfather carved a wooden toy horse for his beloved grandson", "प्यारे दादाजी ने अपने नन्हे पोते के लिए लकड़ी का एक सुंदर खिलौना बनाया"),
    ("The dedicated teacher explained five difficult geometry theorems with remarkable visual clarity", "समर्पित शिक्षक ने श्यामपट्ट पर रेखागणित के पाँच कठिन प्रमेय सिद्ध किए"),
    ("The royal emissary delivered the secret sealed peace parchment to the sovereign", "शाही दूत ने सम्राट के हाथों में शांति का गुप्त पत्र सौंपा"),
    ("The agile archer shot three consecutive golden arrows into the distant target", "कुशल धनुर्धर ने दूर रखे निशाने पर लगातार तीन तीर साधे"),
    ("The industrious bees gathered sweet nectar from thousands of fragrant lotus blossoms", "परिश्रमी मधुमक्खियों ने खिले हुए कमलों से मीठा रस इकट्ठा किया"),
    ("The experienced shipwright repaired the damaged oak timber keel of the vessel", "नाव बनाने वाले ने जहाज़ के पेंदे की टूटी लकड़ी बदली"),
    ("The humble ascetic refused all royal gold coins offered by the emperor", "शांत तपस्वी ने सम्राट द्वारा भेंट की गई सोने की अशर्फियाँ अस्वीकार कीं"),
    ("The little boy planted three mango seeds in the fertile moist earth", "छोटे बालक ने आँगन की नम मिट्टी में आम की तीन गुठलियाँ बोईं"),

    # 46-90: भावे प्रयोग (Differential Object Marking with को -> Verb defaults to -आ)
    ("The strict teacher called the absent students to the office immediately", "कड़े शिक्षक ने अनुपस्थित छात्रों को तुरंत अपने कार्यालय में बुलाया"),
    ("The compassionate doctor treated the injured road accident victims with great skill", "दयालु चिकित्सक ने दुर्घटना में घायल यात्रियों को बहुत ध्यान से संभाला"),
    ("The vigilant police inspector arrested the notorious bank robber outside the city", "सतर्क दरोगा ने कुख्यात बैंक लुटेरे को नगर के बाहर से पकड़ा"),
    ("The loving mother woke up her sleeping children before the morning sunrise", "स्नेही माँ ने सूर्योदय से पहले अपने सोए हुए बच्चों को जगाया"),
    ("The brave commander rewarded the valiant soldiers for their exceptional battlefield courage", "सेनापति ने असाधारण वीरता दिखाने वाले सैनिकों को मेडल देकर सम्मानित किया"),
    ("The village elders summoned the quarreling neighbors to the open village square", "गाँव के बुजुर्गों ने झगड़ा करने वाले दोनों पड़ोसियों को चौपाल में बुलाया"),
    ("The royal guard escorted the foreign diplomatic envoys to the imperial court", "शाही पहरेदारों ने विदेशी राजदूतों को राजदरबार तक सुरक्षित पहुँचाया"),
    ("The honest judge acquitted the innocent youth after reviewing all forensic evidence", "न्यायाधीश ने सभी सबूतों की जाँच के बाद निर्दोष बालक को बरी किया"),
    ("The fierce hunter trapped the man eating tiger in a sturdy wooden cage", "शिकारी ने आदमखोर बाघ को एक मजबूत पिंजरे में कैद किया"),
    ("The caring elder sister fed the hungry street puppies fresh warm milk", "बड़ी बहन ने सड़क के भूखे पिल्लों को कटोरी में दूध पिलाया"),
    ("The generous merchant helped the impoverished weavers with interest free working capital", "उदार व्यापारी ने संकट में फँसे बुनकरों को बिना ब्याज धन देकर संभाला"),
    ("The dedicated social worker educated the street children in the evening school", "समाजसेवी ने बस्ती के कामकाजी बच्चों को शाम की पाठशाला में पढ़ाया"),
    ("The royal physician cured the ailing queen with rare Himalayan botanical herbs", "राजवैद्य ने दुर्लभ जड़ी बूटियों की सहायता से बीमार महारानी को ठीक किया"),
    ("The alert watchman stopped the suspicious intruders at the outer iron gate", "सतर्क चौकीदार ने अजनबी संदिग्धों को मुख्य फाटक पर ही रोक दिया"),
    ("The famous director auditioned fifty young actors for the historical drama role", "प्रसिद्ध निर्देशक ने नाटक के मुख्य पात्र के लिए पचास कलाकारों को परखा"),
    ("The kind stranger guided the lost blind traveler across the busy street", "दयालु अजनबी ने दृष्टिहीन मुसाफिर को हाथ पकड़कर व्यस्त सड़क पार कराई"),
    ("The headmaster praised the hardworking student before the whole morning assembly gathering", "प्रधानाचार्य ने प्रार्थना सभा में मेधावी छात्र को मंच पर बुलाकर सराहा"),
    ("The experienced mountaineer rescued the stranded climber from the icy crevasse ledge", "पर्वतारोही ने बर्फ़ की गहरी दरार में फँसे साथी को सुरक्षित निकाला"),
    ("The village council fined the dishonest contractor for using substandard construction cement", "पंचायत ने घटिया सामग्री लगाने पर बेईमान ठेकेदार को भारी दंड दिया"),
    ("The caring veterinarian treated the injured carriage horse with gentle soothing salves", "पशु चिकित्सक ने घायल घोड़े को दवा लगाकर उसके दर्द को कम किया"),
    ("The resolute general deployed the elite border patrol battalion along the ridge", "सेनापति ने पर्वतीय दर्रे की रक्षा के लिए विशेष टुकड़ी को तैनात किया"),
    ("The dedicated mother comforted her weeping daughter after the painful emotional setback", "माँ ने परीक्षा में असफल होने पर रोती हुई बेटी को ढांढस बंधाया"),
    ("The impartial referee penalized the aggressive player for violating the tournament rules", "रेफरी ने खेल के नियमों का उल्लंघन करने वाले खिलाड़ी को मैदान से बाहर किया"),
    ("The generous host welcomed the exhausted wedding guests with warm herbal drinks", "मेजबान ने दूर से आए थके हुए बारातियों को आदर सहित बैठाया"),
    ("The courageous villagers cornered the dangerous cattle thieves in the dense forest", "साहसी ग्रामीणों ने मवेशी चुराने वाले गिरोह को घने जंगल में घेरा"),
    ("The insightful professor guided the doctoral research scholars through difficult archival materials", "प्रोफेसर ने शोधार्थियों को प्राचीन पांडुलिपियों का सही अर्थ समझाया"),
    ("The dedicated firefighter pulled the trapped child from the smoke filled room", "अग्निशमन कर्मी ने धुएँ से भरे कमरे में से मासूम बच्चे को निकाला"),
    ("The compassionate queen fed the starving famine refugees outside the palace gates", "दयालु महारानी ने महल के बाहर भूखे शरणार्थियों को भरपेट भोजन कराया"),
    ("The vigilant forest ranger fined the reckless tourists for lighting fires illegally", "वनरक्षक ने जंगल में आग जलाने वाले लापरवाह पर्यटकों को पकड़ा"),
    ("The faithful servant served his ailing master with unwavering loyalty and devotion", "वफादार सेवक ने अपने बीमार स्वामी को बड़े जतन से संभाला"),
    ("The wise father cautioned his impetuous sons against engaging in speculative gambling", "पिता ने अपने चंचल पुत्रों को सट्टेबाज़ी के खतरे से आगाह किया"),
    ("The royal emissary introduced the visiting foreign scholars to the imperial academy", "दूत ने बाहर से आए विद्वानों को राजसी पुस्तकालय में आमंत्रित किया"),
    ("The experienced coach trained the promising young athletes for the international championship", "प्रशिक्षक ने अंतरराष्ट्रीय प्रतियोगिता के लिए युवा खिलाड़ियों को तैयार किया"),
    ("The brave sailor pulled the drowning merchant out of the stormy waves", "साहसी नाविक ने उफनती लहरों में से डूबते हुए व्यापारी को बचाया"),
    ("The diligent librarian reminded the forgetful readers to return the borrowed books", "पुस्तकालय अध्यक्ष ने पुस्तक प्रेमियों को समय पर किताबें लौटाने को कहा"),
    ("The kind grandfather cheered up the gloomy children with sweet amusing riddles", "दादाजी ने उदास बच्चों को मजेदार पहेलियाँ सुनाकर हँसाया"),
    ("The alert sentry challenged the unidentifiable midnight stranger at the castle bridge", "पहरेदार ने रात के अंधेरे में पुल पार करने वाले अजनबी को ललकारा"),
    ("The village elders blessed the newly wedded couple with health and longevity", "गाँव के बुजुर्गों ने नवविवाहित वर वधू को सुखी जीवन का आशीर्वाद दिया"),
    ("The dedicated activist inspired the rural youth to eradicate caste discrimination completely", "कार्यकर्ता ने गाँव के युवाओं को सामाजिक कुरीतियों के विरुद्ध संगठित किया"),
    ("The royal court poet entertained the gathered noble audience with witty verses", "दरबारी कवि ने अपनी हास्य कविताओं से पूरे सभा भवन को हँसाया"),
    ("The brave police officer disarmed the violent armed robber in the street", "साहसी पुलिस अधिकारी ने हथियारबंद बदमाश को झपटकर पकड़ा"),
    ("The affectionate grandmother hugged her returning grandson after five long absent years", "दादी ने विदेश से लौटे अपने पोते को प्यार से गले लगाया"),
    ("The generous benefactor financed the orphan child through twelve years of schooling", "दानी सज्जन ने अनाथ बालक को बारहवीं तक की पढ़ाई का खर्च दिया"),
    ("The watchful shepherd protected the newborn lamb from the circling hungry vulture", "चरवाहे ने गिद्ध के हमले से नवजात मेमने को बचाकर गोद में उठाया"),
    ("The wise mediator pacified the enraged litigants with calm and reasoned persuasion", "पंच ने दोनों पक्षों को समझा बुझाकर उनके पुराने विवाद को शांत किया"),

    # 91-135: Tense Concord with ने (Present Perfect, Past Perfect, Future Perfect)
    ("The diligent student has completed all assignments before the deadline set by teacher", "मेहनती छात्र ने शिक्षक द्वारा दिए गए सभी कार्य समय से पहले पूरे कर लिए हैं"),
    ("The farmer has harvested the whole field of ripe golden sugarcane this week", "किसान ने इस हफ्ते अपने खेत का पूरा पका हुआ गन्ना काट लिया है"),
    ("The master architect had designed the blueprints before the foundation stone was laid", "वास्तुकार ने नींव का पत्थर रखने से पहले ही पूरे भवन का नक्शा तैयार कर लिया था"),
    ("The courageous soldiers had defended the frontier fortress through six bitter winter months", "बहादुर सैनिकों ने छह महीने तक बर्फ़ीली सीमा की चौकियों की वीरता से रक्षा की थी"),
    ("The experienced courier will have delivered the confidential royal diplomatic dispatch by now", "दूत ने अब तक राजा का गोपनीय संदेश अवश्य राजधानी पहुँचा दिया होगा"),
    ("The skillful baker will have prepared three hundred loaves of fresh bread today", "नानबाई ने आज सुबह तक तीन सौ ताज़ा रोटियाँ तैयार कर ली होंगी"),
    ("The honest auditor has uncovered the massive financial discrepancy in the company accounts", "ईमानदार लेखा परीक्षक ने कंपनी के बहीखाते में हुई भारी गड़बड़ी पकड़ ली है"),
    ("The kind lady has adopted three abandoned street kittens from the animal shelter", "दयालु महिला ने आश्रम से तीन बेसहारा बिल्ली के बच्चों को गोद ले लिया है"),
    ("The king had granted land titles to the valiant war veterans after victory", "राजा ने विजय के बाद वीर सैनिकों को खेती के लिए उपजाऊ ज़मीनें दी थीं"),
    ("The village community had built the sturdy stone check dam before monsoon rains", "गाँव वालों ने बरसात शुरू होने से पहले ही पत्थर का मजबूत बाँध बना लिया था"),
    ("The talented authoress will have finished her epic historical drama manuscript by tomorrow", "विदुषी लेखिका ने कल तक अपने ऐतिहासिक उपन्यास की पूरी पांडुलिपि लिख ली होगी"),
    ("The dedicated surgeon will have performed the delicate heart operation successfully by noon", "कुशल चिकित्सक ने दोपहर तक हृदय का जटिल ऑपरेशन सफलता से पूरा कर लिया होगा"),
    ("The vigilant border guards have intercepted three smuggling boats along the coastal inlet", "तटरक्षकों ने समुद्र के मुहाने पर तस्करी की तीन नावें पकड़ ली हैं"),
    ("The government has sanctioned generous disaster relief funds for all flood affected districts", "सरकार ने बाढ़ से प्रभावित सभी ज़िलों के लिए राहत राशि स्वीकृत कर दी है"),
    ("The brave explorer had mapped the uncharted interior mountain ranges fifty years ago", "साहसी खोजी ने पचास साल पहले उन दुर्गम पहाड़ी रास्तों का पहला नक्शा बनाया था"),
    ("The pious monks had preserved the ancient Buddhist palm leaf texts inside cave", "भिक्षुओं ने गुफा के भीतर प्राचीन बौद्ध ग्रंथों को सदियों तक सुरक्षित रखा था"),
    ("The diligent farmer will have sown the wheat seeds across thirty fertile acres", "मेहनती किसान ने अपने तीस एकड़ खेत में गेहूँ के बीज बो दिए होंगे"),
    ("The master sculptor will have chiseled the life size statue of the statesman", "मूर्तिकार ने पत्थर पर उस महान नेता की भव्य प्रतिमा तराश ली होगी"),
    ("The dedicated scientist has discovered an effective herbal remedy for chronic tropical malaria", "वैज्ञानिक ने मलेरिया के उपचार के लिए एक अचूक वनौषधि की खोज कर ली है"),
    ("The railway engineers have restored the damaged railway track after the recent landslide", "रेलवे के इंजीनियरों ने भूस्खलन के बाद टूटी हुई पटरी की मरम्मत पूरी कर ली है"),
    ("The ancient emperor had constructed twenty grand stepwells along the historic silk highway", "प्राचीन सम्राट ने राजमार्ग के किनारे बीस सुंदर और विशाल बावडियाँ बनवाई थीं"),
    ("The village council had resolved the delicate inheritance dispute through mutual consensus yesterday", "गाँव की पंचायत ने कल आपसी सहमति से ज़मीन के पुराने विवाद का फैसला कर दिया था"),
    ("The royal chef will have cooked the elaborate seven course banquet for dignitaries", "शाही बावर्ची ने शाम के मेहमानों के लिए सात प्रकार के स्वादिष्ट व्यंजन तैयार कर लिए होंगे"),
    ("The skilled weavers will have completed the intricate silk tapestry before the festival", "बुनकरों ने उत्सव से पहले ही रेशम का सुंदर परदा तैयार कर लिया होगा"),
    ("The young athlete has shattered the international high jump record at national games", "युवा खिलाड़ी ने राष्ट्रीय खेलों में ऊँची कूद का नया कीर्तिमान स्थापित कर दिया है"),
    ("The municipal corporation has planted five thousand shade trees along the newly paved avenues", "नगर निगम ने नई सड़कों के किनारे पाँच हज़ार छायादार वृक्ष लगा दिए हैं"),
    ("The courageous mountain guide had led the stranded pilgrims to safety during blizzard", "पहाड़ी गाइड ने भयानक तूफान के दौरान सभी यात्रियों को सुरक्षित गुफा तक पहुँचा दिया था"),
    ("The dedicated seamstress had stitched the bridal trousseau with golden threads in winter", "दर्ज़िन ने सर्दियों में सुनहरे धागों से विवाह के सुंदर वस्त्र तैयार किए थे"),
    ("The experienced ship captain will have navigated the vessel into the sheltered harbor", "कप्तान ने तूफानी हवाओं से बचाकर जहाज़ को सुरक्षित बंदरगाह पर पहुँचा दिया होगा"),
    ("The young mathematician will have solved the famous unsolved mathematical conjecture by now", "प्रतिभाशाली गणितज्ञ ने गणित के उस जटिल सवाल का सही हल ढूँढ लिया होगा"),
    ("The honest watchman has handed over the dropped purse to the local police", "ईमानदार चौकीदार ने सड़क पर मिला पैसों का बटुआ पुलिस को सौंप दिया है"),
    ("The generous donor has endowed a new wing for pediatric care at hospital", "उदार दानी ने अस्पताल में बच्चों के इलाज के लिए एक नया भवन बनवा दिया है"),
    ("The skilled potters had fired three hundred terracotta vessels in the kiln yesterday", "कुम्हारों ने कल भट्टी में मिट्टी के तीन सौ सुंदर बर्तन पका लिए थे"),
    ("The royal chronicler had documented the complete military campaigns of the emperor in prose", "इतिहासकार ने राजा के सभी युद्ध अभियानों का प्रामाणिक विवरण ग्रंथ में दर्ज किया था"),
    ("The enthusiastic youth will have cleared the weeds from the village playground already", "गाँव के लड़कों ने खेल के मैदान की सारी जंगली घास अब तक साफ़ कर दी होगी"),
    ("The master goldsmith will have set the sparkling emeralds into the royal diadem", "जौहरी ने राजमुकुट में हरे पन्ने बहुत सुंदरता से जड़ दिए होंगे"),
    ("The district administration has evacuated ten thousand vulnerable villagers from the riverbank settlements", "ज़िला प्रशासन ने नदी के किनारे बसी बस्तियों से हज़ारों ग्रामीणों को सुरक्षित निकाल लिया है"),
    ("The independent tribunal has published its comprehensive report on the municipal water quality", "स्वतंत्र आयोग ने पीने के पानी की शुद्धता पर अपनी विस्तृत रिपोर्ट जारी कर दी है"),
    ("The wise grandmother had taught all her grandchildren to read Sanskrit script fluently", "दादी ने बचपन में ही अपने सभी पोते पोतियों को सुंदर संस्कृत पढ़ना सिखा दिया था"),
    ("The master calligrapher had copied the entire epic poem in fine black ink", "सुलेखक ने काली स्याही से पूरा महाकाव्य सुंदर अक्षरों में लिख दिया था"),
    ("The vigilant border sentry will have detected the unauthorized vehicle on the road", "सीमा पर तैनात पहरेदार ने संदिग्ध गाड़ी को पहले ही रोक लिया होगा"),
    ("The skilled seamstresses will have finished the royal robes for the coronation ceremony", "दर्जियों ने राज्याभिषेक समारोह के लिए सभी सुंदर वस्त्र तैयार कर लिए होंगे"),
    ("The honest postman has delivered all official letters to the remote mountain post", "डाकिए ने दुर्गम पहाड़ी चौकी तक सभी ज़रूरी सरकारी पत्र पहुँचा दिए हैं"),
    ("The generous community has rebuilt the damaged schoolhouse after the destructive monsoon storm", "गाँव वालों ने मिलकर तूफान में टूटे हुए विद्यालय की छत फिर से बना दी है"),
    ("The brave commander had fortified the mountain pass against sudden surprise enemy cavalry attacks", "सेनापति ने अचानक होने वाले हमलों से बचने के लिए दर्रे की मजबूत किलेबंदी की थी"),

    # 136-165: Transitive Verbs rejecting ने (लाना, बोलना, भूलना)
    ("The faithful servant brought fresh water from the cold mountain spring for travelers", "वफादार सेवक यात्रियों के लिए पहाड़ी झरने से ठंडा पानी लाया"),
    ("The honest witness spoke the absolute truth before the supreme court judicial bench", "सच्चा गवाह न्यायाधीशों के सामने अदालत में केवल सच बोला"),
    ("The absent minded professor forgot his umbrella and glasses on the passenger train", "भुलक्कड़ प्रोफेसर यात्री गाड़ी में अपना चश्मा और छाता भूल गया"),
    ("The loving father brought delicious sweet mangoes from the fruit market for children", "पिताजी बाज़ार से बच्चों के लिए पके हुए मीठे आम लाए"),
    ("The courageous leader spoke inspiring words of freedom to the massive gathered crowds", "साहसी नेता विशाल जनसभा के सामने देश की आज़ादी की बात बोला"),
    ("The busy clerk forgot to lock the heavy iron office safe before leaving", "दफ्तर से जाते समय मुंशी तिजोरी का ताला लगाना भूल गया"),
    ("The kind merchant brought warm woolen blankets from Kashmir for the village poor", "व्यापारी कश्मीर से गरीबों के लिए गर्म ऊनी शॉल लाया"),
    ("The innocent child spoke with complete sincerity and honesty to his school teacher", "मासूम बालक अपनी शिक्षिका के सामने बहुत सच्चाई से बोला"),
    ("The tired traveler forgot his walking staff beside the shady roadside resting well", "थका हुआ मुसाफिर कुएँ की मुंडेर पर अपनी लाठी भूल गया"),
    ("The generous uncle brought colorful wooden toys and storybooks for the young cousins", "चाचाजी बच्चों के लिए लकड़ी के खिलौने और कहानियों की पुस्तकें लाए"),
    ("The young debater spoke with remarkable poise and razor sharp logic during competition", "प्रतियोगिता में छात्र बहुत सुंदर और अकाट्य तर्क बोला"),
    ("The hurried passenger forgot his leather briefcase upon the railway station waiting bench", "यात्री स्टेशन की बेंच पर अपना ज़रूरी चमड़े का बैग भूल गया"),
    ("The returning soldier brought fragrant tea leaves and spices from the eastern hills", "छुट्टी पर आया सिपाही पूर्व की पहाड़ियों से ताज़ा चाय पत्ती लाया"),
    ("The truthful ascetic spoke gentle words of moral wisdom to the arrogant king", "शांत तपस्वी राजा के सामने बहुत प्रिय और सत्य वचन बोला"),
    ("The forgetful student forgot his admit card on the day of matriculation exam", "लापरवाह छात्र परीक्षा वाले दिन अपना प्रवेश पत्र घर पर ही भूल गया"),
    ("The mountain shepherd brought three lost lambs safely back to the sheep pen", "चरवाहा जंगल में भटके हुए तीन मेमनों को सुरक्षित बाड़े में लाया"),
    ("The fearless journalist spoke boldly against government censorship and public corruption in speech", "पत्रकार अपने भाषण में सत्ता के भ्रष्टाचार के विरुद्ध खुलकर बोला"),
    ("The absent minded chemist forgot to extinguish the gas flame under glass retort", "प्रयोगशाला में काम करते समय वैज्ञानिक बर्नर बुझाना भूल गया"),
    ("The traveling minstrel brought ancient ballads from the desert kingdoms of the west", "गायक राजस्थान के रेतीले इलाकों से वीरों के पुराने गीत लाया"),
    ("The pious devotee spoke with deep reverence while praying before the holy shrine", "भक्त मंदिर में हाथ जोड़कर बड़ी श्रद्धा से प्रार्थना के बोल बोला"),
    ("The careless housekeeper forgot to extinguish the burning candle before going to sleep", "सोने से पहले नौकर कमरे में जलती हुई मोमबत्ती बुझाना भूल गया"),
    ("The forest ranger brought a wounded baby deer to the veterinary rescue center", "वनरक्षक जंगल से घायल हिरण के बच्चे को अस्पताल लाया"),
    ("The candid child spoke whatever came naturally to his pure and innocent mind", "मासूम बच्चे के मन में जो आया वह तुरंत साफ़ साफ़ बोला"),
    ("The old watchman forgot to wind the key of the mechanical tower clock", "बूढ़ा चौकीदार मीनार की बड़ी घड़ी की चाबी भरना भूल गया"),
    ("The royal ambassador brought rare precious emeralds as tribute from the southern empire", "दूत दक्षिण के राज्य से बहुमूल्य रत्नों की भेंट लाया"),
    ("The upright politician spoke strictly in defense of democratic values and civil rights", "ईमानदार नेता संसद में नागरिकों के अधिकारों के पक्ष में बोला"),
    ("The hurried messenger forgot the sealed royal diplomatic envelope on his desk table", "जल्दबाज़ी में हरकारा मेज़ पर रखा हुआ ज़रूरी पत्र भूल गया"),
    ("The mountain boy brought wild purple berries from the high rocky hillside bushes", "पहाड़ी बालक ऊँची चट्टानों से तोड़कर मीठे जंगली फल लाया"),
    ("The courageous advocate spoke against the wrongful imprisonment of the peaceful political protesters", "वकील अदालत में बंदियों की रिहाई के पक्ष में निडर होकर बोला"),
    ("The forgetful gardener forgot to water the delicate potted rose plants in afternoon", "माली दोपहर में गमलों में लगे गुलाब के पौधों को पानी देना भूल गया"),

    # 166-200: Intransitive Verbs taking ने (छींकना, खाँसना, नहाना - Ergative with intransitives)
    ("The old grandfather coughed loudly in the cold damp air of early morning", "बूढ़े दादाजी ने सुबह की ठंडी हवा में ज़ोर से खाँसा"),
    ("The little girl sneezed three times when black pepper was ground in kitchen", "रसोई में काली मिर्च पिसते ही छोटी बच्ची ने तीन बार छींका"),
    ("The tired pilgrim bathed in the sacred waters of the holy mountain river", "थके हुए तीर्थयात्री ने पावन नदी के शीतल जल में श्रद्धा से नहाया"),
    ("The patient coughed throughout the chilly night because of severe throat congestion", "गले में खराश होने के कारण रोगी ने रात भर खाँसा"),
    ("The sensitive child sneezed immediately when entering the dusty abandoned attic room", "धूल भरे पुराने कमरे में जाते ही बालक ने ज़ोर से छींका"),
    ("The ascetic bathed before dawn in the quiet running waters of the brook", "साधु ने सूर्योदय से पहले बहते हुए झरने के जल में नहाया"),
    ("The weary traveler coughed painfully as dry dust swirled along the desert highway", "सड़क पर उड़ती धूल के कारण मुसाफिर ने मुँह पर कपड़ा रखकर खाँसा"),
    ("The apprentice sneezed when the strong aroma of crushed spices filled the workshop", "मसालों की तीखी गंध लगते ही नौसिखिए ने अचानक छींका"),
    ("The king bathed in fragrant water infused with pure rose petals and sandalwood", "राजा ने गुलाब जल और चंदन से सुवासित जल में स्नान किया और नहाया"),
    ("The elderly villager coughed into his woolen shawl to clear his congested chest", "बुजुर्ग ने छाती साफ़ करने के लिए अपनी चादर की ओट में खाँसा"),
    ("The young student sneezed loudly during the silent examination in the study hall", "शांत परीक्षा भवन में एक छात्र ने अचानक बहुत ज़ोर से छींका"),
    ("The pious family bathed together at the holy confluence during the solar eclipse", "ग्रहण के पावन अवसर पर पूरे परिवार ने संगम के जल में नहाया"),
    ("The coal miner coughed from the thick subterranean soot inside the deep pit", "खान से बाहर निकलते ही मजदूर ने कालिख के कारण खाँसा"),
    ("The cook sneezed when chili powder accidentally blew into the kitchen air", "हवा में मिर्च का पाउडर उड़ते ही रसोइए ने तुरंत छींका"),
    ("The warrior bathed in the cool forest spring to cleanse his tired limbs", "युद्ध के बाद वीर सिपाही ने जंगल के ठंडे झरने में नहाया"),
    ("The asthmatic patient coughed gently into a clean handkerchief during the medical examination", "जाँच के समय मरीज ने रुमाल मुँह पर रखकर धीरे से खाँसा"),
    ("The cat sneezed comically when sniffing the pungent mustard oil in the pan", "तेल की गंध सूंघते ही बिल्ली ने अपनी मूँछें हिलाकर छींका"),
    ("The weary farmer bathed after a long day of exhausting labor in fields", "खेतों में दिन भर हल चलाने के बाद किसान ने कुएँ पर नहाया"),
    ("The horse driver coughed in the dense winter fog hanging over the riverbank", "नदी पर छाए घने कोहरे के बीच गाड़ीवान ने कई बार खाँसा"),
    ("The little boy sneezed when the ticklish peacock feather brushed against his nose", "मोरपंख छूते ही छोटे बच्चे ने अपनी आँखें सिकोड़कर छींका"),
    ("The devout pilgrim bathed at dawn reciting sacred Sanskrit prayers for universal peace", "सुबह की पहली किरण फूटते ही श्रद्धालु ने नदी में नहाया"),
    ("The old watchman coughed to announce his presence to the midnight patrolling sergeant", "चौकीदार ने गश्त पर आए अधिकारी को संकेत देने के लिए खाँसा"),
    ("The botanist sneezed from the fine powdery pollen of the rare mountain orchids", "जंगली फूलों के परागकण नाक में जाते ही वैज्ञानिक ने छींका"),
    ("The ascetic bathed in the freezing glacial waters beneath the towering mountain crags", "बर्फीली चोटी के नीचे बहती धारा में तपस्वी ने निर्भय होकर नहाया"),
    ("The smoker coughed heavily in the morning before starting his daily hard labor", "काम शुरू करने से पहले उस व्यक्ति ने अपनी छाती पकड़कर खाँसा"),
    ("The baby sneezed cutely when exposed to the bright outdoor sunlight in garden", "धूप में आते ही नन्हे बच्चे ने अपनी गोल आँखें मटकाकर छींका"),
    ("The traveler bathed at the village stepwell to wash away the highway dust", "लंबी यात्रा की थकान मिटाने के लिए मुसाफिर ने बावड़ी पर नहाया"),
    ("The sick soldier coughed in his bunker during the damp and rainy night", "बरसात की सीलन भरी रात में सिपाही ने अपनी चौकी में खाँसा"),
    ("The girl sneezed when the dry autumn dust blew through the open window", "खिड़की से उड़ती धूल आते ही कमरे में बैठी लड़की ने छींका"),
    ("The wrestler bathed in cold well water after completing his rigorous morning workout", "कठिन व्यायाम पूरा करने के बाद पहलवान ने अखाड़े के कुएँ पर नहाया"),
    ("The teacher coughed discreetly to draw the attention of the noisy classroom students", "कक्षा में शांति कराने के लिए अध्यापक ने मेज़ पर हाथ रखकर खाँसा"),
    ("The puppy sneezed when a blade of green grass tickled its black nose", "घास की पत्ती नाक में लगते ही छोटे पिल्ले ने छींका"),
    ("The holy sage bathed in the quiet mountain lake under the morning stars", "सुबह के तारों की छाँव में महात्मा ने पवित्र सरोवर में नहाया"),
    ("The old clerk coughed as he dusted fifty year old dusty paper files", "पुराने बहीखातों की धूल झाड़ते हुए मुनीम ने बार बार खाँसा"),
    ("The precise rules of ergative agreement govern these classical and colloquial Hindi constructions", "हिंदी व्याकरण के इन सुंदर नियमों ने भाषा को वैज्ञानिक सटीकता प्रदान की"),
]

if __name__ == "__main__":
    process_batch(35, "p35s", PAIRS)
