#!/usr/bin/env python3
"""Batch ID-06: Societal, Moral & Philosophical Proverbs (250 sentences).
File: data/phrases30.json, IDs: p30s001..p30s250.
Themes: न्याय, कर्म, समय, भाग्य, परिश्रम, धर्म, जैसा बोओगे वैसा काटोगे, जिसकी लाठी उसकी भैंस, धीरज का फल मीठा.
"""
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parent))
from gen_batches_pipeline import process_batch

PAIRS = [
    # 1-40: कर्म एवं फल (Karma, Action, Retribution)
    ("As you sow so shall you reap in this moral universe", "इस संसार में जैसा बोओगे वैसा ही फल काटोगे"),
    ("If you plant a thorny acacia tree mangoes will never grow", "बोए पेड़ बबूल का तो आम कहाँ से होय"),
    ("Every person will inevitably suffer the exact fruits of his actions", "जैसी करनी वैसी भरनी का नियम इस संसार में अटल है"),
    ("The wicked criminal had to pay the penalty for his evil deeds", "दुष्ट अपराधी को अपने काले कारनामों का फल भुगतना ही पड़ा"),
    ("Good deeds bring lasting joy while deceit brings inevitable ruin", "नेकी का फल मीठा होता है जबकि धोखे का अंत विनाश होता है"),
    ("The selfish brother realized too late that bad actions yield bitter fruit", "स्वार्थी भाई को देर से समझ आया कि बुरे कर्म का फल कड़वा होता है"),
    ("The honest farmer believed firmly that honest labor always bears fruit", "ईमानदार किसान को दृढ़ विश्वास था कि सच्चा परिश्रम कभी व्यर्थ नहीं जाता"),
    ("The deceitful merchant lost his fortune as retribution for his fraudulent tricks", "धोखेबाज़ व्यापारी ने अपनी बेईमानी के कारण सारा कमाया हुआ धन खो दिया"),
    ("Do good deeds continually and throw them into the flowing river selflessly", "नेकी कर और दरिया में डाल की नीति पर चलने वाला सदा शांत रहता है"),
    ("The arrogant prince fell into the very pit he dug for others", "जो दूसरों के लिए गड्ढा खोदता है वह खुद उसमें गिरता है"),
    ("Those who cultivate thorns cannot expect fragrant roses in their courtyard", "काँटे बोने वाले अपने आँगन में सुगंधित गुलाब खिलने की आशा नहीं कर सकते"),
    ("The greedy usurer suffered severe loss in the divine court of justice", "लालची सूदखोर को ईश्वर के दरबार में अपने पापों का दंड भुगतना पड़ा"),
    ("Virtuous deeds are like seeds that blossom into peace and prosperity", "सत्कर्म ऐसे बीज हैं जो समय आने पर सुख और शांति के फूल खिलाते हैं"),
    ("The cruel commander faced utter defeat because of his ruthless tyranny", "क्रूर सेनापति को अपने भीषण अत्याचारों का दंड पराजय के रूप में मिला"),
    ("Whatever seed of effort you plant today will become your tomorrow harvest", "आज तुम जो परिश्रम का बीज बोओगे वही कल तुम्हारी फसल बनेगा"),
    ("The corrupt officer found that ill gotten wealth brings only disease and sorrow", "भ्रष्ट अधिकारी ने देखा कि अन्याय का धन केवल बीमारी और कलह लाता है"),
    ("One who harms innocent souls will surely weep in his old age", "मासूमों को सताने वाला व्यक्ति अपने बुढ़ापे में अवश्य आँसू बहाएगा"),
    ("The generous donor gave away half his wealth without expecting any praise", "उदार दानी ने किसी प्रशंसा की चाह के बिना अपना आधा धन दान कर दिया"),
    ("Sin may hide in shadows but its consequence walks boldly in daylight", "पाप भले अंधेरे में छिपे पर उसका फल दिन के उजाले में सामने आता है"),
    ("The kind physician treated poor patients freely and earned eternal goodwill", "दयालु वैद्य ने गरीबों का मुफ्त इलाज करके अनमोल पुण्य कमाया"),
    ("Do not lament today over the harvest that your past negligence sowed", "आज उस फसल पर मत रोओ जिसे तुम्हारी अपनी पुरानी लापरवाही ने बोया था"),
    ("The traitor discovered that betrayal destroys the betrayer first of all", "गद्दार ने पाया कि विश्वासघात सबसे पहले विश्वासघाती को ही नष्ट करता है"),
    ("Every righteous action strengthens the moral fabric of human society", "हर नेक कर्म मानव समाज के नैतिक ताने बाने को मजबूत बनाता है"),
    ("The envious courtier poisoned himself with the venom of his own malice", "ईर्ष्यालु दरबारी अपने ही मन के द्वेष के विष से जलकर भस्म हो गया"),
    ("When you give water to thirsty roots the whole tree will bear sweet fruit", "जब तुम प्यासी जड़ों को पानी दोगे तो पूरा वृक्ष मीठे फल देगा"),
    ("The robber repented with bitter tears when retribution knocked at his gate", "जब कर्म का डंडा पड़ा तब डाकू ने पश्चाताप के कड़वे आँसू बहाए"),
    ("Virtue requires patient perseverance while vice offers only swift illusions", "पुण्य के लिए धैर्य की आवश्यकता होती है जबकि पाप केवल क्षणिक भ्रम देता है"),
    ("The benevolent queen built shelters and dug wells along every dusty highway", "दयालु रानी ने हर धूल भरे राजमार्ग पर विश्रामगृह बनवाए और कुएँ खुदवाए"),
    ("A harvest of hatred can never produce a loaf of harmonious peace", "नफरत की फसल कभी आपसी शांति और भाईचारे की रोटी नहीं दे सकती"),
    ("The wise father taught his sons that truthfulness is the supreme treasure", "ज्ञानी पिता ने अपने पुत्रों को सिखाया कि सत्यनिष्ठा ही सबसे बड़ा खजाना है"),
    ("Retribution may arrive with slow footsteps but its strike is unerringly accurate", "कर्म का न्याय भले धीमी गति से चले पर उसका प्रहार अचूक होता है"),
    ("The selfless teacher devoted fifty years to shaping hundreds of young minds", "निःस्वार्थ शिक्षक ने सैकड़ों बालकों के चरित्र निर्माण में पचास वर्ष लगा दिए"),
    ("The proud conqueror lost his vast empire because of unbridled cruelty", "घमंडी विजेता ने अपने अनियंत्रित क्रूर कर्मों के कारण विशाल साम्राज्य गँवा दिया"),
    ("Plant trees of loving kindness so travelers may rest beneath their cool shade", "प्रेम और करुणा के वृक्ष लगाओ ताकि राहगीर उनकी शीतल छाँव में सुस्ता सकें"),
    ("Dishonesty may build a grand palace but integrity creates a peaceful home", "बेईमानी भले महल खड़ा कर दे पर ईमानदारी ही सुखद घर बनाती है"),
    ("The humble clerk was blessed with loyal children because of his pure life", "पवित्र जीवन जीने के कारण गरीब मुंशी को आज्ञाकारी संतान का सुख मिला"),
    ("The tyrant learned in his final hour that power without righteousness is dust", "अत्याचारी ने अंतिम समय में जाना कि धर्म के बिना शक्ति केवल धूल है"),
    ("Sow seeds of knowledge today so the next generation may reap wisdom", "आज ज्ञान के बीज बोओ ताकि आने वाली पीढ़ी बुद्धिमानी की फसल काट सके"),
    ("The spiteful gossip found herself abandoned by all her former acquaintances", "दूसरों की निंदा करने वाली महिला को अंत में सभी परिचितों ने अकेला छोड़ दिया"),
    ("Righteous deeds shine like steady stars across the darkest nocturnal sky", "सत्कर्म अंधेरी रात के आकाश में ध्रुव तारे की तरह सदा जगमगाते रहते हैं"),

    # 41-80: न्याय, सत्य एवं अधर्म (Justice, Truth, Might is Right)
    ("Truth fears no ordeal and needs no false witnesses to defend itself", "साँच को आंच नहीं और सच को किसी झूठे गवाह की ज़रूरत नहीं"),
    ("The honest magistrate separated milk from water with absolute impartiality", "ईमानदार न्यायाधीश ने दूध का दूध और पानी का पानी कर दिखाया"),
    ("The arrogant landlord bullied the poor peasants because might is right", "दबंग ज़मींदार गरीबों को दबाता था क्योंकि जिसकी लाठी उसकी भैंस होती है"),
    ("Truth alone triumphs in the end and falsehood vanishes like morning mist", "अंत में सत्य की ही जीत होती है और झूठ कोहरे की तरह मिट जाता है"),
    ("The courageous witness spoke the absolute truth without fearing the violent gang", "साहसी गवाह ने खूंखार गिरोह के डर के बिना अदालत में सच कह दिया"),
    ("A lie has no legs to stand upon when challenged by fact", "तथ्यों के सामने आते ही झूठ के पाँव उखड़ जाते हैं"),
    ("The greedy feudal lord took the fertile land by force using brute muscle", "सामंत ने अपनी लाठी के बल पर गरीब किसान की उपजाऊ ज़मीन हथिया ली"),
    ("The transparent judicial inquiry revealed the hidden fraud for all to see", "पारदर्शी न्यायिक जाँच ने दूध का दूध पानी का पानी करके सबको चौंका दिया"),
    ("An innocent heart sleeps peacefully because truth fears no flame", "सच्चे इंसान का हृदय शांत रहता है क्योंकि साँच को कोई आंच नहीं आती"),
    ("The law of the jungle prevails where might dictates what is considered right", "जहाँ जिसकी लाठी उसकी भैंस का नियम चले वहाँ जंगल राज कायम होता है"),
    ("Falsehood may wear golden robes but naked truth remains far more radiant", "झूठ भले सुनहरे वस्त्र पहन ले पर नंगा सच उससे कहीं अधिक तेजस्वी होता है"),
    ("The righteous king decreed that justice must be equal for prince and pauper", "धर्मनिष्ठ राजा ने आदेश दिया कि राजकुमार और रंक दोनों के लिए न्याय समान होगा"),
    ("The forensic evidence proved who was guilty and cleared the innocent youth", "वैज्ञानिक साक्ष्यों ने दूध का दूध पानी का पानी करके निर्दोष बालक को छुड़ाया"),
    ("Do not be terrified of false accusations when your conscience is pure", "जब तुम्हारा मन साफ़ हो तो झूठे आरोपों से मत डरो क्योंकि साँच को आंच नहीं"),
    ("The wealthy syndicate used bribed musclemen to dictate terms in the market", "धनी गिरोह ने लठैतों के दम पर बाज़ार में जिसकी लाठी उसकी भैंस का खेल खेला"),
    ("Truth is like pure gold that shines brighter after passing through fire", "सत्य शुद्ध सोने जैसा है जो अग्नि परीक्षा से गुजरकर और निखर जाता है"),
    ("The independent tribunal exposed the corrupt minister without fear or favor", "स्वतंत्र आयोग ने निष्पक्ष होकर दूध का दूध पानी का पानी कर दिया"),
    ("Those who rely solely upon brute force will eventually perish by brute force", "जो केवल लाठी के बल पर जीते हैं उनका अंत भी लाठी से ही होता है"),
    ("A single spark of truth can dispel a mountain of accumulated falsehood", "सत्य की एक छोटी सी चिनगारी झूठ के विशाल पहाड़ को भस्म कर सकती है"),
    ("The upright inspector refused to bow before the pressure of the wealthy elite", "ईमानदार दरोगा ने रसूखदारों के दबाव के आगे झुकने से साफ़ मना कर दिया"),
    ("The impartial village panchayat resolved the bitter land dispute fairly yesterday", "गाँव की निष्पक्ष पंचायत ने कल ज़मीन के पुराने झगड़े का न्यायसंगत फैसला किया"),
    ("The arrogant bully thought his muscle power made him supreme over the weak", "घमंडी लठैत सोचता था कि उसकी ताकत के आगे किसी की आवाज़ नहीं उठ सकती"),
    ("When truth speaks with calm dignity all noisy deceptions fall utterly silent", "जब सत्य धीर स्वर में बोलता है तब सारे झूठे कोलाहल शांत हो जाते हैं"),
    ("The supreme court delivered a historic judgment separating truth from fabrication", "सर्वोच्च न्यायालय ने ऐतिहासिक फैसले में दूध का दूध और पानी का पानी कर दिया"),
    ("Stand firm upon the solid ground of righteousness and you will never falter", "सत्य के दृढ़ धरातल पर खड़े रहो तो तुम्हें कभी कोई हिला नहीं सकेगा"),
    ("The strong oppressive clan confiscated the cows because of raw physical dominance", "ताकतवर खानदान ने अपनी लाठी के दम पर निर्बल चरवाहे की गायें छीन लीं"),
    ("Truth does not require angry shouting because quiet sincerity is its shield", "सच को चिल्लाने की ज़रूरत नहीं होती क्योंकि सादगी ही उसका सच्चा कवच है"),
    ("The wise mediator heard both sides patiently and arrived at just compromise", "समझदार पंच ने दोनों पक्षों को धैर्य से सुना और उचित न्याय प्रदान किया"),
    ("The counterfeit currency was detected instantly by the vigilant bank teller", "सतर्क खज़ांची ने एक नज़र में ही जाली नोट को असली से अलग कर दिया"),
    ("No amount of political influence can bend the scales of upright justice", "कोई भी राजनीतिक दबाव सच्चे न्याय के तराजू को कभी झुका नहीं सकता"),
    ("The oppressed laborers rose in unity against the doctrine of raw might", "शोषित मजदूरों ने एकजुट होकर लाठी के बल पर चलने वाले राज का विरोध किया"),
    ("Truth remains unshakeable like the mighty Himalayas amidst stormy deceitful winds", "छल कपट के तूफानों के बीच भी सत्य हिमालय की तरह अडिग खड़ा रहता है"),
    ("The wise ruler listened to the complaints of the poorest beggar attentively", "न्यायप्रिय शासक ने सबसे निर्धन भिक्षुक की फ़रियाद भी पूरे ध्यान से सुनी"),
    ("When justice is denied in the street revolution knocks loudly upon the palace", "जब गलियों में न्याय नहीं मिलता तब राजमहल के दरवाजों पर क्रांति दस्तक देती है"),
    ("An honest tongue never stutters because it carries no burden of deceit", "सच्ची जीभ कभी लड़खड़ाती नहीं क्योंकि उस पर झूठ का कोई बोझ नहीं होता"),
    ("The tyrant decreed harsh punishments but the moral spirit of people remained unbowed", "अत्याचारी ने कठोर दंड दिए पर जनता की नैतिक चेतना उसके आगे नहीं झुकी"),
    ("Fair play and equal rights must replace the ancient rule of physical coercion", "लाठी के पुराने नियम की जगह अब समानता और न्याय का शासन होना चाहिए"),
    ("The purity of gold is tested on touchstone and character is tested in adversity", "सोने की परख कसौटी पर होती है और मनुष्य के चरित्र की परख विपत्ति में"),
    ("A peaceful society cannot survive if brute power tramples over constitutional rights", "यदि बाहुबल अधिकारों को कुचलता रहे तो कोई भी समाज शांति से नहीं रह सकता"),
    ("The victory of righteousness may take time but it remains completely inevitable", "सत्य की विजय में समय लग सकता है परंतु उसका होना पूरी तरह निश्चित है"),

    # 81-125: धैर्य, समय एवं अवसर (Patience, Time, Opportunity)
    ("The fruit of patience is always sweet and brings enduring inner peace", "धीरज का फल मीठा होता है और वह मन को सच्ची शांति देता है"),
    ("Time waits for no man so seize the fleeting golden opportunity today", "वक्त किसी का इंतज़ार नहीं करता इसलिए आज ही शुभ अवसर का लाभ उठाओ"),
    ("A drowning man catches at a straw when all other hope fails", "डूबते को तिनके का सहारा भी जीवन की नई आस जगा देता है"),
    ("As long as there is life in the body the world remains full of promise", "जान है तो जहान है इसलिए सबसे पहले अपने स्वास्थ्य की रक्षा करो"),
    ("Patience overcomes immense obstacles that brute anger can never resolve", "धैर्य उन विशाल बाधाओं को पार कर लेता है जिन्हें क्रोध कभी हल नहीं कर सकता"),
    ("The train had already departed because time respects no delayed traveler", "समय किसी के लिए नहीं रुकता और गाड़ी यात्री के आने से पहले निकल गई"),
    ("In desperate calamity even the smallest assistance feels like a life raft", "घोर संकट में छोटा सा सहारा भी डूबते को तिनके की तरह बचा लेता है"),
    ("Do not risk your precious existence recklessly because life is supreme wealth", "लापरवाही से अपनी जान खतरे में मत डालो क्योंकि जान है तो जहान है"),
    ("The wise gardener waits patiently through winter for spring blossoms to bloom", "समझदार माली सर्दियों में धैर्य रखता है क्योंकि वह जानता है कि धीरज का फल मीठा होता है"),
    ("Yesterday has departed and tomorrow is uncertain so value the present moment", "बीता हुआ कल लौटता नहीं इसलिए वर्तमान समय का सही उपयोग करना सीखो"),
    ("A kind encouraging word gave hope to the bankrupt businessman like a straw", "दीवालिया हो चुके व्यापारी के लिए मित्र का दिलासा डूबते को तिनके का सहारा बना"),
    ("Escape from the burning building immediately because if life remains everything remains", "जलते मकान से तुरंत बाहर निकलो क्योंकि जान है तो सारा जहान बचा रहेगा"),
    ("Endure the present bitter hardship with fortitude because sweet rewards await", "वर्तमान कठिनाई को धीरज से सहो क्योंकि धीरज का फल हमेशा मीठा होता है"),
    ("Lost gold can be regained through labor but lost seconds vanish forever", "खोया धन फिर कमाया जा सकता है पर बीता हुआ समय कभी वापस नहीं आता"),
    ("The stranded mountaineer clung to the narrow ledge hoping for rescue", "बर्फ़ीले पहाड़ पर फँसे पर्वतारोही के लिए रस्सी का सिरा डूबते को तिनके जैसा लगा"),
    ("The wise doctor advised the patient to rest quietly because health is prime", "अनुभवी चिकित्सक ने रोगी को आराम करने को कहा क्योंकि जान है तो जहान है"),
    ("The young apprentice mastered the craft slowly because patience yields mastery", "युवा कारीगर ने धीरज के साथ काम सीखा और अंत में उत्तम सफलता प्राप्त की"),
    ("Do not postpone today task until tomorrow because time slips like sand", "आज का काम कल पर मत टालो क्योंकि समय हाथ से रेत की तरह फिसल जाता है"),
    ("The poor widow found solace in the small monthly charity from the temple", "बेसहारा विधवा के लिए मंदिर से मिलने वाली थोड़ी सी सहायता डूबते को तिनके जैसी थी"),
    ("First ensure personal safety in the storm because life is irreplaceable", "तूफान में पहले अपनी सुरक्षा करो क्योंकि जान है तो जहान की सारी खुशियाँ हैं"),
    ("The fruit that ripens naturally on the branch tastes sweetest of all", "डाल पर प्राकृतिक रूप से पका फल सबसे मीठा होता है जैसे धीरज का फल मीठा होता है"),
    ("Wasted youth brings bitter regrets when the cold winter of age arrives", "समय गँवाने वाले को बुढ़ापा आने पर केवल पश्चाताप ही हाथ लगता है"),
    ("A small loan from a childhood friend saved the craftsman from complete bankruptcy", "बचपन के मित्र का छोटा सा कर्ज़ उस संकटग्रस्त कारीगर के लिए डूबते को तिनका साबित हुआ"),
    ("Leave the heavy luggage behind and flee the floodwaters because life comes first", "बाढ़ के पानी से बचते समय सामान छोड़ दो क्योंकि जान है तो जहान है"),
    ("Those who cultivate patient endurance never taste the bitter defeat of despair", "जो धीरज रखना जानते हैं वे कभी निराशा के कड़वे घूँट नहीं पीते"),
    ("The river of time flows constantly without ever reversing its rapid current", "समय की धारा निरंतर बहती रहती है और कभी उल्टी दिशा में नहीं मुड़ती"),
    ("The encouraging letter from his mother gave the soldier strength to persevere", "माँ के सांत्वना भरे पत्र ने युद्ध के मैदान में सिपाही को डूबते का सहारा दिया"),
    ("Protect your breath and body first because wealth can always be earned again", "पहले अपनी देह और प्राण की रक्षा करो क्योंकि जान है तो सारा संसार तुम्हारा है"),
    ("Sweet mangoes require months of sunshine so bear the long waiting willingly", "मीठे आम पकने में महीनों की धूप लगती है इसलिए धीरज रखना सीखो"),
    ("Every ticking second brings you closer to the inevitable sunset of life", "घड़ी की हर टिक टिक मनुष्य को जीवन के अंतिम पड़ाव के निकट लाती है"),
    ("The distant lighthouse gave hope to the battered vessel amidst giant waves", "तूफानी लहरों के बीच दूर का प्रकाश स्तंभ नाविकों के लिए डूबते को तिनके का सहारा बना"),
    ("Do not venture into the treacherous swamp at midnight because life is precious", "अंधेरी रात में उस खतरनाक दलदल में मत उतरो क्योंकि जान है तो जहान है"),
    ("Patience is the golden key that unlocks the door to enduring greatness", "धैर्य वह सुनहरी चाबी है जो महान सफलता के द्वार खोल देती है"),
    ("The season of sowing passed while the lazy farmer remained idle at home", "आलसी किसान घर बैठा रहा और बुआई का सुनहरा समय हाथ से निकल गया"),
    ("A single supportive witness turned the entire murder trial in favor of defense", "एक अकेले सच्चे गवाह ने हत्या के मुकदमे में डूबते अभियुक्त को सहारा दिया"),
    ("Surrender your purse to the robbers but save your life without hesitation", "लुटेरों को अपनी थैली दे दो पर अपनी जान बचाओ क्योंकि जान है तो जहान है"),
    ("The harvest of sweet grapes rewards the patient vinedresser who labored all summer", "गर्मियों भर पसीना बहाने वाले माली को अंत में मीठे अंगूरों का फल मिलता है"),
    ("Do not quarrel over minor matters when the urgent deadline is approaching fast", "जब समय कम बचा हो तब व्यर्थ के मुद्दों पर बहस करके वक्त मत गँवाओ"),
    ("A tiny flashlight beam guided the lost speleologists out of the dark cave", "घनी अंधेरी गुफा में टॉर्च की छोटी सी रोशनी भटके यात्रियों के लिए तिनके का सहारा बनी"),
    ("Remember the ancient proverb and preserve your health above all earthly ambitions", "पुरानी कहावत याद रखो कि जान है तो जहान है और स्वास्थ्य ही पहला सुख है"),
    ("The sweetest melody comes from strings that have been tuned with patience", "सबसे मधुर धुन उन्हीं तारों से निकलती है जिन्हें बड़े धीरज से साधा गया हो"),
    ("Time heals the deepest wounds that medicine cannot soothe or cure", "समय उन गहरे घावों को भी भर देता है जिन्हें कोई दवा ठीक नहीं कर सकती"),
    ("The kind stranger offered water and bread to the starving beggar on road", "सड़क पर गिरे भूखे भिक्षुक के लिए अजनबी की रोटी डूबते को तिनका बन गई"),
    ("Do not take foolish wagers with your existence because life is a gift", "अपने अनमोल जीवन के साथ खिलवाड़ मत करो क्योंकि जान है तो जहान है"),
    ("He who waits with steady calm will see the turbulent storm subside completely", "जो शांत मन से प्रतीक्षा करता है वह भयंकर तूफान को भी थमता हुआ देखता है"),

    # 126-170: भाग्य, परिश्रम एवं स्वावलंबन (Destiny, Labor, Self-reliance)
    ("God helps those who take the courageous initiative to help themselves", "ईश्वर भी उन्हीं की सहायता करता है जो अपनी सहायता स्वयं करते हैं"),
    ("Destiny smiles upon the valiant who dare to cross the stormy seas", "भाग्य भी उन्हीं साहसी वीरों पर मुस्कुराता है जो तूफानी सागर में उतरते हैं"),
    ("Empty wishing will never fill the granary without the sweat of hard labor", "केवल कामना करने से अन्न भंडार नहीं भरता जब तक कठोर परिश्रम न किया जाए"),
    ("The lazy beggar blamed his poor stars while sleeping under the banyan tree", "आलसी भिक्षुक पेड़ के नीचे सोता रहा और अपने दुर्भाग्य को कोसता रहा"),
    ("The iron will of a resolute human can carve roads through solid mountains", "दृढ़ इच्छाशक्ति वाला मनुष्य अपनी मेहनत से पहाड़ का सीना चीरकर रास्ता बना देता है"),
    ("Do not depend upon the charity of others when you possess two strong arms", "जब तुम्हारे पास दो मजबूत हाथ हैं तो दूसरों की दया पर निर्भर मत रहो"),
    ("Fortune favors the brave warrior who charges forward with unflinching courage", "किस्मत भी उसी शूरवीर का साथ देती है जो बिना डरे आगे बढ़ता है"),
    ("A field left unplowed produces only weeds regardless of fertile soil and rain", "खेत में हल न चलाओ तो उपजाऊ भूमि भी केवल खरपतवार ही पैदा करती है"),
    ("Self reliance is the foundation upon which true independence and dignity stand", "स्वावलंबन ही वह ठोस आधार है जिस पर सच्चा स्वाभिमान और सम्मान टिकता है"),
    ("The skilled artisan takes immense pride in the honest work of his hands", "कुशल कारीगर अपने हाथों की सच्ची मेहनत से बनी वस्तु पर गर्व करता है"),
    ("Blaming cruel fate is the customary excuse of the indolent and the faint hearted", "किस्मत को दोष देना केवल कायरों और कामचोरों का पुराना बहाना होता है"),
    ("Every drop of honest sweat fallen upon soil turns into grain of gold", "धरती पर गिरी पसीने की हर बूँद समय आने पर सोने का दाना बन जाती है"),
    ("Stand upon your own feet rather than leaning upon the fragile crutches of others", "दूसरों की कमज़ोर बैसाखियों के सहारे चलने के बजाय अपने पैरों पर खड़े होना सीखो"),
    ("The ambitious youth changed his destiny through relentless nocturnal studies", "लगनशील युवक ने रात रात भर पढ़ाई करके अपनी तकदीर खुद बदल डाली"),
    ("Those who wait for luck to strike them remain hungry beside overflowing streams", "जो केवल भाग्य के भरोसे बैठे रहते हैं वे बहती नदी के किनारे भी प्यासे मरते हैं"),
    ("Dignity of labor elevates the humblest sweeper above the idle aristocratic prince", "परिश्रम का गौरव साधारण मजदूर को भी निकम्मे राजकुमार से ऊँचा उठा देता है"),
    ("Build your own boat before the catastrophic flood washes the peaceful valley away", "इससे पहले कि विनाशकारी बाढ़ आ जाए अपनी नाव खुद तैयार कर लो"),
    ("The diligent ant gathers food during pleasant summer for the harsh winter ahead", "मेहनती चींटी गर्मियों में ही खाना जमा कर लेती है ताकि सर्दियों में कष्ट न हो"),
    ("Do not stretch your begging bowl when your limbs are healthy and strong", "जब तुम्हारे अंग स्वस्थ और बलवान हैं तो किसी के आगे हाथ मत फैलाओ"),
    ("Sweat is the sacred water with which the temple of fortune is washed", "पसीना वह पवित्र जल है जिससे सफलता के मंदिर की वेदी धोई जाती है"),
    ("The blacksmith shapes glowing iron by heavy blows not by passive wishing", "लोहार हथौड़े की भारी चोट से लोहे को आकार देता है केवल इच्छा करने से नहीं"),
    ("A person who relies upon his own strength walks with head held high", "जो अपनी ताकत पर भरोसा करता है वह हमेशा सिर उठाकर गर्व से चलता है"),
    ("Luck may open the front door but perseverance alone can build the mansion", "किस्मत भले दरवाज़ा खोल दे पर महल का निर्माण केवल सतत परिश्रम ही करता है"),
    ("The idle dreamer weaves golden castles in the air that vanish at dawn", "आलसी सपने देखने वाला हवा में महल बनाता है जो सुबह होते ही गायब हो जाते हैं"),
    ("Honest bread earned by hard toil tastes sweeter than stolen rich confection", "मेहनत से कमाई सूखी रोटी भी चोरी के स्वादिष्ट पकवान से अधिक मीठी लगती है"),
    ("The true hero creates his own favorable circumstances through courage and sweat", "सच्चा कर्मवीर परिस्थितियों का रोना नहीं रोता बल्कि अपने अवसर खुद बनाता है"),
    ("Relying upon inherited wealth without personal industry leads to swift poverty", "बिना मेहनत किए केवल पैतृक धन पर निर्भर रहने वाला जल्द कंगाल हो जाता है"),
    ("The mountain stream cuts through solid basalt rock by unceasing daily motion", "पहाड़ी झरना निरंतर बहकर सख्त से सख्त चट्टान का सीना भी काट देता है"),
    ("A diligent student never complains about the difficulty of the competitive test", "परिश्रमी छात्र कभी कठिन परीक्षा का बहाना बनाकर हार नहीं मानता"),
    ("God has given two hands to labor and one tongue to speak wisely", "ईश्वर ने काम करने के लिए दो हाथ दिए हैं और सोच समझकर बोलने के लिए एक जीभ"),
    ("The farmer rises before dawn to till the dry earth under blistering heat", "किसान भोर होते ही उठकर चिलचिलाती धूप में सूखी धरती पर हल चलाता है"),
    ("Do not wait for wind to blow your sailboat row with your oars", "हवा चलने की प्रतीक्षा मत करो बल्कि अपनी पतवारें उठाकर नाव खुद चलाओ"),
    ("Indolence is a slow poison that rusts the brightest talents of human mind", "आलस्य वह धीमा ज़हर है जो मनुष्य की सर्वोत्तम प्रतिभा को भी नष्ट कर देता है"),
    ("The architect of his own destiny leaves footprints upon the sands of history", "अपनी तकदीर का निर्माता इतिहास के पन्नों पर अपने अमिट पदचिह्न छोड़ जाता है"),
    ("A bird resting upon a high branch trusts its wings not the branch", "शाखा पर बैठा पक्षी डाल पर नहीं बल्कि अपने मजबूत पंखों पर भरोसा करता है"),
    ("Continuous practice turns the clumsy novice into an accomplished master artisan", "लगातार अभ्यास अनाड़ी नौसिखिए को भी कुशल उस्ताद कारीगर बना देता है"),
    ("The wealth of self reliance can never be stolen by any highway robber", "स्वावलंबन का खजाना ऐसा है जिसे दुनिया का कोई डाकू कभी नहीं लूट सकता"),
    ("Work done with genuine devotion becomes its own sacred reward and benediction", "सच्चे समर्पण से किया गया कार्य स्वयं अपनी सबसे बड़ी पूजा बन जाता है"),
    ("The tiny seed splits the hard concrete pavement by sheer persistent life", "छोटा सा बीज भी अपने निरंतर प्रयास से पक्की सड़क को फाड़कर बाहर निकल आता है"),
    ("Those who plow in tears of exhaustion will reap in songs of joy", "जो पसीने और आँसुओं के साथ खेत जोतते हैं वे अंत में आनंद के गीत गाते हैं"),
    ("The master sculptor hammered the stubborn marble stone ten thousand times patiently", "मूर्तिकार ने पत्थर पर दस हज़ार चोटें मारकर सुंदर मूर्ति बनाई"),
    ("Do not gaze at the high mountain summit begin climbing the first step", "पहाड़ की ऊँची चोटी को केवल देखते मत रहो बल्कि पहला कदम आगे बढ़ाओ"),
    ("True nobility belongs not to noble birth but to noble and selfless deeds", "सच्ची कुलीनता ऊँचे कुल में जन्म लेने से नहीं बल्कि श्रेष्ठ कर्मों से मिलती है"),
    ("He who conquers his own indolence has conquered the mightiest enemy within", "जिसने अपने आलस्य को जीत लिया उसने अपने सबसे बड़े आंतरिक शत्रु को हरा दिया"),
    ("Labor brings sweet sound sleep that gold and soft feather mattresses cannot buy", "कठिन परिश्रम वह मीठी नींद लाता है जिसे सोने की अशर्फियाँ भी नहीं खरीद सकतीं"),

    # 171-210: धर्म, नीति एवं सदाचार (Righteousness, Ethics, Virtue)
    ("Righteousness protects those who uphold righteousness with steadfast devotion", "धर्म की रक्षा करने वाले की रक्षा धर्म स्वयं करता है"),
    ("A tranquil mind is the supreme temple wherein divine peace abides forever", "शांत और निर्मल मन ही वह सच्चा मंदिर है जहाँ ईश्वर का वास होता है"),
    ("Anger begins in foolish delusion and ends in bitter lifelong repentance", "क्रोध की शुरुआत मूर्खता से होती है और उसका अंत पश्चाताप पर होता है"),
    ("Greed is an insatiable fire that consumes virtue honor and human peace", "लालच वह कभी न बुझने वाली आग है जो धर्म मान और शांति सबको जला देती है"),
    ("Forgiveness is the noble ornament that adorns the truly strong and brave", "क्षमा वीरों का सच्चा आभूषण है जो समर्थ व्यक्ति की शोभा बढ़ाता है"),
    ("Humility is not weakness but the calm strength of deep self knowledge", "विनम्रता कोई दुर्बलता नहीं बल्कि गहरे आत्मज्ञान की शांत शक्ति होती है"),
    ("The tongue has no bones yet it can break the strongest human heart", "जीभ में हड्डी नहीं होती फिर भी वह मनुष्य के सबसे मजबूत दिल को तोड़ सकती है"),
    ("Compassion toward all living creatures is the supreme duty of civilized mankind", "सभी जीवों पर दया करना ही सभ्य मनुष्य का सबसे बड़ा धर्म है"),
    ("An evil deed leaves a dark stain that centuries of rain cannot wash", "कुकर्म का काला दाग ऐसा होता है जिसे सदियों की बारिश भी नहीं धो सकती"),
    ("Contentment is the greatest treasure that makes a poor pauper richer than kings", "संतोष ही वह सबसे बड़ा धन है जो निर्धन को भी सम्राट से अधिक सुखी रखता है"),
    ("The company of the wise uplifts the soul like sweet morning mountain air", "सत्संग मनुष्य के मन को सुबह की ठंडी और शुद्ध हवा की तरह पावन बना देता है"),
    ("Envy eats away the heart just as hidden rust eats away strong iron", "ईर्ष्या मनुष्य के मन को उसी तरह खा जाती है जैसे जंग लोहे को खा जाता है"),
    ("Speak the truth with gentleness and never utter truth with harsh cruelty", "सत्य को प्रिय और मधुर वाणी में बोलो कभी कड़वाहट के साथ सत्य मत कहो"),
    ("A pure conscience needs no locked doors to protect its inner serenity", "पवित्र अंतःकरण को अपनी मानसिक शांति की रक्षा के लिए किसी ताले की ज़रूरत नहीं"),
    ("Charity performed with arrogance loses all its spiritual merit and virtue", "घमंड के साथ दिया गया दान अपना सारा पुण्य और धार्मिक फल खो देता है"),
    ("The virtuous man remains calm in prosperity and unshaken in deep calamity", "सज्जन पुरुष सुख में विनम्र रहता है और घोर विपत्ति में भी विचलित नहीं होता"),
    ("Pride goes before a tragic fall just as dry leaves fall before storm", "विनाश से पहले अहंकार आता है जैसे आंधी आने से पहले सूखे पत्ते झड़ते हैं"),
    ("Kindness is a universal language that the deaf can hear and blind understand", "दयालुता वह भाषा है जिसे बहरे सुन सकते हैं और अंधे भी समझ सकते हैं"),
    ("Do not repay harsh hatred with hatred conquer hatred through boundless love", "नफरत का बदला नफरत से मत लो बल्कि नफरत को असीम प्रेम से जीतो"),
    ("A righteous life is like a fragrant flower that perfumes the whole garden", "धार्मिक जीवन उस सुगंधित फूल की तरह है जो पूरे बगीचे को महका देता है"),
    ("The highest worship consists in serving the distressed and wiping their tears", "दुखियों की सेवा करना और उनके आँसू पोंछना ही ईश्वर की सबसे बड़ी पूजा है"),
    ("Lust for power blinds the intellect and leads kings into utter ruin", "सत्ता का मोह बुद्धि को अंधा कर देता है और राजाओं को विनाश की ओर ले जाता है"),
    ("Purity of thought words and actions constitutes the true essence of religion", "मन वचन और कर्म की पवित्रता ही सच्चे धर्म का वास्तविक सार है"),
    ("Do unto others as you would have them do unto you always", "दूसरों के साथ वही व्यवहार करो जैसा तुम अपने लिए दूसरों से चाहते हो"),
    ("A selfish man lives only for himself and dies forgotten by everyone", "स्वार्थी मनुष्य केवल अपने लिए जीता है और मरने के बाद भुला दिया जाता है"),
    ("The shield of patience turns away the sharpest poisoned arrows of malice", "धैर्य का कवच द्वेष के सबसे तीखे और विषैले तीरों को भी मोड़ देता है"),
    ("Generosity enriches the giver far more than it enriches the humble receiver", "उदारता पाने वाले से कहीं अधिक देने वाले के हृदय को समृद्ध बनाती है"),
    ("The light of knowledge dispels the gloomy shadows of ignorance and superstition", "ज्ञान का प्रकाश अज्ञान और अंधविश्वास के घने अंधेरे को पूरी तरह मिटा देता है"),
    ("Do not covet the possessions of your neighbor live peacefully within your means", "पड़ोसी के धन पर बुरी नज़र मत डालो और अपने साधनों में संतोष से जियो"),
    ("A promise given by an upright man is as firm as carved granite", "सच्चे और नेक इंसान का वचन पत्थर पर खुदी लकीर की तरह अटल होता है"),
    ("Sympathy without practical assistance is like rain clouds that bring no water", "बिना मदद की केवल खोखली सहानुभूति उन बादलों जैसी है जो बरसते नहीं"),
    ("Self control is the highest form of mastery that a human can attain", "अपनी इंद्रियों पर नियंत्रण रखना ही मनुष्य की सबसे बड़ी विजय होती है"),
    ("The fragrance of good character spreads far beyond the boundaries of empires", "उत्तम चरित्र की सुगंध साम्राज्यों की सीमाओं से भी बहुत आगे तक फैलती है"),
    ("Never betray the sacred trust reposed in you by a trusting friend", "विश्वास करने वाले मित्र के साथ कभी छल या विश्वासघात मत करो"),
    ("Peace of mind cannot be bought in any marketplace of glittering gold", "मन की शांति को सोने चाँदी के किसी बाज़ार से कभी नहीं खरीदा जा सकता"),
    ("The righteous path may be narrow and rocky but it leads to light", "सच्चाई का मार्ग भले संकरा और पथरीला हो पर वह उजाले की ओर ले जाता है"),
    ("A gentle response disarms the violent wrath of an enraged adversary completely", "मधुर और शांत उत्तर क्रोधी शत्रु के भयानक गुस्से को भी ठंडा कर देता है"),
    ("Gratitude for past favors is the hallmark of a noble civilized soul", "किए गए उपकारों के प्रति कृतज्ञता प्रकट करना ही श्रेष्ठ आत्मा का लक्षण है"),
    ("Live each day so that you can look into the mirror with honour", "हर दिन ऐसा जीवन जियो कि शाम को आईने में सिर उठाकर देख सको"),
    ("The eternal moral laws of nature can never be broken with impunity", "प्रकृति के शाश्वत नैतिक नियमों को तोड़कर कोई भी कभी सुखी नहीं रह सकता"),

    # 211-250: समाज, संगति एवं लोक-विवेक (Society, Company, Folk Wisdom)
    ("A man is judged by the companionship he chooses to keep habitually", "मनुष्य की पहचान उसकी चुनी हुई संगति से ही समाज में होती है"),
    ("One rotten apple in the wooden basket spoils all the sound fruit", "टोकरी का एक सड़ा हुआ सेब बाकी सभी अच्छे फलों को भी सड़ा देता है"),
    ("Keep distance from wicked scoundrels whose honeyed words conceal deadly poison", "उन दुष्टों से दूर रहो जिनकी मीठी बातों के पीछे विष छिपा होता है"),
    ("A loyal and dependable friend is a rare treasure beyond all diamonds", "सच्चा और वफादार मित्र अनमोल हीरों से भी बढ़कर दुर्लभ खजाना होता है"),
    ("United we stand unconquerable while divided we fall like brittle dry twigs", "संगठन में ही शक्ति है और आपस में बँटकर हम तिनके की तरह बिखर जाते हैं"),
    ("Listen to the counsel of experienced elders before taking any perilous step", "कोई भी कठिन कदम उठाने से पहले अनुभवी बुजुर्गों की सलाह अवश्य लो"),
    ("Flattery is like sweet syrup that attracts swarms of troublesome buzzing flies", "चापलूसी वह मीठा शीरा है जो अपने चारों ओर मक्खियों को आकर्षित करता है"),
    ("The company of the virtuous turns even ordinary iron into glittering gold", "सत्संगति साधारण लोहे को भी पारस की तरह छूकर सोना बना देती है"),
    ("Do not wash your dirty linen in public before mocking nosy neighbors", "अपने घर की निजी बातों का तमाशा पड़ोसियों के सामने मत बनाओ"),
    ("A quarrel between two brothers invites the greedy outsider to loot both", "दो भाइयों का आपसी झगड़ा तीसरे लालची व्यक्ति को लूटने का अवसर देता है"),
    ("Social harmony flourishes when every community respects the traditions of others", "सामाजिक सद्भाव तभी पनपता है जब हर समुदाय दूसरों की परंपराओं का आदर करे"),
    ("Bad company leads the most innocent youth into the dark quagmire of crime", "बुरी संगति सीधे सादे बालक को भी अपराध के दलदल में धकेल देती है"),
    ("True friendship is tested in the crucible of poverty and bitter adversity", "सच्ची मित्रता की असली परीक्षा गरीबी और घोर विपत्ति के समय होती है"),
    ("The village functions smoothly when all castes and trades cooperate with goodwill", "गाँव तभी खुशहाल रहता है जब सभी वर्ग और कारीगर मिलकर काम करें"),
    ("Beware of false friends who praise you to your face and stab your back", "उन दिखावटी मित्रों से बचो जो मुँह पर मीठे और पीठ पीछे छुरा घोंपते हैं"),
    ("Collective effort can lift heavy mountains that single hands cannot even budge", "सामूहिक प्रयास उस विशाल पहाड़ को भी हिला देता है जिसे अकेला हाथ नहीं हिला सकता"),
    ("Respect the customary hospitality of the humble village home that shelters you", "उस गरीब झोपड़ी के आतिथ्य का सम्मान करो जिसने तुम्हें आश्रय दिया"),
    ("A poisonous snake remains venomous even if bathed in pure fresh milk", "साँप को दूध पिलाने पर भी उसका ज़हर कभी कम नहीं होता"),
    ("The wisdom of ages is preserved in the simple proverbs of common folk", "सदियों का अनुभव और ज्ञान आम जनता की सीधी सादी कहावतों में सुरक्षित रहता है"),
    ("Do not mock the physical infirmity of an unfortunate fellow human being", "किसी असहाय व्यक्ति की शारीरिक दुर्बलता का कभी उपहास मत उड़ाओ"),
    ("Mutual trust is the delicate glass vase that breaks with single deceit", "आपसी विश्वास का नाज़ुक शीशा एक ही धोखे की चोट से टूट जाता है"),
    ("A community without respect for teachers and elders decays into barbarous chaos", "जो समाज बुजुर्गों और गुरुओं का आदर नहीं करता वह पतन की ओर जाता है"),
    ("Speak words that heal broken spirits rather than words that ignite quarrels", "ऐसी वाणी बोलो जो टूटे दिलों को जोड़े न कि झगड़े की आग भड़काए"),
    ("The wise traveler adapts himself gracefully to the customs of the land", "बुद्धिमान मुसाफिर जिस देश में जाता है वहाँ के रीति रिवाजों को अपना लेता है"),
    ("Greedy relatives gather around wealth like ants gathering around a lump of sugar", "गुड़ की भेली के पास चींटियों की तरह मतलबी रिश्तेदार धन के पास जमा होते हैं"),
    ("Shared sorrow becomes lighter while shared happiness multiplies across the whole village", "बाँटा गया दुख आधा हो जाता है और बाँटी गई खुशी चौगुनी हो जाती है"),
    ("A good neighbor is closer and more helpful than a distant wealthy brother", "सच्चा पड़ोसी संकट के समय दूर रहने वाले धनी भाई से भी अधिक काम आता है"),
    ("Do not judge a book by its cover or a saint by his clothes", "किसी पुस्तक को उसके आवरण से और साधु को उसके वस्त्रों से मत आँको"),
    ("Peaceful dialogue can dismantle high fortress walls of long standing prejudice", "शांतिपूर्ण बातचीत पुरानी से पुरानी गलतफहमियों की दीवारों को ढहा सकती है"),
    ("The health of the social body depends upon justice for the weakest member", "समाज का स्वास्थ्य सबसे कमज़ोर वर्ग को न्याय मिलने पर ही निर्भर करता है"),
    ("Never burn down your own thatched cottage just to spite an annoying neighbor", "पड़ोसी से चिढ़कर अपनी ही झोपड़ी में आग लगाना घोर मूर्खता होती है"),
    ("True wisdom lies in understanding the difference between transient wealth and enduring honor", "सच्ची समझदारी इसी में है कि क्षणिक धन और स्थायी मान का अंतर समझा जाए"),
    ("A harmonious home is heaven on earth where laughter echoes through every room", "जिस घर में आपसी प्रेम और शांति हो वह धरती पर स्वर्ग के समान होता है"),
    ("Avoid associating with gamblers and drunkards lest their ruin overtake you as well", "जुआरी और शराबी की संगति से बचो ताकि उनका विनाश तुम्हें भी न ले डूबे"),
    ("The blessings of contented parents form the strongest protective shield for children", "संतुष्ट माता पिता का आशीर्वाद संतान के लिए सबसे मजबूत रक्षा कवच होता है"),
    ("Common sense is the rarest gift that bookish learning often fails to provide", "व्यावहारिक सामान्य ज्ञान वह दुर्लभ गुण है जिसे केवल किताबी पढ़ाई नहीं दे सकती"),
    ("Every citizen must contribute his honest share toward the progress of nation", "हर नागरिक को राष्ट्र की उन्नति में अपनी ईमानदारी की आहुति देनी चाहिए"),
    ("Live with such dignity that your departure leaves a fragrant memory behind", "ऐसा गरिमामय जीवन जियो कि तुम्हारे जाने के बाद संसार तुम्हारी यादों को नमन करे"),
    ("The strength of the chain is measured by its weakest single link", "ज़ंजीर की ताकत उसके सबसे कमज़ोर छल्ले से ही आँकी जाती है"),
    ("True moral greatness consists in lifting up those who have stumbled down", "सच्चा बड़प्पन गिरे हुए को सहारा देकर अपने पैरों पर खड़ा करने में है"),
]

if __name__ == "__main__":
    process_batch(30, "p30s", PAIRS)
