#!/usr/bin/env python3
"""Batch ID-07: Colloquial & Folk Sayings (250 sentences).
File: data/phrases31.json, IDs: p31s001..p31s250.
Themes: नाच न जाने आँगन टेढ़ा, उल्टा चोर कोतवाल को डांटे, कंगाली में आटा गीला, अंधों में काना राजा, एक अनार सौ बीमार, मान न मान मैं तेरा मेहमान, चमड़ी जाए पर दमड़ी न जाए.
"""
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parent))
from gen_batches_pipeline import process_batch

PAIRS = [
    # 1-35: नाच न जाने आँगन टेढ़ा (Blaming tools, excuses)
    ("The incompetent singer blamed the musical instruments because he could not sing", "गाना न आने पर गवैया साज़ों को दोष देने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("The bad workman quarrels with his tools when the wooden chair broke", "कुर्सी टूटने पर बढ़ई अपने औज़ारों को कोसने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("The lazy typist complained that the mechanical typewriter keys were too stiff", "टाइपिस्ट अपनी गलती मानने के बजाय कहने लगा कि नाच न जाने आँगन टेढ़ा"),
    ("The clumsy archer blamed the gentle wind for missing the target completely", "निशाना चूकने पर तीरंदाज हवा को दोष देने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("The failed candidate blamed the examination hall lighting for his bad performance", "अनुत्तीर्ण छात्र परीक्षा भवन की रोशनी को दोष देने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("The bad cook claimed that the stove heat was improper for baking", "रसोइया अपनी अकुशलता छिपाने के लिए चूल्हे को दोष देने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("An unskilled craftsman will always find fault with the material provided to him", "अकुशल कारीगर हमेशा सामग्री में खोट निकालता है जैसे नाच न जाने आँगन टेढ़ा"),
    ("The novice driver blamed the steering wheel when the car hit the fence", "गाड़ी टकराने पर नौसिखिया चालक स्टीयरिंग को दोष देने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("The careless painter claimed that the imported brushes were of poor quality", "चित्रकार अपनी गलती मानने के बजाय ब्रश को खराब बताने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("Do not blame the playground pitch when your batting technique is faulty", "अपनी कमज़ोर बल्लेबाज़ी छिपाने के लिए मैदान को दोष मत दो जैसे नाच न जाने आँगन टेढ़ा"),
    ("The unsuccessful salesman blamed the rural market instead of his bad speech", "बिक्री न होने पर सेल्समैन ग्राहकों को दोष देने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("The arrogant musician said that the hall acoustics ruined his performance entirely", "प्रदर्शन बिगड़ने पर गवैया सभागार की आवाज़ को कोसने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("A poor tailor blames the sewing machine needle for irregular crooked stitches", "सिलाई बिगड़ने पर दर्जी मशीन की सुई को दोष देता है जैसे नाच न जाने आँगन टेढ़ा"),
    ("The boastful runner claimed that his running shoes were too tight today", "दौड़ में पिछड़ने पर धावक अपने जूतों को दोष देने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("He could not solve the simple arithmetic and said the paper was torn", "सवाल हल न होने पर बालक कहने लगा कि नाच न जाने आँगन टेढ़ा"),
    ("The inexperienced gardener blamed the garden soil when the seeds failed to sprout", "पौधे न उगने पर माली मिट्टी में खोट निकालने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("Accept your personal shortcomings honestly instead of finding faults in external surroundings", "अपनी कमियाँ स्वीकार करो न कि यह कहो कि नाच न जाने आँगन टेढ़ा"),
    ("The clumsy waiter dropped the soup bowl and blamed the smooth floor", "सूप गिराने पर बैरा फर्श के चिकने होने का बहाना बनाने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("The careless barber cut the customer beard and blamed the sharp razor", "दाढ़ी कटने पर नाई उस्तरे को खराब बताने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("The lazy clerk said that the office pen ran out of blue ink", "काम न करने का बहाना बनाते हुए बाबू ने कहा कि नाच न जाने आँगन टेढ़ा"),
    ("The student failed the history test and blamed the difficult question paper", "इतिहास में फेल होने पर छात्र पर्चे को कठिन बताने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("The unskilled blacksmith said that the charcoal did not heat the iron", "लोहा न मुड़ने पर लोहार कोयले को ठंडा बताने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("Do not make foolish excuses like complaining about the crooked courtyard floor", "अपनी विफलता पर बहाने मत बनाओ जैसे कोई कहे कि नाच न जाने आँगन टेढ़ा"),
    ("The amateur photographer blamed the bright sunlight for the blurry picture taken", "तस्वीर खराब आने पर कैमरामैन धूप को दोष देने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("The arrogant debater blamed the debate microphone when his arguments were demolished", "तर्क हारने पर वक्ता माइक को खराब बताने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("The bad potter broke the clay vessel and blamed the potter wheel", "बर्तन टूटने पर कुम्हार अपने चाक को दोष देने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("He never prepares his lessons and complains that the syllabus is lengthy", "पढ़ाई न करने वाला छात्र हमेशा पाठ्यक्रम को कोसता है जैसे नाच न जाने आँगन टेढ़ा"),
    ("The novice chess player blamed the wooden chess pieces for his defeat", "शतरंज में मात खाने पर खिलाड़ी मोहरों को दोष देने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("The lazy maid said that the broom handle was too short today", "झाड़ू न लगाने पर दासी झाड़ू को छोटी बताने लगी जैसे नाच न जाने आँगन टेढ़ा"),
    ("An incompetent workman will always seek excuses to shield his professional failure", "अक्षम व्यक्ति हमेशा अपनी असफलता छिपाने के लिए नाच न जाने आँगन टेढ़ा कहता है"),
    ("The clumsy carpenter blamed the quality of timber for the uneven table", "मेज़ टेढ़ी बनने पर बढ़ई लकड़ी को खराब बताने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("The bad archer claimed that the wooden bow string had lost elasticity", "निशाना चूकने पर शिकारी धनुष की डोरी को ढीली बताने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("Do not find fault with the tools when your hands lack skill", "जब तुम्हारे हाथों में हुनर न हो तो औज़ारों को दोष मत दो जैसे नाच न जाने आँगन टेढ़ा"),
    ("The poor speaker blamed the audience inattention for his dull boring speech", "भाषण न जमने पर वक्ता श्रोताओं को उदासीन बताने लगा जैसे नाच न जाने आँगन टेढ़ा"),
    ("The failed baker claimed that the dry yeast had expired last week", "रोटी न फूलने पर हलवाई खमीर को खराब बताने लगा जैसे नाच न जाने आँगन टेढ़ा"),

    # 36-70: उल्टा चोर कोतवाल को डांटे (Culprit scolding police/accuser)
    ("The caught pickpocket shouted angrily at the victim like thief scolding constable", "पकड़े जाने पर जेबकतरा उल्टा पीड़ित पर चिल्लाने लगा जैसे उल्टा चोर कोतवाल को डांटे"),
    ("The reckless driver who jumped the red light began scolding the traffic police", "लाल बत्ती तोड़ने वाले चालक ने उल्टा सिपाही को डांटना शुरू कर दिया"),
    ("The cheating student accused the teacher of bias when caught with notes", "नकल करते पकड़े जाने पर छात्र शिक्षक पर आरोप लगाने लगा जैसे उल्टा चोर कोतवाल को डांटे"),
    ("The corrupt contractor threatened the honest auditor who detected the financial fraud", "घोटाला पकड़ने वाले ईमानदार लेखा परीक्षक को ठेकेदार धमकाने लगा जैसे उल्टा चोर कोतवाल को डांटे"),
    ("The arrogant tenant did not pay rent and insulted the rightful landlord", "किराया न देने वाले किरायेदार ने मकान मालिक को ही खरी खोटी सुना दी"),
    ("You broke the delicate glass vase and now you are shouting at me", "फूलदान तुमने तोड़ा और अब मुझ पर ही गुस्सा कर रहे हो जैसे उल्टा चोर कोतवाल को डांटे"),
    ("The habitual latecomer arrived at noon and criticized the punctuality of the manager", "देर से आने वाले कर्मचारी ने उल्टा प्रबंधक के अनुशासन पर सवाल उठा दिया"),
    ("The greedy shopkeeper who gave short weight began abusing the customer who noticed", "कम तौलने वाले दुकानदार ने पकड़ने पर ग्राहक को ही गाली दी जैसे उल्टा चोर कोतवाल को डांटे"),
    ("The negligent doctor blamed the patient relatives after making a fatal medical error", "अपनी गलती छिपाने के लिए डॉक्टर तीमारदारों को डांटने लगा जैसे उल्टा चोर कोतवाल को डांटे"),
    ("The trespasser climbed over the garden wall and scolded the vigilant homeowner", "दीवार फाँदने वाले अजनबी ने मकान मालिक को ही डांट दिया जैसे उल्टा चोर कोतवाल को डांटे"),
    ("The borrower refused to repay the loan and insulted the generous lender", "कर्ज़ न लौटाने वाले ने उल्टे साहूकार को ही भला बुरा कहा जैसे उल्टा चोर कोतवाल को डांटे"),
    ("The aggressive dog owner blamed the bitten postman for walking on the road", "कुत्ता काटने पर मालिक ने डाकिए को ही सड़क पर चलने के लिए डांट दिया"),
    ("Look at his sheer audacity where the guilty scolds the innocent investigator", "उसकी ढिठाई तो देखो जहाँ दोषी व्यक्ति जाँचकर्ता पर ही बरस रहा है जैसे उल्टा चोर कोतवाल को डांटे"),
    ("The unfaithful partner accused the loyal spouse of suspicion when caught red handed", "रंगे हाथों पकड़े जाने पर धोखेबाज़ साथी उल्टा ईमानदार पर शक करने का आरोप लगाने लगा"),
    ("The unruly passenger broke airline rules and quarreled loudly with the cabin crew", "नियम तोड़ने वाले यात्री ने उल्टे विमान कर्मचारियों को धमकाना शुरू कर दिया"),
    ("The careless cleaner broke the antique lamp and blamed the museum curator", "दीपक तोड़ने पर सफाईकर्मी ने उल्टे संग्रहालय अध्यक्ष को डांट दिया जैसे उल्टा चोर कोतवाल को डांटे"),
    ("Instead of apologizing for the collision the speeding motorist began threatening the pedestrian", "टक्कर मारने के बाद चालक उल्टे पैदल यात्री को धमकाने लगा जैसे उल्टा चोर कोतवाल को डांटे"),
    ("The fraudulent salesman accused the gullible buyer of demanding unreasonable product guarantees", "नकली सामान बेचने वाला दुकानदार उल्टे ग्राहक पर दोष मढ़ने लगा जैसे उल्टा चोर कोतवाल को डांटे"),
    ("You spilled hot milk on the carpet and now you blame your brother", "दूध तुमने गिराया और अब भाई को डांट रहे हो जैसे उल्टा चोर कोतवाल को डांटे"),
    ("The disobedient soldier refused orders and criticized the tactical wisdom of the general", "आज्ञा न मानने वाले सिपाही ने उल्टे सेनापति की रणनीति में खोट निकाल दिया"),
    ("The aggressive squatter refused to vacate the land and threatened the legal owner", "कब्जा करने वाले ने उल्टे ज़मीन के असली मालिक को अदालत में घसीटने की धमकी दी"),
    ("The plagiarist author claimed that the original scholar had stolen his private notes", "साहित्यिक चोर ने उल्टे मूल लेखक पर अपनी रचना चुराने का हास्यास्पद आरोप लगा दिया"),
    ("The noisy student disrupted the entire classroom and complained about the strict discipline", "कक्षा में शोर मचाने वाले छात्र ने उल्टे अध्यापक की सख्ती पर शिकायत कर दी"),
    ("The reckless bowler bowled wide balls and scolded the alert field umpire", "खराब गेंद फेंकने वाले गेंदबाज़ ने उल्टे अंपायर को घूरकर देखा जैसे उल्टा चोर कोतवाल को डांटे"),
    ("It is ridiculous that the accused person is interrogating the prosecuting lawyer", "यह तो वही बात हुई कि अभियुक्त उल्टे सरकारी वकील से सवाल पूछने लगा"),
    ("The defaulting debtor yelled at the bank recovery agent outside the branch", "कर्ज़ न चुकाने वाले ने उल्टे बैंक अधिकारी को धमकाया जैसे उल्टा चोर कोतवाल को डांटे"),
    ("The rude intruder demanded entry and scolded the polite watchman at gate", "घुसपैठिए ने उल्टे द्वारपाल को डांट दिया जैसे उल्टा चोर कोतवाल को डांटे"),
    ("You lost the keys and now you are shouting at the family", "चाबी तुमने खोई और अब पूरे परिवार पर गुस्सा निकाल रहे हो जैसे उल्टा चोर कोतवाल को डांटे"),
    ("The careless mechanic damaged the automobile engine and blamed the previous owner", "इंजन खराब करने पर मिस्त्री ने उल्टे मालिक पर आरोप लगा दिया जैसे उल्टा चोर कोतवाल को डांटे"),
    ("The fraudulent accountant accused the internal audit committee of malice and ignorance", "घपला करने वाले मुनीम ने उल्टे लेखा परीक्षकों की योग्यता पर सवाल उठा दिए"),
    ("The dishonest supplier delivered rotten vegetables and insulted the school kitchen staff", "सड़ी सब्जियाँ देने वाले ठेकेदार ने उल्टे रसोई कर्मचारियों को धमका दिया"),
    ("The aggressive squatter filed a police complaint against the rightful land heir", "अवैध कब्ज़ेदार ने उल्टे ज़मीन के वारिस के खिलाफ रपट लिखा दी जैसे उल्टा चोर कोतवाल को डांटे"),
    ("You delayed the project and now you are criticizing the hardworking team", "काम में देरी तुमने की और अब पूरी टीम को डांट रहे हो जैसे उल्टा चोर कोतवाल को डांटे"),
    ("The clumsy barber blamed the client moving head for the bloody nick", "कट लगने पर नाई ग्राहक को ही सिर हिलाने का दोषी ठहराने लगा जैसे उल्टा चोर कोतवाल को डांटे"),
    ("He stole the ripe mangoes and accused the orchard owner of cruelty", "आम चुराने वाले लड़के ने उल्टे बगीचे के रखवाले को निर्दयी बता दिया"),

    # 71-105: कंगाली में आटा गीला (Compounding misfortunes, double blow)
    ("The poor peasant lost his crop and now the roof collapsed too", "फसल बर्बाद होने के बाद झोपड़ी भी गिर गई इसे कहते हैं कंगाली में आटा गीला"),
    ("He lost his job yesterday and his purse was stolen this morning", "कल नौकरी छूटी और आज बटुआ चोरी हो गया यह तो कंगाली में आटा गीला हो गया"),
    ("The flood destroyed our farm and then sickness struck the entire family", "बाढ़ ने खेत डुबो दिए और ऊपर से बीमारी आ गई यानी कंगाली में आटा गीला"),
    ("Already burdened with debt the trader had to pay an unexpected medical bill", "पहले से कर्ज़ में डूबे व्यापारी पर अस्पताल का भारी खर्च आ पड़ा जैसे कंगाली में आटा गीला"),
    ("The sudden tax penalty arrived just when the small factory was closing", "कारखाना बंद होने के कगार पर था और तभी भारी जुर्माना लग गया जैसे कंगाली में आटा गीला"),
    ("The unemployed youth broke his leg on the very day of his interview", "बेरोजगार युवक का साक्षात्कार वाले दिन ही पैर टूट गया यह कंगाली में आटा गीला हुआ"),
    ("Severe drought destroyed the wheat crop and locusts devoured the remaining grass", "सूखे के बाद टिड्डियों के हमले ने किसानों के लिए कंगाली में आटा गीला कर दिया"),
    ("The leaking roof began dripping right over the only dry bed mattress", "टूटी छत का पानी उसी बिस्तर पर टपकने लगा जहाँ वे सो रहे थे जैसे कंगाली में आटा गीला"),
    ("Already running late for the examination his bicycle tire got punctured completely", "परीक्षा के लिए पहले ही देर हो रही थी और साइकिल भी पंक्चर हो गई जैसे कंगाली में आटा गीला"),
    ("The bankrupt shop was destroyed by a midnight accidental electric fire yesterday", "दीवालिया हो चुकी दुकान में रात को आग लग गई इसे कहते हैं कंगाली में आटा गीला"),
    ("Misfortunes never come singly but arrive in rapid succession to crush hope", "विपत्तियाँ कभी अकेली नहीं आतीं और कंगाली में आटा गीला करके ही छोड़ती हैं"),
    ("The sick mother had no money for medicines and the doctor raised fees", "दवा के पैसे नहीं थे और डॉक्टर ने फीस बढ़ा दी यह कंगाली में आटा गीला हुआ"),
    ("Already exhausted from walking the travelers were drenched by torrential midnight rain", "थके हुए यात्रियों पर रात में मूसलाधार बारिश बरस पड़ी जैसे कंगाली में आटा गीला"),
    ("The poor clerk received a salary cut right when house rent increased", "वेतन कटने के साथ ही मकान मालिक ने किराया बढ़ा दिया यह कंगाली में आटा गीला हुआ"),
    ("His small savings were wiped out by fraud and then inflation doubled prices", "धोखे में बचत लुट गई और ऊपर से महंगाई बढ़ गई यानी कंगाली में आटा गीला"),
    ("The stranded motorboat ran out of fuel and a fierce tempest erupted", "नाव का ईंधन खत्म हुआ और समुद्र में तूफान आ गया जैसे कंगाली में आटा गीला"),
    ("Losing his wallet at the railway station added calamity to his poverty", "स्टेशन पर बटुआ खो जाने से गरीब मजदूर के लिए कंगाली में आटा गीला हो गया"),
    ("The famine broke the village and then an epidemic broke out suddenly", "अकाल के तुरंत बाद महामारी फैल गई जिससे गाँव में कंगाली में आटा गीला हो गया"),
    ("Already suffering from fever the child developed a painful tooth infection too", "बुखार के साथ बच्चे के दाँत में भी भयंकर दर्द उठ आया जैसे कंगाली में आटा गीला"),
    ("The small merchant had no credit left and his storehouse caught fire", "कर्ज़ मिलना बंद हुआ और गोदाम में आग लग गई यह कंगाली में आटा गीला साबित हुआ"),
    ("His business collapsed in winter and his landlord evicted him in snow", "व्यापार चौपट हुआ और कड़ाके की ठंड में मकान से निकाल दिया गया जैसे कंगाली में आटा गीला"),
    ("The broken cart broke its axle right in the middle of forest", "जंगल के बीच गाड़ी की धुरी टूट गई और कंगाली में आटा गीला हो गया"),
    ("Already suffering from crop failure the farmers faced unprecedented hail storms today", "फसल मारी गई थी और ऊपर से ओले पड़ गए यानी कंगाली में आटा गीला"),
    ("He lost the court case and had to pay heavy legal penalties", "मुकदमा हारने के बाद भारी हर्जाना भी भरना पड़ा यह कंगाली में आटा गीला हुआ"),
    ("The school roof fell down right when winter examinations were scheduled tomorrow", "परीक्षा से एक दिन पहले स्कूल की छत ढह गई जैसे कंगाली में आटा गीला"),
    ("His only milk cow died on the day the moneylender arrived demanding dues", "साहूकार के आने के दिन ही दुधारू गाय मर गई यह कंगाली में आटा गीला हुआ"),
    ("The old watchman lost his job and his wooden cottage caught fire", "चौकीदारी की नौकरी छूटी और झोपड़ी जल गई इसे कहते हैं कंगाली में आटा गीला"),
    ("Heavy medical expenses drained his bank account and his pension was delayed", "अस्पताल के खर्च के बाद पेंशन भी अटक गई यह कंगाली में आटा गीला हुआ"),
    ("The bus broke down on the deserted highway and dark rain started falling", "सूनसान सड़क पर बस खराब हुई और मूसलाधार बारिश शुरू हो गई जैसे कंगाली में आटा गीला"),
    ("Already struggling with severe illness the poor patient lost his hearing too", "गंभीर बीमारी के बीच मरीज की सुनने की शक्ति भी चली गई जैसे कंगाली में आटा गीला"),
    ("The market crash ruined his investments and his house loan interest spiked", "बाज़ार गिरने के बाद कर्ज़ का ब्याज भी बढ़ गया यह कंगाली में आटा गीला हुआ"),
    ("His donkey died during harvest and the hired cart was stolen overnight", "कटाई के समय गधा मरा और किराए की गाड़ी चोरी हो गई जैसे कंगाली में आटा गीला"),
    ("The village faced water shortage and the only working tube well failed", "पानी की किल्लत के बीच गाँव का इकलौता नल भी सूख गया जैसे कंगाली में आटा गीला"),
    ("He lost the train ticket and the ticket examiner imposed double fine", "टिकट खोने पर परीक्षक ने दोगुना जुर्माना लगा दिया यह कंगाली में आटा गीला हुआ"),
    ("The small hut flooded and then a venomous snake entered inside it", "बाढ़ के पानी के साथ झोपड़ी में विषैला साँप घुस आया जैसे कंगाली में आटा गीला"),

    # 106-140: अंधों में काना राजा (One-eyed king among blind, mediocrity)
    ("Among foolish villagers who cannot read the primary school dropout acts like king", "निरक्षर ग्रामीणों के बीच थोड़ा पढ़ा लिखा युवक अंधों में काना राजा बना घूमता है"),
    ("In a company of incompetent workers the mediocre mechanic becomes the chief foreman", "अकुशल मजदूरों के बीच मामूली मिस्त्री भी अंधों में काना राजा बन जाता है"),
    ("He knows only basic words but boasts among illiterates like a scholar", "थोड़े से ज्ञान के बल पर वह अनपढ़ों के बीच अंधों में काना राजा बना बैठा है"),
    ("In that backward remote hamlet the only cycle owner was like royal king", "उस पिछड़े गाँव में साइकिल वाला व्यक्ति भी अंधों में काना राजा जैसा लगता था"),
    ("The shallow poet gained applause only because the listeners knew nothing about verse", "श्रोताओं की अज्ञानता के कारण वह मामूली कवि अंधों में काना राजा बना हुआ था"),
    ("Among children who know no chess the novice boy felt like grandmaster", "छोटे बच्चों के बीच थोड़ा खेल जानने वाला लड़का अंधों में काना राजा बन गया"),
    ("In a team of lazy amateurs the average player was appointed team captain", "सुस्त खिलाड़ियों के बीच औसत दर्जे का खिलाड़ी अंधों में काना राजा साबित हुआ"),
    ("He can barely operate a phone yet acts like computer engineer among elders", "बुजुर्गों के बीच साधारण फोन चलाने वाला युवक अंधों में काना राजा बन जाता है"),
    ("In an isolated valley where none had traveled the mule driver seemed cosmopolitan", "घाटी के सीधे लोगों के बीच खच्चर वाला व्यक्ति अंधों में काना राजा बना फिरता था"),
    ("Do not boast of your minor talent among those who possess no skills", "अकुशल लोगों के बीच शेखी बघारकर अंधों में काना राजा बनने का कोई मान नहीं"),
    ("Among deaf spectators the clumsy drummer was praised like a musical prodigy", "अज्ञानियों के बीच मामूली ढोलकिया भी अंधों में काना राजा की तरह मान पाता है"),
    ("He passed third division and preens himself among village dropouts like genius", "गाँव के अनपढ़ लड़कों के बीच तीसरी श्रेणी में पास छात्र अंधों में काना राजा बन गया"),
    ("In that small rustic tavern the local fiddler was hailed as legendary maestro", "गाँव की सराय में साधारण सारंगी बजाने वाला अंधों में काना राजा बना बैठा था"),
    ("The quack treated common colds and acted like surgeon among gullible forest tribes", "सीधे वनवासियों के बीच मामूली नीम हकीम भी अंधों में काना राजा बना फिरता था"),
    ("Among cowardly soldiers the slightly bolder corporal was hailed as fearless warrior", "डरपोक सिपाहियों के बीच थोड़ा साहसी नायक भी अंधों में काना राजा बन गया"),
    ("In a village with no doctor the compounder ruled like great royal physician", "चिकित्सक न होने के कारण गाँव में दवा बाँटने वाला अंधों में काना राजा बना हुआ था"),
    ("He learned three foreign words and acts like diplomat among rustic farm laborers", "तीन अंग्रेज़ी शब्द सीखकर वह खेत मजदूरों के बीच अंधों में काना राजा बन बैठा"),
    ("Among illiterate weavers the clerk who wrote letters was revered like minister", "अनपढ़ बुनकरों के बीच चिट्ठी लिखने वाला मुंशी अंधों में काना राजा बना रहता था"),
    ("The amateur singer received loud ovations only because competitors were completely tone deaf", "कमज़ोर गायकों के मुकाबले वह औसत गवैया अंधों में काना राजा साबित हुआ"),
    ("In that superstitious clan the clever charlatan declared himself a divine prophet", "अंधविश्वासी कबीले में वह धूर्त ढोंगी अंधों में काना राजा बनकर हुकूमत करने लगा"),
    ("Do not mistake local preeminence among fools for genuine global artistic excellence", "अज्ञानियों के बीच अंधों में काना राजा बनने को सच्ची महानता मत समझो"),
    ("Among children who cannot swim the boy who can float seems hero", "तैरना न जानने वाले बालकों के बीच तैरने वाला अंधों में काना राजा बन जाता है"),
    ("In a region with no schools the temple priest was the sole scholar", "पाठशाला न होने से मंदिर का पुजारी पूरे इलाके में अंधों में काना राजा बना हुआ था"),
    ("The street acrobat performed simple somersaults and amazed the naive mountain crowd", "सीधे ग्रामीणों के बीच मामूली नट अंधों में काना राजा की तरह करतब दिखा रहा था"),
    ("He knows only two songs but performs proudly among people who hate music", "संगीत न जानने वालों के बीच वह औसत गायक अंधों में काना राजा बना हुआ है"),
    ("In that backward department the clerk who knows English typed all official letters", "दफ्तर के अनपढ़ कर्मचारियों के बीच अंग्रेज़ी जानने वाला बाबू अंधों में काना राजा था"),
    ("A little knowledge makes an arrogant man act like monarch among simpletons", "अल्प ज्ञान पाकर घमंडी मनुष्य अज्ञानियों के बीच अंधों में काना राजा बन जाता है"),
    ("Among timid youths who fear darkness the bolder teenager led the group", "डरपोक बालकों के बीच थोड़ा निर्भीक लड़का अंधों में काना राजा की तरह आगे बढ़ा"),
    ("In a village where none read newspapers the tea vendor shared state gossip", "अखबार न पढ़ने वाले गाँव में चाय वाला अंधों में काना राजा बना खबरें सुनाता था"),
    ("The mediocre swordsman was undefeated only because he fought unarmed peasant boys", "हथियार न जानने वाले लड़कों के बीच वह साधारण तलवारबाज़ अंधों में काना राजा था"),
    ("He drives an old tractor and acts like aviation pilot among cart drivers", "बैलगाड़ी वालों के बीच पुराना ट्रैक्टर चलाने वाला अंधों में काना राजा बना घूमता है"),
    ("Among ignorant villagers the cunning astrologer predicted rain and extracted rich grain", "अज्ञानियों के बीच मामूली ज्योतिषी अंधों में काना राजा बनकर अन्न बटोरता था"),
    ("In that remote mountain outpost the junior sergeant commanded like supreme general", "सुदूर चौकी पर कनिष्ठ हवलदार अंधों में काना राजा बनकर हुक्म चला रहा था"),
    ("True excellence shines among masters not merely as one eyed ruler among blind", "सच्ची प्रतिभा उस्तादों के बीच चमकती है न कि केवल अंधों में काना राजा बनने में"),
    ("He knows simple arithmetic and boasts like university mathematics professor in hamlet", "गाँव के बच्चों के बीच साधारण गिनती जानने वाला अंधों में काना राजा बना बैठा है"),

    # 141-175: एक अनार सौ बीमार (Too little supply, immense demand)
    ("There was only one vacant job and a thousand unemployed applicants applied", "नौकरी एक थी और उम्मीदवार हज़ार इसे कहते हैं एक अनार सौ बीमार"),
    ("One single rented room in the university town attracted fifty eager students", "विश्वविद्यालय के पास एक कमरे के लिए पचास छात्र आए जैसे एक अनार सौ बीमार"),
    ("The merchant had only one sack of sugar and thirty customers clamored", "दुकान में चीनी की एक ही बोरी थी और ग्राहक तीस यानी एक अनार सौ बीमार"),
    ("Only one medicine bottle remained in the clinic while twenty patients queued", "अस्पताल में दवा की एक शीशी थी और बीस मरीज़ कतार में खड़े थे जैसे एक अनार सौ बीमार"),
    ("One railway berth was available in the train and hundred passengers demanded it", "गाड़ी में एक ही सीट खाली थी और सौ यात्री खड़े थे जैसे एक अनार सौ बीमार"),
    ("The shortage of wheat in the town turned into a classic scarcity crisis", "अनाज कम होने और खरीदार अधिक होने से नगर में एक अनार सौ बीमार वाली स्थिति बन गई"),
    ("There was only one ticket left for the final cricket match tournament", "मैच का एक ही टिकट बचा था और खरीदने वाले सैकड़ों यानी एक अनार सौ बीमार"),
    ("One glass of fresh milk remained and four hungry crying infants wept", "दूध का एक कटोरा था और चार भूखे बच्चे रो रहे थे जैसे एक अनार सौ बीमार"),
    ("The library possessed only one copy of the rare historical manuscript book", "पुस्तकालय में दुर्लभ पुस्तक की एक ही प्रति थी और पाठक सैकड़ों जैसे एक अनार सौ बीमार"),
    ("Only one government loan scheme was announced for ten thousand struggling farmers", "दस हज़ार किसानों के लिए एक ही सरकारी योजना थी जैसे एक अनार सौ बीमार"),
    ("The scarce commodity created fierce bidding among all the wealthy royal collectors", "दुर्लभ वस्तु की नीलामी में खरीदार अनेक थे और स्थिति एक अनार सौ बीमार बन गई"),
    ("There was only one vacancy for the post of head schoolmaster here", "प्रधानाध्यापक का एक ही पद खाली था और आवेदन सैकड़ों जैसे एक अनार सौ बीमार"),
    ("One single water tap in the slum served five hundred thirsty residents", "बस्ती में एक ही नल था और पानी भरने वाले सैकड़ों इसे कहते हैं एक अनार सौ बीमार"),
    ("The desert oasis had only one bucket of water for the caravan", "रेगिस्तान के कुएँ में एक ही बाल्टी पानी था और काफिला प्यासा जैसे एक अनार सौ बीमार"),
    ("Only one scholarship was available for the entire graduating college class this year", "पूरे कॉलेज में एक ही छात्रवृत्ति थी और दावेदार दर्जनों जैसे एक अनार सौ बीमार"),
    ("The scarce vaccine doses arrived in the clinic and thousands rushed forward", "टीके की कुछ ही खुराकें आई थीं और भीड़ भारी थी यानी एक अनार सौ बीमार"),
    ("There was only one bicycle for rent and ten tourists wanted it", "किराए की एक ही साइकिल थी और पर्यटक दस इसे कहते हैं एक अनार सौ बीमार"),
    ("The sudden shortage of onions in the city created a desperate scramble", "बाज़ार में प्याज़ कम होने पर हर खरीदार झपट रहा था जैसे एक अनार सौ बीमार"),
    ("Only one warm blanket remained in the relief camp during freezing blizzard", "राहत शिविर में एक ही कंबल बचा था और काँपते लोग अनेक जैसे एक अनार सौ बीमार"),
    ("The single opening for the civil service exam received two million forms", "प्रशासनिक सेवा के कुछ पदों के लिए लाखों आवेदन आ गए जैसे एक अनार सौ बीमार"),
    ("One slice of bread remained on the plate and three hungry dogs growled", "थाली में रोटी का एक टुकड़ा था और तीन भूखे कुत्ते झपट रहे थे जैसे एक अनार सौ बीमार"),
    ("The small hand pump was the only source of water in that parched village", "सूखे गाँव में एक ही हैंडपंप था और पानी भरने वाले सैकड़ों जैसे एक अनार सौ बीमार"),
    ("Only one seat remained vacant on the crowded mountain passenger bus today", "पहाड़ी बस में केवल एक सीट खाली थी और यात्री खड़े दर्जनों जैसे एक अनार सौ बीमार"),
    ("The rare antique diamond attracted twelve competing European royal museum curators", "दुर्लभ हीरे का एक ही टुकड़ा था और खरीदार अनेक यानी एक अनार सौ बीमार"),
    ("One single umbrella sheltered four drenched travelers during the torrential monsoon downpour", "मूसलाधार बारिश में एक ही छाता था और भीगते लोग चार जैसे एक अनार सौ बीमार"),
    ("The company had only one promotion opening for twenty ambitious marketing managers", "पदोन्नति का एक पद था और दावेदार बीस प्रबंधक इसे कहते हैं एक अनार सौ बीमार"),
    ("There was only one flashlight among the six spelunkers in the cavern", "अंधेरी गुफा में एक ही टॉर्च थी और छह यात्री साथ जैसे एक अनार सौ बीमार"),
    ("The single bowl of sweet pudding was contested by five hungry brothers", "खीर का एक ही कटोरा था और पाँच भाई लड़ने लगे जैसे एक अनार सौ बीमार"),
    ("Only one tender was issued and fifty hungry contracting firms submitted bids", "सरकारी ठेका एक था और बोली लगाने वाली कंपनियाँ पचास जैसे एक अनार सौ बीमार"),
    ("The village well had very little water left and pitchers were countless", "कुएँ में पानी थोड़ा बचा था और घड़े अनगिनत थे जैसे एक अनार सौ बीमार"),
    ("A single ticket for the musical concert sold for ten times price", "संगीत समारोह का एक टिकट पाने के लिए सैकड़ों लोग कतार में खड़े थे जैसे एक अनार सौ बीमार"),
    ("The relief boat had capacity for ten people while hundred victims waited", "नाव में दस लोगों की जगह थी और बाढ़ में फँसे लोग सैकड़ों जैसे एक अनार सौ बीमार"),
    ("One single gold medal was at stake and forty athletes sprinted hard", "स्वर्ण पदक एक था और दौड़ने वाले चालीस धावक इसे कहते हैं एक अनार सौ बीमार"),
    ("The rare medicinal herb was scarce while the plague affected whole valley", "दवा की बूटी एक थी और पूरी घाटी में महामारी फैली थी जैसे एक अनार सौ बीमार"),
    ("There was only one loaf of bread left in the besieged city", "घेरे में आए नगर में रोटी की एक ही ढेरी थी और भूखे नागरिक हज़ारों जैसे एक अनार सौ बीमार"),

    # 176-210: मान न मान मैं तेरा मेहमान (Forced intrusion, unsolicited guest)
    ("The shameless stranger sat down at our dining table without any invitation", "बिन बुलाए घर में आकर वह ऐसे बैठ गया मानो मान न मान मैं तेरा मेहमान"),
    ("He arrived with heavy luggage at our doorstep claiming distant unknown kinship", "अनजान रिश्तेदारी बताकर वह हमारे घर आ जमा जैसे मान न मान मैं तेरा मेहमान"),
    ("The annoying broker intruded into private negotiations without being asked by anyone", "निजी बातचीत में वह दलाल जबरन दखल देने लगा जैसे मान न मान मैं तेरा मेहमान"),
    ("Nobody invited the gossip to the wedding feast yet he sat in front", "विवाह में किसी ने नहीं बुलाया फिर भी वह आगे बैठ गया जैसे मान न मान मैं तेरा मेहमान"),
    ("The self appointed advisor began giving unsolicited lectures on financial investment management", "बिना माँगे सलाह देने वाला व्यक्ति ऐसे बोलने लगा मानो मान न मान मैं तेरा मेहमान"),
    ("He parked his caravan in our orchard and declared himself our permanent guest", "बगीचे में डेरा डालकर वह ऐसे रहने लगा मानो मान न मान मैं तेरा मेहमान"),
    ("Do not force your company upon people who clearly wish to be alone", "जबरन किसी के गले मत पड़ो और यह मत कहो कि मान न मान मैं तेरा मेहमान"),
    ("The unwanted flatterer followed the minister everywhere without any appointment or duty", "बिना पद के वह चापलूस मंत्री के पीछे ऐसे घूमता था मानो मान न मान मैं तेरा मेहमान"),
    ("He joined our family picnic uninvited and ate all the sweet pastries", "पिकनिक में बिन बुलाया पड़ोसी ऐसे शामिल हो गया जैसे मान न मान मैं तेरा मेहमान"),
    ("The persistent salesman entered the private living room without waiting for permission", "अनुमति के बिना घर में घुसकर सेल्समैन बैठ गया जैसे मान न मान मैं तेरा मेहमान"),
    ("Nobody asked for his intervention yet he jumped into the delicate mediation", "विवाद में किसी ने नहीं बुलाया फिर भी वह कूद पड़ा जैसे मान न मान मैं तेरा मेहमान"),
    ("The rude acquaintance stayed three weeks in our flat without contributing anything", "तीन हफ्ते हमारे घर रहकर वह मुफ्त खाता रहा जैसे मान न मान मैं तेरा मेहमान"),
    ("He claims friendship with the royal governor who does not even know him", "राज्यपाल का करीबी बताकर वह अपनी धाक जमाता है जैसे मान न मान मैं तेरा मेहमान"),
    ("The insolent gatecrasher took the front seat at the exclusive private banquet", "दावत में बिना बुलाए आकर वह मुख्य अतिथि बन बैठा जैसे मान न मान मैं तेरा मेहमान"),
    ("Do not invite yourself to feasts where host has not sent an invitation", "जहाँ कोई न पूछे वहाँ जबरन जाकर मत बैठो जैसे मान न मान मैं तेरा मेहमान"),
    ("He entered the business boardroom unasked and started lecturing the board members", "बैठक में बिना बुलाए घुसकर वह भाषण देने लगा जैसे मान न मान मैं तेरा मेहमान"),
    ("The meddlesome aunt offered unsolicited marriage advice to all the young cousins", "बिना माँगे सलाह देने वाली मौसी ऐसे बोलने लगीं मानो मान न मान मैं तेरा मेहमान"),
    ("He appeared at the farewell party and grabbed the microphone to sing", "विदाई समारोह में बिन बुलाए आकर वह माइक पकड़ बैठा जैसे मान न मान मैं तेरा मेहमान"),
    ("The uninvited spectator gave loud tactical advice to the professional football players", "मैदान के बाहर से वह ऐसे निर्देश दे रहा था मानो मान न मान मैं तेरा मेहमान"),
    ("He assumed leadership of the committee without being elected by the members", "बिना चुने ही वह समिति का अध्यक्ष बन बैठा जैसे मान न मान मैं तेरा मेहमान"),
    ("The shameless relative demanded the best guest room in the crowded house", "भीड़ भरे घर में वह रिश्तेदार अधिकार जताने लगा जैसे मान न मान मैं तेरा मेहमान"),
    ("He joined our private discussion uninvited and started expressing foolish opinions loudly", "निजी बातचीत में आकर वह ज़ोर ज़ोर से बोलने लगा जैसे मान न मान मैं तेरा मेहमान"),
    ("Do not intrude upon private sorrow unless family specifically requests your presence", "दुख की घड़ी में बिना बुलाए जबरन मत जाओ जैसे मान न मान मैं तेरा मेहमान"),
    ("The opportunistic politician climbed the stage uninvited during the religious festival rally", "धार्मिक मंच पर नेताजी बिना बुलाए चढ़ गए जैसे मान न मान मैं तेरा मेहमान"),
    ("He acted as though the whole household existed solely to serve him", "घर में आकर वह ऐसे हुक्म चलाने लगा मानो मान न मान मैं तेरा मेहमान"),
    ("The unwelcome passerby joined the dinner party and drank all the cider", "अजनबी मुसाफिर दावत में बैठकर शरबत पीने लगा जैसे मान न मान मैं तेरा मेहमान"),
    ("Nobody desired his company yet he insisted upon accompanying us on pilgrimage", "यात्रा में कोई उसे नहीं चाहता था फिर भी वह साथ हो लिया जैसे मान न मान मैं तेरा मेहमान"),
    ("He appointed himself defense spokesperson without consulting the accused family in court", "बिना पूछे ही वह प्रवक्ता बनकर बयान देने लगा जैसे मान न मान मैं तेरा मेहमान"),
    ("The brazen stranger sat beside the fireplace and demanded a warm blanket", "अजनबी ने चूल्हे के पास बैठकर कंबल माँग लिया जैसे मान न मान मैं तेरा मेहमान"),
    ("Do not force yourself into social circles that do not welcome you", "जहाँ तुम्हारा मान न हो वहाँ जबरन मत जाओ जैसे मान न मान मैं तेरा मेहमान"),
    ("He entered the artist studio uninvited and started criticizing the unfinished canvas", "चित्रकार के कमरे में घुसकर वह चित्र में खोट निकालने लगा जैसे मान न मान मैं तेरा मेहमान"),
    ("The parasitic friend moved into our cottage and refused to leave ever", "मित्र हमारे घर आकर ऐसे जम गया मानो मान न मान मैं तेरा मेहमान"),
    ("He claimed close relationship with the celebrity who walked past without looking", "प्रसिद्ध व्यक्ति का रिश्तेदार बताकर वह शेखी बघार रहा था जैसे मान न मान मैं तेरा मेहमान"),
    ("The officious clerk tried to mediate between two senior directors without authorization", "बड़े अधिकारियों के बीच वह क्लर्क जबरन पंच बन बैठा जैसे मान न मान मैं तेरा मेहमान"),
    ("He arrived at dawn with empty pockets expecting royal hospitality all week", "खाली हाथ आकर वह शाही खातिरदारी की उम्मीद करने लगा जैसे मान न मान मैं तेरा मेहमान"),

    # 211-250: चमड़ी जाए पर दमड़ी न जाए (Extreme miserliness, avarice)
    ("The wretched miser would rather die of sickness than spend single penny", "कंजूस इलाज पर एक पैसा खर्च नहीं करता क्योंकि चमड़ी जाए पर दमड़ी न जाए"),
    ("The greedy usurer walked ten miles in heat just to save bus fare", "बस का किराया बचाने के लिए वह चिलचिलाती धूप में पैदल चला जैसे चमड़ी जाए पर दमड़ी न जाए"),
    ("The wealthy landowner wore ragged clothes and ate stale bread to save gold", "अपार धन होने पर भी वह फटे कपड़े पहनता है क्योंकि चमड़ी जाए पर दमड़ी न जाए"),
    ("The stingy merchant refused to repair his leaking roof and got drenched", "छत की मरम्मत न कराने से कंजूस भीगता रहा क्योंकि चमड़ी जाए पर दमड़ी न जाए"),
    ("He would endure severe starvation rather than spend money on fresh nutritious food", "भूखा मर जाएगा पर भोजन पर पैसा खर्च नहीं करेगा जैसे चमड़ी जाए पर दमड़ी न जाए"),
    ("The miserly landlord suffered pneumonia rather than buy firewood for his fireplace", "ठंड से काँपता रहा पर लकड़ी नहीं खरीदी क्योंकि चमड़ी जाए पर दमड़ी न जाए"),
    ("He carries millions in bank account yet haggles for hours over five pennies", "लाखों की संपत्ति होते हुए भी वह पाँच पैसे के लिए झगड़ता है जैसे चमड़ी जाए पर दमड़ी न जाए"),
    ("The skinflint lawyer drank dirty pond water instead of purchasing clean bottled water", "साफ़ पानी खरीदने के बजाय गंदा पानी पी लिया क्योंकि चमड़ी जाए पर दमड़ी न जाए"),
    ("He walked bare feet on burning desert sand to save leather sole shoes", "जूते घिसने के डर से वह तपती रेत पर नंगे पैर चला जैसे चमड़ी जाए पर दमड़ी न जाए"),
    ("The greedy miser begged for stale crusts while burying pots of gold coins", "सोना गाड़कर रखने वाला कंजूस दूसरों से बासी रोटी माँगता है जैसे चमड़ी जाए पर दमड़ी न जाए"),
    ("His greed is so extreme that he would trade his skin for farthing", "उसका लालच इतना अंधा है कि चमड़ी जाए पर दमड़ी न जाए वाली बात सच लगती है"),
    ("The stingy traveler shivered all night rather than renting a cheap warm blanket", "कंबल किराए पर न लेकर रात भर ठंड में ठिठुरता रहा जैसे चमड़ी जाए पर दमड़ी न जाए"),
    ("He denied milk to his sick daughter just to accumulate useless paper notes", "बीमार बेटी को दूध न पिलाकर धन जोड़ता रहा क्योंकि चमड़ी जाए पर दमड़ी न जाए"),
    ("The miserly shopkeeper worked in pitch darkness rather than lighting a candle wick", "मोमबत्ती का खर्च बचाने के लिए अंधेरे में बैठा रहा जैसे चमड़ी जाए पर दमड़ी न जाए"),
    ("He would allow his tooth to rot painfully rather than pay the dentist", "दाँत का दर्द सहता रहा पर डॉक्टर को फीस नहीं दी क्योंकि चमड़ी जाए पर दमड़ी न जाए"),
    ("The wealthy skinflint took free food at charitable soup kitchen every single day", "करोड़पति होकर भी वह मुफ्त के लंगर में खाता था जैसे चमड़ी जाए पर दमड़ी न जाए"),
    ("He mended his worn shoes with iron wire fifty times to avoid buying", "जूते खरीदने के बजाय तार से गाँठता रहा क्योंकि चमड़ी जाए पर दमड़ी न जाए"),
    ("The stingy farmer refused to purchase fertilizer and ruined his whole crop harvest", "खाद का पैसा बचाने के चक्कर में पूरी फसल गँवा दी जैसे चमड़ी जाए पर दमड़ी न जाए"),
    ("He starved his carriage horse until the poor beast collapsed upon the road", "घोड़े को दाना न देकर मार डाला क्योंकि मालिक की नीति थी चमड़ी जाए पर दमड़ी न जाए"),
    ("The miser cried bitter tears when asked to donate single coin to orphanage", "अनाथालय को एक सिक्का देने में उसकी जान निकलती थी जैसे चमड़ी जाए पर दमड़ी न जाए"),
    ("He carried heavy iron luggage on his head to avoid paying coolie porter", "कुली के पैसे बचाने के लिए भारी बोझ खुद सिर पर ढोया जैसे चमड़ी जाए पर दमड़ी न जाए"),
    ("The rich miser lived in a crumbling ruin rather than spending on repairs", "महल की मरम्मत न कराकर मलबे में रहता रहा क्योंकि चमड़ी जाए पर दमड़ी न जाए"),
    ("He avoided visiting doctors and swallowed bitter wild grass to save doctor fees", "दवा के पैसे बचाने के लिए जंगली घास खाता रहा जैसे चमड़ी जाए पर दमड़ी न जाए"),
    ("The greedy collector never lit a fire even when snow covered the windows", "खिड़की पर बर्फ़ जमने पर भी उसने आग नहीं जलाई क्योंकि चमड़ी जाए पर दमड़ी न जाए"),
    ("He would rather walk twenty miles in thunderstorm than spend on public bus", "तूफान में बीस मील पैदल चला पर बस का टिकट नहीं लिया जैसे चमड़ी जाए पर दमड़ी न जाए"),
    ("The stingy banker washed his only shirt in cold river without soap bar", "साबुन का खर्च बचाने के लिए नदी के ठंडे पानी में कमीज़ धोई जैसे चमड़ी जाए पर दमड़ी न जाए"),
    ("He allowed his eyesight to weaken rather than buying a pair of spectacles", "चश्मा न बनवाकर आँखों को खराब होने दिया क्योंकि चमड़ी जाए पर दमड़ी न जाए"),
    ("The old miser locked his bread in safe while his pet dog starved", "कुत्ता भूखा मर गया पर रोटी तिजोरी में बंद रखी क्योंकि चमड़ी जाए पर दमड़ी न जाए"),
    ("He refused to hire a boat and tried to swim across dangerous whirlpool", "नाव का भाड़ा बचाने के लिए भंवर में तैरने कूद पड़ा जैसे चमड़ी जाए पर दमड़ी न जाए"),
    ("The extreme skinflint died of malnutrition beside chests overflowing with silver coins", "चाँदी के संदूकों के पास बैठकर भूख से मर गया क्योंकि चमड़ी जाए पर दमड़ी न जाए"),
    ("He never celebrated any family festival to avoid offering sweets to friendly neighbors", "मिठाई बाँटने के डर से कभी त्योहार नहीं मनाया क्योंकि चमड़ी जाए पर दमड़ी न जाए"),
    ("The stingy merchant wore patched garments until rags dropped off his thin body", "चिथड़े लटकने तक वही फटी धोती पहनता रहा क्योंकि चमड़ी जाए पर दमड़ी न जाए"),
    ("He preferred drinking muddy ditch water to purchasing a cup of clean tea", "चाय का पैसा बचाने के लिए गड्ढे का मटमैला पानी पी लिया जैसे चमड़ी जाए पर दमड़ी न जाए"),
    ("The selfish hoarder accumulated bags of grain until rats ate every single grain", "अनाज सड़ गया और चूहे खा गए पर किसी को नहीं दिया क्योंकि चमड़ी जाए पर दमड़ी न जाए"),
    ("His miserly nature became legendary in all the neighboring townships and ancient villages", "उसकी कंजूसी पूरे इलाके में मशहूर थी जहाँ चमड़ी जाए पर दमड़ी न जाए का नियम चलता था"),
    ("He refused to light lamp and broke his toe against heavy stone threshold", "दीपक न जलाकर अंधेरे में पैर की उँगली तुड़वा ली जैसे चमड़ी जाए पर दमड़ी न जाए"),
    ("The avaricious trader stored gold underground and died dressed in torn beggar rags", "ज़मीन में सोना दबाकर भिखारी की तरह मरा क्योंकि चमड़ी जाए पर दमड़ी न जाए"),
    ("He would walk in blistering midday heat rather than paying two pennies for shade", "दो पैसे बचाने के लिए चिलचिलाती धूप में तपता रहा जैसे चमड़ी जाए पर दमड़ी न जाए"),
    ("The skinflint ate uncooked raw rice to save firewood for his kitchen hearth", "चूल्हे की लकड़ी बचाने के लिए कच्चे चावल चबा लिए जैसे चमड़ी जाए पर दमड़ी न जाए"),
    ("Such unthinking miserliness brings shame upon human dignity and true wealth of life", "ऐसी अंधी कंजूसी जहाँ चमड़ी जाए पर दमड़ी न जाए इंसानियत को लज्जित करती है"),
]

if __name__ == "__main__":
    process_batch(31, "p31s", PAIRS)
