#!/usr/bin/env python3
"""Batch VT-04: Compound Verbs & Vector Verbs (संयुक्त क्रियाएँ) (200 sentences).
File: data/phrases36.json, IDs: p36s001..p36s200.
Themes:
- Primary Verb Stem + Vector Verb (रंजक क्रियाएँ)
- जाना (completion, telicity, transition: खा जाना, सो जाना, गिर जाना, टूट जाना, पहुँच जाना)
- लेना (self-directed, inward benefactive: कर लेना, पढ़ लेना, समझ लेना, रख लेना, बाँध लेना)
- देना (other-directed, outward benefactive: समझा देना, बता देना, छोड़ देना, भेज देना, दे देना)
- पड़ना (sudden, involuntary: कूद पड़ना, रो पड़ना, चमक पड़ना, बोल पड़ना, टूट पड़ना)
- बैठना (impulsive, regrettable: लड़ बैठना, कह बैठना, खो बैठना, कर बैठना)
- उठना (sudden inception, upward outburst: जाग उठना, चिल्ला उठना, काँप उठना, भड़क उठना)
- डालना (forceful, violent, rash completeness: मार डालना, काट डालना, तोड़ डालना, फेंक डालना)
- Transitivity & Ergative inheritance in compound verbs.
"""
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parent))
from gen_batches_pipeline import process_batch

PAIRS = [
    # 1-35: जाना (Completion, Telicity, Transition: खा जाना, सो जाना, गिर जाना, टूट जाना, पहुँच जाना)
    ("The hungry child ate up all the sweet golden mangoes in few minutes", "भूखा बच्चा कुछ ही मिनटों में सारे मीठे आम खा गया"),
    ("The exhausted traveler fell asleep under the cool shade of the leafy banyan tree", "थका हुआ मुसाफिर घने बरगद के पेड़ की ठंडी छाँव में सो गया"),
    ("The fragile clay pitcher slipped from her hands and broke into tiny pieces", "मिट्टी का नाज़ुक घड़ा हाथ से छूटकर सख्त पत्थर पर गिर गया"),
    ("The ancient wooden bridge collapsed under the immense weight of the flood waters", "बाढ़ के पानी के भारी दबाव से पुराना लकड़ी का पुल टूट गया"),
    ("The swift royal courier reached the capital fortress before the gates were closed", "तेज़ संदेशवाहक नगर के मुख्य फाटक बंद होने से पहले राजधानी पहुँच गया"),
    ("The morning mist evaporated completely as the bright sun climbed above the eastern hills", "सूरज चढ़ते ही वादियों में छाया हुआ सुबह का घना कोहरा छँट गया"),
    ("All the sweet milk in the brass pot turned sour due to summer heat", "भीषण गर्मी के कारण पीतल के बर्तन में रखा सारा दूध फट गया"),
    ("The wounded soldier recovered his strength quickly after drinking the soothing herbal medicine", "जड़ी बूटी का काढ़ा पीते ही घायल सिपाही का सारा दर्द मिट गया"),
    ("The wild forest fire died down when the heavy torrential rain began falling", "मूसलाधार बारिश शुरू होते ही जंगल में लगी भयानक आग बुझ गई"),
    ("The clever thief slipped away quietly into the dark shadowy alley before police arrived", "पुलिस के आने से पहले ही चालाक चोर अंधेरी गली में खिसक गया"),
    ("The frightened little birds flew away when the ferocious falcon circled overhead", "शिकारी बाज़ को ऊपर मंडराते देखकर पेड़ की सारी छोटी चिड़ियाँ उड़ गईं"),
    ("The ice on the high mountain pass melted rapidly under the warm spring sun", "वसंत की गुनगुनी धूप लगते ही पहाड़ी दर्रे पर जमी सारी बर्फ़ पिघल गई"),
    ("The valuable historical treaty document deteriorated completely due to damp storage conditions", "सीलन भरे तहखाने में रखे होने के कारण प्राचीन संधि पत्र सड़ गया"),
    ("The fierce anger of the king subsided when he heard the honest truth", "पूरी सच्चाई सुनते ही राजा का धधकता हुआ भयंकर क्रोध शांत हो गया"),
    ("The old grandfather sat down on the stone bench to rest his tired limbs", "थकावट के कारण बूढ़े दादाजी रास्ते के किनारे बने चबूतरे पर बैठ गए"),
    ("The secret underground spring dried up during the unprecedented three year drought", "लगातार तीन साल पड़े भीषण सूखे के कारण गुप्त पहाड़ी झरना सूख गया"),
    ("The frightened rabbit darted into its deep underground burrow to escape the eagle", "चील के झपट्टे से बचने के लिए डरपोक खरगोश अपने बिल में घुस गया"),
    ("The fragile paper boat sank into the whirlpool of the swollen village gutter", "बरसाती पानी के तेज़ भंवर में कागज़ की छोटी नाव डूब गई"),
    ("The young student understood the difficult mathematical theorem after working on it patiently", "धैर्य से हल करने के बाद छात्र को कठिन सवाल का रहस्य समझ आ गया"),
    ("The colorful flower petals withered away as the cold frosty autumn wind blew", "ठंडी हवा के थपेड़े लगते ही खिले हुए सुंदर फूलों की पंखुड़ियाँ मुरझा गईं"),
    ("The noisy chatter of the gathered crowd died away as the judge entered court", "न्यायाधीश के आते ही अदालत के कमरे में फैला सारा शोरगुल थम गया"),
    ("The heavy iron key turned smoothly and the ancient rusted padlock opened up", "चाबी घुमाते ही सदियों पुराना भारी लोहे का ताला आसानी से खुल गया"),
    ("The entire wealth of the reckless gambler vanished into thin air overnight", "जुआरी की सारी पुश्तैनी दौलत एक ही रात के दांव में हवा हो गई"),
    ("The brave commander horse leaped across the wide rocky chasm with ease", "सेनापति का वफादार घोड़ा गहरी पथरीली खाई के उस पार कूद गया"),
    ("The dark storm clouds rolled away revealing the twinkling stars of night", "तूफान थमते ही आकाश से काले बादल छँट गए और तारे निकल आए"),
    ("The sharp iron needle slipped through the thick layers of leather smoothly", "नुकीली सुई मोटे चमड़े की परतों के आर पार आसानी से निकल गई"),
    ("The sweet aroma of fresh incense filled every corner of the peaceful temple", "सुगंधित धूप की महक से मंदिर का कोना कोना महक उठा और भर गया"),
    ("The wounded leopard dragged itself into the dark cave to heal its wounds", "घायल तेंदुआ अपने घाव सहलाने के लिए गुफा के अंधेरे में चला गया"),
    ("The heavy earthen dyke washed away during the fierce midnight monsoon cloudburst", "आधी रात को बादल फटने से मिट्टी का पूरा कच्चा बाँध बह गया"),
    ("The little girl grew up into an accomplished and compassionate young doctor", "समय बीतने के साथ वह छोटी बालिका एक कुशल और दयालु चिकित्सक बन गई"),
    ("The sudden loud explosion shook the windows and the glass panes cracked", "अचानक हुए धमाके से खिड़कियों के काँच टूट गए और सब हिल गया"),
    ("The stubborn rebel yielded his weapons and surrendered before the lawful magistrate", "हठी विद्रोही ने अपने हथियार डाल दिए और कानून के आगे झुक गया"),
    ("The sweet water of the mountain lake froze solid during the subzero winter blizzard", "कड़ाके की ठंड में पहाड़ी झील का सारा मीठा पानी बर्फ़ बन गया"),
    ("The memory of that terrifying battlefield nightmare faded slowly from his mind", "समय के साथ उस भयानक युद्ध की दर्दनाक यादें उसके मन से मिट गईं"),
    ("The magnificent royal cavalcade passed through the grand gateway into the fortress", "शाही काफिला भव्य तोरण द्वार के नीचे से होकर किले के भीतर चला गया"),

    # 36-70: लेना (Self-directed, Inward Benefactive: कर लेना, पढ़ लेना, समझ लेना, रख लेना, बाँध लेना)
    ("The prudent student completed all his examination preparation well before the final date", "मेहनती छात्र ने अंतिम तारीख से पहले ही अपनी सारी पढ़ाई पूरी कर ली"),
    ("The wise merchant read through the entire commercial agreement before putting his seal", "समझदार व्यापारी ने हस्ताक्षर करने से पहले पूरा व्यापारिक अनुबंध ध्यान से पढ़ लिया"),
    ("The attentive listener understood the hidden subtle implication of the philosophical lecture", "सतर्क श्रोता ने विद्वान के भाषण का गूढ़ रहस्य अच्छी तरह समझ लिया"),
    ("The careful traveler kept his gold coins securely inside his inner leather vest", "सावधान मुसाफिर ने अपने सोने के सिक्के अपनी अंदरूनी जेब में सुरक्षित रख लिए"),
    ("The brave warrior tightened his leather belt and drew his sharp steel sword", "वीर योद्धा ने अपनी कमर कस ली और लोहे की तलवार बाहर निकाल ली"),
    ("The kind grandmother accepted the humble gift from her little grandson with joy", "दादी ने अपने नन्हे पोते का छोटा सा उपहार बड़े प्यार से स्वीकार कर लिया"),
    ("The diligent clerk recorded all daily expenses in his personal pocket ledger book", "ईमानदार मुनीम ने दिन भर के सारे खर्च अपनी निजी डायरी में लिख लिए"),
    ("The young athlete tied the laces of his running shoes firmly before sprint", "धावक ने दौड़ शुरू होने से पहले अपने जूतों के फीते मजबूती से बाँध लिए"),
    ("The thirsty farmer drank up two bowls of cool buttermilk under the tree", "प्यासे किसान ने पेड़ की छाँव में बैठकर दो कटोरे ठंडी छाछ पी ली"),
    ("The clever detective memorized the physical features of the suspicious stranger in market", "चतुर जासूस ने भीड़ में उस संदिग्ध अजनबी का हुलिया अपने मन में बैठा लिया"),
    ("The peaceful community adopted the orphaned child into their collective loving care", "गाँव वालों ने उस बेसहारा अनाथ बच्चे को अपने परिवार का सदस्य मान लिया"),
    ("The prudent housewife saved a portion of her household allowance for emergency needs", "गृहणी ने संकट के समय के लिए हर महीने थोड़े पैसे बचाकर रख लिए"),
    ("The mountain shepherd wrapped his heavy woolen blanket tightly against the cold wind", "चरवाहे ने बर्फीली हवा से बचने के लिए अपनी मोटी चादर कसकर लपेट ली"),
    ("The young scholar mastered three difficult classical Indian languages in five years", "लगनशील छात्र ने पाँच वर्षों में तीन कठिन प्राचीन भाषाएँ अच्छी तरह सीख लीं"),
    ("The honest watchman secured all iron bolts and locks on the storehouse doors", "चौकीदार ने गोदाम के सभी दरवाजों के भारी ताले और सिटकनियाँ लगा लीं"),
    ("The pious lady recited the sacred morning prayers silently in her serene mind", "धर्मात्मा महिला ने शांत मन से सुबह के पावन मंत्रों का पाठ कर लिया"),
    ("The tired worker washed his dusty face and hands at the village tube well", "थके हुए मजदूर ने कुएँ के ठंडे पानी से अपने हाथ मुँह धो लिए"),
    ("The decisive general accepted the surrender of the opposing army with magnanimous terms", "सेनापति ने पराजित सेना का आत्मसमर्पण उदार शर्तों के साथ स्वीकार कर लिया"),
    ("The little girl gathered all her colorful wooden toys into the wicker basket", "छोटी बालिका ने अपने सारे खिलौने समेटकर बाँस की टोकरी में रख लिए"),
    ("The careful archer checked the balance and straightness of his arrows before battle", "धनुर्धर ने युद्ध से पहले अपने तरकश के सभी तीरों की जाँच कर ली"),
    ("The wise elder resolved the internal family dispute before it reached the courts", "बुजुर्ग ने अदालत जाने से पहले ही परिवार का सारा झगड़ा आपस में निपटा लिया"),
    ("The humble ascetic wore his simple unstitched saffron robe before morning meditation", "साधु ने प्रातःकालीन ध्यान से पहले अपना साधारण भगवा वस्त्र धारण कर लिया"),
    ("The diligent apprentice copied all the traditional geometric architectural motifs into his sketchbook", "शिष्य ने गुरु की कार्यशाला के सभी सुंदर नमूने अपनी पुस्तिका में बना लिए"),
    ("The generous neighbor shared half of his winter firewood with the freezing widow", "दयालु पड़ोसी ने अपने हिस्से की आधी लकड़ियाँ उस गरीब बुढ़िया को दे दीं"),
    ("The patient teacher explained the difficult grammatical rules until every student understood them", "शिक्षक ने व्याकरण के सारे नियम बच्चों को पूरी तरह समझा दिए"),
    ("The careful banker deposited the rare imperial gold coins into the deep vault", "खज़ांची ने बहुमूल्य प्राचीन सिक्के लोहे की गहरी तिजोरी में सुरक्षित रख लिए"),
    ("The courageous youth pulled himself up onto the safety of the rocky ledge", "साहसी युवक ने अपनी पूरी ताकत लगाकर खुद को चट्टान के ऊपर खींच लिया"),
    ("The loving mother held her weeping little son close to her warm heart", "माँ ने रोते हुए नन्हे बालक को प्यार से अपने सीने से लगा लिया"),
    ("The village committee elected an honest and educated woman as their village head", "पंचायत ने एक पढ़ी लिखी और ईमानदार महिला को अपना मुखिया चुन लिया"),
    ("The cautious hunter loaded his crossbow with a sharp iron tipped wooden bolt", "शिकारी ने अपने धनुष पर लोहे की नोक वाला नुकीला बाण चढ़ा लिया"),
    ("The talented painter captured the fleeting golden light of sunset on his canvas", "चित्रकार ने ढलते सूरज की सुनहरी आभा को अपने कैनवास पर उतार लिया"),
    ("The practical traveler bought two loaves of fresh bread for his long journey", "मुसाफिर ने लंबी यात्रा के लिए बाज़ार से दो ताज़ा रोटियाँ खरीद लीं"),
    ("The thoughtful reader marked the inspiring passages of the philosophical book with pencil", "पाठक ने पुस्तक की सबसे सुंदर पंक्तियों के नीचे पेंसिल से निशान लगा लिए"),
    ("The determined runner summoned all his remaining physical energy for the final lap", "धावक ने अंतिम चक्कर के लिए अपने शरीर की सारी बची हुई ताकत जुटा ली"),
    ("The honest citizen paid all his municipal property taxes before the fiscal deadline", "सच्चे नागरिक ने समय सीमा समाप्त होने से पहले अपने सारे कर जमा कर दिए"),

    # 71-105: देना (Other-directed, Outward Benefactive: समझा देना, बता देना, छोड़ देना, भेज देना, दे देना)
    ("The generous teacher explained the entire scientific lesson to the struggling student patiently", "दयालु शिक्षक ने कमज़ोर छात्र को पूरा पाठ बहुत प्यार से समझा दिया"),
    ("The honest guide showed the safe mountain path to the lost wandering travelers", "ईमानदार गाइड ने भटके हुए यात्रियों को आगे का सुरक्षित रास्ता बता दिया"),
    ("The compassionate king released all innocent political prisoners on the festival of lights", "दयालु राजा ने विजय उत्सव के पावन अवसर पर सभी बंदियों को छोड़ दिया"),
    ("The district magistrate sent immediate disaster relief supplies to the flood affected villages", "ज़िलाधिकारी ने बाढ़ से घिरे गाँवों में तुरंत राहत सामग्री भेज दी"),
    ("The benevolent doctor gave free life saving medicines to the destitute village patients", "परोपकारी चिकित्सक ने गरीब मरीजों को मुफ्त में जीवन रक्षक दवाइयाँ दे दीं"),
    ("The loyal servant delivered the secret sealed diplomatic letter to the prime minister", "वफादार सेवक ने प्रधानमंत्री के हाथों में गोपनीय पत्र सौंप दिया"),
    ("The kind grandmother told a charming bedtime story to her eager little grandchildren", "दादी ने उत्सुक बच्चों को सोने से पहले परियों की एक सुंदर कहानी सुना दी"),
    ("The brave commander ordered his cavalry troops to advance toward the mountain pass", "सेनापति ने अपनी घुड़सवार सेना को आगे बढ़ने का स्पष्ट आदेश दे दिया"),
    ("The village elder donated half of his fertile agricultural land for building school", "गाँव के बुजुर्ग ने स्कूल बनाने के लिए अपनी आधी उपजाऊ ज़मीन दान दे दी"),
    ("The careful accountant handed over the complete financial audit report to the board", "मुनीम ने कंपनी के निदेशकों को पूरे साल का वित्तीय बहीखाता सौंप दिया"),
    ("The mother applied cooling herbal paste on the painful sting of the bee", "माँ ने ततैया के डंक पर ठंडक पहुँचाने वाला तुलसी का लेप लगा दिया"),
    ("The honest watchman returned the valuable lost gold bracelet to its rightful owner", "चौकीदार ने सोने का खोया हुआ कंगन उसके असली मालिक को लौटा दिया"),
    ("The skilled mechanic repaired the broken tractor engine and returned it to farmer", "मिस्त्री ने खराब ट्रैक्टर का इंजन ठीक करके किसान को वापस दे दिया"),
    ("The generous merchant lowered the grain prices for the starving townspeople during famine", "व्यापारी ने अकाल के समय गरीबों के लिए अनाज के दाम आधे कर दिए"),
    ("The schoolmaster taught five difficult geometry proofs on the blackboard with chalk diagrams", "गुरुजी ने श्यामपट्ट पर चित्र बनाकर रेखागणित के पाँच कठिन नियम समझा दिए"),
    ("The forest ranger warned the careless campers about the presence of wild tigers", "वनरक्षक ने पर्यटकों को जंगल में घूमते बाघों के खतरे से सावधान कर दिया"),
    ("The kind host served steaming hot lentil soup and fresh flatbreads to guests", "मेजबान ने अतिथियों को गरमा गरम दाल और ताज़ा रोटियाँ परोस दीं"),
    ("The village council granted permission to build a stone well in the pasture", "पंचायत ने चरागाह में नया कुआँ खोदने की अनुमति तुरंत दे दी"),
    ("The experienced captain steered the vessel safely past the treacherous hidden coral reefs", "कप्तान ने नाविकों को सही निर्देश देकर जहाज़ को चट्टानों से बचा लिया"),
    ("The court judge granted bail to the falsely accused youth after examining evidence", "न्यायाधीश ने निर्दोष बालक की दलीलें सुनकर उसे तुरंत ज़मानत दे दी"),
    ("The caring sister gave her only warm woolen scarf to her shivering brother", "बहन ने ठंड से काँपते हुए अपने छोटे भाई को अपनी ऊनी शॉल दे दी"),
    ("The wise counselor pacified the angry disputants with gentle and persuasive reasoned words", "समझदार सलाहकार ने दोनों पक्षों को समझाकर उनके पुराने झगड़े को खत्म करा दिया"),
    ("The artisan polished the carved brass lamp until it shone like bright gold", "कारीगर ने पीतल के दीये को चमकाकर सोने जैसा रूप दे दिया"),
    ("The postman delivered the long awaited military letter to the anxious soldier mother", "डाकिए ने सिपाही के घर पर उसकी माँ को बेटे की चिट्ठी पहुँचा दी"),
    ("The generous queen opened five new medical clinics for women in rural districts", "महारानी ने ग्रामीण क्षेत्रों में महिलाओं के लिए पाँच नए औषधालय खुलवा दिए"),
    ("The brave youth warned the approaching train about the washed out bridge ahead", "साहसी बालक ने लाल कपड़ा दिखाकर रेलगाड़ी को टूटे पुल से पहले ही रोक दिया"),
    ("The honest bank teller returned the excess currency notes mistakenly deposited by merchant", "खज़ांची ने व्यापारी द्वारा भूल से दिए गए अतिरिक्त नोट तुरंत लौटा दिए"),
    ("The skilled tailor stitched the delicate silk wedding dress with remarkable professional speed", "दर्जी ने विवाह के सुंदर रेशमी वस्त्र बहुत कम समय में तैयार कर दिए"),
    ("The watchful shepherd led his flock to the green clover meadows across river", "चरवाहे ने अपनी सभी भेड़ों को नदी पार हरी घास के मैदान में पहुँचा दिया"),
    ("The district administration distributed warm blankets and dry firewood to homeless destitute people", "प्रशासन ने कड़ाके की ठंड में बेसहारा लोगों को कंबल और अलाव की लकड़ियाँ बँटवा दीं"),
    ("The master architect explained the structural engineering blueprints to the construction foremen clearly", "वास्तुकार ने कारीगरों को नए भवन के निर्माण की पूरी योजना समझा दी"),
    ("The devoted daughter dedicated her medical research discovery to her beloved late father", "बेटी ने अपनी वैज्ञानिक खोज का सारा श्रेय अपने पूज्य पिता को दे दिया"),
    ("The peacemaker extinguished the rising flames of communal discord with sweet truthful speech", "शांति दूत ने अपने मधुर वचनों से भड़कते विवाद की आग को बुझा दिया"),
    ("The generous landlord canceled all unpaid agricultural rent arrears of the impoverished tenants", "ज़मींदार ने गरीब किसानों का पुराना सारा लगान पूरी तरह माफ़ कर दिया"),
    ("The experienced navigator pointed out the bright northern polar star to the apprentices", "नाविक ने युवा शिष्यों को आकाश में दिशा दिखाने वाले ध्रुव तारे की पहचान करा दी"),

    # 106-135: पड़ना (Sudden, Involuntary: कूद पड़ना, रो पड़ना, चमक पड़ना, बोल पड़ना, टूट पड़ना)
    ("The brave lifeguard jumped into the stormy river to save the drowning child", "डूबते हुए बच्चे को देखकर साहसी तैराक तुरंत उफनती नदी में कूद पड़ा"),
    ("The grieving mother burst into bitter tears upon hearing the tragic railway news", "दुर्घटना का दुखद समाचार सुनते ही शोकाकुल माँ फूट फूटकर रो पड़ी"),
    ("A brilliant flash of blue lightning shone across the dark nocturnal monsoon sky", "काले बादलों से घिरे रात के आकाश में अचानक नीली बिजली चमक पड़ी"),
    ("The shy little girl spoke up fearlessly when the school bully threatened her", "शरारती लड़के द्वारा डराए जाने पर वह संकोची बालिका अचानक निर्भय होकर बोल पड़ी"),
    ("The starving wolves fell upon the fallen deer carcass with ferocious animal hunger", "शिकार को देखते ही भूखे भेड़िए उस पर भूखे पेट के साथ टूट पड़े"),
    ("The sudden loud thunderstorm struck the sleepy mountain village in the dead midnight", "आधी रात को अचानक भयानक गर्जना के साथ गाँव पर आंधी तूफान टूट पड़ा"),
    ("The joyful crowd broke into loud spontaneous cheering as the champion crossed finish", "विजेता के रेखा पार करते ही पूरा मैदान खुशी के नारों से गूँज पड़ा"),
    ("The timid hare bolted in terror when the shadow of the eagle fell", "चील की परछाई देखते ही डरा हुआ खरगोश झाड़ियों की ओर तेज़ी से भाग पड़ा"),
    ("A sharp shooting star blazed across the clear velvet black dome of heaven", "शांत रात के आकाश में अचानक एक चमकीला तारा टूटकर चमक पड़ा"),
    ("The guilty student blurted out the absolute truth when questioned by the principal", "प्रधानाचार्य के पूछते ही घबराया हुआ छात्र अचानक सारी सच्चाई बोल पड़ा"),
    ("The angry mob attacked the fortress gates with heavy wooden battering ram logs", "उग्र भीड़ भारी लट्ठों के साथ किले के मुख्य फाटक पर टूट पड़ी"),
    ("The little infant burst into joyous laughter upon seeing the colorful dancing butterfly", "रंग बिरंगी तितली को उड़ते देखकर नन्हा बच्चा अचानक खिलखिलाकर हँस पड़ा"),
    ("The old stone retaining wall cracked open and collapsed under the torrential rain", "लगातार बारिश के दबाव से पत्थर की पुरानी दीवार अचानक ढह पड़ी"),
    ("The courageous youth stepped forward into the breach to protect his wounded comrade", "घायल साथी को बचाने के लिए साहसी युवक तुरंत आगे कूद पड़ा"),
    ("The sensitive actress broke down in tears while delivering the tragic dramatic monologue", "मंच पर करुण संवाद बोलते समय अभिनेत्री की आँखों से आँसू छलक पड़े"),
    ("A sudden spark of inspiration flashed in the mind of the great inventor", "समस्या का हल ढूँढते हुए वैज्ञानिक के मस्तिष्क में अचानक एक नया विचार कौंध पड़ा"),
    ("The honest witness spoke up in open court refuting the fabricated police testimony", "अदालत में झूठी गवाही सुनकर सच्चा गवाह अपनी जगह से उठकर बोल पड़ा"),
    ("The wild mountain blizzard descended upon the unprotected climbers without any prior warning", "बिना किसी चेतावनी के पर्वतारोहियों पर अचानक भयानक बर्फ़ीला तूफान टूट पड़ा"),
    ("The frightened horse reared up on its hind legs and bolted down road", "तेज़ आवाज़ सुनकर डरपोक घोड़ा अपने पिछले पैरों पर खड़ा होकर भाग पड़ा"),
    ("The whole assembly gasped in astonishment when the hidden traitor was exposed publicly", "गद्दार का चेहरा सामने आते ही पूरी राजसभा विस्मय से चौंक पड़ी"),
    ("The tired traveler collapsed upon the soft grassy bank after walking thirty miles", "तीस मील चलने के बाद थका हुआ मुसाफिर नदी के किनारे घास पर गिर पड़ा"),
    ("The dry autumn thatch caught fire when a stray spark drifted from chimney", "चूल्हे की चिनगारी उड़कर लगते ही झोपड़ी का सूखा छप्पर अचानक सुलग पड़ा"),
    ("The brave soldiers charged into the breach in the enemy outer defensive rampart", "किले की दीवार टूटते ही बहादुर सैनिक वीरता से आगे टूट पड़े"),
    ("The mother wept tears of unbounded joy when her missing son returned home", "बरसों बाद खोए हुए बेटे को सामने देखकर माँ की आँखों से खुशी के आँसू बह पड़े"),
    ("A radiant golden rainbow arched across the valley when the storm clouds parted", "बादल छँटते ही हरी भरी घाटी के ऊपर सात रंगों का सुंदर इंद्रधनुष चमक पड़ा"),
    ("The quiet hermit spoke words of profound spiritual warning to the gathered crowd", "शांत तपस्वी अचानक खड़े होकर जनता को नैतिक पतन के खतरों से आगाह कर पड़े"),
    ("The hungry stray dog pounced upon the piece of bread thrown by traveler", "यात्री द्वारा फेंकी गई रोटी के टुकड़े पर भूखा कुत्ता तुरंत झपट पड़ा"),
    ("The ancient wooden staircase gave way and crumbled under the heavy iron luggage", "भारी बक्से का वजन पड़ते ही लकड़ी का पुराना जीना अचानक चरमराकर टूट पड़ा"),
    ("The infant woke up startled by the distant rumble of deep mountain thunder", "दूर पहाड़ों में बादल गरजते ही पालने में सोया हुआ बच्चा चौंक पड़ा"),
    ("The entire village rallied behind the patriotic freedom fighters with boundless popular enthusiasm", "आज़ादी की पुकार सुनते ही पूरा गाँव क्रांतिकारियों के समर्थन में कूद पड़ा"),

    # 136-160: बैठना (Impulsive, Regrettable: लड़ बैठना, कह बैठना, खो बैठना, कर बैठना)
    ("The hot tempered youth picked a foolish fight with his best childhood friend", "क्रोधी युवक बिना सोचे समझे अपने बचपन के सबसे अच्छे मित्र से लड़ बैठा"),
    ("In his uncontrollable anger the minister uttered words he deeply regretted later on", "गुस्से में आकर मंत्री राजा के सामने ऐसी अनुचित बात कह बैठा जिस पर बाद में पछताया"),
    ("The reckless gambler lost his entire ancestral fortune in a single foolish wager", "लापरवाह जुआरी एक ही मूर्खतापूर्ण दांव में अपनी सारी पुश्तैनी जायदाद खो बैठा"),
    ("The novice clerk committed a serious accounting blunder in the royal tax ledger", "नौसिखिया मुनीम जल्दबाज़ी में सरकारी बहीखाते में एक बहुत बड़ी गलती कर बैठा"),
    ("Do not pick unnecessary quarrels with influential neighbors over trivial property border disputes", "छोटी सी बात पर अपने पड़ोसियों से बेवजह लड़ बैठना कोई समझदारी नहीं है"),
    ("In a moment of blind emotional passion he revealed the confidential state secret", "भावुकता में आकर वह अपने देश का सबसे बड़ा गोपनीय राज़ किसी अजनबी से कह बैठा"),
    ("The foolish merchant lost the confidence of his creditors through deceptive fraudulent promises", "अपनी चालाकियों के कारण वह व्यापारी बाज़ार में अपनी सारी साख खो बैठा"),
    ("He made an impulsive promise that he could never fulfill throughout his life", "उत्साह में आकर वह एक ऐसा कठिन वादा कर बैठा जिसे निभाना उसके वश में न था"),
    ("The impatient driver took a dangerous turn on the narrow mountain cliff road", "जल्दबाज़ी के चक्कर में चालक खतरनाक मोड़ पर अपनी गाड़ी को टकरा बैठा"),
    ("The arrogant prince quarreled with the venerable royal preceptor over ceremonial seating arrangements", "घमंड में चूर होकर राजकुमार अपने पूज्य कुलगुरु से ही विवाद कर बैठा"),
    ("Under pressure of interrogation the weak accomplice blurted out the names of all conspirators", "सख्ती होते ही डरपोक साथी अपने सभी षड्यंत्रकारियों के नाम पुलिस से कह बैठा"),
    ("The careless traveler lost his passport and all travel funds at the terminus", "लापरवाही के कारण मुसाफिर स्टेशन पर अपना पहचान पत्र और सारा धन खो बैठा"),
    ("He took an enormous financial loan that destroyed his modest family retail store", "बिना सोचे समझे वह इतना बड़ा कर्ज़ ले बैठा जिसने उसकी दुकान को बर्बाद कर दिया"),
    ("Do not quarrel impulsively with the judge while presenting your delicate legal petition", "अदालत में बहस करते समय न्यायाधीश से लड़ बैठना अपने ही पैर पर कुल्हाड़ी मारना है"),
    ("In his excitement the young scientist disclosed his secret formula before filing patent", "उत्साह में आकर वैज्ञानिक अपनी खोज का गुप्त रहस्य पेटेंट कराने से पहले ही बता बैठा"),
    ("The corrupt officer lost his honorable reputation and pension after the sudden raid", "छापा पड़ते ही वह अधिकारी अपनी सारी इज़्ज़त और सरकारी नौकरी खो बैठा"),
    ("He made a hasty investment in a fraudulent speculative company that collapsed overnight", "लालच में आकर वह एक फर्जी कंपनी में अपनी सारी जमा पूँजी लगा बैठा"),
    ("The hot headed boxer struck the referee during the heated championship boxing bout", "गुस्से में आकर मुक्केबाज़ रिंग में खेल के रेफरी से ही हाथापाई कर बैठा"),
    ("She spoke harsh and wounding words to her sister that fractured their lifelong bond", "क्रोध के आवेग में वह अपनी सगी बहन से ऐसी कड़वी बात कह बैठी जिससे रिश्ता टूट गया"),
    ("The desperate debtor mortgaged his only ancestral home to pay off gambling debts", "कर्ज़ चुकाने की मजबूरी में वह अपना इकलौता पुश्तैनी मकान भी गिरवी रख बैठा"),
    ("He made a foolish bet with the professional card sharp and lost everything", "चालाक जुआरी की बातों में आकर वह अपनी सारी कमाई एक बाज़ी में हार बैठा"),
    ("The stubborn rebel defied the lawful imperial decree and invited his own destruction", "हठ में आकर विद्रोही राजा के आदेश का उल्लंघन कर बैठा और विपत्ति मोल ली"),
    ("In a fit of unwarranted jealousy the lover accused his devoted faithful partner", "शक के वशीभूत होकर वह अपनी निष्कपट और वफादार साथी पर झूठा आरोप लगा बैठा"),
    ("The careless mechanic damaged the fragile delicate sensor of the modern jet engine", "लापरवाही से काम करते हुए कारीगर विमान के नाज़ुक कलपुर्जे को तोड़ बैठा"),
    ("He undertook a perilous journey across the desert without sufficient water and provisions", "बिना तैयारी के वह तपते रेगिस्तान की ऐसी यात्रा पर निकल बैठा जहाँ जान का खतरा था"),

    # 161-180: उठना (Sudden Inception, Upward Outburst: जाग उठना, चिल्ला उठना, काँप उठना, भड़क उठना)
    ("The sleeping tiger woke up suddenly with a low growl when branches snapped", "सूखी टहनी टूटने की आवाज़ सुनते ही सोया हुआ बाघ अचानक जाग उठा"),
    ("The terrified child screamed in horror when the dark shadow fell across window", "खिड़की पर भयानक परछाई देखते ही डरा हुआ बच्चा ज़ोर से चिल्ला उठा"),
    ("The fragile cottage trembled violently when the powerful subterranean earthquake tremor shook mountains", "भूकंप का तेज़ झटका लगते ही लकड़ी की पूरी कुटिया थर थर काँप उठी"),
    ("The dry timber of the ancient storehouse flared up into blazing uncontrollable flames", "चिनगारी लगते ही सूखे गोदाम की पुरानी लकड़ियाँ धू धू करके भड़क उठीं"),
    ("The patriotic spirit of the whole nation awakened at the clarion freedom call", "आज़ादी की एक ही पुकार पर पूरे देश की सोई हुई स्वाभिमानी चेतना जाग उठी"),
    ("The wounded soldier cried out in agony when the surgeon extracted the bullet", "घाव से गोली निकालते ही घायल सिपाही असहनीय दर्द से कराह उठा और चिल्ला पड़ा"),
    ("The delicate leaves of the aspen tree shivered in the cold mountain gust", "पहाड़ी हवा का ठंडा झोंका लगते ही पेड़ की कोमल पत्तियाँ काँप उठीं"),
    ("The smoldering sectarian resentment flared into an open riot after the inflammatory speech", "भड़काऊ भाषण के बाद लोगों के मन में सुलगती पुरानी नफरत अचानक भड़क उठी"),
    ("The ancient maternal instinct of the tigress awakened to defend her helpless cubs", "अपने नन्हे बच्चों पर संकट देखकर बाघिन की रक्षात्मक ममता अचानक जाग उठी"),
    ("The startled deer bolted across the clearing when the hunter rifle cracked loudly", "बंदूक की आवाज़ सुनते ही शांत मैदान में चरता हुआ हिरण चौंक उठा"),
    ("The entire audience cheered with thunderous applause as the national flag was unfurled", "मंच पर तिरंगा झंडा फहराते ही पूरा सभागार तालियों की गड़गड़ाहट से गूँज उठा"),
    ("The timid rabbit quivered with fear under the dark canopy of the bramble", "शिकारी कुत्ते की आहट पाकर झाड़ी में छिपा छोटा खरगोश डर से काँप उठा"),
    ("The smoldering charcoal embers in the open hearth blazed up in the wind", "हवा का झोंका लगते ही चूल्हे में दबी हुई राख के नीचे के अंगारे भड़क उठे"),
    ("The moral conscience of the guilty clerk awakened and he returned the money", "गलती का अहसास होते ही मुनीम का सोया हुआ अंतःकरण जाग उठा और उसने धन लौटा दिया"),
    ("The watchman yelled an alarm warning the sleeping palace of the midnight intruders", "किले की दीवार पर अजनबी को देखते ही पहरेदार ज़ोर से चिल्ला उठा"),
    ("The old woman hands trembled with emotion when she embraced her returning grandson", "विदेश से लौटे पोते को गले लगाते ही बुढ़िया के काँपते हाथ खुशी से सिहर उठे"),
    ("The long suppressed rebellion flared across all twenty districts within forty eight hours", "दबा हुआ जन आक्रोश दो ही दिनों के भीतर पूरे प्रांत में क्रांति बनकर भड़क उठा"),
    ("The slumbering giant of national industry awakened to meet the challenging wartime demand", "संकट के समय राष्ट्र के सभी कारखाने अपनी पूरी क्षमता के साथ सक्रिय होकर जाग उठे"),
    ("The wounded gladiator groaned in deep pain on the sandy floor of arena", "रेत पर गिरते ही घायल योद्धा असहनीय पीड़ा के मारे कराह उठा"),
    ("The dark surface of the tranquil lake rippled and rose in violent waves", "तूफानी हवा के थपेड़े लगते ही शांत झील का पानी अचानक उफन उठा"),

    # 181-200: डालना (Forceful, Violent, Rash Completeness: मार डालना, काट डालना, तोड़ डालना, फेंक डालना)
    ("The ruthless poachers killed the magnificent one horned rhinoceros for its valuable horn", "क्रूर शिकारियों ने सींग के लालच में उस दुर्लभ एक सींग वाले गैंडे को मार डाला"),
    ("The lumberjacks felled the ancient sacred cedar tree in the virgin mountain forest", "लकड़हारों ने जंगल के उस प्राचीन और पवित्र देवदार के विशाल वृक्ष को काट डाला"),
    ("The enraged rioters smashed the glass windows of all public municipal transportation buses", "उपद्रवियों ने गुस्से में आकर नगर निगम की सभी बसों के शीशे तोड़ डाले"),
    ("The angry woman threw away all the deceitful letters written by the traitor", "महिला ने धोखेबाज़ द्वारा लिखे गए सारे झूठे और कपटपूर्ण पत्र आग में फेंक डाले"),
    ("The poisonous venom of the black krait would kill a healthy adult in hours", "काले करैत का विषैला ज़हर कुछ ही घंटों में किसी स्वस्थ मनुष्य को मार डालता है"),
    ("The invader soldiers cut down all the fertile fruit orchards surrounding the besieged city", "हमलावर सेना ने घेरे में आए नगर के चारों ओर के सभी हरे भरे बाग काट डाले"),
    ("The powerful earthquake destroyed hundreds of stone houses across the vulnerable seismic valley", "विनाशकारी भूकंप ने उस पहाड़ी घाटी के सैकड़ों पक्के मकानों को तोड़ डाला"),
    ("The rebellious prisoner cast off his heavy iron chains with supreme desperate strength", "साहसी बंदी ने अपनी पूरी ताकत लगाकर लोहे की भारी बेड़ियों को तोड़ डाला"),
    ("The ferocious wolf pack killed five sheep in the mountain pen overnight", "जंगल के भूखे भेड़ियों ने रात के अंधेरे में बाड़े की पाँच भेड़ों को मार डाला"),
    ("The greedy timber contractors cut down ten thousand hectares of pristine Himalayan woodland", "लालची ठेकेदारों ने अपने मुनाफ़े के लिए हिमालय के घने जंगलों को बेरहमी से काट डाला"),
    ("The rebellious mob broke down the heavy iron gates of the royal granary", "भूखी जनता ने अनाज पाने के लिए शाही गोदाम के भारी लोहे के फाटक तोड़ डाले"),
    ("The reforming king cast away all superstitious and regressive social customs of kingdom", "सुधारक राजा ने अपने राज्य की सभी पुरानी और कुरीतियों को उखाड़ फेंका"),
    ("The severe winter frost killed all the delicate orange blossoms in the valley", "कड़ाके की ठंड और पाले ने घाटी के संतरों के सभी नाज़ुक फूलों को मार डाला"),
    ("The highway robbers chopped down heavy trees to block the narrow mountain trade road", "लुटेरों ने व्यापारियों का रास्ता रोकने के लिए सड़क पर बड़े बड़े पेड़ काट डाले"),
    ("The wild elephant smashed the wooden fences and crushed the ripe sugarcane harvest", "जंगली हाथी ने बाड़ को तोड़ डाला और गन्ने की पूरी पकी हुई फसल रौंद डाली"),
    ("The courageous freedom fighters tore down the foreign colonial imperial flag from mast", "क्रांतिकारियों ने सरकारी इमारत से विदेशी हुकूमत के झंडे को उतार फेंका"),
    ("The drought and starvation killed thousands of cattle across the arid western desert", "भीषण अकाल और चारे की कमी ने रेगिस्तान के हज़ारों मवेशियों को मार डाला"),
    ("The sharp iron buzzsaw cut through the thick teak log within two minutes", "तेज़ आरी ने सागौन के मोटे लट्ठे को दो मिनट के भीतर चीर डाला"),
    ("The violent tempest smashed twenty wooden fishing trawlers against the rocky coastal reef", "समुद्री तूफान ने मछुआरों की बीस नावों को चट्टानों से टकराकर चकनाचूर कर डाला"),
    ("Compound vector verbs enrich the semantic nuance and expressive vibrancy of Hindi syntax", "संयुक्त क्रियाओं का यह सुंदर प्रयोग हिंदी भाषा के सौंदर्य को अद्वितीय बना देता है"),
]

if __name__ == "__main__":
    process_batch(36, "p36s", PAIRS)
