#!/usr/bin/env python3
"""Batch VT-02: Progressive & Continuous Aspects (200 sentences).
File: data/phrases34.json, IDs: p34s001..p34s200.
Themes:
- Present Continuous (रहा है / रही है / रहे हैं / रहा हूँ / रही हूँ / रहे हो)
- Past Continuous (रहा था / रही थी / रहे थे / रही थीं)
- Future Continuous (रहा होगा / रही होगी / रहे होंगे)
- Contrafactual Continuous (रहा होता / रही होती)
- Stative vs Dynamic Continuous (बैठा है, खड़ा है, लेटा है, सोया है, पहने हुए है)
"""
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parent))
from gen_batches_pipeline import process_batch

PAIRS = [
    # 1-40: Present Continuous (रहा है, रही है, रहे हैं, रहा हूँ, रही हूँ, रहे हो)
    ("The dedicated doctor is examining the critical patients in the emergency ward right now", "समर्पित चिकित्सक इस समय आपातकालीन कक्ष में गंभीर रोगियों की जाँच कर रहा है"),
    ("The talented artist is painting a magnificent portrait of the national freedom fighter today", "प्रतिभाशाली चित्रकार आज राष्ट्रीय स्वतंत्रता सेनानी का भव्य चित्र बना रही है"),
    ("The hardworking farmers are harvesting the golden ripe wheat across the vast northern plains", "मेहनती किसान विशाल उत्तरी मैदानों में पकी हुई सुनहरी फसल काट रहे हैं"),
    ("I am reading an insightful commentary on ancient Indian political philosophy this morning", "मैं आज सुबह प्राचीन भारतीय राजनीति दर्शन पर एक ज्ञानवर्धक टीका पढ़ रहा हूँ"),
    ("I am preparing aromatic herbal tea for the distinguished foreign delegates in conference", "मैं सम्मेलन में आए विशिष्ट विदेशी प्रतिनिधियों के लिए सुगंधित चाय बना रही हूँ"),
    ("You are explaining difficult mathematical concepts to the junior students with commendable clarity", "तुम कनिष्ठ विद्यार्थियों को कठिन गणितीय सूत्र बहुत सरलता से समझा रहे हो"),
    ("You are singing a soulful classical thumri in the cultural concert hall right now", "तुम सांस्कृतिक सभागार में इस समय बहुत भावपूर्ण शास्त्रीय ठुमरी गा रही हो"),
    ("The gentle monsoon rain is falling steadily over the dry parched agricultural fields", "सूखे खेतों पर इस समय लगातार हल्की मानसूनी बारिश बरस रही है"),
    ("The swift mountain stream is rushing with immense force through the narrow rocky canyon", "पहाड़ी झरना संकरे पथरीले दर्रे से होकर अत्यंत वेग के साथ बह रहा है"),
    ("The master weaver is crafting an exquisite Pashmina shawl on his wooden handloom", "कारीगर अपने करघे पर एक अत्यंत सुंदर पश्मीना शॉल तैयार कर रहा है"),
    ("The experienced sculptress is carving a life size marble statue for the central museum", "अनुभवी मूर्तिकार संग्रहालय के लिए संगमरमर की आदमकद मूर्ति तराश रही है"),
    ("The bright school children are solving complex scientific puzzles in the modern science laboratory", "मेधावी बच्चे आधुनिक प्रयोगशाला में जटिल वैज्ञानिक पहेलियाँ हल कर रहे हैं"),
    ("I am writing an urgent memorandum to the district magistrate regarding clean water supply", "मैं पीने के पानी की समस्या पर जिलाधिकारी को एक ज़रूरी पत्र लिख रहा हूँ"),
    ("I am translating classical Sanskrit dramatic verses into modern poetic Hindi for the stage", "मैं रंगमंच के लिए संस्कृत नाटकों का सरल हिंदी में अनुवाद कर रही हूँ"),
    ("You are building a sturdy wooden boat for navigating the turbulent seasonal monsoon river", "तुम उफनती मानसूनी नदी को पार करने के लिए एक मजबूत नाव बना रहे हो"),
    ("You are weaving delicate lace borders on the ceremonial silk saree for the wedding", "तुम विवाह के लिए रेशमी साड़ी पर सुंदर गोटा किनारी लगा रही हो"),
    ("The brave firemen are battling the raging flames inside the commercial warehouse courageously", "साहसी अग्निशमन कर्मी गोदाम में लगी भीषण लपटों पर काबू पाने का प्रयास कर रहे हैं"),
    ("The diligent librarian is cataloging the rare ancient palm leaf manuscripts in the archives", "पुस्तकालय अध्यक्ष अभिलेखागार में दुर्लभ प्राचीन ताड़पत्रों की सूची बना रही है"),
    ("The enthusiastic athletes are running around the municipal stadium track in the morning fog", "उत्साही धावक सुबह के कोहरे में नगर के मैदान के चक्कर लगा रहे हैं"),
    ("I am learning classical sitar from an accomplished musical maestro of the Senia tradition", "मैं सेनिया घराने के एक सिद्ध उस्ताद से शास्त्रीय सितार सीख रहा हूँ"),
    ("I am designing an eco friendly rainwater harvesting system for our dry arid township", "मैं अपने कस्बे के लिए जल संरक्षण की एक पर्यावरण अनुकूल योजना बना रही हूँ"),
    ("You are repairing the broken grandfather clock with delicate steel instruments and great patience", "तुम बहुत धैर्य और बारीक औज़ारों से पुरानी दीवार घड़ी की मरम्मत कर रहे हो"),
    ("You are organizing a relief camp for the flood victims along the swollen riverbank", "तुम नदी किनारे बाढ़ पीड़ितों के लिए सहायता शिविर का प्रबंध कर रही हो"),
    ("The industrious blacksmith is hammering the red hot iron bar upon the heavy anvil", "मेहनती लोहार भारी निहाई पर लाल गरम लोहे की छड़ को हथौड़े से पीट रहा है"),
    ("The kind nurse is administering soothing medication to the injured mountain rescue workers", "दयालु नर्स घायल पर्वतारोहियों को आराम पहुँचाने वाली दवा दे रही है"),
    ("The skilled potters are shaping elegant clay vessels on the rapidly spinning wooden wheels", "कुशल कुम्हार तेज़ी से घूमते चाक पर मिट्टी के सुंदर बर्तन तैयार कर रहे हैं"),
    ("I am compiling an exhaustive historical dictionary of regional Hindi colloquial proverbs and idioms", "मैं स्थानीय मुहावरों और लोकोक्तियों का एक विस्तृत ऐतिहासिक शब्दकोश बना रहा हूँ"),
    ("I am cultivating organic culinary herbs in the sunny greenhouse behind our rural cottage", "मैं अपनी कुटिया के पीछे बने छोटे घर में तरह तरह की जड़ी बूटियाँ उगा रही हूँ"),
    ("You are leading the youth mountaineering expedition toward the treacherous high Himalayan col", "तुम दुर्गम पहाड़ी दर्रे की ओर युवाओं के साहसी दल का नेतृत्व कर रहे हो"),
    ("You are conducting a thorough linguistic survey of endangered tribal dialects in the district", "तुम ज़िले की विलुप्त होती जनजातीय बोलियों का एक वैज्ञानिक सर्वेक्षण कर रही हो"),
    ("The fearless soldiers are guarding the snowy mountain frontiers amidst subzero freezing blizzards", "बहादुर सैनिक शून्य से नीचे तापमान में देश की बर्फीली सीमाओं की पहरेदारी कर रहे हैं"),
    ("The young aerospace engineer is testing the propulsion rocket engine in the wind tunnel", "युवा वैज्ञानिक सुरंग में नए रॉकेट इंजन की क्षमता की जाँच कर रही है"),
    ("The energetic youth volunteers are planting ten thousand fruit saplings along the coastal highway", "युवा स्वयंसेवक तटीय राजमार्ग के दोनों ओर हज़ारों छायादार पौधे लगा रहे हैं"),
    ("I am documenting the rich oral folk legends of our elderly village bards carefully", "मैं गाँव के बुजुर्ग गायकों से लोकगीतों की प्राचीन परंपरा को लिपिबद्ध कर रहा हूँ"),
    ("I am training stray dogs to assist visually impaired people in their daily commute", "मैं सड़क के बेसहारा कुत्तों को दृष्टिहीन लोगों की सहायता करने का प्रशिक्षण दे रही हूँ"),
    ("You are restoring the magnificent antique fresco paintings in the historic heritage palace hall", "तुम ऐतिहासिक महल के दीवानखाने में बने प्राचीन भित्तिचित्रों का संरक्षण कर रहे हो"),
    ("You are practicing complex yogic breathing techniques to attain deep meditative mental tranquility", "तुम मानसिक शांति प्राप्त करने के लिए प्राणायाम और ध्यान का गहरा अभ्यास कर रही हो"),
    ("The experienced ship captain is steering the vessel through the choppy dark coastal swells", "अनुभवी कप्तान तूफानी तटीय लहरों के बीच से विशाल जहाज़ को बाहर निकाल रहा है"),
    ("The dedicated botanist is classifying rare high altitude alpine flowering plants in the valley", "वनस्पति वैज्ञानिक घाटी में पाई जाने वाली दुर्लभ जंगली वनस्पतियों का वर्गीकरण कर रही है"),
    ("The honest municipal workers are cleaning the historic stone stepwell before the monsoon arrives", "सफाई कर्मचारी वर्षा ऋतु आने से पहले प्राचीन ऐतिहासिक बावड़ी की सफाई कर रहे हैं"),

    # 41-80: Past Continuous (रहा था, रही थी, रहे थे, रही थीं)
    ("The weary traveler was walking slowly along the dusty desert track under scorching sun", "थका हुआ मुसाफिर तपती धूप में धूल भरी सड़क पर धीरे धीरे आगे बढ़ रहा था"),
    ("The young maiden was fetching water from the deep village well in copper pitcher", "युवती ताँबे के घड़े में गाँव के गहरे कुएँ से ठंडा पानी भर रही थी"),
    ("The courageous freedom fighters were planning a secret strategy inside the underground mountain cavern", "क्रांतिकारी गुप्त गुफा में बैठकर स्वतंत्रता संग्राम की अगली योजना बना रहे थे"),
    ("The elderly grandmothers were narrating ancient mythological folk tales to the gathering children", "बुजुर्ग दादियाँ जमा हुए बच्चों को प्राचीन पौराणिक कहानियाँ सुना रही थीं"),
    ("I was studying constitutional law when the sudden electric power failure occurred in town", "जब नगर में बिजली गुल हुई तब मैं संविधान के महत्वपूर्ण फैसलों का अध्ययन कर रहा था"),
    ("I was knitting a warm woolen sweater for the newborn baby near the fireplace", "मैं जलती अंगीठी के पास बैठकर नवजात शिशु के लिए ऊनी स्वेटर बुन रही थी"),
    ("You were repairing the broken wooden bridge when the flash flood waters crested dangerously", "जब बाढ़ का पानी अचानक बढ़ा तब तुम टूटे हुए पुल की मरम्मत कर रहे थे"),
    ("You were reciting heroic verses from Ramcharitmanas during the sacred evening temple prayer", "तुम शाम की आरती के समय मंदिर में रामचरितमानस की चौपाइयों का पाठ कर रही थीं"),
    ("The royal guard was patrolling the high stone battlements of the fortress at midnight", "पहरेदार आधी रात को किले की ऊँची पत्थर की दीवारों पर सतर्कता से गश्त कर रहा था"),
    ("The skilled seamstress was stitching the ornate golden border onto the royal wedding gown", "दर्ज़िन राजसी विवाह के सुंदर जोड़े पर सोने की ज़री का काम कर रही थी"),
    ("The diligent peasants were digging irrigation canals to divert river water to their crops", "मेहनती किसान नदी का पानी खेतों तक लाने के लिए नई नहरें खोद रहे थे"),
    ("The village women were singing soulful auspicious marriage songs in the decorated courtyard", "सजे हुए आँगन में महिलाएँ विवाह के मंगलकारी लोकगीत गा रही थीं"),
    ("I was writing the final chapter of my historical research monograph when dawn broke", "सुबह होने से पहले मैं अपने शोध ग्रंथ का अंतिम अध्याय पूरा कर रहा था"),
    ("I was grinding aromatic sandalwood paste upon the stone slab for the deity worship", "मैं भगवान की पूजा के लिए पत्थर की सिल पर सुगंधित चंदन घिस रही थी"),
    ("You were steering the loaded cargo boat against the fierce counter current of river", "तुम नदी के तेज़ बहाव के विपरीत माल से लदी भारी नाव को संभाल रहे थे"),
    ("You were teaching alphabets to the illiterate village women in the evening primary school", "तुम शाम की पाठशाला में गाँव की अनपढ़ बहनों को अक्षर ज्ञान सिखा रही थीं"),
    ("The wild wind was howling through the tall pine trees on the dark mountain ridge", "अंधेरी पहाड़ी पर चीड़ के ऊँचे पेड़ों के बीच से तूफानी हवा सनसनाती हुई गुज़र रही थी"),
    ("The devoted mother was gently fanning her feverish child with a palm leaf fan", "स्नेही माँ ताड़ के पंखे से अपने बीमार बच्चे को धीरे धीरे हवा कर रही थी"),
    ("The skilled masons were constructing the tall minaret using red sandstone and white marble", "कारीगर लाल बलुआ पत्थर और सफेद संगमरमर से ऊँची मीनार का निर्माण कर रहे थे"),
    ("The temple dancers were practicing delicate classical rhythmic movements before the sacred shrine", "नृत्यांगनाएं गर्भगृह के सामने अपने शास्त्रीय नृत्य के कठिन ताल का अभ्यास कर रही थीं"),
    ("I was observing the celestial movement of planets through the brass astronomical quadrant telescope", "मैं दूरबीन से रात के आकाश में ग्रहों और तारों की गति का निरीक्षण कर रहा था"),
    ("I was collecting fallen dry oak branches to keep our fireplace burning through night", "मैं रात भर आग जलाने के लिए जंगल से सूखी लकड़ियाँ एकत्र कर रही थी"),
    ("You were training the young stallion to leap across the high thorny wooden fences", "तुम युवा घोड़े को ऊँची बाड़ के ऊपर से छलांग लगाने का अभ्यास करा रहे थे"),
    ("You were preparing traditional sweet delicacies for the upcoming autumn festival of lights", "तुम दीपावली के त्योहार के लिए रसोई में तरह तरह के स्वादिष्ट पकवान बना रही थीं"),
    ("The experienced scout was tracking the faint hoof prints of the lost horses carefully", "अनुभवी खोजी ज़मीन पर खोए हुए घोड़ों के खुरों के निशानों का पीछा कर रहा था"),
    ("The master architect was drawing detailed structural elevations on large sheets of parchment paper", "वास्तुकार कागज़ के बड़े पन्नों पर नए महल का विस्तृत नक्शा तैयार कर रहा था"),
    ("The loyal palace sentries were keeping strict watch while the emperor rested in chambers", "जब सम्राट अपने कक्ष में विश्राम कर रहे थे तब अंगरक्षक सतर्क पहरा दे रहे थे"),
    ("The maidens were picking fresh jasmine blossoms from the bushes in the early morning", "लड़कियाँ सुबह सवेरे बगीचे से चमेली के ताज़ा फूल चुन रही थीं"),
    ("I was exploring the ancient ruined stone corridors of the deserted hill fortress yesterday", "मैं कल उस निर्जन पहाड़ी किले के प्राचीन पत्थरों के बीच से गुज़र रहा था"),
    ("I was spinning fine yarn on the wooden charkha during the quiet afternoon hours", "मैं दोपहर के शांत समय में लकड़ी के चरखे पर बारीक सूत कात रही थी"),
    ("You were demonstrating advanced self defense techniques to the cadets in the academy hall", "तुम प्रशिक्षण कक्ष में छात्रों को आत्मरक्षा के आधुनिक दांव पेंच सिखा रहे थे"),
    ("You were curating the precious medieval coin collection for the public state exhibition", "तुम सार्वजनिक प्रदर्शनी के लिए प्राचीन ऐतिहासिक सिक्कों का वर्गीकरण कर रही थीं"),
    ("The dark storm clouds were gathering rapidly over the jagged peaks of the Himalayas", "हिमालय की ऊँची चोटियों के ऊपर काले तूफानी बादल बहुत तेज़ी से घिर रहे थे"),
    ("The river was eroding the fertile agricultural embankments during the furious seasonal monsoon overflow", "उफनती नदी बरसात के दिनों में उपजाऊ खेतों की मिट्टी को लगातार काट रही थी"),
    ("The villagers were building a temporary mud dyke to protect their homes from flooding", "ग्रामीण अपने घरों को बचाने के लिए मिट्टी का एक कच्चा बाँध बना रहे थे"),
    ("The sisters were embroidering colorful silk threads onto the ceremonial tapestry for the pavilion", "बहनें शामियाने के लिए सुंदर रेशमी परदे पर रंगीन धागों से बेलबूटे बना रही थीं"),
    ("I was meditating beside the sacred mountain hermitage waterfall when the golden sun rose", "जब सूर्योदय हुआ तब मैं पवित्र झरने के पास बैठकर गहरे ध्यान में लीन था"),
    ("I was kneading fresh wheat dough on the wooden board for baking evening flatbreads", "मैं शाम की रोटियाँ बनाने के लिए परात में गेहूँ का आटा गूँथ रही थी"),
    ("You were carving intricate floral rosettes on the wooden door frame of the mansion", "तुम हवेली के मुख्य द्वार पर लकड़ी की बहुत सुंदर नक्काशी कर रहे थे"),
    ("You were tending the wounded mountain deer with herbal salves and clean bandages", "तुम घायल हिरण के घावों पर जड़ी बूटियों का लेप लगाकर पट्टी बाँध रही थीं"),

    # 81-120: Future & Presumptive Continuous (रहा होगा, रही होगी, रहे होंगे)
    ("The farmer must be tilling his arid fields in the expectation of seasonal rain", "किसान इस समय बादलों की उम्मीद में अपने सूखे खेत जोत रहा होगा"),
    ("The grandmother must be telling delightful folk stories to the children in village", "दादी इस समय गाँव में बच्चों को सुंदर परियों की कहानियाँ सुना रही होगी"),
    ("The scholars must be debating complex philosophical questions in the quiet university seminar hall", "विद्वान इस समय विश्वविद्यालय के सभागार में किसी गूढ़ विषय पर शास्त्रार्थ कर रहे होंगे"),
    ("The mail train must be crossing the long steel girder bridge over the river", "डाक गाड़ी इस समय नदी के ऊपर बने लंबे लोहे के पुल को पार कर रही होगी"),
    ("He must be writing his final thesis chapter under the soft glow of table lamp", "वह इस समय मेज़ की बत्ती के नीचे बैठकर अपने शोध का अंतिम पन्ना लिख रहा होगा"),
    ("She must be practicing her difficult classical violin piece before tomorrow evening concert performance", "वह कल के संगीत कार्यक्रम के लिए वायलिन पर कठिन राग का अभ्यास कर रही होगी"),
    ("The travelers will be resting beside the desert oasis well under tall palm trees", "यात्री इस समय रेगिस्तान के नखलिस्तान में ताड़ के पेड़ों की छाँव में सुस्ता रहे होंगे"),
    ("The workers will be assembling the railway tracks through the difficult mountain pass terrain", "मजदूर दुर्गम पहाड़ी दर्रे में रेल की नई पटरियाँ बिछाने का काम कर रहे होंगे"),
    ("The gentle breeze must be rustling through the golden wheat fields at sunset hour", "शाम के समय पके हुए गेहूँ के खेतों में मंद हवा सरसरा रही होगी"),
    ("The mother must be anxiously awaiting the arrival of her son from the city", "माँ इस समय नगर से अपने बेटे के लौटने की राह देख रही होगी"),
    ("The soldiers will be patrolling the treacherous mountain frontiers in the subzero cold night", "सैनिक कड़ाके की ठंड में सीमा की बर्फीली चौकियों पर सतर्क गश्त कर रहे होंगे"),
    ("The astronomers will be tracking the distant passing asteroid with high powered optical telescope", "खगोलशास्त्री दूरबीन से किसी दूर से गुज़रते हुए उल्कापिंड की गति को माप रहे होंगे"),
    ("He must be negotiating the difficult commercial peace treaty on behalf of the kingdom", "वह इस समय राज्य की ओर से शांति संधि की कठिन शर्तों पर बातचीत कर रहा होगा"),
    ("She will be teaching classical dance steps to the young disciples in the academy", "वह इस समय नृत्य अकादमी में नए शिष्यों को घुंघरुओं के बोल सिखा रही होगी"),
    ("The pilgrims will be climbing the sacred stone steps of the ancient mountain shrine", "तीर्थयात्री इस समय श्रद्धा भाव से मंदिर की ऊँची सीढ़ियाँ चढ़ रहे होंगे"),
    ("The fishermen will be casting their wide nets into the deep ocean before nightfall", "मछुआरों का दल शाम ढलने से पहले गहरे समुद्र में अपने जाल फेंक रहा होगा"),
    ("The artist must be giving final finishing touches to the magnificent oil canvas masterpiece", "चित्रकार अपनी सबसे उत्कृष्ट पेंटिंग पर अंतिम रंग भर रहा होगा"),
    ("The little girl must be sleeping peacefully in her warm wooden crib beside mother", "छोटी बालिका इस समय माँ के पास अपने पालने में चैन की नींद सो रही होगी"),
    ("The scouts will be searching the dense woodland for the lost sheep and cattle", "चरवाहे इस समय घने जंगल में अपनी भटकी हुई भेड़ों की तलाश कर रहे होंगे"),
    ("The village elders will be resolving the delicate boundary dispute in the open council", "गाँव के पंच चौपाल में बैठकर ज़मीन के पुराने विवाद का फैसला कर रहे होंगे"),
    ("He must be repairing the tractor engine in the barn before morning fieldwork begins", "वह सुबह काम शुरू होने से पहले बाड़े में ट्रैक्टर का इंजन सुधार रहा होगा"),
    ("She will be weaving the delicate floral patterns into the ceremonial silk prayer rug", "वह प्रार्थना के लिए रेशमी आसन पर बहुत सुंदर फूल काढ़ रही होगी"),
    ("The mountain river will be cascading with roar over the jagged black basalt boulders", "पहाड़ी नदी इस समय चट्टानों के ऊपर से तेज़ गर्जना के साथ नीचे गिर रही होगी"),
    ("The forest rangers will be tracking the pugmarks of the royal Bengal tiger carefully", "वन विभाग के कर्मचारी जंगल में बाघ के ताज़ा पदचिह्नों का पीछा कर रहे होंगे"),
    ("He must be composing a new patriotic anthem to celebrate our national sovereignty anniversary", "वह स्वतंत्रता दिवस के उपलक्ष्य में एक नया ओजस्वी देशभक्ति गीत लिख रहा होगा"),
    ("She will be baking fresh cinnamon pastries for the morning visitors to the cafe", "वह सुबह आने वाले ग्राहकों के लिए भट्टी में ताज़ा मीठी रोटियाँ पका रही होगी"),
    ("The students will be preparing diligently for their crucial competitive civil service entrance examinations", "विद्यार्थी इस समय प्रशासनिक सेवा की कठिन परीक्षा की तैयारी में जुटे होंगे"),
    ("The monks will be chanting sacred Sanskrit mantras in the mountain monastery temple hall", "बौद्ध भिक्षु इस समय पहाड़ी मठ के प्रांगण में पावन मंत्रों का पाठ कर रहे होंगे"),
    ("He must be steering his cargo truck through the winding foggy hill station roads", "वह इस समय कोहरे भरी संकरी पहाड़ी सड़कों पर अपना भारी ट्रक चला रहा होगा"),
    ("She will be examining the ancient archaeological pottery shards under the laboratory microscope carefully", "वह प्रयोगशाला में सूक्ष्मदर्शी से प्राचीन बर्तनों के टुकड़ों की जाँच कर रही होगी"),
    ("The sentinels will be watching the dark perimeter of the fortress for suspicious movements", "किले के बुर्जों पर तैनात पहरेदार अंधेरे में किसी भी हलचल पर नज़र रख रहे होंगे"),
    ("The migratory birds will be flying across the vast northern sky toward southern lakes", "विदेशी पक्षी इस समय दक्षिण की झीलों की ओर आकाश में उड़ान भर रहे होंगे"),
    ("He must be calculating the complex astrological chart for the royal coronation auspicious day", "राज ज्योतिषी राज्याभिषेक के शुभ मुहूर्त के लिए ग्रहों की गणना कर रहा होगा"),
    ("She will be collecting fragrant wildflowers from the sunny alpine valley to make remedies", "वह दवाइयाँ बनाने के लिए घाटी से तरह तरह के जंगली फूल चुन रही होगी"),
    ("The construction team will be pouring reinforced concrete for the foundation of the bridge", "इंजीनियरों का दल इस समय नदी के बड़े पुल की नींव में कंक्रीट भर रहा होगा"),
    ("The weavers will be dyeing cotton yarns in vibrant indigo and saffron wooden vats", "कारीगर लकड़ी के बड़े हौदों में सूत के धागों को गहरे रंगों में रंग रहे होंगे"),
    ("He must be inspecting the agricultural grain storehouses to protect against damp and pests", "वह अनाज को कीड़ों और सीलन से बचाने के लिए गोदामों का निरीक्षण कर रहा होगा"),
    ("She will be playing the bamboo flute in the quiet garden under the moonlight", "वह चाँदनी रात में बगीचे में बैठकर बहुत सुरीली बांसुरी बजा रही होगी"),
    ("The rescue team will be clearing the heavy snow avalanche debris from the road", "राहत दल इस समय सड़क से बर्फ़ीले तूफान का मलबा हटाने का काम कर रहा होगा"),
    ("The judges will be deliberating upon the complex constitutional questions in their private chambers", "न्यायाधीश अपने कक्ष में बैठकर संविधान के इस गंभीर प्रश्न पर विचार कर रहे होंगे"),

    # 121-160: Contrafactual Continuous (रहा होता / रही होती)
    ("If he had been studying diligently he would have passed the examination with honors", "अगर वह लगन से पढ़ रहा होता तो परीक्षा में प्रथम श्रेणी से उत्तीर्ण हो जाता"),
    ("If she had been driving carefully she would not have collided with the stone", "अगर वह ध्यान से गाड़ी चला रही होती तो पत्थर से कभी न टकराती"),
    ("If they had been guarding the border vigilantly the infiltrators could never have crossed", "अगर वे सीमा पर सतर्क पहरा दे रहे होते तो घुसपैठिए कभी पार न कर पाते"),
    ("If you had been listening to my advice you would not be suffering now", "अगर तुम मेरी बात ध्यान से सुन रहे होते तो आज इस संकट में न पड़ते"),
    ("If I had been working in the capital I would have met the foreign ambassadors", "अगर मैं राजधानी में काम कर रहा होता तो विदेशी राजदूतों से अवश्य मिलता"),
    ("If the rain had been falling regularly our crops would not have withered away", "अगर समय पर बारिश हो रही होती तो हमारी फसलें कभी सूखकर नष्ट न होतीं"),
    ("If the doctor had been attending the patient immediately the tragedy might have been averted", "अगर डॉक्टर तुरंत मरीज की देखभाल कर रहा होता तो अनहोनी को टाला जा सकता था"),
    ("If she had been practicing archery daily she would have won the golden trophy easily", "अगर वह रोज़ तीरंदाज़ी का अभ्यास कर रही होती तो स्वर्ण पदक आसानी से जीत जाती"),
    ("If the soldiers had been watching the narrow gorge the enemy could not ambush", "अगर सैनिक दर्रे पर नज़र रख रहे होते तो शत्रु कभी अचानक हमला न कर पाता"),
    ("If he had been speaking the truth from the beginning everyone would have trusted him", "अगर वह शुरू से सच बोल रहा होता तो आज सब उस पर भरोसा करते"),
    ("If the wind had been blowing from the west the fire would have spread", "अगर हवा पश्चिम से बह रही होती तो आग पूरे जंगल में फैल जाती"),
    ("If you had been saving your hard earned money you would not be in debt", "अगर तुम अपनी गाढ़ी कमाई बचा रहे होते तो आज कर्ज़ में न डूबे होते"),
    ("If she had been cultivating the fertile garden it would not be covered with weeds", "अगर वह बगीचे की देखभाल कर रही होती तो उसमें काँटेदार झाड़ियाँ न उगतीं"),
    ("If they had been repairing the dyke properly the river would not have flooded village", "अगर वे बाँध की ठीक से मरम्मत कर रहे होते तो गाँव में बाढ़ का पानी न घुसता"),
    ("If I had been traveling with the royal caravan I would have seen the monuments", "अगर मैं शाही काफिले के साथ चल रहा होता तो वे ऐतिहासिक स्थल ज़रूर देखता"),
    ("If the mechanic had been inspecting the aircraft engine the defect would have surfaced", "अगर मिस्त्री विमान के इंजन की जाँच कर रहा होता तो खराबी पहले ही दिख जाती"),
    ("If she had been learning the craft from master she would have excelled today", "अगर वह उस्ताद से काम सीख रही होती तो आज उसकी कला की प्रशंसा होती"),
    ("If he had been managing his business accounts honestly his firm would have flourished", "अगर वह अपने व्यापार का हिसाब ईमानदारी से रख रहा होता तो कंपनी कभी न डूबती"),
    ("If you had been paying attention to the road signs you would not have lost way", "अगर तुम सड़क के संकेतों को देख रहे होते तो कभी रास्ता न भटकते"),
    ("If the watchman had been staying awake the thieves could never have broken safe", "अगर चौकीदार जाग रहा होता तो चोर तिजोरी को कभी हाथ न लगा पाते"),
    ("If she had been writing regularly her historical novel would have been published by now", "अगर वह रोज़ लिख रही होती तो उसका ऐतिहासिक उपन्यास अब तक छप चुका होता"),
    ("If they had been cooperating with unity the dispute would have been settled peacefully", "अगर वे आपस में मिलकर काम कर रहे होते तो विवाद कब का सुलझ गया होता"),
    ("If I had been living in the quiet mountain valley my health would be better", "अगर मैं शांत पहाड़ी घाटी में रह रहा होता तो मेरा स्वास्थ्य कहीं बेहतर होता"),
    ("If he had been following the doctor dietary advice his fever would have subsided", "अगर वह परहेज़ के नियमों का पालन कर रहा होता तो बुखार कब का उतर चुका होता"),
    ("If the bridge had been supporting the heavy weight it would not have cracked", "अगर पुल इतना भारी वजन सह रहा होता तो उसमें कभी दरार न आती"),
    ("If she had been teaching the children with patience they would have understood arithmetic", "अगर वह बच्चों को धैर्य से पढ़ा रही होती तो वे गणित जल्दी समझ जाते"),
    ("If you had been steering the boat toward shore we would not be stranded", "अगर तुम नाव को किनारे की ओर ले जा रहे होते तो हम बीच मझधार में न फँसते"),
    ("If they had been planting fruit trees every year the orchard would be abundant", "अगर वे हर साल नए पौधे लगा रहे होते तो आज बगीचा फलों से लदा होता"),
    ("If the scouts had been tracking the enemy movements our battalion would be prepared", "अगर दूत शत्रु की हर हरकत पर नज़र रख रहे होते तो हमारी सेना तैयार रहती"),
    ("If she had been wearing her warm woolen cloak she would not feel cold", "अगर उसने अपनी गर्म शॉल ओढ़ रखी होती तो उसे इतनी ठंड न लगती"),
    ("If he had been preserving his strength he would have run the whole marathon", "अगर वह अपनी ताकत बचाकर दौड़ रहा होता तो पूरी दौड़ आसानी से पूरी कर लेता"),
    ("If you had been watering the young sapling daily it would be blooming today", "अगर तुम उस छोटे पौधे को रोज़ पानी दे रहे होते तो आज उसमें फूल खिलते"),
    ("If the committee had been reviewing the petitions the injustice would have been corrected", "अगर समिति शिकायतों पर ध्यान दे रही होती तो अन्याय कब का दूर हो जाता"),
    ("If she had been singing with full heart the audience would have been moved", "अगर वह पूरे मन से गा रही होती तो श्रोताओं की आँखों में आँसू आ जाते"),
    ("If I had been maintaining the vintage car engine it would run smoothly now", "अगर मैं पुरानी गाड़ी के इंजन की देखभाल कर रहा होता तो वह आज भी चलती"),
    ("If they had been weaving during daylight they would have finished the royal carpet", "अगर वे दिन के उजाले में काम कर रहे होते तो कालीन समय पर पूरा हो जाता"),
    ("If he had been standing guard at the gate no stranger could enter courtyard", "अगर वह दरवाज़े पर पहरा दे रहा होता तो कोई अजनबी आँगन में न घुस पाता"),
    ("If she had been cooking on gentle flame the milk would not have burned", "अगर वह धीमी आँच पर पका रही होती तो दूध कभी जलकर कड़ाही में न चिपकता"),
    ("If you had been climbing with caution you would not have slipped on ice", "अगर तुम सावधानी से चढ़ रहे होते तो बर्फ़ पर तुम्हारा पैर कभी न फिसलता"),
    ("If everyone had been fulfilling their moral duties our society would be completely peaceful", "अगर हर व्यक्ति अपने कर्तव्यों का पालन कर रहा होता तो समाज में पूर्ण शांति होती"),

    # 161-200: Stative Continuous (बैठा है, खड़ा है, लेटा है, सोया है, पहने हुए है)
    ("The venerable old sage is sitting quietly under the shade of ancient banyan tree", "वृद्ध महात्मा विशाल बरगद के पेड़ की शीतल छाँव में शांत भाव से बैठे हैं"),
    ("The patient mother is sitting beside the bed of her ailing young daughter", "माँ अपनी बीमार बेटी के बिस्तर के पास बहुत प्यार से बैठी है"),
    ("The brave palace sentinel is standing alert at the grand entrance of the fortress", "साहसी पहरेदार किले के मुख्य द्वार पर हाथ में भाला लिए सतर्क खड़ा है"),
    ("The majestic marble pillar is standing firm despite centuries of earthquakes and storms", "संगमरमर का विशाल खंभा सदियों के तूफानों के बावजूद अपनी जगह पर अडिग खड़ा है"),
    ("The exhausted mountain traveler is lying upon the soft green grass of meadow", "थका हुआ पर्वतारोही हरे मैदान की कोमल घास पर आँखें मूँदकर लेटा है"),
    ("The sick old farmer is lying quietly on the wooden cot inside cottage", "बीमार किसान अपनी कुटिया के भीतर लकड़ी की चारपाई पर चुपचाप लेटा है"),
    ("The innocent newborn infant is sleeping peacefully in the hand woven wicker cradle", "नवजात शिशु हाथ से बुने हुए सुंदर पालने में गहरी और मीठी नींद सोया है"),
    ("The faithful pet watchdog is sleeping near the threshold of the family kitchen", "वफादार कुत्ता रसोई की चौखट के पास ज़मीन पर अपना सिर रखकर सोया है"),
    ("The royal prince is wearing an exquisite robe of golden silk and jewels", "राजकुमार सुनहरे रेशम और बहुमूल्य रत्नों से जड़ा हुआ भव्य चोगा पहने हुए है"),
    ("The modest village bride is wearing a red veil embroidered with silver threads", "गाँव की नई दुल्हन चाँदी के तारों से कढ़ा हुआ सुंदर लाल घूँघट ओढ़े हुए है"),
    ("The thoughtful philosopher is sitting on the stone ledge gazing at the sunset", "दार्शनिक पत्थर की मुंडेर पर बैठकर ढलते हुए सूरज को ध्यान से देख रहा है"),
    ("The weary beggar is sitting beside the busy highway with an empty bowl", "थका हुआ भिक्षुक सड़क के किनारे अपना खाली कटोरा आगे रखकर बैठा है"),
    ("The tall pine trees are standing like silent sentinels along the mountain ridge", "चीड़ के ऊँचे पेड़ पहाड़ी पर किसी शांत पहरेदार की तरह सीधे खड़े हैं"),
    ("The great bronze statue of the national hero is standing in city square", "राष्ट्रीय नायक की काँसे की विशाल प्रतिमा नगर के चौराहे पर गर्व से खड़ी है"),
    ("The wounded soldier is lying on the stretcher inside the emergency field hospital", "घायल सिपाही सेना के अस्पताल में स्ट्रेचर पर शांति से लेटा है"),
    ("The playful puppy is lying on the warm sunlit flagstones of the courtyard", "छोटा पिल्ला आँगन के धूप से तपे पत्थरों पर आराम से लेटा है"),
    ("The tired laborer is sleeping soundly under the cool shade of the neem", "थका हुआ मजदूर नीम के पेड़ की ठंडी छाँव में बेखबर सोया है"),
    ("The golden cat is sleeping curled up upon the soft velvet cushion chair", "सुनहरी बिल्ली मखमली गद्दे पर गोल होकर बहुत सुकून से सोई है"),
    ("The venerable high priest is wearing pure white unstitched sacred garments for ritual", "मंदिर के मुख्य पुजारी पूजा के लिए शुद्ध सफेद धोती और उत्तरीय पहने हुए हैं"),
    ("The brave warrior is wearing an impenetrable coat of steel chain mail armor", "वीर योद्धा युद्ध के लिए लोहे की मजबूत जिरहबख्तर पहने हुए है"),
    ("The little girl is sitting on her father shoulders to see the festival", "छोटी बच्ची मेला देखने के लिए अपने पिता के कंधों पर बैठी है"),
    ("The flock of white pigeons is sitting upon the tiled roof of temple", "सफेद कबूतरों का झुंड मंदिर की खपरैल वाली छत पर शांति से बैठा है"),
    ("The ancient tower is standing tall against the blue horizon of historical city", "ऐतिहासिक मीनार नीले आकाश के सामने सदियों से सीना ताने खड़ी है"),
    ("The flag bearer is standing motionless with the national tricolor in his hand", "ध्वजवाहक अपने हाथों में तिरंगा झंडा थामे मंच के पास अडिग खड़ा है"),
    ("The traveler is lying in the hammock strung between two shady mango trees", "यात्री दो आम के पेड़ों के बीच बँधे झूले पर आराम से लेटा है"),
    ("The cat is lying motionless near the mouse hole waiting for its prey", "बिल्ली चूहे के बिल के पास बिना हिले डुले चुपचाप लेटी है"),
    ("The child is sleeping wrapped warmly in a colorful handmade wool patchwork quilt", "बच्चा रंग बिरंगी रज़ाई में लिपटकर सर्दी की रात में चैन से सोया है"),
    ("The entire household is sleeping soundly while the cool midnight breeze blows softly", "रात के समय जब ठंडी बयार बह रही है तब पूरा घर गहरी नींद में सोया है"),
    ("The chief justice is wearing black judicial robes with spotless white collar bands", "न्यायाधीश अदालत में अपना पारंपरिक काला चोगा और सफेद पट्टियाँ पहने हुए हैं"),
    ("The young graduate is wearing an academic black gown and ceremonial square cap", "स्नातक छात्र दीक्षांत समारोह में अपना काला गाउन और चौकोर टोपी पहने हुए है"),
    ("The village elder is sitting on the rope cot smoking traditional hookah pipe", "गाँव के बुजुर्ग चौपाल की चारपाई पर बैठकर तसल्ली से हुक्का गुड़गुड़ा रहे हैं"),
    ("The vulture is sitting high on the dead dry branch of oak", "गिद्ध सूखे पेड़ की सबसे ऊँची डाल पर बैठकर नीचे नज़र गड़ाए बैठा है"),
    ("The lighthouse is standing firm amidst the crashing waves of the stormy ocean", "प्रकाश स्तंभ तूफानी समुद्र की उठती लहरों के बीच चट्टान पर मजबूती से खड़ा है"),
    ("The schoolboy is standing on the bench as punishment for talking in class", "कक्षा में बात करने के दंड स्वरूप छात्र बेंच पर दोनों कान पकड़कर खड़ा है"),
    ("The tired mountaineer is lying in his warm thermal sleeping bag inside tent", "पर्वतारोही बर्फ़ीले तूफान के बीच तंबू के अंदर अपने स्लीपिंग बैग में लेटा है"),
    ("The tiger is lying in the tall golden grass waiting for its moment", "बाघ शिकार की प्रतीक्षा में घनी घास के बीच ज़मीन से सटकर लेटा है"),
    ("The baby is sleeping with a sweet innocent smile upon its rosy lips", "दूधमुहाँ बच्चा अपने होठों पर प्यारी मुस्कान लिए माँ की गोद में सोया है"),
    ("The forest is sleeping under the serene silver canopy of the midnight moon", "चाँदनी रात में पूरा घना जंगल एक शांत और गहरी नींद में सोया है"),
    ("The elegant lady is wearing a string of lustrous pearls around her neck", "सभ्य महिला अपने गले में चमकीले मोतियों की सुंदर माला पहने हुए है"),
    ("The brave commander is wearing a shining steel helmet crested with golden plumes", "सेनापति अपने सिर पर सुनहरे पंखों से सजा हुआ लोहे का चमकीला टोप पहने हुए है"),
]

if __name__ == "__main__":
    process_batch(34, "p34s", PAIRS)
