#!/usr/bin/env python3
"""Batch VT-05: Causatives, Modals, Moods & Impersonal Bhavavachya (200 sentences).
File: data/phrases37.json, IDs: p37s001..p37s200.
Themes:
- Primary & Secondary Causatives (करना -> कराना -> करवाना, लिखना -> लिखाना -> लिखवाना, धोना -> धुलाना -> धुलवाना, सिलना -> सिलाना -> सिलवाना)
- Modals of Ability (सकना), Opportunity (पाना)
- Obligation (चाहिए, पड़ना, होना with dative subject)
- Subjunctive Mood (संभाव्य पक्ष: अगर वह आए तो, शायद हम चलें)
- Passive with जाना & Impersonal Bhavavachya (भाववाच्य: मुझसे चला नहीं जाता, उससे बोला नहीं गया)
"""
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parent))
from gen_batches_pipeline import process_batch

PAIRS = [
    # 1-45: Causatives - Prathama & Dvitiya (कराना, करवाना, लिखाना, लिखवाना, सिलाना, सिलवाना, धुलाना, धुलवाना, आदि)
    ("The wealthy merchant had a grand marble palace built by the royal architect", "धनी व्यापारी ने शाही वास्तुकार से एक भव्य संगमरमर का महल बनवाया"),
    ("The caring mother makes her little children drink warm turmeric milk every morning", "स्नेही माँ रोज़ सुबह अपने नन्हे बच्चों को हल्दी वाला गरम दूध पिलाती है"),
    ("The kind grandfather had a new set of warm clothes stitched for the orphan", "दयालु दादाजी ने दर्जी से अनाथ बालक के लिए नए गर्म कपड़े सिलवाए"),
    ("The strict schoolmaster made the careless student write the difficult poem ten times", "कड़े शिक्षक ने लापरवाह छात्र से उस कठिन कविता को दस बार लिखवाया"),
    ("The landowner got his vast agricultural fields plowed by twenty hired tractor drivers", "ज़मींदार ने किराए के ट्रैक्टरों से अपने विशाल खेतों की जुताई करवाई"),
    ("The queen had delicious sweet festive delicacies prepared for all the palace guests", "महारानी ने राजमहल के रसोइयों से सभी अतिथियों के लिए स्वादिष्ट पकवान बनवाए"),
    ("The kind lady had all the dirty blankets washed before donating them to shelter", "दयालु महिला ने आश्रम में देने से पहले सभी पुराने कंबलों को धुलवाया"),
    ("The general had a deep defensive trench dug along the vulnerable northern border", "सेनापति ने सीमा की रक्षा के लिए मजदूरों से एक गहरी खाई खुदवाई"),
    ("The father made his young son practice classical violin three hours every day", "पिताजी रोज़ शाम को अपने बेटे से वायलिन का कठिन अभ्यास कराते हैं"),
    ("The director had the historic play rehearsed fifty times before the public premiere", "निर्देशक ने जनता के सामने मंचन से पहले कलाकारों से पचास बार नाटक का अभ्यास करवाया"),
    ("The merchant got the heavy sacks of wheat loaded onto the cargo carts", "व्यापारी ने पल्लेदारों से गेहूँ की भारी बोरियाँ गाड़ियों पर लदवाईं"),
    ("The caring sister feeds delicious warm vegetable soup to her ailing younger brother", "बड़ी बहन अपने बीमार छोटे भाई को चम्मच से गरम सूप पिलाती है"),
    ("The king had fifty stone stepwells excavated along the dry desert trade highway", "राजा ने रेगिस्तान के व्यापारिक मार्ग पर यात्रियों के लिए पचास बावडियाँ खुदवाईं"),
    ("The school headmistress had all the classroom furniture repaired and painted in summer", "प्रधानाचार्या ने छुट्टियों के दौरान बढ़ई से स्कूल की सभी मेज़ों की मरम्मत करवाई"),
    ("The farmer gets his dairy cows milked by the experienced milkman every dawn", "किसान रोज़ सुबह अनुभवी ग्वाले से अपनी सभी दुधारू गायों को दुहवाता है"),
    ("The doctor made the sick patient walk a short distance in the garden", "चिकित्सक ने स्वास्थ्य लाभ के लिए मरीज को बगीचे में थोड़ा टहलाया"),
    ("The author had his epic manuscript translated into five classical European foreign tongues", "लेखक ने अपने महाकाव्य का अनुवाद कुशल विद्वानों से कई भाषाओं में करवाया"),
    ("The village elder had a sturdy stone bridge constructed across the mountain torrent", "गाँव के मुखिया ने राजमिस्त्रियों से पहाड़ी नदी पर पत्थर का मजबूत पुल बनवाया"),
    ("The caring mother got her daughter hair oiled and braided neatly for school", "माँ ने सुबह स्कूल जाने से पहले बेटी के बालों में तेल लगाकर चोटी बनवाई"),
    ("The forest ranger had the injured leopard cub treated at the veterinary hospital", "वनरक्षक ने पशु चिकित्सालय के डॉक्टरों से घायल तेंदुए के बच्चे का इलाज करवाया"),
    ("The contractor gets the multi storey commercial building painted by professional skilled painters", "ठेकेदार कुशल कारीगरों से पूरे व्यावसायिक भवन की रंगाई पुताई करवाता है"),
    ("The grandmother makes her little granddaughter recite ancient Sanskrit verses with correct intonation", "दादी अपनी नन्हीं पोती से बहुत शुद्ध उच्चारण के साथ श्लोकों का पाठ कराती हैं"),
    ("The captain had the damaged canvas sails replaced before the long ocean voyage", "कप्तान ने लंबी समुद्री यात्रा से पहले जहाज़ के सभी फटे पालों को बदलवाया"),
    ("The philanthropist had five hundred warm blankets distributed among the homeless street destitute", "परोपकारी सज्जन ने स्वयंसेवकों के माध्यम से बेसहारा लोगों में कंबल बँटवाए"),
    ("The editor made the young reporter rewrite the entire investigative article with evidence", "संपादक ने युवा पत्रकार से पूरे खोजी लेख को दोबारा नए तथ्यों के साथ लिखवाया"),
    ("The lady had her ancestral gold ornaments polished at the traditional jewelry workshop", "महिला ने सुनार की दुकान पर ले जाकर अपने पुश्तैनी गहनों की सफाई करवाई"),
    ("The gardener gets the overgrown lawn grass trimmed by the young apprentice assistant", "माली अपने सहायक से बगीचे की बढ़ी हुई घास की कटाई करवाता है"),
    ("The teacher made the quiet children sing the national patriotic anthem with enthusiasm", "शिक्षिका ने सभी संकोची बच्चों से मिलकर पूरे उत्साह से राष्ट्रगान गवाया"),
    ("The royal preceptor had the young princes instructed in classical statecraft and diplomacy", "कुलगुरु ने योग्य विद्वानों से युवा राजकुमारों को राजनीति और कूटनीति की शिक्षा दिलवाई"),
    ("The landlord had the leaking tiled roof of the village school completely repaired", "ज़मींदार ने मिस्त्रियों को बुलाकर गाँव के स्कूल की टपकती छत ठीक करवाई"),
    ("The mother got warm woolen socks knitted for all her five little children", "माँ ने सर्दियों के लिए अपनी सहेली से बच्चों के लिए ऊनी मोज़े बनवाए"),
    ("The wise judge had the complex legal document explained to the illiterate petitioner", "न्यायाधीश ने अपने सहायक से उस सीधे फरियादी को कानूनी बात समझवाई"),
    ("The merchant gets the storehouse disinfected every spring to prevent grain spoilage pests", "व्यापारी हर साल अनाज को सुरक्षित रखने के लिए गोदाम में कीटनाशक का छिड़काव करवाता है"),
    ("The officer made the recruits run ten miles with heavy backpacks at dawn", "अधिकारी ने सुबह सवेरे सभी रंगरूटों से भारी बस्ते लेकर दस मील की दौड़ लगवाई"),
    ("The lady had a beautiful marble water fountain installed in the private courtyard", "महिला ने अपने निजी आँगन में कारीगरों से संगमरमर का एक सुंदर फव्वारा लगवाया"),
    ("The father makes his daughter solve three difficult arithmetic puzzles before evening dinner", "पिताजी रोज़ शाम के भोजन से पहले अपनी बेटी से गणित के तीन कठिन सवाल हल करवाते हैं"),
    ("The temple committee had the grand bronze temple bell recast by traditional metallurgists", "मंदिर समिति ने पीतल के कारीगरों से विशाल घंटे को दोबारा ढलवाया"),
    ("The doctor had the blood samples tested at the regional central pathological laboratory", "चिकित्सक ने प्रयोगशाला के विशेषज्ञों से मरीज के खून की जाँच करवाई"),
    ("The farmer gets the ripe golden wheat threshed by the modern mechanical machine", "किसान आधुनिक मशीन के माध्यम से अपने खेत के पूरे गेहूँ की गहाई करवाता है"),
    ("The headmaster had the entire school compound cleaned by all students on Saturday", "प्रधानाचार्य ने शनिवार को स्वच्छता अभियान के तहत पूरे विद्यालय प्रांगण की सफाई करवाई"),
    ("The queen had an intricate gold embroidered tapestry woven for the ceremonial hall", "महारानी ने कुशल बुनकरों से दीवानखाने के लिए ज़री का सुंदर परदा तैयार करवाया"),
    ("The mother makes the baby sleep by singing a sweet gentle bedtime lullaby", "माँ बहुत मीठी लोरी गाकर अपने नन्हे बच्चे को प्यार से सुलाती है"),
    ("The contractor had the asphalt road resurfaced before the heavy monsoon rains arrived", "ठेकेदार ने बरसात शुरू होने से पहले ही सड़क पर डामर की नई परत बिछवाई"),
    ("The scholar had his rare research notes photocopied and preserved in steel vault", "विद्वान ने अपने दुर्लभ शोध पत्रों की नकल करवाकर उन्हें सुरक्षित रखवाया"),
    ("The village community got a large earthen check dam built through voluntary labor", "गाँव वालों ने श्रमदान के माध्यम से नदी पर एक मजबूत कच्चा बाँध बनवाया"),

    # 46-85: Modals of Ability (सकना) & Opportunity (पाना)
    ("The courageous young athlete can run forty kilometers without showing any severe fatigue", "साहसी युवा धावक बिना थके चालीस किलोमीटर तक लगातार दौड़ सकता है"),
    ("The experienced mountain guide can predict sudden changes in high alpine weather accurately", "अनुभवी पहाड़ी गाइड मौसम के अचानक बदलने का बिल्कुल सही अनुमान लगा सकता है"),
    ("I can speak four classical and modern Indian languages with complete native fluency", "मैं पूरी धाराप्रवाह गति के साथ चार भारतीय भाषाएँ आसानी से बोल सकता हूँ"),
    ("She can play the difficult classical sitar compositions with extraordinary musical melodic sensitivity", "वह सितार पर शास्त्रीय संगीत के कठिन से कठिन राग बहुत सुंदरता से बजा सकती है"),
    ("We could not cross the swollen mountain river because the bridge had collapsed", "पुल टूट जाने के कारण हम उफनती हुई पहाड़ी नदी को पार नहीं कर सके"),
    ("Due to heavy snow blizzards the relief helicopters could not land at base", "भीषण बर्फ़ीले तूफान के कारण राहत दल के विमान हवाई पट्टी पर नहीं उतर सके"),
    ("The little girl could not find her lost kitten despite searching all afternoon", "दोपहर भर ढूँढने के बाद भी वह छोटी बच्ची अपनी खोई हुई बिल्ली को नहीं पा सकी"),
    ("After months of rigorous physical therapy the injured soldier could walk without crutches", "महीनों के उपचार के बाद घायल सिपाही बिना बैसाखी के अपने पैरों पर चल सका"),
    ("Can you explain the intricate philosophical meaning of this ancient Sanskrit couplet clearly", "क्या तुम इस प्राचीन संस्कृत श्लोक का गहरा अर्थ मुझे विस्तार से समझा सकते हो"),
    ("Nobody can challenge the absolute unblemished integrity and honesty of our high court judge", "हमारे उच्च न्यायालय के न्यायाधीश की निष्पक्षता और ईमानदारी पर कोई उँगली नहीं उठा सकता"),
    ("I could not meet the honorable prime minister because the appointment was canceled suddenly", "अचानक बैठक रद्द होने के कारण मैं प्रधानमंत्री जी से व्यक्तिगत रूप से नहीं मिल सका"),
    ("She could not complete her doctoral thesis in time due to prolonged medical illness", "लंबे समय तक बीमार रहने के कारण वह अपना शोध ग्रंथ समय पर पूरा नहीं कर सकी"),
    ("With persistent diligent effort anyone can overcome the most formidable and daunting obstacles", "निरंतर और सच्चे प्रयास से कोई भी मनुष्य बड़ी से बड़ी बाधा को पार कर सकता है"),
    ("The ancient mariners could navigate the vast open oceans by observing stellar constellations", "प्राचीन नाविक रात के आकाश में तारों की स्थिति देखकर दिशा का सही ज्ञान पा सकते थे"),
    ("We could not attend the grand wedding celebration because of the sudden railway strike", "रेलगाड़ियों के बंद होने के कारण हम उस भव्य विवाह समारोह में शामिल नहीं हो सके"),
    ("He could not sleep throughout the turbulent stormy night due to severe tooth pain", "दाँत में असहनीय दर्द होने के कारण वह रात भर चैन से नहीं सो सका"),
    ("Can a mother ever forget the tender and innocent laughter of her child", "क्या कोई स्नेही माँ अपने नन्हे बच्चे की भोली मुस्कान को कभी भूल सकती है"),
    ("The keen eyed eagle can spot a tiny field mouse from high clouds", "तेज़ नज़र वाला बाज़ बादलों की ऊँचाई से भी ज़मीन पर दौड़ते चूहे को देख सकता है"),
    ("I could not visit my ancestral village this autumn owing to pressing professional duties", "काम की अधिकता के कारण मैं इस साल अपने पुश्तैनी गाँव नहीं जा सका"),
    ("She could not secure the coveted government scholarship despite securing first rank in test", "परीक्षा में अव्वल आने के बाद भी वह कुछ तकनीकी कारणों से छात्रवृत्ति नहीं पा सकी"),
    ("Only a truly selfless and courageous human being can sacrifice personal comfort for nation", "केवल एक सच्चा और निःस्वार्थ देशभक्त ही राष्ट्र के लिए अपने सुखों का त्याग कर सकता है"),
    ("The skilled watchmaker can repair the most delicate and complicated mechanical timepiece gears", "कुशल घड़ीसाज़ सबसे बारीक और जटिल घड़ियों के कलपुर्जों को भी ठीक कर सकता है"),
    ("We could not hear the quiet speech of the speaker above the noisy crowd", "भीड़ के भारी शोरगुल के कारण हम मंच से बोले गए वक्ता के शब्द नहीं सुन सके"),
    ("He could not hide his profound emotional joy upon receiving the prestigious national award", "सम्मान प्राप्त करते समय वह अपनी आँखों से छलकती खुशी को छिपा नहीं सका"),
    ("Can true enduring friendship be purchased in any commercial marketplace with bags of gold", "क्या सच्ची और स्थायी मित्रता को दुनिया के किसी बाज़ार से सोने के बल पर खरीदा जा सकता है"),
    ("The blind musician can distinguish between thirty subtle microtonal musical notes with ease", "दृष्टिहीन संगीतकार संगीत के सबसे बारीक सुरों के अंतर को भी आसानी से पहचान सकता है"),
    ("I could not decipher the faded inscriptions carved upon the ancient weathered stone pillar", "धूप और बारिश से घिसे हुए उस प्राचीन शिलालेख के अक्षरों को मैं ठीक से नहीं पढ़ सका"),
    ("She could not control her sorrow and burst into tears at the sad news", "दुखद समाचार सुनते ही वह अपने मन के दर्द को संभाल नहीं सकी और रो पड़ी"),
    ("Human beings can achieve remarkable spiritual greatness through continuous meditation and ethical self control", "सच्चे संयम और साधना के बल पर मनुष्य आत्मिक उन्नति के सर्वोच्च शिखर को छू सकता है"),
    ("The swift hunting cheetah can sprint at hundred kilometers per hour across open savanna", "शिकारी चीता खुले मैदान में सौ किलोमीटर प्रति घंटे की गति से दौड़ सकता है"),
    ("We could not reach the mountain summit before the dangerous sunset mist rolled in", "शाम का घना कोहरा घिरने से पहले हम पर्वत की मुख्य चोटी तक नहीं पहुँच सके"),
    ("He could not repay the heavy financial loan within the strict stipulated bank timeline", "तय समय सीमा के भीतर वह बैंक का भारी कर्ज़ किसी भी तरह नहीं चुका सका"),
    ("Can an unjust tyrant ever sleep with peaceful serenity in his fortified royal palace", "क्या कोई क्रूर अत्याचारी अपने पहरेदारों के बीच भी कभी चैन की नींद सो सकता है"),
    ("The master archer can split a willow wand from distance of hundred paces effortlessly", "सच्चा धनुर्धर सौ कदम की दूरी से भी पेड़ की पतली टहनी को अपने तीर से बींध सकता है"),
    ("I could not believe my own eyes when I saw the legendary ancient city", "जब मैंने उस प्राचीन नगर के भव्य खंडहर देखे तो मुझे अपनी आँखों पर विश्वास नहीं हो सका"),
    ("She could not hold back her righteous indignation against the rampant municipal bureaucratic corruption", "प्रशासन के खुले भ्रष्टाचार को देखकर वह अपने मन के तीव्र आक्रोश को दबा नहीं सकी"),
    ("A peaceful mind can discover solutions to problems that rage and anger only aggravate", "एक शांत और स्थिर मन उन समस्याओं का हल ढूँढ सकता है जिन्हें क्रोध और उलझा देता है"),
    ("The skilled diver can hold his breath underwater for five whole minutes safely", "कुशल गोताखोर पानी के भीतर पाँच मिनट तक बिना साँस लिए आसानी से रह सकता है"),
    ("We could not find single drop of fresh drinking water in that desolate desert", "उस सूखे और बंजर रेगिस्तान में हमें पीने के पानी की एक बूँद भी नहीं मिल सकी"),
    ("He could not finish the marathon race because of a painful sudden muscle sprain", "पैर की नस खिंच जाने के कारण वह उस लंबी दौड़ को पूरा नहीं कर सका"),

    # 86-125: Obligation & Necessity (चाहिए, पड़ना, होना with dative subject: मुझे जाना पड़ा, तुम्हें करना चाहिए)
    ("Every citizen ought to respect the sovereign constitution and national symbols of our republic", "हर नागरिक को अपने देश के संविधान और राष्ट्रीय प्रतीकों का सच्चा आदर करना चाहिए"),
    ("We should always speak the truth gently and never utter words that wound hearts", "हमें हमेशा सच बोलना चाहिए और ऐसी वाणी कभी नहीं बोलनी चाहिए जो दूसरों का दिल दुखाए"),
    ("You ought to help the poor and needy people residing in your immediate neighborhood", "तुम्हें अपने आस पास रहने वाले निर्धन और असहाय लोगों की सहायता अवश्य करनी चाहिए"),
    ("One should never betray the sacred trust reposed by an innocent and honest friend", "किसी सच्चे और विश्वासपात्र मित्र के साथ कभी कोई छल या विश्वासघात नहीं करना चाहिए"),
    ("Students must study with focused dedication to build a prosperous and enlightened modern society", "छात्रों को एक बेहतर समाज के निर्माण के लिए पूरे मन से विद्या का अध्ययन करना चाहिए"),
    ("I had to walk twenty kilometers on foot because the passenger bus broke down", "बस खराब हो जाने के कारण मुझे बीस किलोमीटर पैदल चलकर अपने गंतव्य तक जाना पड़ा"),
    ("The poor farmer had to sell his only pair of draft bullocks to survive", "अकाल के दिनों में पेट भरने के लिए गरीब किसान को अपने दोनों बैल बेचने पड़े"),
    ("The honest clerk had to resign from his lucrative post to preserve his integrity", "अपने स्वाभिमान की रक्षा के लिए उस ईमानदार बाबू को अपनी अच्छी नौकरी छोड़नी पड़ी"),
    ("We had to wait for five hours at the station due to heavy fog", "घने कोहरे के कारण हमें रेलवे स्टेशन पर पाँच घंटे तक गाड़ी का इंतज़ार करना पड़ा"),
    ("She had to cancel her foreign academic research trip owing to her mother illness", "माताजी की बीमारी के कारण उसे अपनी विदेश यात्रा का कार्यक्रम अचानक रद्द करना पड़ा"),
    ("You have to submit all your verified academic credentials to the university admission board", "तुम्हें प्रवेश पाने के लिए अपने सभी प्रमाण पत्र विश्वविद्यालय के कार्यालय में जमा करने होंगे"),
    ("The government has to construct durable stone embankments along the flood prone river banks", "बाढ़ को रोकने के लिए सरकार को नदी के किनारे मजबूत पक्के बाँध बनाने होंगे"),
    ("I have to complete this comprehensive financial audit report before the fiscal year ends", "साल खत्म होने से पहले मुझे यह पूरा वित्तीय हिसाब किताब तैयार करके देना है"),
    ("Every driver has to obey all traffic regulations strictly to ensure road passenger safety", "सड़क पर सुरक्षा बनाए रखने के लिए हर चालक को यातायात के नियमों का पालन करना होता है"),
    ("We have to preserve the rich biodiversity of our ancient virgin Himalayan temperate forests", "हमें अपने जंगलों और नदियों के प्राकृतिक सौंदर्य की रक्षा के लिए कड़े कदम उठाने होंगे"),
    ("The wounded soldier had to endure painful surgery without any modern anesthetic medical drugs", "घायल सिपाही को बिना किसी दर्द निवारक दवा के कठिन ऑपरेशन का कष्ट सहना पड़ा"),
    ("The merchant had to declare bankruptcy when his ocean cargo ship sank in storm", "तूफान में मालवाहक जहाज़ डूब जाने से व्यापारी को खुद को दीवालिया घोषित करना पड़ा"),
    ("The children had to study under the streetlamp when the village transformer blew up", "गाँव में बिजली गुल होने पर बच्चों को सड़क की बत्ती के नीचे बैठकर पढ़ना पड़ा"),
    ("She had to leave her ancestral homeland due to severe political unrest and violence", "युद्ध के भड़कने के कारण उस परिवार को अपना पुश्तैनी घर बार छोड़कर भागना पड़ा"),
    ("The doctor had to perform an emergency caesarean operation to save mother and child", "माँ और बच्चे की जान बचाने के लिए डॉक्टर को तुरंत बड़ा ऑपरेशन करना पड़ा"),
    ("One ought to exercise daily in the fresh morning air to maintain physical health", "अपने शरीर को निरोगी रखने के लिए हर व्यक्ति को रोज़ सुबह खुली हवा में व्यायाम करना चाहिए"),
    ("Governments should invest generously in public schools and rural healthcare infrastructure without delay", "सरकार को शिक्षा और स्वास्थ्य सेवाओं के विस्तार पर अधिक से अधिक ध्यान देना चाहिए"),
    ("You should apologize sincerely when you realize that your actions have caused someone pain", "अपनी भूल का अहसास होते ही मनुष्य को सच्चे मन से क्षमा माँग लेनी चाहिए"),
    ("We ought to protect rare endangered animal species from merciless illegal commercial wildlife poachers", "हमें जंगली जानवरों को शिकारियों से बचाने के लिए सख्त कानूनी उपाय करने चाहिए"),
    ("Children should obey and revere their elderly parents who sacrificed everything for their welfare", "संतान को अपने माता पिता की सेवा और उनके वचनों का सदा आदर करना चाहिए"),
    ("The traveler had to spend the cold rainy night inside a damp mountain cave", "रात घिर आने पर मुसाफिर को एक सीलन भरी पहाड़ी गुफा में पूरी रात काटनी पड़ी"),
    ("The defense lawyer had to present additional documentary evidence to prove the client innocence", "अभियुक्त को निर्दोष सिद्ध करने के लिए वकील को अदालत में नए दस्तावेज़ पेश करने पड़े"),
    ("The mountaineers had to abandon their summit attempt due to an unexpected massive avalanche", "अचानक गिरे बर्फ़ीले तूफान के कारण पर्वतारोहियों को अपनी यात्रा बीच में ही छोड़नी पड़ी"),
    ("The villagers had to drink muddy pond water when the only tube well failed", "गाँव का इकलौता नल खराब हो जाने पर लोगों को पोखर का गंदा पानी पीना पड़ा"),
    ("He had to borrow money from relatives to pay for his daughter university fees", "बेटी की पढ़ाई का खर्च उठाने के लिए उस गरीब पिता को रिश्तेदारों से कर्ज़ लेना पड़ा"),
    ("You have to sign the legal property deed in the presence of two witnesses", "ज़मीन की रजिस्ट्री कराने के लिए तुम्हें दो गवाहों के सामने हस्ताक्षर करने पड़ेंगे"),
    ("The municipality has to repair all broken asphalt roads before the annual monsoon arrives", "बरसात शुरू होने से पहले नगर पालिका को सभी टूटी सड़कों की मरम्मत करानी होगी"),
    ("I have to wake up at four in the morning to catch the express", "सुबह की तेज़ गाड़ी पकड़ने के लिए मुझे भोर में चार बजे ही उठना पड़ेगा"),
    ("She has to appear before the public service commission interview panel tomorrow morning", "कल सुबह उसे प्रशासनिक सेवा आयोग के साक्षात्कार बोर्ड के सामने उपस्थित होना है"),
    ("We have to stand united as a nation to overcome this unprecedented economic challenge", "इस बड़े आर्थिक संकट से उबरने के लिए हम सभी देशवासियों को एकजुट होना होगा"),
    ("One ought never to mock the physical deformity or poverty of any fellow human", "किसी की गरीबी या शारीरिक दुर्बलता का कभी किसी को मज़ाक नहीं उड़ाना चाहिए"),
    ("Society should provide equal educational and career opportunities to all women without prejudice", "समाज को बेटियों की शिक्षा और उनकी उन्नति के लिए समान अवसर उपलब्ध कराने चाहिए"),
    ("Judges must weigh evidence with complete impartiality without fear favor or sectarian bias", "न्यायाधीश को बिना किसी भय या पक्षपात के केवल सत्य और साक्ष्यों के आधार पर फैसला करना चाहिए"),
    ("We should reduce our carbon footprint to protect planet earth for future generations", "पर्यावरण को विनाश से बचाने के लिए हम सभी को प्राकृतिक संसाधनों का विवेकपूर्ण उपयोग करना चाहिए"),
    ("You ought to listen patiently to constructive criticism instead of reacting with defensive anger", "आलोचना सुनकर क्रोधित होने के बजाय व्यक्ति को अपनी कमियों को सुधारने का प्रयास करना चाहिए"),

    # 126-165: Subjunctive Mood (संभाव्य पक्ष: अगर वह आए तो, शायद हम चलें, काश ऐसा हो)
    ("If he should arrive before nightfall we might start the important council meeting immediately", "अगर वह शाम ढलने से पहले आ जाए तो हम तुरंत सभा की बैठक शुरू कर सकते हैं"),
    ("Perhaps we may travel to the cool mountain hill station during upcoming summer holidays", "शायद इस बार गर्मियों की छुट्टियों में हम किसी शांत पहाड़ी इलाके की यात्रा पर चलें"),
    ("Would that peace and universal brotherhood may prevail across all warring nations of world", "काश दुनिया के सभी देशों के बीच युद्ध समाप्त हो जाए और चारों ओर शांति स्थापित हो"),
    ("If it should rain heavily tonight the parched agricultural fields will revive with life", "अगर आज रात मूसलाधार बारिश हो जाए तो सूखे खेतों में नई जान आ जाएगी"),
    ("Lest the secret be disclosed to the enemy let us guard our words carefully", "कहीं ऐसा न हो कि हमारा भेद शत्रु को पता चल जाए इसलिए हमें बहुत सतर्क रहना होगा"),
    ("May the almighty bestow good health wisdom and long life upon our venerable elders", "ईश्वर करे कि हमारे पूज्य बुजुर्गों को उत्तम स्वास्थ्य और दीर्घायु का वरदान मिले"),
    ("If you should meet the foreign ambassador please convey our warm greetings of peace", "अगर तुम्हारी मुलाकात विदेशी राजदूत से हो तो उन्हें हमारी ओर से मित्रता का संदेश देना"),
    ("Perhaps the doctor may permit the recovering patient to return home by tomorrow afternoon", "शायद कल दोपहर तक चिकित्सक मरीज को अस्पताल से घर जाने की अनुमति दे दें"),
    ("Would that poverty and ignorance might be eradicated completely from our beloved motherland", "काश हमारे देश से अज्ञान और निर्धनता का अंधकार हमेशा के लिए पूरी तरह मिट जाए"),
    ("If the truth be spoken boldly the false fabricated accusations will crumble like dust", "अगर सच निडर होकर सामने आ जाए तो सारे झूठे आरोप तिनके की तरह बिखर जाएँगे"),
    ("Lest you should slip upon the icy pavement walk with great caution and care", "कहीं तुम्हारा पैर बर्फ़ पर फिसल न जाए इसलिए बहुत संभलकर और धीरे धीरे कदम बढ़ाओ"),
    ("May truth and justice triumph over tyranny and deception in the supreme court tomorrow", "अदालत में कल होने वाले फैसले में सत्य और न्याय की ही विजय हो"),
    ("If she should pass this competitive civil service examination the entire village will celebrate", "अगर वह इस कठिन परीक्षा में सफल हो जाए तो पूरे गाँव में खुशियाँ मनाई जाएँगी"),
    ("Perhaps the lost caravan may have found shelter beside the ancient desert stone well", "शायद भटका हुआ काफिला रेगिस्तान के किसी पुराने कुएँ के पास सुरक्षित पहुँच गया हो"),
    ("Would that human beings might learn to love one another without communal hatred", "काश सभी मनुष्य एक दूसरे से नफरत करना छोड़कर आपसी प्रेम और सद्भाव से रहना सीख लें"),
    ("If they should demand an explanation we shall present all documentary audit evidence fearlessly", "अगर वे हमसे कोई हिसाब माँगें तो हम निर्भय होकर सभी कागज़ात उनके सामने रख देंगे"),
    ("Lest the fire should spread to the granary let us extinguish every flying spark", "कहीं आग गोदाम तक न पहुँच जाए इसलिए हर सुलगती चिनगारी को तुरंत बुझा देना चाहिए"),
    ("May our sovereign democratic republic flourish in prosperity harmony and enduring moral strength", "हमारा लोकतांत्रिक देश हमेशा उन्नति सौहार्द और नैतिक शक्ति के मार्ग पर आगे बढ़ता रहे"),
    ("If the wise counselor should advise peace the king will surely sign the treaty", "अगर प्रधानमंत्री शांति की सलाह दें तो राजा अवश्य उस संधि पत्र पर हस्ताक्षर कर देंगे"),
    ("Perhaps the storm may subside before the morning fishing boats set sail for sea", "शायद सुबह होने से पहले समुद्री तूफान थम जाए और मछुआरे अपने काम पर जा सकें"),
    ("Would that every child in our country might receive free quality primary school education", "काश हमारे देश के हर बच्चे को अच्छी और निःशुल्क शिक्षा पाने का अधिकार मिल सके"),
    ("If you should find my lost diary please return it to my address safely", "अगर तुम्हें मेरी खोई हुई डायरी मिले तो कृपया उसे मेरे पते पर पहुँचा देना"),
    ("Lest we should be late for the train let us depart from home immediately", "कहीं गाड़ी छूट न जाए इसलिए हमें अभी इसी समय घर से निकल पड़ना चाहिए"),
    ("May the sacred flame of liberty burn brightly in the hearts of our youth", "हमारे युवाओं के दिलों में आज़ादी और स्वाभिमान की पावन ज्योति सदा जगमगाती रहे"),
    ("If the river should overflow its stone banks the low lying hamlets will flood", "अगर नदी अपने किनारों को तोड़कर बाहर बह निकले तो निचले गाँव पानी में डूब सकते हैं"),
    ("Perhaps the historical research committee may discover new evidence regarding the ancient Indus script", "शायद शोध समिति को सिंधु घाटी की प्राचीन लिपि को पढ़ने की कोई नई कुंजी मिल जाए"),
    ("Would that the beauty of our pristine natural environment might remain unpolluted forever", "काश हमारी नदियों और वनों का यह पावन सौंदर्य हमेशा प्रदूषण से मुक्त बना रहे"),
    ("If he should ask for assistance give him food and shelter without any hesitation", "अगर वह भूखा प्यासा तुम्हारे द्वार पर आए तो बिना संकोच उसे भोजन और आश्रय देना"),
    ("Lest the young sapling should wither protect it from the scorching midday summer heat", "कहीं छोटा पौधा झुलस न जाए इसलिए उसे दोपहर की तेज़ धूप से बचाकर रखो"),
    ("May universal peace reign across all five continents of this fragile shared blue planet", "ईश्वर करे कि इस सुंदर धरती के सभी कोनों में शांति और बंधुत्व का वास हो"),
    ("If the medicine should bring relief the patient will sleep peacefully through the night", "अगर इस काढ़े से आराम मिल जाए तो मरीज रात भर बिना दर्द के सो सकेगा"),
    ("Perhaps the winter snow may fall upon the high pine ridges before late December", "शायद दिसंबर का महीना खत्म होने से पहले ही ऊँची पहाड़ियों पर ताज़ा बर्फ़बारी हो जाए"),
    ("Would that all human sorrow and suffering might dissolve like morning dew before sun", "काश संसार के सारे दुख और कष्ट सुबह की ओस की तरह सूरज निकलते ही मिट जाएँ"),
    ("If they should invite us cordially we shall attend the festival of classical music", "अगर वे हमें आदर सहित बुलाएँ तो हम उस शास्त्रीय संगीत समारोह में अवश्य जाएँगे"),
    ("Lest the milk should boil over keep a watchful eye upon the kitchen hearth", "कहीं दूध उबलकर गिर न जाए इसलिए चूल्हे की आँच पर लगातार नज़र रखनी चाहिए"),
    ("May the bonds of cultural friendship between our two sovereign nations grow ever stronger", "दोनों देशों के बीच सांस्कृतिक और कूटनीतिक संबंधों की मित्रता दिन दूनी रात चौगुनी बढ़े"),
    ("If she should compose a new patriotic song the children will sing it happily", "अगर वह कोई नया गीत रचे तो स्कूल के सभी बच्चे उसे बड़े चाव से गाएँगे"),
    ("Perhaps the weary travelers may reach the roadside caravanserai before the darkness deepens completely", "शायद अंधेरा घिरने से पहले मुसाफिर सड़क किनारे बनी सराय में सुरक्षित पहुँच जाएँ"),
    ("Would that truth might always illuminate the path of our national legislative parliament decisions", "काश हमारे सभी निर्णय सत्य न्याय और लोक कल्याण की भावना से प्रेरित होकर लिए जाएँ"),
    ("If the wind should blow favorably our sailboat will reach the harbor by dusk", "अगर अनुकूल हवा बहती रहे तो हमारी पाल वाली नाव शाम तक बंदरगाह पहुँच जाएगी"),

    # 166-200: Impersonal Bhavavachya (भाववाच्य) & Passive (मुझसे चला नहीं जाता, उससे बोला नहीं गया)
    ("I am so exhausted from the long mountain hike that I cannot walk anymore", "थकावट के कारण अब मुझसे एक कदम भी आगे चला नहीं जाता"),
    ("Due to severe throat infection and hoarseness he could not speak a single word", "गले में भयंकर दर्द होने के कारण उस बीमार व्यक्ति से एक शब्द भी बोला नहीं गया"),
    ("In this intense sweltering summer heat it is impossible to sleep inside the room", "इस भीषण उमस और गर्मी में बंद कमरे के भीतर किसी से सोया नहीं जाता"),
    ("After hearing the heartbreaking tragic news the grieving mother could not eat anything", "इतनी बड़ी दुर्घटना की खबर सुनकर उस शोकाकुल माँ से कुछ भी खाया नहीं गया"),
    ("The elderly grandmother has such weak knees that she cannot sit on floor", "घुटनों में दर्द होने के कारण अब बूढ़ी दादी से ज़मीन पर बैठा नहीं जाता"),
    ("Overcome with deep shame and remorse the guilty clerk could not lift his eyes", "शर्मिंदगी के मारे उस बेईमान मुनीम से किसी के सामने अपनी आँखें उठाई नहीं गईं"),
    ("In the bitter freezing Himalayan blizzard it is impossible to stay outdoors without fire", "कड़ाके की ठंड और बर्फीली हवा में बिना अलाव के बाहर रात भर ठहरा नहीं जाता"),
    ("After running forty kilometers in the hot sun the marathon runner could not stand", "धूप में इतनी लंबी दौड़ लगाने के बाद उस थके हुए धावक से खड़ा भी नहीं हुआ गया"),
    ("The wounded soldier was in such agony that he could not bear the pain", "घायल सिपाही की हालत इतनी नाज़ुक थी कि उससे असहनीय पीड़ा सही नहीं जा रही थी"),
    ("When overcome with boundless joy it is impossible to hide the tears of happiness", "जब मन में असीम आनंद उमड़ता है तब आँखों से छलकते खुशी के आँसू रोके नहीं जाते"),
    ("Due to severe asthma and breathing difficulty the patient cannot climb the steep stairs", "दमे की बीमारी के कारण उस वृद्ध मरीज से अस्पताल की सीढ़ियाँ चढ़ी नहीं जातीं"),
    ("Hearing the ridiculous funny joke the serious judge could not stop his loud laughter", "इतनी हास्यास्पद बात सुनकर गंभीर न्यायाधीश से भी अपनी हँसी रोकी नहीं गई"),
    ("After working sixteen continuous hours in the fields the laborer cannot move his limbs", "दिन भर कड़ी धूप में काम करने के बाद थके हुए किसान से हिला भी नहीं जाता"),
    ("The grief was so profound and overwhelming that not a single tear could be shed", "मन का दुख इतना गहरा था कि उस अभागे व्यक्ति से अपनी आँखों से रोया भी नहीं गया"),
    ("In the pitch black darkness of the cavern it is impossible to see anything", "उस गहरी और अंधेरी गुफा के भीतर किसी से एक हाथ दूर भी देखा नहीं जाता"),
    ("With both legs broken in the carriage accident the horse could not stand up", "दोनों पैर टूट जाने के कारण उस घायल घोड़े से अपनी जगह से उठा नहीं गया"),
    ("On an empty starving stomach it is impossible to study complex philosophical treatises attentively", "भूखे पेट रहकर किसी भी विद्यार्थी से गंभीर विषयों की कठिन पढ़ाई नहीं की जाती"),
    ("Overcome with sudden panic during the fire the trapped clerk could not move forward", "आग की लपटें देखकर घबराहट के मारे उस कर्मचारी से आगे बढ़ा नहीं गया"),
    ("With heavy weights upon their heads the laborers cannot walk briskly up hill", "सिर पर इतना भारी बोझ उठाकर मजदूरों से इस खड़ी पहाड़ी पर तेज़ी से चढ़ा नहीं जाता"),
    ("The shock of the sudden catastrophe was so intense that nothing could be understood", "विपत्ति इतनी अचानक आई कि किसी से कुछ सोचते समझते नहीं बना"),
    ("In the noisy crowded marketplace it is impossible to read or write with concentration", "बाज़ार के इतने भारी शोरगुल के बीच किसी से शांत मन से पढ़ा नहीं जाता"),
    ("Having suffered continuous betrayals from friends he could not trust anyone ever again", "बार बार धोखा खाने के बाद उस सीधे इंसान से किसी पर भरोसा किया नहीं गया"),
    ("Due to blinding dust storm blowing across desert travelers cannot open their dry eyes", "रेगिस्तान की रेतीली आंधी में मुसाफिरों से अपनी आँखें खोली नहीं जातीं"),
    ("The ancient manuscript was so faded and damaged that it could not be deciphered", "दीमकों द्वारा चाटे जाने के कारण उस प्राचीन ग्रंथ के अक्षरों को पढ़ा नहीं जा सका"),
    ("With severe back pain the old carpenter cannot bend down to pick up tools", "कमर में तेज़ दर्द होने के कारण अब उस वृद्ध बढ़ई से नीचे झुका नहीं जाता"),
    ("Confronted with the overwhelming evidence of corruption the dishonest minister could not reply", "सारे सबूत सामने आ जाने पर उस भ्रष्ट नेता से कोई उत्तर दिया नहीं गया"),
    ("In subzero freezing water it is impossible to swim for more than three minutes", "बर्फ़ जैसे ठंडे पानी में किसी से कुछ मिनटों से अधिक तैरा नहीं जाता"),
    ("The little girl was so terrified of darkness that she could not sleep alone", "अंधेरे से डरने के कारण उस छोटी बच्ची से अकेले कमरे में सोया नहीं गया"),
    ("Without drinking clean water for two whole days the traveler cannot endure the thirst", "दो दिन से प्यासे मुसाफिर से अब अपनी प्यास का कष्ट सहा नहीं जाता"),
    ("The emotional reunion after twenty long years was so touching that words failed completely", "बरसों बाद मिलने पर भावुकता के कारण दोनों मित्रों से मुँह से कुछ बोला नहीं गया"),
    ("With high fever and trembling limbs the child cannot play with his wooden toys", "तेज़ बुखार के कारण उस नन्हे बच्चे से अब अपने खिलौनों से भी खेला नहीं जाता"),
    ("Overwhelmed by the majestic grandeur of the Himalayas travelers cannot turn away their eyes", "हिमालय के दिव्य सौंदर्य को देखकर किसी से अपनी नज़रें हटाई नहीं जातीं"),
    ("In the thick suffocating smoke of the burning room firefighters could not breathe easily", "कमरे में भरे घने धुएँ के कारण साहसी जवानों से भी साँस ली नहीं जा रही थी"),
    ("Having lost his entire family in the flood the destitute man could not survive", "बाढ़ में सब कुछ लुट जाने के बाद उस अभागे व्यक्ति से यह असहनीय दुख सहा नहीं गया"),
    ("These nuanced passive and impersonal constructions reflect the sublime richness of Hindi grammar", "भाववाच्य और कर्मवाच्य के इन प्रयोगों से हिंदी भाषा की अद्वितीय अभिव्यक्ति और निखर उठती है"),
]

if __name__ == "__main__":
    process_batch(37, "p37s", PAIRS)
