"""Generate data/phrases18.json — Batch 3 (missing1 remainder, rank 5001+).

Skips: फ़ाइलों (English-origin), दशाला (unclear headword), अल्जेरिया (proper
noun), मदन (proper name) — documented exceptions. Plus tense boosters.
Aligns hand-authored; auto-repair via gen_align.derive on structural failure.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

N = [
    ("The flooded river flows in a strong stream", "बाढ़ वाली नदी तेज़ धारी से बहती है", "1 1 2 6 7 4 3 3"),
    ("The volume of the sphere was calculated", "गोले का आयतन निकाला गया", "4 2 1 6 6"),
    ("People think about the future", "लोग भविष्य के बारे में सोचते हैं", "0 4 2 2 2 1 1"),
    ("Big bridges were built on the highways", "राजमार्गों पर बड़े पुल बने", "6 4 0 1 3"),
    ("The mint makes coins", "टकसाल सिक्के बनाती है", "1 3 2 2"),
    ("Big companies give jobs to the youth", "बड़ी कंपनियाँ युवाओं को रोज़गार देती हैं", "0 1 6 4 3 2 2"),
    ("Reading of good books improves the language", "अच्छी पुस्तकों का पठन भाषा सुधारता है", "2 3 1 0 6 4 4"),
    ("Income tax is deposited every year", "आयकर हर साल जमा होता है", "0-1 4 5 3 3 2"),
    ("I want to talk to you", "मैं आपसे बात करना चाहता हूँ", "0 4-5 3 3 1 1"),
    ("The wheels of the cart creaked", "गाड़ी के पहिये चरमराए", "4 2 1 5"),
    ("The convoy had to pass through the forest", "काफ़िले को जंगल से गुजरना पड़ा", "1 2 7 5 4 2"),
    ("The matter was settled despite differences", "मतभेदों के बावजूद मामला सुलझ गया", "5 4 4 1 3 3"),
    ("The sick child was troubled by fever", "बीमार बच्चा बुख़ार से प्रताड़ित था", "1 2 6 5 4 3"),
    ("Grandma began teaching the children", "दादी माँ बच्चों को सिखाने लगीं", "0 0 4 3 2 1"),
    ("The craftsmen ran the factory for years", "कारीगरों ने कारखाना सालों तक चलाए", "1 2 4 6 5 2"),
    ("The worker went to ask for wages", "मज़दूर मज़दूरी मांगने गया", "1 6 4 2"),
    ("This event is from the era of the king", "यह प्रसंग राजा के दौर का है", "0 1 8 3 5 3 2"),
    ("The meeting of the commissioners was postponed", "आयुक्तों की बैठक टल गई", "4 2 1 6 6"),
    ("Psychotherapy helps in mental illness", "मनोचिकित्सा मानसिक बीमारी में मदद करती है", "0 3 4 2 1 1 1"),
    ("The governors attended the ceremony", "राज्यपालों ने समारोह में भाग लिया", "1 2 4 3 2 2"),
    ("The teacher drew a triangle", "शिक्षक ने त्रिभुज बनाया", "1 2 4 2"),
    ("The burning of fuel causes smoke", "ईंधन के दहन से धुआँ निकलता है", "3 2 1 4 5 4 4"),
    ("The travelers left the vehicle and walked on foot", "यात्रियों ने गाड़ी छोड़ी और पैदल चले", "1 2 4 2 5 7-8 6"),
    ("Speeches are given in the assemblies", "सभाओं में भाषण दिए जाते हैं", "4 3 0 2 2 1"),
    ("The tenant was evicted from the shop", "किरायेदार दुकान से बेदखल हुआ", "1 6 4 3 2"),
    ("The bus arrives in minutes", "बस मिनटों में आती है", "1 4 3 2 2"),
    ("The party released its manifesto", "दल ने अपना घोषणापत्र जारी किया", "1 2 3 4 2 2"),
    ("The legislators demanded a debate", "विधायकों ने बहस की माँग की", "1 2 4 2 2 2"),
    ("The crows began cawing on the wall", "कौवे दीवार पर काँव काँव करने लगे", "1 6 4 3 3 3 2"),
    ("The paintings are kept in the gallery", "चित्र दीर्घा में रखे हैं", "1 6 4 3 2"),
    ("The weakness of the body increased with age", "उम्र के साथ शरीर की कमजोरी बढ़ी", "7 6 6 4 2 1 5"),
    ("The fetus grows in the uterus", "गर्भ गर्भाशय में बढ़ता है", "1 5 3 2 2"),
    ("The camp of the painters was held", "चित्रकारों का शिविर आयोजित हुआ", "4 2 1 6 6"),
    ("Care prevents accidents", "सावधानी दुर्घटनाओं को रोकती है", "0 2 1 1 1"),
    ("The vice chancellor inaugurated the lab", "कुलपति ने प्रयोगशाला का उद्घाटन किया", "1-2 3 5 3 3 3"),
    ("The extraction of oil from seeds happens", "बीजों से तेल का निष्कर्षण होता है", "5 4 3 2 1 6 6"),
    ("Songs of the braves are sung in the village", "गाँव में शूरवीरों के गीत गाए जाते हैं", "8 6 3 2 0 5 5 4"),
    ("The cow gave birth at night", "गाय का प्रसव रात में हुआ", "1 3 3 5 4 2"),
    ("Realism is seen in the stories of the writer", "लेखक की कहानियों में यथार्थवाद दिखता है", "8 6 5 3 0 2 1"),
    ("The fields of the Jat community are fertile", "जाट समुदाय के खेत उपजाऊ हैं", "4 5 2 1 7 6"),
    ("The federation of states made the law", "राज्यों के परिसंघ ने कानून बनाया", "3 2 1 4 6 4"),
    ("The scholars interpreted the theological texts", "विद्वानों ने धर्मशास्त्रीय ग्रंथों की व्याख्या की", "1 2 4 5 2 2 2"),
    ("Lead is a heavy metal", "सीसा भारी धातु है", "0 3 4 1"),
    ("The judge heard both sides", "न्यायमूर्ति ने दोनों पक्ष सुने", "1 2 4 2"),
    ("The factory makes weapons", "कारखाना आयुध बनाता है", "1 3 2 2"),
    ("The niece is like a daughter", "भतीजी बेटी जैसी होती है", "1 5 3 2 2"),
    ("The two countries signed a bilateral treaty", "दोनों देशों ने द्विपक्षीय संधि पर हस्ताक्षर किए", "1 2 3 5 6 3 3 3"),
    ("Parents respect the desires of children", "माता पिता बच्चों की इच्छाओं का सम्मान करते हैं", "0 0 5 4 3 2 1 1 1"),
    ("The property was divided among the heirs", "संपत्ति उत्तराधिकारियों में बँट गई", "1 6 4 3 3"),
    ("The strengthening of the bridge was ordered", "पुल के सुदृढीकरण का आदेश दिया गया", "4 2 1 5 6 6 6"),
    ("A new talent emerged from the world of music", "संगीत की दुनिया से नई प्रतिभा उभरी", "8 7 6 4 1 2 3"),
    ("The student was unwilling to go on stage", "छात्र मंच पर जाने से अनिच्छुक था", "1 7 6 5 4 3 2"),
    ("The exploitation of workers will not be tolerated", "मज़दूरों के दोहन की इजाज़त नहीं दी जाएगी", "3 2 1 6 7 5 7 7"),
    ("The player remained undefeated", "खिलाड़ी अपराजित रहा", "1 3 2"),
    ("The indicator turned red", "संकेतक लाल हो गया", "1 3 2"),
    ("Proving guilt was difficult", "दोषसिद्धि करना कठिन था", "0-1 0 3 2"),
    ("The cleric explained the book", "मौलाना ने ग्रंथ की व्याख्या की", "1 2 4 2 2 2"),
    ("The speed of light is a universal constant", "प्रकाश की गति एक सार्वत्रिक स्थिरांक है", "3 2 1 5 6 7 4"),
    ("The majority community lives in the state", "राज्य में बहुसंख्यक समुदाय रहता है", "1 2 3 5 6 3"),
    ("The birthplace of the poet became a shrine", "कवि का जन्मस्थान तीर्थ बन गया", "4 2 1 7 5 5"),
    ("The punishment of treason was announced", "राजद्रोह का दंड सुनाया गया", "3 2 1 5 5"),
    ("The festival brought the siblings together", "त्योहार ने भाईबहनों को एक किया", "1 2 4 2 5 2"),
    ("The minister is answerable to the public", "मंत्री जनता के प्रति उत्तरदायी है", "1 6 4 4 3 2"),
    ("The dictatorships collapsed one by one", "तानाशाही एक एक करके ढह गई", "1 3 4 4 2 2"),
    ("The emperor built a big fort", "बादशाह ने बड़ा किला बनवाया", "1 2 4 5 2"),
    ("The study of law is called jurisprudence", "न्याय का अध्ययन न्यायशास्त्र कहलाता है", "3 2 1 6 5 4"),
    ("Tea grows in the northeastern states", "उत्तरपूर्वी राज्यों में चाय होती है", "0 4 5 2 1 1"),
    ("The officers follow the guidelines", "अधिकारी दिशानिर्देशों का पालन करते हैं", "1 4 3 2 2 2"),
    ("Bhang is made from the leaves", "भांग पत्तियों से बनती है", "0 5 3 2 1"),
    ("The garden is full of plants", "उद्यान वनस्पतियों से भरा है", "1 5 4 3 2"),
    ("This disease is hereditary in the family", "परिवार में यह रोग वंशानुगत है", "0 1 6 4 3 2"),
    ("The pilgrims reached the shrine", "तीर्थयात्री धाम पहुंचे", "1 4 2"),
    ("The court discussed the rights related to homosexuality", "न्यायालय ने समलैंगिकता से जुड़े अधिकारों पर चर्चा की", "1 2 7 6 5 4 2 2 2"),
    ("The watershed of the two rivers is the mountain", "दोनों नदियों का जलविभाजक पहाड़ है", "4 5 2 1 8 6"),
    ("The bleeding from the wound stopped", "घाव से रक्तस्राव रुक गया", "4 2 1 5 5"),
    ("The old manuscript remained unaltered", "पुरानी पांडुलिपि अपरिवर्तित रही", "1 2 4 3"),
    ("Weather is forecast with satellites", "उपग्रहों से मौसम की भविष्यवाणी होती है", "4 3 0 2 2 1 1"),
    ("The police caught the murderer", "पुलिस ने खूनी को पकड़ा", "1 2 4 3 2"),
    ("The respondent presented the documents", "प्रतिवादी ने दस्तावेज़ पेश किए", "1 2 4 2"),
    ("The grandfather wrote a will", "दादा ने वसीयतनामा लिखा", "1 2 4 2"),
    ("The peripheral areas of the city developed", "शहर के परिधीय इलाके विकसित हुए", "5 3 1 2 6 6"),
    ("The stolen goods were recovered", "चोरी का माल पुनर्प्राप्त हुआ", "1 1 2 4 3"),
    ("Hindus celebrate many festivals", "हिंदुओं के अनेक त्योहार होते हैं", "0 1 2 3 1 1"),
    ("The government made a big plan", "सरकार ने बड़ी योजना बनाई", "1 2 4 5 2"),
    ("Success is the right use of opportunities", "सफलता मौकों का सही उपयोग है", "0 6 5 3 4 1"),
    ("The shopkeeper took the shop on lease", "दुकानदार ने दुकान का पट्टा लिया", "1 2 4 5 6 2"),
    ("The fleet of submarines sailed", "पनडुब्बियों का बेड़ा रवाना हुआ", "3 2 1 4 4"),
    ("The gambling dens were raided", "जुए के अड्डों पर छापा मारा गया", "1 2 2 3 4 4 4"),
    ("The child grew tall", "बच्चा ऊंचा हो गया", "1 3 2"),
    ("The forest stays full of sounds", "जंगल आवाज़ों से भरा रहता है", "1 5 4 3 2 2"),
    ("The revelation surprised everyone", "रहस्योद्घाटन ने सबको चौंका दिया", "1 2 3 2 2"),
    ("The cobra raised its hood", "नाग ने फन उठाया", "1 2 4 2"),
    ("Shares are a type of security", "अंश प्रतिभूति का एक प्रकार हैं", "0 5 4 2 3 1"),
    ("The parameters of the test were changed", "परीक्षा के मापदंड बदले गए", "4 2 1 6 6"),
    ("The tribal dance is traditional", "जनजातीय नृत्य परंपरागत है", "1 2 4 3"),
    ("The frog is an amphibian", "मेंढक उभयचर है", "1 4 2"),
]
N += [
    ("The chief went to hand over the charge", "प्रमुख पद सौंपने गए", "1 3 2 2"),
    ("A respectful behavior wins hearts", "सम्मानजनक व्यवहार दिल जीतता है", "0 1 3 2 2"),
    ("Practical knowledge is useful in life", "प्रायोगिक ज्ञान जीवन में काम आता है", "0 1 4 3 3 3"),
    ("Many travelers got stuck in the swamp", "अनेक यात्री दलदल में फंसे", "2 1 5 4 3"),
    ("The organizers of the fair met the officials", "मेले के आयोजकों ने अधिकारियों से मुलाकात की", "3 2 5 1 2 2 2 2"),
    ("The tyranny of the ruler increased", "शासक का अत्याचार बढ़ गया", "1 2 3 4 4"),
    ("Transparency came in the tender process", "नीलामी की प्रक्रिया में पारदर्शिता आई", "4 2 3 5 2"),
    ("The complaint of neglect reached the court", "अनदेखी की शिकायत न्यायालय तक पहुंची", "1 2 3 4 5 2"),
    ("The devotees queued up at the temple", "भक्तों ने मंदिर पर कतार लगाई", "1 2 4 4 3 2"),
    ("The address of the speaker was simple", "वक्ता का संबोधन सरल था", "1 2 3 4"),
    ("Many battles took place on this land", "इस भूमि पर अनेक लड़ाइयों हुईं", "3 4 1 2 5 5"),
    ("The architect presented a novel design", "वास्तुकार ने अभिनव रूप पेश किया", "1 2 2 3 4 2"),
    ("Ivory is costly", "हाथीदांत महँगा होता है", "0 2 3"),
    ("The rider got control of the horse", "सवार ने घोड़े पर काबू पा लिया", "1 2 5 4 2 2 2"),
    ("The cruelty of the hunter shocked all", "शिकारी की बर्बरता ने सबको झकझोर दिया", "1 2 3 2 4 3 2"),
    ("The sum of two whole numbers is an integer", "दो पूर्णांकों का योग पूर्णांक होता है", "2 2 3 1 5 4 4"),
    ("The area of the field was measured", "खेत की आयत नापी गई", "3 2 1 3 3"),
    ("The book gained prominence", "पुस्तक को उल्लेखनीयता मिली", "1 2 3 2"),
    ("The treasury of words is vast", "शब्दों का कोश विशाल है", "3 2 1 4 2"),
    ("The attachment of the child grew with the nanny", "बच्चे का लगाव धाय के साथ बढ़ा", "2 2 1 4 5 3 3"),
    ("The young man went to earn in the city", "युवक शहर में कमाने गया", "1 5 3 2 2"),
    ("The runner finished seventh", "धावक सातवां स्थान पर रहा", "1 2 4 3 2"),
    ("The idol worshipper prayed daily", "मूर्तिपूजक प्रतिदिन प्रार्थना करता था", "1 5 3 3 2"),
    ("The married couple settled in the village", "शादीशुदा जोड़ा गाँव में बस गया", "0 1 5 4 3 3"),
    ("The farmers will keep the seeds", "किसान बीज रखेंगे", "1 3 4"),
    ("The scheme brought developmental changes", "योजना से विकासात्मक बदलाव आए", "3 2 1 4 2"),
    ("The pause in the meeting surprised the members", "बैठक में ठहराव से सदस्य चौंके", "3 4 2 5 2"),
    ("Feminism demands equal rights", "नारीवाद समान अधिकार माँगता है", "0 2 1 2 2"),
    ("The colors of the picture faded", "चित्र के वर्णों की चमक गिरी", "2 2 1 4 4"),
    ("The order was published in the gazette", "आदेश राजपत्र में प्रकाशित हुआ", "1 3 4 4 2"),
    ("The player performed better than his peers", "खिलाड़ी ने समकक्षों से बेहतर प्रदर्शन किया", "1 2 4 2 5 2 2"),
    ("The independent candidate won the seat", "निर्दलीय उम्मीदवार ने सीत जीती", "0 1 2 5 3 2"),
    ("Trust grows with honesty", "ईमानदारी से यकीन बढ़ता है", "1 2 2 2 2"),
    ("The land was transferred to the society", "भूमि समिति को हस्तांतरित हुई", "3 5 4 4"),
    ("The expenses of the journey were high", "यात्रा के खर्चों ने जेब खाली की", "2 2 3 4 5 4 2"),
    ("The maps came from the surveys", "सर्वेक्षणों से नक्शे बने", "3 2 4 2"),
    ("The effects of the scheme are visible", "योजना का प्रभाव परिलक्षित है", "2 2 3 4 2"),
    ("The fountains of the garden charmed the children", "बगीचे के फव्वारे बच्चों को मोह लेते हैं", "4 2 5 6 6 3 3"),
    ("He did madness in love", "प्रेम में उसने पागलपन किया", "2 3 1 2 2"),
    ("Many species of birds live in the forest", "जंगल में पक्षियों की अनेक प्रजातियां रहती हैं", "5 6 2 3 4 7 7"),
    ("The speaker spoke with passion", "वक्ता ने आवेश से भाषण दिया", "1 2 3 2 5 2"),
    ("The coordinator called the meeting", "संयोजक ने बैठक बुलाई", "1 2 3 2"),
    ("The ethnicity of the tribe is ancient", "जनजाति की जातीयता प्राचीन है", "1 2 3 4 2"),
    ("The entrance of the fort is grand", "किले का प्रवेशद्वार भव्य है", "2 2 3 4 2"),
    ("Experiments go on in the laboratories", "प्रयोगशालाओं में प्रयोग होते रहते हैं", "4 3 0 2 2 4"),
    ("The friends shared an intimate talk", "मित्रों ने अंतरंग बातें कीं", "1 2 3 3 2"),
    ("The fine is in proportion to the crime", "दंड अपराध के आनुपातिक होता है", "1 3 2 4 5 4"),
    ("The weather became worse", "मौसम और बदतर हो गया", "1 3 4 3 3"),
    ("The implications of the decision are far reaching", "निर्णय के निहितार्थ दूर तक हैं", "1 2 3 4 5 4"),
    ("Freedom is the right of all", "स्वतन्त्रता सबका अधिकार है", "0 3 2 2"),
    ("The bus stopped at once", "बस एकदम रुकी", "1 2 3"),
    ("The multinational company opened an office", "बहुराष्ट्रीय कंपनी ने दफ़्तर खोला", "0-1 1 2 5 2"),
    ("The rent of the house increased", "मकान के किराये बढ़ गए", "3 2 3 4 4"),
    ("The separation of the brothers pained the mother", "भाइयों का पृथक्करण माँ को चुभा", "2 2 3 4 5 2"),
    ("The eligibility of the players was checked", "खिलाड़ियों की पात्रता जाँची गई", "2 2 3 3 3"),
    ("The islanders depend on the sea", "द्वीपवासी समुद्र पर निर्भर हैं", "1 4 3 4 2"),
    ("The tremors of the quake were felt far", "भूकंप के सदमे दूर तक महसूस हुए", "1 2 3 5 3 5 3"),
    ("Decomposition of waste makes manure", "कचरे के अपघटन से खाद बनती है", "2 3 1 4 5 2 2"),
    ("The encroachment on the road was removed", "सड़क पर अतिक्रमण हटाया गया", "3 3 4 3 3"),
    ("The ovaries release the egg", "अंडाशय से अंडा निकलता है", "1 2 4 3 3"),
    ("Superstitions weakened the beliefs", "अंधविश्वासों ने विश्वासों को कमज़ोर किया", "1 2 3 4 4 2"),
    ("Mental illness needs care", "मनोरोग में देखभाल चाहिए", "1 3 2 2"),
    ("The teacher asked to repeat the poem", "शिक्षक ने कविता दोहराने को कहा", "1 2 4 3 2 2 2"),
    ("Cells divide and grow", "कोशिकाएँ बँटकर बढ़ती हैं", "0 2 2 2"),
    ("The shareholders approved the plan", "शेयरधारकों ने योजना स्वीकार की", "1 2 4 2 2"),
    ("Folktales teach values", "लोककथाओं से संस्कार सीखते हैं", "2 2 3 1 1"),
    ("Both paths are equivalent", "दोनों रास्ते समतुल्य हैं", "0-1 1 2 2"),
    ("The unused room gathered dust", "अप्रयुक्त कमरे में धूल जमी", "0 2 3 3 2"),
    ("The discourse of the saint was sweet", "संत का प्रवचन मधुर था", "1 2 3 4"),
    ("The derived word is in use", "अनुप्रयुक्त शब्द प्रचलन में है", "0 1 4 2 2"),
    ("The timeline of events is on the wall", "घटनाओं की समयरेखा दीवार पर है", "2 2 1 6 5 4 2"),
    ("The boat rose on the waves", "नाव तरंगों पर उठती गई", "1 5 4 3 2"),
    ("The picture got hung upside down", "चित्र उल्टा लग गया", "1 3 3 3"),
    ("The old medicine proved ineffective", "पुरानी दवा अप्रभावी साबित हुई", "0 1 2 3 2"),
    ("The migrants came for work", "अप्रवासियों का आगमन काम के लिए हुआ", "2 2 3 5 2 2 2"),
    ("Archery needs steady hands", "तीरंदाजी के लिए स्थिर हाथ चाहिए", "0 2 3 3 2 2"),
    ("The unfortunate family lost the house", "दुर्भाग्यपूर्ण परिवार से मकान छूट गया", "0 1 3 4 3 3"),
    ("The working committee met in the evening", "कामकाजी समिति शाम को मिली", "0 1 3 4 4 2"),
    ("The subfamily of plants is large", "पौधों का उपपरिवार बड़ा है", "2 2 3 4 2"),
    ("The dialogue resolved the dispute", "संवादात्मक तरीके से विवाद सुलझा", "0 2 3 4 5 2"),
    ("The evergreen tree gives shade all year", "सदाबहार पेड़ साल भर छाया देता है", "0 1 5 4 4 3 3"),
    ("The demographic profile of the state changed", "राज्य की जनसांख्यिकीय संरचना बदली", "2 2 3 4 5 2"),
    ("The charms of the fair pulled the children", "मेले के आकर्षणों ने बच्चों को खींचा", "2 2 3 1 6 4 2"),
    ("The plan seems feasible", "योजना व्यवहार्य लगती है", "1 2 2 2"),
    ("The plots of land were auctioned", "भूखंडों की नीलामी हुई", "3 2 3 2"),
    ("The exam of twelfth is tough", "बारहवीं की परीक्षा कठिन होती है", "2 2 3 4 4 2"),
    ("The archer hit the target", "तीरंदाज ने निशाना साधा", "1 2 3 2"),
    ("He flatly refused the offer", "उसने बिलकुल मना कर दिया", "1 2 3 3 2 2"),
    ("All is well at last", "अंत में सब ख़ैर हुआ", "4 5 0 1 3"),
    ("The indicator moved with the price", "दाम के साथ सूचक चला", "2 2 3 2"),
    ("The efficiency of the workers improved", "कामगारों की कार्यक्षमता सुधरी", "2 2 3 4"),
    ("The reference of the book is given below", "पुस्तक का हवाला नीचे दिया है", "2 2 3 5 4 2 2"),
    ("Every sect respects its scriptures", "हर सम्प्रदाय अपने ग्रंथों का सम्मान करता है", "1 1 4 2 3 4 4 4"),
    ("The dispatch of goods was delayed", "माल का प्रेषण देर से हुआ", "2 2 3 5 3 2"),
    ("The prefix changes the meaning", "उपसर्ग अर्थ बदल देता है", "0 2 3 3 3"),
    ("The legends of the region are old", "क्षेत्र की किंवदंतियों में इतिहास छिपा है", "2 2 4 5 3 5 2"),
    ("The contractor is bound by the agreement", "ठेकेदार अनुबंधित है", "1 2 2"),
    ("The artifacts of the museum are precious", "संग्रहालय की कलाकृतियाँ बहुमूल्य हैं", "3 2 4 5 2"),
    ("The mistress of the house was kind", "घर की मालकिन दयालु थीं", "3 2 4 5 2"),
    ("The blows of fate test the person", "जीवन की चोटें इंसान को परखती हैं", "2 2 3 5 3 2 2"),
]
N += [
    ("The village comes under the old district", "गाँव पुराने परगना में पड़ता है", "1 3 2 4 4 2"),
    ("Zinc prevents rust", "जस्ता जंग को रोकता है", "0 2 2 3 3"),
    ("The study was financed by the institute", "संस्थान से अध्ययन वित्तपोषित हुआ", "3 3 1 2 4"),
    ("The songs of the singer are melodious", "गायक के गानों में मिठास है", "2 2 5 4 2 2"),
    ("The patient needs clinical care", "रोगी को चिकित्सीय देखभाल चाहिए", "1 2 2 3 3 2"),
    ("The ideals of the family are high", "परिवार के आदर्शों की ऊँचाई कम है नहीं", "2 2 3 4 5 6 7 7"),
    ("The scenes of the valley are lovely", "घाटी के परिदृश्यों में सुंदरता है", "2 2 5 4 2 2"),
    ("The graduates applied for the post", "स्नातकों ने पद के लिए आवेदन किया", "1 2 5 2 2 3 2"),
    ("The guardians of the law are the courts", "कानून के संरक्षकों में न्यायालय प्रमुख हैं", "2 2 4 5 4 6 2"),
    ("The subject matter of the lesson is nature", "पाठ की विषयवस्तु प्रकृति है", "1 2 3 4 2"),
    ("Prostitution is a social evil", "वेश्यावृत्ति सामाजिक बुराई है", "0 2 3 2"),
    ("Long queues formed at the counter", "काउंटर पर लम्बे कतारें लगीं", "0 4 1 3 3"),
    ("The brother in law helped in the marriage", "बहनोई ने शादी में मदद की", "0-3 2 3 4 2 2"),
    ("Creativity grows with practice", "अभ्यास से रचनात्मकता बढ़ती है", "1 2 2 2 2"),
    ("The bachelor lives alone", "अविवाहित युवक अकेला रहता है", "0 1 3 3 2"),
    ("Atoms combine to make molecules", "परमाणुओं से अणु बनते हैं", "3 2 4 2 2"),
    ("The stains on the cloth did not go", "कपड़े के धब्बों से छुटकारा नहीं मिला", "2 2 3 4 5 5 5"),
    ("The final decision rests with the court", "अन्तिम निर्णय न्यायालय का है", "0 1 3 2 2"),
    ("The secondary school opened early", "द्वितीयक विद्यालय सुबह खुला", "0 1 4 3 2"),
    ("The windmill turns in the wind", "पवन चक्की हवा में घूम रही है", "1 2 3 4 3 2 2"),
    ("Engineering is a respected field", "अभियांत्रिकी सम्मानित क्षेत्र है", "0 2 3 2"),
    ("There was mention of the old event", "पुराने प्रसंग का जिक्र आया", "1 2 2 3 3 2"),
    ("The crusade was long", "धर्मयुद्ध लंबा चला", "0 2 2"),
    ("The wine despoiled the youth", "सूरा ने युवाओं को बर्बाद किया", "1 2 3 4 4 2"),
    ("The colonial rulers kept the wealth", "उपनिवेशवादियों ने संपदा लूटी", "1 2 2 3 3"),
    ("The subtitle explains the scene", "उपशीर्षक दृश्य समझाता है", "0 2 2 2"),
    ("The eccentric man lived in the hills", "सनकी आदमी पहाड़ों में रहता था", "0 1 4 4 3 3 2"),
    ("The circumstances changed suddenly", "हालात अचानक बदल गए", "1 3 3 3"),
    ("A meeting was held on the solutions of the problems", "समस्याओं के समाधानों पर बैठक हुई", "9 7 6 4 1 3"),
    ("The seed germinates in the soil", "बीजों से पौधे उगते हैं", "2 2 4 2 2"),
    ("The agreement is one sided", "समझौता एकतरफा है", "1 2 2"),
    ("The collision of the two buses was inevitable", "दोनों बसों की टक्कर अपरिहार्य थी", "1 2 2 3 4 2"),
    ("The remains are found in the hills", "अवशेष पाये गए पहाड़ियों में", "1 2 3 5 3"),
    ("The proof of existence was shown", "विद्यमान प्रमाण दिखाया गया", "1 2 3 3 3"),
    ("The clash of opinions spoils the talk", "राय का टकर बहस बिगाड़ता है", "2 2 1 3 4 3 3"),
    ("The special contribution of the doctor was honored", "चिकित्सक के विशेषयोगदान का सम्मान हुआ", "1 2 3 5 4 2 2"),
    ("The lamp lit the corners of the room", "दीपक ने कमरे के कोनों को रोशन किया", "1 2 3 2 4 4 4 5 2"),
    ("The miners went into the pit", "खनिकों ने खदान में प्रवेश किया", "1 2 3 4 4 5 2"),
    ("The hen laid an egg", "मुर्गी ने अंडा दिया", "1 2 3 2"),
    ("Current affairs are asked in the exam", "परीक्षा में सामयिक ज्ञान पूछा जाता है", "4 3 0 1 5 5 2 2"),
    ("Heavy rains occurred in the provinces", "प्रदेशों में भारी बारिश हुई", "4 3 0 1 2"),
    ("The excuses of the student did not work", "छात्र के बहाने नहीं चले", "1 2 3 5 3"),
    ("The cinematography of the film won praise", "चलचित्र की छायांकन की प्रशंसा हुई", "1 2 2 3 4 2 2"),
    ("The perennial river never dries", "बारहमासी नदी कभी नहीं सूखती", "0 1 5 4 2 2"),
    ("The duties of the post are written", "पद के दायित्वों का उल्लेख है", "1 2 3 4 5 2 2"),
    ("The wolves howled in the night", "भेड़िये रात में दहाड़े", "1 4 4 2"),
    ("The proposal was late yet it passed", "प्रस्ताव देर से आया तथापि पारित हुआ", "1 5 3 2 6 3 2 2"),
    ("The customs of the tribe are strict", "जनजाति के रीतिरिवाजों में कठोरता है", "1 2 3 4 5 2 2"),
    ("The important thing is honesty", "गौरतलब बात ईमानदारी है", "0 1 2 2 2"),
    ("The birds were freed from the cages", "पिंजरे से पक्षी आज़ाद किए गए", "5 3 4 4 3 3 3"),
    ("The details are as follows", "विवरण निम्नानुसार है", "1 2 2"),
    ("These kinds of fruits are sweet", "इस किस्में के फल मीठे होते हैं", "2 2 3 1 4 4 2"),
    ("The aspirant worked hard", "प्रत्याशी ने कड़ी मेहनत की", "1 2 3 3 2 2"),
    ("The false promise broke hearts", "झूठा वादा दिल तोड़ता है", "0 1 3 2 2"),
    ("The sensory nerves send signals", "संवेदी तंत्रिकाएँ संकेत भेजती हैं", "0 1 2 3 2 2"),
    ("The society becomes strong with coexistence", "सहनिर्माण से समाज मज़बूत होता है", "5 4 1 3 2 2"),
    ("The jugglery of words does not last", "शब्दों की पैंतरेबाज़ी ज़्यादा नहीं चलती", "2 2 1 4 5 3 4"),
    ("The boat was taken on rent", "नाव भाड़े पर ली गई", "1 2 4 3 3 3"),
    ("The NGO opened a school", "गैरसरकारी संस्था ने विद्यालय खोला", "0 1 2 5 2"),
    ("The revolt crushed the peasants", "विद्रोह ने किसानों को कुचल दिया", "1 2 3 4 3 3 2"),
    ("The subspecies differs slightly", "उपप्रजाति में थोड़ा अंतर होता है", "1 3 3 4 4 4 2"),
    ("The directors decided to expand", "निदेशकों ने विस्तार का निर्णय लिया", "1 2 2 3 4 2 2"),
    ("The angular speed of the wheel changed", "पहिये की कोणीय गति बदली", "3 2 1 2 2"),
    ("The loans of the farmers were waived", "किसानों के ऋणों में छूट दी गई", "2 2 3 5 3 3 3"),
    ("The servants of the temple were old", "मंदिर के सेवकों में बुज़ुर्ग थे", "1 2 4 5 3 3"),
    ("The fond boy collected old coins", "शौकीन लड़के ने पुराने सिक्के जमा किए", "1 2 3 4 5 3 3"),
    ("The recommendations of the committee were acted upon", "समिति की सिफारिशों पर अमल हुआ", "4 2 1 6 7 6"),
    ("The talent of the child is inborn", "बच्चे की प्रतिभा जन्मजात है", "2 2 3 4 2"),
    ("The fragrance spread in the garden", "बगीचे में सौरभ फैल गया", "4 3 0 3 3"),
    ("The surface of the earth trembled", "भूतल काँपने लगा", "2 1 2"),
    ("The initiatives of the youth succeeded", "युवाओं की पहलों को सफलता मिली", "2 2 3 4 4 4"),
    ("The styles of painting differ by region", "चित्रकारी की शैलियाँ क्षेत्र से बदलती हैं", "2 2 3 4 3 4 4"),
    ("Good fortune favored the family", "परिवार पर सौभाग्य मुस्कुराया", "1 3 2 4 2"),
    ("Friction produces heat", "घर्षण से गर्मी पैदा होती है", "0 2 1 4 3 3 3"),
    ("The company runs the bus service", "कंपनी बस सेवा चलाती है", "1 2 1 4 2 2"),
    ("The task remained incomplete", "काम अपूर्ण रह गया", "1 3 2 3"),
    ("The viceroy held the court", "वायसराय ने दरबार संभाला", "1 2 3 2"),
    ("The syllabus is well structured", "पाठ्यक्रम संरचित है", "1 2 2"),
    ("Tuberculosis is a curable disease", "तपेदिक एक साध्य रोग है", "0 3 2 4 2"),
    ("The producers got fair prices", "उत्पादकों को उचित दाम मिले", "1 2 3 3 3 3"),
    ("The hooligan was caught by the police", "बदमाश पुलिस के हाथों पकड़ा गया", "1 2 2 5 4 3 3"),
    ("The lamppost fell in the storm", "आँधी में प्रकाशस्तंभ गिर गया", "3 3 4 2 3"),
    ("The soldier is not afraid of fighting", "सैनिक लड़ने से नहीं डरता", "1 4 3 3 2 2"),
    ("The activation of the scheme took time", "योजना के सक्रियण में समय लगा", "1 2 3 4 5 3"),
    ("The company earns in crores", "कंपनी करोड़ में कमाती है", "1 4 3 2 2"),
    ("The wards of the hospital were cleaned", "अस्पताल के वार्डों की सफ़ाई हुई", "2 2 3 4 4 2 2"),
    ("The vector has direction", "सदिश में दिशा होती है", "1 3 2 2 2"),
    ("These medicines cure the fever", "ये दवाएं बुख़ार में काम आती हैं", "1 2 3 4 3 3 2"),
    ("The uncontrollable horse threw the rider", "अनियंत्रित घोड़े ने सवार गिरा दिया", "0 1 2 4 4 3 3 3"),
    ("The abbot blessed the pilgrims", "मठाधीश ने तीर्थयात्रियों को आशीर्वाद दिया", "1 2 4 4 5 2 2"),
    ("The suicidal tendency needs counseling", "आत्मघाती प्रवृत्ति में परामर्श चाहिए", "0 1 4 4 2 2"),
    ("The rule was generalized", "नियम सामान्यीकृत किया गया", "1 3 2 3"),
    ("The inscriptions speak of the king", "शिलालेखों से राजा का उल्लेख मिलता है", "3 2 4 2 3 5 5 2"),
    ("The chemist synthesized a new compound", "रसायनज्ञ ने नया यौगिक संश्लेषित किया", "1 2 3 4 5 2 2"),
    ("The distributor delivered the goods", "वितरक ने माल पहुंचाया", "1 2 3 2"),
    ("The towel dried the body", "अँगोछे ने शरीर पोंछा", "1 2 3 2"),
]

# tense boosters (checker-matching constructions)
T = [
    ("The shepherd was playing the flute", "ग्वाला बांसुरी बजा रहा था", "1 5 4 3 2"),
    ("The old woman was sweeping the courtyard", "बुज़ुर्ग औरत आँगन बुहार रही थी", "0-1 2 5 4 3 2"),
    ("The fox was watching the grapes", "लोमड़ी अंगूर देख रही थी", "1 3 2 2 2"),
    ("The girls will be plucking mangoes", "लड़कियाँ आम तोड़ रही होंगी", "1 3 3 3 2"),
    ("The cows will be returning from the pond", "गायें तालाब से लौट रही होंगी", "1 5 3 4 3 2"),
    ("The farmer will be watering the field", "किसान खेत में पानी दे रहा होगा", "1 5 4 3 3 3 2"),
    ("The weaver will be weaving the cloth", "बुनकर कपड़ा बुन रहा होगा", "1 3 3 3 2"),
    ("The teacher has given the lesson", "शिक्षक ने पाठ दिया है", "1 2 5 3 2"),
    ("The farmer has sown the seeds", "किसान ने बीज बोया है", "1 2 5 3 2"),
    ("The workman has built the wall", "राज मिस्त्री ने दीवार बनाई है", "1-2 2 5 3 2 2"),
    ("The girl has milked the cow", "लड़की ने गाय दुही है", "1 2 4 3 2"),
    ("The boys have thrown the ball", "लड़कों ने गेंद फेंकी है", "1 2 4 3 2"),
    ("The potter had fired the pots", "कुम्हार ने घड़े पकाए थे", "1 2 5 3 2"),
    ("The gardener had planted the roses", "माली ने गुलाब लगाए थे", "1 2 5 3 2"),
    ("The servant had closed the gate", "नौकर ने द्वार बंद किया था", "1 2 5 3 3 2"),
    ("The tailor had stitched the clothes", "दर्ज़ी ने कपड़े सिले थे", "1 2 5 3 2"),
    ("The farmer will have reaped the harvest", "किसान फसल काट चुका होगा", "1 5 3 3 3 2"),
    ("The girls will have drawn the water", "लड़कियाँ पानी खींच चुकी होंगी", "1 3 3 3 2"),
    ("The birds will have reached the nest", "पक्षी घोंसला पहुंच चुके होंगे", "1 4 3 3 3 2"),
    ("The mother will have fed the baby", "माँ शिशु को खिला चुकी होगी", "1 3 3 3 3 2"),
    ("The clerk will have written the ledger", "लिपिक ने बही लिख ली होगी", "1 2 5 3 3 2"),
]

out = []
def add(en, hi, align):
    out.append({"id": f"k{len(out)+1:03d}", "en": en, "hi": hi, "align": align})
for e, h, a in N:
    add(e, h, a)
for e, h, a in T:
    add(e, h, a)

import importlib.util
spec = importlib.util.spec_from_file_location("ga", ROOT / "scripts" / "gen_align.py")
ga = importlib.util.module_from_spec(spec); spec.loader.exec_module(ga)

def ok(s):
    a = s.get("align")
    if not a:
        return False
    toks = a.split(); en = s["en"].split(); hi = s["hi"].split()
    if len(toks) != len(hi):
        return False
    return all(pp.isdigit() and int(pp) < len(en)
               for t in toks for pp in re.split(r"[-,]", t))

bad = []
for s in out:
    if not ok(s):
        bad.append(s["id"])
        s["align"] = ga.derive(s["en"], s["hi"])
print(f"valid: {sum(ok(s) for s in out)}/{len(out)} (derived for: {' '.join(bad) or 'none'})")

(ROOT / "data" / "phrases18.json").write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n")
man = json.load(open(ROOT / "data" / "manifest.json"))
man["files"] = [f for f in man["files"] if f["file"] != "data/phrases18.json"] + [
    {"file": "data/phrases18.json", "count": len(out)}]
json.dump(man, open(ROOT / "data" / "manifest.json", "w"), ensure_ascii=False, indent=2)
print(f"wrote {len(out)} sentences -> data/phrases18.json")
