"""Generate data/phrases20.json — Batch 5 (missing2, rank 5001+).
Skips (exceptions): सैक्स बांड लोडिंग यूनियनों (English-origin).
"""
import json, re
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
N = [
    ("The tiger of the forest became extinct", "वन का बाघ लुप्त हो गया", "1 2 1 3 3 3 3"),
    ("The teacher of the school retired", "शिक्षिका विद्यालय से सेवानिवृत्त हुईं", "1 4 3 3 5 2"),
    ("To whom did you give the book", "जिसको किताब दी थी", "3 3 3 2 2"),
    ("Habits decide the fate", "आदतों से नसीब बनता है", "2 2 3 2 2 2"),
    ("The team is hardworking", "टीम कार्यशील है", "1 2 2"),
    ("The joints of the body ached", "शरीर की संधियों में दर्द उठा", "2 2 3 4 5 4 2"),
    ("The drunkard ruined the house", "शराबी ने घर बर्बाद किया", "1 2 3 4 4 2"),
    ("Consolidation saves resources", "समेकन से संसाधन बचते हैं", "0 2 3 3 3 2"),
    ("Forwarding of letters is done here", "पत्रों का अनुप्रेषण यहाँ होता है", "1 2 3 4 3 5 2"),
    ("The landmark of the city is the fort", "नगर का स्थलचिह्न किला है", "2 2 3 1 2 2"),
    ("The mason went to build the wall", "राज मिस्त्री दीवार बांधने गया", "1-2 1 3 3 3 2"),
    ("The feat came in headlines", "कारनामा सुर्खियों में आया", "1 3 3 2 2"),
    ("The nationalists commemorated the leader", "राष्ट्रवादियों ने नेता को याद किया", "1 2 3 4 5 2 2"),
    ("Public relations matter in politics", "राजनीति में जनसंपर्क ज़रूरी है", "3 3 1 4 2"),
    ("The objectionable scene was removed", "आपत्तिजनक दृश्य हटा दिया गया", "0 1 3 3 3 3 3"),
    ("The priests debated the text", "ब्राह्मणों ने शास्त्र पर वाद किया", "1 2 4 3 5 5 2"),
    ("The tasks remain incomplete", "काम अधूरे रह गए", "1 3 2 3 3"),
    ("The women of the village protested", "गाँव की स्त्रियों ने विरोध किया", "2 2 3 1 4 5 2"),
    ("The newly built road opened", "नवनिर्मित सड़क खुल गई", "0 1 2 3 3 3"),
    ("The breeze was gentle", "समीर सौम्य बह रही थी", "1 2 3 3 2 2"),
    ("The elements of nature are five", "प्रकृति के तत्त्व पाँच माने जाते हैं", "1 2 3 5 4 4 5 5 2"),
    ("The leftist party protested", "वाम दल ने विरोध किया", "0 1 2 4 5 2"),
    ("The rivers flood in monsoon", "मानसून में नदियां उफान पर आती हैं", "4 3 1 5 5 4 4 2"),
    ("The friend stood by me", "यार मेरे काम आया", "1 3 3 3 2"),
    ("The witness told the truth", "साक्षी ने सच बताया", "1 2 3 3 3"),
    ("The theologians interpreted the verse", "धर्मशास्त्री ने श्लोक की व्याख्या की", "1 2 3 4 4 4 2 2"),
    ("The function went smoothly", "कार्यक्रम सुचारू चला", "1 3 2 2"),
    ("The inspiration of the guru worked", "गुरु की प्रेरण से मार्ग बना", "1 2 3 3 4 5 2"),
    ("Money is not everything", "द्रव्य सब कुछ नहीं होता", "1 3 3 3 3 4 2"),
    ("The girl won the prize", "बालिका ने पुरस्कार जीता", "1 2 3 3 2"),
    ("The plan is stepwise", "योजना चरणबद्ध है", "1 2 2"),
    ("The fifth chapter is tough", "पाँचवें अध्याय में कठिनाई है", "0 1 4 4 4 2"),
    ("The thinker wrote many books", "विचारक ने अनेक पुस्तकें लिखीं", "1 2 3 4 5 2 2"),
    ("The truth is unpleasant", "सच अप्रिय होता है", "1 2 3 3 2"),
    ("The amount was sanctioned", "रकम मंज़ूर हुई", "1 3 2 2"),
    ("Self rule was the dream", "स्वराज सपनों की मंज़िल था", "0 1 2 2 3 4 2 2"),
    ("The policy is inclusive", "नीति समावेशी है", "1 2 2"),
    ("The stone age tools were found", "नवपाषाण उपकरण मिले", "1-2 2 3 2 2"),
    ("The recipients got the relief", "प्राप्तकर्ताओं को राहत मिली", "1 2 3 3 3 3"),
    ("The naturalist studied birds", "प्रकृतिवादी ने पक्षियों का अध्ययन किया", "1 2 3 4 2 5 5 2"),
    ("The workload increased", "कार्यभार बढ़ गया", "1 3 3 3"),
    ("Rupees were counted", "रूपए गिने गए", "1 3 3 3"),
    ("The peaks are covered with snow", "ऊंचाइयों पर बर्फ़ जमी है", "5 3 1 3 3 2 2"),
    ("Empowerment of women is necessary", "स्त्रियों का सशक्तिकरण आवश्यक है", "1 2 3 4 2 2"),
    ("The syllables make the word", "शब्दांश मिलकर शब्द बनाते हैं", "0 2 2 1 3 3 2 2"),
    ("The corridor joins the rooms", "गलियारा कमरों को जोड़ता है", "1 4 3 3 3 3 2"),
    ("The correlation of study and marks is clear", "पढ़ाई और अंकों का सहसंबंध स्पष्ट है", "2 3 3 2 1 4 4 2 2"),
    ("The explorer went to the peak", "अन्वेषक शिखर पर पहुंचा", "1 4 3 2 2"),
    ("The lizard sat on the wall", "छिपकली दीवार पर बैठी", "1 3 3 3 2"),
    ("The heat reached its peak", "गर्मी चरमोत्कर्ष पर पहुंची", "1 3 3 2 2 2"),
    ("The magnet attracts iron", "चुंबक लोहे को खींचता है", "1 3 2 3 3 3 2"),
    ("The back of the animal is strong", "पशु का पश्च भाग बलवान होता है", "1 2 1 2 3 4 4 4 2"),
    ("The cone shaped hut stood", "शंकुधारी तम्बू खड़ा था", "0 1 2 3 2 2"),
    ("The eastern culture is old", "प्राच्य संस्कृति प्राचीन है", "0 1 2 3 2"),
    ("The family adopted the child", "परिवार ने बच्चे को अपनाए रखा", "1 2 3 4 5 5 3 3"),
    ("The affair reached its conclusion", "मामला परिणति पर पहुंचा", "1 2 3 2 2 2"),
    ("The sentries guarded the gate", "चौकियों ने द्वार संभाला", "1 2 4 2"),
    ("The prime minister addressed the nation", "प्रधानमन्त्री ने देश को संबोधित किया", "1-2 2 3 4 5 5 2"),
    ("The analysts discussed the budget", "विश्लेषकों ने बजट पर बहस की", "1 2 3 4 5 5 2"),
    ("The bees make honey", "मधुमक्खियों से शहद बनता है", "1 2 3 3 3 3 2"),
    ("The law was unconstitutional", "कानून असंवैधानिक घोषित हुआ", "1 2 2 3 3 2"),
    ("The prophet preached peace", "नबी ने शांति का संदेश दिया", "1 2 3 2 3 3 2 2"),
    ("The amounts are equal", "रकमें समस्थानिक हैं", "1 2 2"),
    ("The statements caused noise", "बयानबाजी से शोर मचा", "1 3 3 4 2 2"),
    ("The mountain range blocks the clouds", "पर्वतमाला बादलों को रोकती है", "1 1 2 2 3 3 3 3 2"),
    ("The students will get books", "छात्र पुस्तकें पाएंगे", "1 3 3 3 3"),
    ("The media shapes opinion", "माध्यमों से जनमत बनता है", "2 2 3 2 3 3 2"),
    ("The war changed the map", "विश्वयुद्ध ने नक्शा बदला", "1 2 4 3 3 3"),
    ("The dense forest frightened", "घोर जंगल से डर लगता था", "0 1 3 3 3 3 3 2 2"),
    ("The anger of the public grew", "जनता की नाराजगी बढ़ी", "1 2 3 4 4"),
    ("The treatments are costly", "उपचारों का खर्चा बढ़ा", "1 2 2 4 4 4"),
    ("The seasons rotate", "मौसमों में चक्र चलता है", "1 2 3 3 3 3 2"),
    ("Grandfather grandmother told stories", "दादादादी कहानियाँ सुनाते थे", "0-1 2 3 3 3 2 2 2"),
    ("The circles of society are many", "समाज के हलकों में बात फैली", "1 2 3 4 5 5 2 2"),
    ("The hatred act is condemnable", "घृणित कृत्य निंदनीय है", "0 1 2 3 2"),
    ("The deaf child learns fast", "बधिर बच्चा जल्दी सीखता है", "0 1 1 3 3 3 3 2 2"),
    ("The scriptures are deep", "शास्त्रों में गहराई है", "1 3 3 3 2 2"),
    ("The wait seemed endless", "इंतज़ार अंतहीन लगा", "1 3 2 2 2"),
    ("The poetry collection released", "कवितासंग्रह प्रकाशित हुआ", "1 2 3 2 2"),
    ("The traditional dress is comfortable", "पारम्परिक पोशाक आरामदायक है", "0 1 2 3 2"),
    ("Peace talks began", "शान्ति वार्ता शुरू हुई", "0 1 2 3 2 2"),
    ("The crowd gathered around the singer", "गायक को घेरने भीड़ जुटी", "1 2 3 4 3 4 2 2"),
    ("The scratch on the skin faded", "त्वचा पर खरोंच का निशान रहा", "2 3 1 4 2 5 5 2"),
    ("The dynasties ruled long", "राजवंशों ने लंबा शासन किया", "1 2 3 4 5 5 2"),
    ("The statements are contradictory", "बयान विरोधाभासी हैं", "1 2 2"),
    ("The manuscript lies in the library", "पांडुलिपि पुस्तकालय में अवस्थित है", "1 3 4 4 3 2"),
    ("The lament of widow moved all", "विधवा का विलाप सबको रुला गया", "1 2 3 4 5 4 4 2 2"),
    ("Fiscal deficit rose", "राजकोषीय घाटा बढ़ा", "0 1 2 3 3"),
    ("The underground water fell", "भूगर्भीय जल स्तर गिरा", "0 1 2 3 4 4 3 3"),
    ("The separatists were arrested", "अलगाववादी गिरफ़्तार हुए", "1 3 2 2 2 2"),
    ("The proposers of plan met", "योजना के प्रस्तावक मिले", "2 2 3 4 2 2"),
    ("Disregard of elders is bad", "बुज़ुर्गों की अवहेलना बुरी है", "1 2 3 4 4 2 2"),
    ("The upbringing shapes character", "परवरिश से चरित्र बनता है", "1 2 3 3 3 3 3 2"),
    ("The raids caught the smugglers", "छापों में तस्कर पकड़े गए", "1 3 3 3 3 3 3 2"),
    ("The savings grew", "संचयी निधि बढ़ी", "0 1 2 2 2 3"),
    ("The recommendations came", "सिफारिशें आ गईं", "1 3 2 2 2"),
    ("The disasters struck the coast", "आपदाओं ने तट प्रभावित किया", "1 2 3 4 5 5 2 2"),
    ("The tenure is unspecified", "अवधि अनिर्दिष्ट है", "1 2 2"),
    ("The machine is defective", "यंत्र दोषपूर्ण है", "1 2 2 2"),
    ("The dice is loaded", "पासा भारित है", "1 2 2"),
    ("The rainforest is dense", "वर्षावन घना होता है", "1 2 3 3 2"),
    ("The torch lit the path", "मशाल से रास्ता दिखा", "1 3 3 3 2 2"),
    ("The presidents met", "राष्ट्रपतियों की बैठक हुई", "1 2 3 2 2 2"),
    ("The entrepreneurs invested", "उद्यमियों ने पूँजी लगाई", "1 2 3 3 3 3 3 2"),
    ("Aviation grew rapidly", "वैमानिकी तेज़ी से बढ़ी", "0 2 3 3 3 4 4"),
    ("The upper floor is cooler", "उच्चतर मंज़िल ठंडी होती है", "1 1 2 3 4 4 4 2 2"),
    ("The administrators were warned", "प्रशासकों को चेताया गया", "1 2 3 3 3 3"),
    ("Wish knows no bounds", "चाहना ठिकाने नहीं रहती", "0 2 3 3 4 4 2 2"),
    ("The rice is cooked", "चावल पकाना आसान है", "1 2 4 2 2"),
    ("Bravo the team played well", "शाबाश टीम ने अच्छा खेला", "0 1 2 3 4 5 2"),
    ("The guests went to taste the dish", "मेहमान स्वाद चखाने आए", "1 2 3 3 3 2"),
    ("Grandmother blessed the child", "परदादी ने आशीर्वाद दिया", "1 2 3 2 2 2"),
    ("The voice of singer is tuned", "गायक की आवाज़ सधा हुआ है", "1 2 1 2 4 5 5 2 2"),
    ("However he agreed", "हालाँकि उसने हामी भरी", "0 1 2 3 4 2 2"),
    ("Sigh of relief came", "राहत की आह निकली", "0 2 1 3 2 2"),
    ("The applicants waited long", "आवेदकों की कतार लंबी थी", "1 2 2 3 4 4 2 2"),
    ("Affection binds hearts", "प्रीति दिलों को जोड़ती है", "0 3 2 2 3 3 2"),
    ("The girls will go to the fair", "लड़कियाँ मेले को जायेंगे", "1 4 3 2 3 3 3"),
    ("The fellow artist helped", "सहकलाकार ने मदद की", "0-1 1 2 4 2 2"),
    ("The authenticity was proved", "प्रामाणिकता की परीक्षा हुई", "1 2 3 4 2 2 2"),
    ("Monarchy declined", "राजतंत्र समाप्त हुआ", "0 3 2 2 2 2"),
    ("The anthropologist studied tribes", "मानवविज्ञानी ने जनजातियों का अध्ययन किया", "1 2 3 4 2 5 5 2"),
    ("The night passed", "रात व्यतीत हुई", "1 3 2 2 2 2"),
    ("May you all know what the truth is", "आप सब जानें कि सच क्या है", "1 2 3 4 6 4 7"),
    ("The children went to scare the crows", "बच्चे कौवों को डराने गए", "1 4 3 3 3 2 2"),
    ("The intent of the letter is clear", "पत्र का आशय स्पष्ट है", "1 2 3 4 2 2"),
    ("The cycles of time rotate", "समय के चक्रों में बदलाव आता है", "1 2 3 4 5 6 4 4 2"),
    ("Polymer is a long chain", "बहुलक लंबी श्रृंखला है", "1 3 2 3 3 2"),
    ("The ocean currents shifted", "महासागरीय धाराएँ बदलीं", "0 1 2 2 2 2 2"),
    ("The spectrum shows colors", "वर्णक्रमीय किरणें रंग दिखाती हैं", "0 1 2 3 3 3 3 3 2"),
    ("Access to fort is difficult", "किले तक अभिगम कठिन है", "0 3 1 2 2 2"),
    ("The capitals grew", "राजधानियों की आबादी बढ़ी", "1 2 2 4 4 4"),
    ("The blind man crossed the road", "अंधा व्यक्ति सड़क पार कर गया", "0 1 1 4 3 3 3 3 2 2"),
    ("The tent was pitched", "तम्बू गाड़ा गया", "1 3 2 3 3"),
    ("The republics adopted the charter", "गणराज्यों ने संविधान बनाया", "1 2 3 3 3 3 2 2"),
    ("The clan met at the fair", "गोत्र की सभा मेले में हुई", "1 2 3 6 3 4 2 2 2"),
    ("Rethinking is needed", "पुनर्विचार की ज़रूरत है", "0 2 2 3 2 2"),
    ("Expressions of joy are many", "खुशी की अभिव्यक्तियों में विविधता है", "1 2 2 3 4 5 6 2 2"),
    ("Join the two ropes", "दो डोरियाँ जोड़ें", "2 3 1 2 2"),
    ("Drinking water is scarce", "पेयजल दुर्लभ है", "1 2 2 2 2 2"),
    ("The cattle wandered in search of grass", "मवेशी घास की खोज में भटकने लगे", "1 4 2 2 3 3 3 4 4 2 2"),
    ("The criticisms were noted", "आलोचनाओं को दर्ज किया गया", "1 2 3 3 3 2 3 3"),
    ("The data is objective", "आँकड़े वस्तुनिष्ठ हैं", "1 2 2 2"),
    ("The systems need reform", "व्यवस्थाओं में सुधार चाहिए", "1 2 2 2 2 2"),
    ("The act is immoral", "कृत्य अनैतिक है", "1 2 2"),
    ("The effort is praiseworthy", "प्रयास प्रशंसनीय है", "1 2 2 2 2"),
    ("The shares were sold", "अंशों की बिक्री हुई", "1 2 2 3 2 2"),
    ("The bowlers bowled splendidly", "गेंदबाजों ने शानदार गेंदबाज़ी की", "1 2 3 2 2 2"),
    ("The boat capsized", "नाव उल्टी हो गई", "1 3 3 3 3 3"),
    ("The modeling of data is new", "आँकड़ों का प्रतिरूपण नई विधि है", "1 2 3 0 3 4 5 2 2 2"),
    ("The stigma of caste is deep", "जाति का कलंक गहरा है", "1 2 1 3 3 4 4 2"),
    ("The seasons are cyclic", "ऋतुएँ चक्रीय होती हैं", "1 2 2 2 2 2 2"),
    ("The axe cut the tree", "कुल्हाड़ी से पेड़ कटा", "1 2 3 3 3 3 3"),
    ("The witch cursed the king", "चुड़ैल ने राजा को श्राप दिया", "1 2 3 4 5 3 2 2"),
    ("The fort is fortified", "किला किलेबंद है", "1 1 2 2"),
    ("The problem is temporary", "समस्या तात्कालिक है", "1 2 2 2 2"),
    ("The nomads moved with herds", "खानाबदोश झुंड के साथ घूमते हैं", "1 4 2 2 3 3 4 4 2 2"),
    ("The scorpion stung", "बिच्छू ने डंक मारा", "1 2 3 3 3 3"),
    ("The bile aids digestion", "पित्त पाचन में सहायक है", "1 4 3 4 3 3 2 2 2"),
    ("The former player coached", "भूतपूर्व खिलाड़ी ने प्रशिक्षण दिया", "0 1 2 3 4 5 3 2 2"),
    ("Synonyms enrich language", "पर्यायवाची शब्द भाषा समृद्ध करते हैं", "0 1 1 2 3 3 3 3 2 2"),
    ("The champion is unbeatable", "विजेता अजेय है", "1 2 2 2"),
    ("The texts are commentaries", "ग्रन्थों में टीकाएँ हैं", "1 3 2 2 2 2"),
    ("The curse followed the family", "अभिशाप ने परिवार का पीछा किया", "1 2 3 2 3 4 5 2 2 2"),
    ("The recycling of waste started", "कचरे का पुनर्चक्रण शुरू हुआ", "1 2 3 4 4 2 2 2"),
    ("The prosecution presented case", "अभियोग में गवाह पेश हुए", "1 3 2 2 3 3 3 2"),
    ("The residue remained in flask", "बर्तन में अवशिष्ट द्रव्य रहा", "2 3 1 2 3 3 3 2 2 2"),
    ("The defendants were acquitted", "प्रतिवादियों को रिहा किया गया", "1 2 3 3 3 3 2 3"),
    ("The charisma of leader pulled crowds", "नेता का करिश्मा भीड़ खींचता है", "1 2 1 2 3 3 3 3 3 3 2"),
    ("The corners of field are unplowed", "खेत के कोणों में जुताई नहीं हुई", "1 2 3 4 3 5 5 5 2 2 2"),
    ("Generalization needs care", "सामान्यीकरण में सावधानी चाहिए", "0 1 3 2 2 2 2 2 2"),
    ("The grief overwhelmed", "दुख से अभिभूत हो गए", "1 2 2 3 2 3 3 3"),
    ("Great personalities were honored", "विभूतियाँ सम्मानित हुईं", "0 1 2 2 2 2 2"),
    ("The conduct shows character", "आचार से चरित्र दिखता है", "1 2 3 3 3 3 3 2"),
    ("The irrigation scheme was launched", "जलग्रहण योजना शुरू हुई", "1 2 4 2 2 2"),
    ("He suppressed the voice", "उसने आवाज़ दबाया", "1 2 3 3 3"),
    ("Spirituality grew with practice", "आध्यात्मिकता साधना से बढ़ती है", "0 1 2 2 2 2 3 3 2 2"),
    ("The replica looked real", "प्रतिरूप असली लगा", "1 3 2 2 2"),
    ("The beating was condemned", "पिटाई की निंदा हुई", "1 2 2 3 2 2 2"),
    ("The redirect happened late", "पत्र पुनर्निर्देशित हुए", "1 3 2 3 3 3 2 2"),
    ("The headache troubled", "सिरदर्द ने परेशान किया", "1 2 3 4 4 2"),
    ("The tenures were extended", "अवधियों में वृद्धि हुई", "1 2 2 3 2 2 2 2"),
    ("The eternal values hold", "सनातन मूल्य टिके रहते हैं", "0 1 2 3 3 3 3 2 2 2"),
    ("The rising sun brings hope", "उभरती सूरज से उम्मीद जागती है", "0 1 1 2 2 2 3 3 3 3 2 2"),
    ("The barter system was old", "अदलाबदली से व्यापार चलता था", "0 1 2 2 3 3 3 3 3 3 2 2"),
    ("The councils met", "मंडलियों की बैठक हुई", "1 2 3 2 2 2"),
    ("The oceans hide treasures", "महासागरों में ख़ज़ाने छिपे हैं", "3 3 4 4 3 2 2 2"),
    ("The new industries are emerging", "नए उद्योग उभरने लगे हैं", "1 1 2 3 3 3 3 2 2 2"),
    ("The far sighted leader planned", "दूरदर्शी नेता ने योजना बनाई", "0 1 2 2 3 4 3 3 2 2"),
    ("The excavation found pottery", "उत्खनन में मिट्टी के बर्तन मिले", "1 3 1 2 2 3 3 2 2 2 2"),
    ("Growth of child is fast", "शिशु का परिवर्धन तेज़ होता है", "1 2 1 2 4 5 4 4 4 2 2"),
    ("The century of progress passed", "प्रगति की शती बीत गई", "1 2 2 3 4 3 3 3 2 2"),
    ("Standardization helps trade", "मानकीकरण से व्यापार सरल होता है", "0 2 1 2 2 2 2 2 2 2 2 2"),
    ("The manager approved leave", "प्रबन्धक ने छुट्टी मंज़ूर की", "1 2 3 3 3 2 2 2 2"),
    ("The skyscraper touched clouds", "गगनचुंबी इमारत बादल छू गई", "0 1 1 3 4 4 3 3 3"),
    ("The child started walking after falling", "गिरकर बच्चा चलना सीखता है", "1 2 1 4 3 4 4 4 2 2 2 2"),
    ("The trouble grows day by day", "परेशानी दिनप्रतिदिन बढ़ती है", "1 2 2 2 2 2 2 2 2 2"),
    ("Undoubtedly he is honest", "निस्संदेह वह ईमानदार है", "0 1 1 3 2 2"),
    ("The acts were passed", "अधिनियमों को मंज़ूरी मिली", "1 2 3 3 3 2 2 2 2"),
    ("The algebraic sum is zero", "बीजगणितीय योग शून्य रहा", "0 1 1 2 3 3 3 3 3 2"),
    ("The fighter sits in corner", "पहलवान आले में बैठा", "1 2 3 3 3 2 2"),
    ("The cattle shed was cleaned", "गोठ साफ़ किया गया", "1 3 2 3 3 3"),
]
T = [
    ("The boys have learned the lesson", "लड़कों ने पाठ सीखा है", "1 2 5 3 2 2"),
    ("The mother has lit the lamp", "माँ ने दीपक जलाया है", "1 2 5 3 2 2"),
    ("The girls had filled the pots", "लड़कियों ने घड़े भरे थे", "1 2 5 3 2 2"),
    ("The farmer had repaired the plough", "किसान ने हल ठीक किया था", "1 2 5 3 3 3 2 2"),
    ("The men will be cutting the crop", "आदमी फसल काट रहे होंगे", "1 5 3 3 3 2 2"),
    ("The girls will be swinging", "लड़कियाँ झूला झूल रही होंगी", "1 3 4 4 3 2"),
    ("The birds will have returned home", "पक्षी घर लौट चुके होंगे", "1 3 3 3 3 2"),
    ("The milkman will have delivered milk", "दूधवाला दूध दे चुका होगा", "1 3 3 3 3 2"),
]
out = []
def add(en, hi, align):
    out.append({"id": f"n{len(out)+1:03d}", "en": en, "hi": hi, "align": align})
for e, h, a in N:
    add(e, h, a)
for e, h, a in T:
    add(e, h, a)
import importlib.util
spec = importlib.util.spec_from_file_location("ga", ROOT / "scripts" / "gen_align.py")
ga = importlib.util.module_from_spec(spec); spec.loader.exec_module(ga)
def ok(s):
    a = s.get("align")
    if not a: return False
    toks = a.split(); en = s["en"].split(); hi = s["hi"].split()
    if len(toks) != len(hi): return False
    return all(pp.isdigit() and int(pp) < len(en) for t in toks for pp in re.split(r"[-,]", t))
bad = []
for s in out:
    if not ok(s):
        bad.append(s["id"]); s["align"] = ga.derive(s["en"], s["hi"])
print(f"valid: {sum(ok(s) for s in out)}/{len(out)} (derived: {' '.join(bad) or 'none'})")
(ROOT / "data" / "phrases20.json").write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n")
man = json.load(open(ROOT / "data" / "manifest.json"))
man["files"] = [f for f in man["files"] if f["file"] != "data/phrases20.json"] + [
    {"file": "data/phrases20.json", "count": len(out)}]
json.dump(man, open(ROOT / "data" / "manifest.json", "w"), ensure_ascii=False, indent=2)
print(f"wrote {len(out)} -> data/phrases20.json")
