"""Generate data/phrases15.json: gap-closing chunk.

- tense boosters (present/past perfect, future/present continuous, subjunctive,
  sakna/pana) aimed at thin rows in scripts/coverage_vakya.py
- verb-form boosters for core verbs lacking future/imperative/continuous forms
- vocab-gap sentences using uncovered rank 2001-5000 words from VAKYA.md

All aligns are hand-authored. Validate with scripts/validate_corpus.py after.
Run once; re-running rewrites the file.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
out = []


def add(en, hi, align):
    out.append({"id": f"h{len(out)+1:03d}", "en": en, "hi": hi, "align": align})


# ---------------- A. present perfect (whitelisted perfective + hai/ho)
G = [
 ("The teacher has completed the syllabus","शिक्षक ने पाठ्यक्रम पूरा किया है","0-1 1 5 4 3 2"),
 ("I have given the message","मैंने संदेश दिया है","0 2 1 1"),
 ("The fields have gotten drenched in the rain","बारिश में खेत भीग गए हैं","7 5-6 1 4 3-4 2"),
 ("He has changed his opinion","उसने अपना मत बदल दिया है","0 3 4 2 1 1"),
 ("The birds have returned to the nest","पक्षी घोंसले लौट आए हैं","0-1 6 3 2 2"),
 ("The guests have finished eating dinner","मेहमान रात का खाना खा चुके हैं","0-1 5 5 4-5 4 5 2"),
 ("I have finished reading the book","मैं किताब पढ़ चुका हूँ","0 5 3 2 1"),
 ("The workers have submitted the application","कार्यकर्ताओं ने अर्ज़ी जमा किया है","0-1 1 5 3 2 2"),
 ("The mason has built the wall","राजमिस्त्री ने दीवार का निर्माण किया है","0-1 1 5 5 3 3 2"),
 ("He has taken the umbrella","उसने छाता लिया है","0 4 2 1"),
 ("The letter has reached the village","चिट्ठी गाँव पहुँच गई है","0-1 5 3 3 2"),
 ("The lamp has gone out in the wind","दीया हवा में बुझ गया है","0-1 7 5-6 4 3-4 2"),
 ("The sisters have reached home","बहनें घर पहुँच गई हैं","0-1 4 3 3 2"),
 ("The seeds have been sown in the field","खेत में बीज बोए गए हैं","7 5-6 0-1 4 3-4 2"),
 ("I have finished singing the song","मैं गीत गा चुका हूँ","0 5 3 2 1"),
 ("The plane has taken off","विमान उड़ चुका है","0-1 3-4 2-3 2"),
]
for e,h,a in G: add(e,h,a)

# ---------------- B. past perfect (perfective + tha/the/thi)
G = [
 ("The sun had set before we arrived","हमारे पहुँचने से पहले सूरज डूब चुका था","5 6 4 3-4 1 3 2-3 2"),
 ("The children had eaten all the sweets","बच्चे सारी मिठाई खा चुके थे","0-1 4 6 3 2-3 2"),
 ("The train had left before I reached","मैं पहुँचने से पहले रेलगाड़ी निकल चुकी थी","5 6 4 3 1 3 2-3 2"),
 ("The clerk had submitted all the papers","लिपिक सारे काग़ज़ जमा कर चुका था","0-1 4 6 3 3 2-3 2"),
 ("The milk had curdled in the heat","गर्मी में दूध जम गया था","6 4-5 1 3 3 2"),
 ("The thieves had fled before the guards came","पहरेदारों के आने से पहले चोर भाग चुके थे","5-6 5 7 4 3-4 1 3 2-3 2"),
 ("The farmer had sold the crop before the price fell","दाम गिरने से पहले किसान फसल बेच चुका था","8 9 6-7 6 1 5 3 2-3 2"),
 ("The letter had arrived before he left the house","उसके घर से जाने से पहले चिट्ठी आ चुकी थी","5 8 7 6 4-5 3-4 0-1 3 2-3 2"),
 ("The lamps had gone out in the storm","तूफ़ान में दीये बुझ चुके थे","7 5-6 0-1 4 2-3 2"),
 ("The women had fetched water before sunrise","सूर्योदय से पहले औरतें पानी ला चुकी थीं","6 5 4-5 1 4 3 2-3 2"),
 ("The students had written the exam before noon","दोपहर से पहले छात्र परीक्षा लिख चुके थे","7 6 5-6 1 4-5 3 2-3 2"),
 ("The old tree had fallen in the storm","तूफ़ान में पुराना पेड़ गिर चुका था","7 5-6 1 2 4 3-4 3"),
 ("The speech had ended before the evening","शाम से पहले भाषण समाप्त हो चुका था","6 5 3-4 1 2 3 2-3 2"),
 ("The pot had broken before the water was filled","पानी भरने से पहले मटका टूट चुका था","5-6 8 4 3-4 1 3 2-3 2"),
 ("The gardener had watered the plants before noon","दोपहर से पहले माली ने पौधों को पानी दे दिया था","7 6 5-6 1 1 4-5 4 4 3 2-3 2"),
 ("The guest had left the village before dawn","भोर से पहले मेहमान गाँव छोड़ चुका था","7 6 5-6 1 5 3 2-3 2"),
]
for e,h,a in G: add(e,h,a)

# ---------------- C. future continuous (raha + hoga)
G = [
 ("Tomorrow evening the women will be planting saplings","कल शाम औरतें पौधे लगा रही होंगी","0 1 2-3 7 6 6 4-5"),
 ("The farmers will be reaping the crop at that time","उस समय किसान फसल काट रहे होंगे","0-2 0-2 3-4 8-9 7 7 5-6"),
 ("The children will be flying kites on the roof","बच्चे छत पर पतंग उड़ा रहे होंगे","0-1 8 6-7 5 4 4 2-3"),
 ("In the morning the cook will be cooking vegetables","सुबह रसोइया सब्ज़ी पका रहा होगा","0-2 3-4 7-8 6 6 4-5"),
 ("The shepherds will be grazing sheep on the hill","पहाड़ पर चरवाहे भेड़ें चरा रहे होंगे","0-2 0-2 3-4 8 7 7 5-6"),
 ("The blacksmith will be beating iron at that time","उस समय लोहार लोहा पीट रहा होगा","0-2 0-2 3-4 8 7 7 5-6"),
 ("In the evening the mother will be feeding the child","शाम को माँ बच्चे को खिला रही होगी","0-2 0-2 3-4 8-9 8 7 7 5-6"),
 ("The washerman will be washing clothes by the river","नदी किनारे धोबी कपड़े धो रहा होगा","0-2 2 3-4 8 7 7 5-6"),
 ("The players will be practicing on the field at that time","उस समय खिलाड़ी मैदान पर अभ्यास कर रहे होंगे","0-2 0-2 3-4 8-10 8-9 7 7 7 5-6"),
 ("The sisters will be singing songs at the wedding","शादी में बहनें गीत गा रही होंगी","0-2 0-2 3-4 8 7 7 5-6"),
 ("By night the travelers will be resting in the inn","रात तक यात्री सराय में आराम कर रहे होंगे","0-1 1 2-3 7-9 7-9 6 6 6 4-5"),
 ("In the morning the teacher will be checking the answer books","सुबह शिक्षक उत्तर पुस्तिकाएँ देख रहा होगा","0-2 3-4 8-9 9-10 7 7 5-6"),
 ("At that time the girls will be drawing water from the well","उस समय लड़कियाँ कुएँ से पानी खींच रही होंगी","0-2 0-2 3-4 10-11 9-10 8 7 7 5-6"),
 ("Tomorrow the village men will be building the bridge","कल गाँव के लोग पुल बना रहे होंगे","0 1-3 1-3 1-3 7-8 6 6 4-5"),
]
for e,h,a in G: add(e,h,a)

# ---------------- D. present continuous (raha + hai)
G = [
 ("The goat is grazing grass in the field","बकरी खेत में घास चर रही है","0-1 7 5-6 4 3 3 2"),
 ("The bird is building a nest","चिड़िया घोंसला बना रही है","0-1 5 3 3 2"),
 ("The calf is drinking milk","बछड़ा दूध पी रहा है","0-1 4 3 3 2"),
 ("The oxen are pulling the cart","बैल गाड़ी खींच रहे हैं","0-1 4-5 3 3 2"),
 ("The sisters are grinding flour","बहनें आटा पीस रही हैं","0-1 4 3 3 2"),
 ("The old man is telling a story under the tree","पेड़ के नीचे बूढ़ा कहानी सुना रहा है","8-9 8 7-8 0-2 5-6 4 3-4 3"),
 ("The women are painting a picture on the wall","औरतें दीवार पर चित्र बना रही हैं","0-1 7-8 6 4-5 3 3 2"),
 ("The child is crying for a toy","बच्चा खिलौने के लिए रो रहा है","0-1 6 4-5 4 3 3 2"),
 ("The crows are cawing on the roof","कौए छत पर काँव काँव कर रहे हैं","0-1 6 4-5 3 3 3 3 2"),
 ("The moon is shining in the sky","आकाश में चाँद चमक रहा है","5-6 4 0-1 3 3 2"),
 ("The farmer is plowing the field","किसान खेत जोत रहा है","0-1 4-5 3 3 2"),
 ("The potter is making pots on the wheel","कुम्हार चाक पर घड़े बना रहा है","0-1 6-7 5-6 4 3 3 2"),
]
for e,h,a in G: add(e,h,a)

# ---------------- E. subjunctive (chaaye / kaash)
G = [
 ("May he pass the exam this time","काश वह इस बार परीक्षा में पास हो जाए","0 1 5-6 5-6 3-4 3 2 2 2"),
 ("May the fields get good rain this year","काश इस साल खेतों को अच्छी बारिश मिल जाए","0 6-7 6-7 1-2 2 4 5 3 3"),
 ("Whether the son stays home or goes to the city the mother keeps worrying","चाहे बेटा घर रहे या शहर जाए माँ चिंता करती है","0 1-2 4 3 5 6-9 6 10-11 13 12-13 12"),
 ("Even if it rains heavily the farmers will work","चाहे मूसलाधार बारिश हो किसान काम करेंगे","0-1 4 2-3 2-3 5-6 8 7-8"),
 ("May the sick person get well soon","काश बीमार जल्दी स्वस्थ हो जाए","0 1-3 5-6 4-5 4 4"),
 ("Whether you believe it or not the truth is the truth","चाहे तुम मानो या न मानो सच सच ही रहेगा","0 1 2 4 5 2 6 10 8 9-10"),
 ("May the guest arrive before evening","काश मेहमान शाम से पहले आ जाए","0 1-2 5 4 4 3 3"),
 ("Even if the price of grain rises the poor will not stop eating","चाहे अनाज का दाम बढ़े गरीब खाना नहीं छोड़ेंगे","0-1 4-5 4 3 6 7-8 12 10-11 11-12"),
 ("May your shadow never leave you","काश तुम्हारा साया कभी न छूटे","0 1 2 3 3 4"),
 ("Even if the road is bad we will reach the village","चाहे रास्ता खराब हो हम गाँव पहुँचेंगे","0-3 1-2 4 3 5 9 7-9"),
 ("May the mango trees give fruit this time","काश आम के पेड़ इस बार फल दें","0 2 2 2-3 6-7 6-7 5 4"),
 ("Whether it is day or night the lamp of the temple keeps burning","चाहे दिन हो या रात मंदिर का दीपक जलता रहे","0-2 3 2 4 5 9-10 9 7 11-12 11-12"),
 ("May the new king rule justly","काश नया राजा न्याय से राज्य करे","0 2 3 5 5 4 4"),
 ("Even if the mother scolds she still wishes well","चाहे माँ डाटे भी वह भला चाहती है","0-1 2-3 4 8 5 6-7 7 7"),
 ("May the granary always remain filled with grain","काश कोठी हमेशा अनाज से भरी रहे","0 1-2 3 7 6-7 5 4"),
 ("Even if the leader comes speeches will not do the work","चाहे नेता आए भी भाषणों से काम नहीं होगा","0-1 2-3 4 4 5 5 10 7-9 8"),
]
for e,h,a in G: add(e,h,a)

# ---------------- F. sakna / paana
G = [
 ("After many days the farmer could buy a pair of oxen","कई दिनों के बाद किसान बैलों की जोड़ी खरीद पाया","1-2 2 3 0 4 10 9 7-8 6 5-6"),
 ("The traveler could not walk due to thirst","प्यास से यात्री चल नहीं सका","7 5-6 1 4 2-3 2-3"),
 ("Can you lift this heavy sack","क्या तुम यह भारी बोरा उठा सकते हो","0 1 3 4 5 2 2 0"),
 ("No one could answer this question","कोई भी इस प्रश्न का उत्तर नहीं दे पाया","0-1 1 4 4-5 4 3 2 2 2-3"),
 ("I will be able to finish this work by evening","मैं यह काम शाम तक निपटा सकूँगा","0 6-7 7 9 8 5 1-5"),
 ("The little child can now climb the stairs alone","छोटा बच्चा अब सीढ़ियाँ अकेला चढ़ सकता है","0-2 2 4 8 5 5 3 3"),
 ("By diligence a poor student can also succeed","मेहनत से गरीब छात्र भी सफल हो सकता है","0-1 1 2-3 4 5 7 7 5-6 5"),
 ("He could not stop his tears","वह अपने आँसू रोक नहीं पाया","0 4 5 3 2 1-2"),
 ("You can see the whole valley from this peak","इस चोटी से तुम पूरी घाटी देख सकते हो","1-2 2 0 3 7 8 5 4-5 4"),
 ("The bird was not able to escape the net","चिड़िया जाल से बच नहीं पाई","0-1 7 7 6 2-5 2-5"),
 ("Only the brave can cross this river","यह नदी केवल निडर ही पार कर सकते हैं","5-6 6 0 1-2 1 4 4 3 3"),
 ("I could not sleep the whole night","मैं पूरी रात सो नहीं सका","0 4-6 4-6 3 2 1-2"),
 ("With practice you can also speak sweetly","अभ्यास से तुम मीठा भी बोल सकते हो","0-1 1 2 6 4 5 3 3"),
 ("The deaf cannot hear and the blind cannot see","बहरे सुन नहीं सकते और अंधे देख नहीं सकते","0-1 3 2 2-3 4 5-6 8 7 7-8"),
 ("After many days the letter could reach home","बहुत दिनों बाद चिट्ठी घर पहुँच पाई","1-2 2 0 3-4 7 6 5-6"),
 ("Everyone can learn this art with a little effort","थोड़ी मेहनत से यह कला सब सीख सकते हैं","7-8 8 1 3 4 0 2 1-2 1"),
]
for e,h,a in G: add(e,h,a)

# ---------------- H. verb-form boosters (dena/lena/dhona/bhagna/pahachanna/chunna)
G = [
 ("The contractor will pay the wages by evening","ठेकेदार शाम तक मज़दूरी देगा","0-1 7 6-7 4-5 2-3"),
 ("Please give water in the glass","कृपया गिलास में पानी दीजिए","0 4-5 3-4 2 1"),
 ("The mother is giving fruits to the children","माँ बच्चों को फल दे रही है","0-1 6-7 6 4 3 3 2"),
 ("Tomorrow he will take his book","कल वह अपनी पुस्तक लेगा","0 1 2 4-5 2-3"),
 ("Take your umbrella along","अपना छाता साथ लो","1 2 3 0"),
 ("The children are taking milk","बच्चे दूध ले रहे हैं","0-1 4 3 3 2"),
 ("He will wash the clothes tomorrow","वह कल कपड़े धोएगा","0 5 3-4 1-2"),
 ("Wash your hands and eat the food","हाथ धोकर खाना खाओ","1-2 0 5-6 4"),
 ("The women are washing clothes by the river","नदी किनारे औरतें कपड़े धो रही हैं","6-7 6-7 0-1 4 3 3 2"),
 ("The mouse will run away on seeing the cat","चूहा बिल्ली को देखकर भागेगा","0-1 7-8 7-8 5-6 2-4"),
 ("The dog ran away on seeing the monkey","बंदर को देखकर कुत्ता भाग गया","6-7 6-7 4-5 1 2-3 2-3"),
 ("The children are running toward the playground","बच्चे खेल के मैदान की ओर भाग रहे हैं","0-1 6 6 5-6 4 4 3 3 2"),
 ("I recognized the fragrance of the wet earth","मैंने गीली मिट्टी की खुशबू पहचान ली","0 6-7 7 4 2-3 1 1"),
 ("Tomorrow you will recognize him","कल तुम उसे पहचान लोगे","0 1 4 2-3 2-3"),
 ("The villagers chose a wise headman","गाँव वालों ने बुद्धिमान सरपंच चुना","0-1 1 2 4 5 3"),
]
for e,h,a in G: add(e,h,a)

print(f"grammar boosters: {len(out)}")

# ---------------- V. vocab-gap sentences (rank 2001-5000 uncovered words, exact forms)
V = [
 ("The critic wrote reviews of the poems","आलोचक ने कविताओं की समीक्षाएँ लिखीं","0-1 1 6 4 3 2"),
 ("The editors published the poems of the playwright","संपादकों ने नाटककार की कविताएँ प्रकाशित कीं","0-1 1 7 5 4 2 2"),
 ("The book of collected works of the authors was released at the event","लेखकों की कृतियाँ अनुमोदित होकर प्रकाशनों में आईं","0-2 4 7 5 6 3 1"),
 ("The research paper throws light on the origin of words","शोध पत्र शब्दावली की व्युत्पत्ति पर प्रकाश डालता है","0-1 5 7 6 2-3 3-4 4"),
 ("Statistical methods explain the use of numbers","सांख्यिकीय तरीके संख्याएँ समझाने में सहायक हैं","0 2 5 3-4 6-7 7"),
 ("The dictionary also contains the vocabulary of dialects","शब्दकोश में बोलियों की शब्दावली भी सम्मिलित है","0 2 3 6 4 7 5"),
 ("Vertical lines were drawn on the black board","श्यामपट्ट पर ऊर्ध्वाधर रेखाएँ खींची गईं","2 3 1 0 4-5 5"),
 ("The postgraduate student is doing research on ancient poems","स्नातकोत्तर छात्र पुरानी कविताओं पर शोध कर रहा है","0-1 2 4 6 5 7 7 8"),
 ("New rules were made for the regulation of the market","बाज़ार के विनियमन के लिए नए नियम बनाए गए","0-1 2 5-6 6-7 3 4 1"),
 ("Hand written copies of the stories are safe in the museum","कहानियों की पांडुलिपि संग्रहालयों में सुरक्षित है","0 3 4 6 5 7"),
 ("The rights of the disabled are protected by law","विकलांगों के अधिकार विधान से सुरक्षित हैं","0 2-3 3 5 6 4 7"),
 ("The continuity of the program did not break","कार्यक्रम की निरंतरता नहीं टूटी","0 3 4 2 1"),
 ("After the coronation the king entered the fort","राज्याभिषेक के बाद राजा ने दुर्ग में पदार्पण किया","0 2-3 3-4 1 6 5 7"),
 ("The revival of old crafts is going on","पुराने शिल्प का पुनरुद्धार जारी है","0-2 3 4 5 6"),
 ("The rebuilt bridge connects the two villages","पुनर्निर्मित पुल दोनों गाँवों को जोड़ता है","0-1 2 5-6 4 3 7"),
 ("The difference of opinions is natural in debate","विचारविमर्श में भिन्नता स्वाभाविक है","1 2 4 3 0"),
 ("The culprit was caught by the guards","अपराधी पहरेदारों द्वारा पकड़ा गया","0 3-4 4 2 2"),
 ("Funds are needed for the construction of the hospital","अस्पताल के विनिर्माण के लिए धन चाहिए","0 2 5-6 6-7 4 3"),
 ("The government arranged money for the project","सरकार ने परियोजना के वित्तपोषण की व्यवस्था की","0-1 1 3 6-7 7 4 5"),
 ("The destructive storm ruined the crop","विनाशकारी तूफ़ान ने फसल बर्बाद कर दी","0-1 1 3 4 2 5"),
 ("The army chief foiled the coup","सेना प्रमुख ने तख्तापलट नाकाम कर दिया","0-1 1 1 3 4 2 5"),
 ("The excellence of classical music is famous","शास्त्रीय संगीत की उत्कृष्टता प्रसिद्ध है","0-2 3-4 4 5 6"),
 ("The ideology of the party keeps changing","दल की विचारधारा बदलती रहती है","0-1 2 4 5 3"),
 ("The group of islands lies in the sea","समुद्र में द्वीपसमूह स्थित है","1 2 3 0 4"),
 ("The editorial of the newspaper raised the question","अख़बार के संपादकीय ने प्रश्न उठाया","0-1 2 4 5 3 4"),
 ("Telecommunication has connected villages to cities","दूरसंचार ने गाँवों को शहरों से जोड़ दिया है","0 1 4 6 5 7 7 3"),
 ("The plant absorbed water from the soil","पौधे ने मिट्टी से पानी अवशोषित किया","0-1 1 5 4 6 2 3"),
 ("Virtual classes replaced the classroom","आभासी कक्षों ने कक्षा का स्थान लिया","0 2 5 3-4 4 6"),
 ("The renaissance of art began in the cities","कला का पुनरुत्थान शहरों से आरंभ हुआ","0 1 2 3-4 5-6 6"),
 ("The synthesis of both ideas gave a new view","दोनों विचारों के संश्लेषण से नया दृष्टिकोण बना","0 2-3 4-5 5-6 6 7-8 8"),
 ("The acting chairman gave the order","कार्यवाहक अध्यक्ष ने आदेश दिया","0-1 1 1 3 2 4"),
 ("The opposition members walked out of the house","विपक्षी सदस्य सदन से बाहर चले गए","0-1 2 6 4-5 5 3"),
 ("The pregnant woman needs rest and good food","गर्भवती स्त्री को आराम और अच्छा भोजन चाहिए","0-1 2 3 4-5 6-7 7-8 8"),
 ("Scientific methods strengthen the system","वैज्ञानिक विधियों से प्रणाली मज़बूत होती है","0 2-3 3 4 5 6"),
 ("The middle benches of the school were repaired","विद्यालय की मध्यवर्ती कतारें मरम्मत कर दी गईं","0 1 3-4 5 6-7 7"),
 ("The presentations of the students were excellent","छात्रों की प्रस्तुतियाँ उत्कृष्ट थीं","0 2-3 4 5 6"),
 ("He is committed to social service","वह समाज सेवा के प्रति प्रतिबद्ध है","0 1-2 2 5 6 4 3"),
 ("The officer got a new designation","अधिकारी को नया पदनाम मिला","0 1 4 2-3 5"),
 ("The manuscript of the novel was found in the archive","उपन्यास की पांडुलिपि अभिलेखागार में मिली","0 1 3 4-5 5 6 2"),
 ("The armored vehicle stopped at the gate","बख्तरबंद गाड़ी द्वार पर रुकी","0-1 2 5 3-4 4"),
 ("His beloved waits for letters","प्रेमिका पत्रों की प्रतीक्षा करती है","0 3 1-2 4 5"),
 ("The scheme is managed by the village council","योजना पंचायत द्वारा प्रबंधित है","0 2 3-4 4 5"),
 ("The responsibility of the post is great","पद की प्रतिबद्धता बड़ी होती है","0 1 2-3 4 5 6"),
 ("There is no justification for this argument","इस तर्क का औचित्य नहीं है","1 2 0 4 5 3"),
 ("The infected patients were kept separately","संक्रमित रोगियों को अलग रखा गया","0-1 2 5 6 3-4 4"),
 ("Immunity protects the body from disease","प्रतिरक्षा शरीर को बीमारी से बचाती है","0 2 3 6 5 4"),
 ("The entry of names in the register is necessary","रजिस्टर में नामों की प्रविष्टि आवश्यक है","1 2 5 3-4 6 7"),
 ("Boxing is a tough game","मुक्केबाजी कठिन खेल है","0 2 1 3"),
 ("Buses run between the two states","दोनों राज्यों के बीच अंतरराज्यीय बसें चलती हैं","3-4 5 6 0-1 2 7 8"),
 ("The queen donated ornaments to the temple","महारानी ने मंदिर को आभूषण दान किए","0-1 1 2 5 6 3 4"),
 ("The reign of the old kingdom is remembered","पुराने राज्य की राजशाही याद की जाती है","0-1 1 2 3-4 5 6 7"),
 ("The study of archaeology reveals the past","पुरातत्व का अध्ययन अतीत को दर्शाने में सहायक है","0 1-2 2 5 3 6 7 8"),
 ("The rewarded compositions of poets are read","कवियों की पुरस्कृत कृतियों का अध्ययन होता है","0 1-2 3 4 6 7"),
 ("The arsenal was guarded day and night","शस्त्रागार की रखवाली दिन रात होती थी","0 2 3 5-6 6 7"),
 ("The batsman hit a long boundary","गेंदबाज ने लंबा षट्क लगाया","0-1 1 3 4 2 5"),
 ("The investigation revealed the secret","अन्वेषण से रहस्य सामने आया","0 2 3 4 5"),
 ("The order was executed immediately","आदेश तत्काल निष्पादित किया गया","0 2-3 1 4 5"),
 ("The letters of the poet were published after his death","कवि की पत्रों का मरणोपरांत प्रकाशन हुआ","0 1 4 5 6 2 7"),
 ("Trust between neighbors is necessary","पड़ोसियों में पारस्परिक विश्वास आवश्यक है","1 2 0 3 4 5"),
 ("The empire was administered by able officers","साम्राज्य कुशल अधिकारियों द्वारा प्रशासित था","0 2 3-4 4-5 5 1"),
 ("In the second half the team played well","उत्तरार्ध में टीम ने अच्छा खेला","2 1 0-1 3 4-5 5"),
 ("Ill treatment of animals is a crime","पशुओं के साथ दुर्व्यवहार अपराध है","0-1 1 3-4 5 6 2"),
 ("The use of solar energy is increasing","सौर ऊर्जा की उपयोगिता बढ़ रही है","0-2 2 3-4 5 6 7"),
 ("Investors put money in new companies","निवेशकों ने नई कंपनियों में धन लगाया","0-1 1 3 5-6 6-7 4 2"),
 ("The by election was held in spring","उपचुनाव बसंत में हुआ","0 2 1 3"),
 ("Do not ignore the advice of elders","बड़ों की सलाह का नज़रअंदाज़ मत करो","0-1 1 2-3 6 5 4 7"),
 ("The sea coast has a high density of ships","समुद्र तट पर जहाज़ों की सांद्रता अधिक है","1 2 0 4-5 6 7 8 9"),
 ("The lecture of the professor was interesting","प्रोफ़ेसर का व्याख्यान रोचक था","0 1 3 2 4 5"),
 ("The protesters gathered at the square","प्रदर्शनकारियों ने चौक पर धरना दिया","0-1 1 2 4-5 5 3"),
 ("The figures of the census surprised everyone","जनगणना के आँकड़ों ने सबको चौंका दिया","0 1 2-3 4 5 6 7"),
 ("The poor man mortgaged his field","गरीब आदमी ने अपना खेत बंधक रखा","0-1 1 1 4 5 3 6"),
 ("The machine was removed from the shed","मशीन फैक्ट्री से हटाई गई","0 3-4 1-2 4 5"),
 ("The refined manners of the prince charmed all","राजकुमार के परिष्कृत व्यवहार ने सबको मोहित किया","0 1 2-3 4 5 6 7 8"),
 ("The left party demanded an inquiry","वामपंथी दल ने जाँच की माँग की","0-1 1 1 3 4-5 5 2 6"),
 ("The travelers crossed the great continent","यात्रियों ने विशाल महाद्वीप पार किया","0-1 1 3 4-5 5 2 6"),
 ("This theory of mathematics is famous","गणित का यह प्रमेय प्रसिद्ध है","0 1 2 3 4 5"),
 ("The train fare is now regulated","अब यात्रा किराया विनियमित है","2 3 0-1 4 5"),
 ("The horizontal line is shorter than the vertical","क्षैतिज रेखा ऊर्ध्वाधर रेखा से छोटी होती है","0 1 4 2 3 5-6 6 7"),
 ("Organic farming improves the soil","कार्बनिक खेती मिट्टी को सुधारती है","0 1 2 3 4 5"),
 ("The warship patrolled the sea border","युद्धपोत समुद्री सीमा पर निकला","0 2 4-5 5 1 6"),
 ("The feminist writer raised her voice for rights","नारीवादी लेखिका ने अधिकारों के लिए आवाज़ उठाई","0-1 1 1 4 5-6 6 3 7"),
 ("The boycott of foreign goods began","विदेशी वस्तुओं का बहिष्कार आरंभ हुआ","0 1-2 3 4 5 6"),
 ("Long discussions are going on in the assembly","सभा में चर्चाओं का दौर जारी है","1 2 3-4 5 6 7 8"),
 ("The reporter asked the minister a question","संवाददाता ने मंत्री से प्रश्न पूछा","0-1 1 1 4 5 2 6"),
 ("The nineteenth century saw many changes","उन्नीसवीं सदी में अनेक परिवर्तन आए","0-1 1 2 5 3-4 6"),
 ("The unveiling of the statue took place","मूर्ति का अनावरण समारोह में हुआ","0 1 2 5 3 6 4"),
 ("This function of science is beyond me","विज्ञान का यह फलन मेरी समझ से बाहर है","0 1 2 3 6-7 7-8 8 5"),
 ("The news of the accident is unbelievable","दुर्घटनाग्रस्त होने की खबर अविश्वसनीय है","0 1-2 2-3 4 5 6 7"),
 ("He raised an objection to the decision","उसने निर्णय पर आपत्ति जताई","0 1 3 2 4 5"),
 ("The scheme is nominal not real","योजना नाममात्र की है वास्तविक नहीं","0 1 3 2 5 4"),
 ("The temple and the mosque came along with the city","मंदिर समेत नगर की इमारतें बनीं","0 3 1 2 4 5"),
 ("Mercury rises in summer heat","गर्मी में पारा चढ़ता है","1 2 0 3 4"),
 ("The acoustic design of the hall is praised","सभागार का ध्वनिक डिज़ाइन की सराहना होती है","0 1 2-3 3 5-6 6 7"),
 ("The statements of politicians often change","राजनेताओं के बयानों में अक्सर बदलाव आता है","0 1-2 3-4 5 6 7 8 9"),
 ("The adventurous youth climbed the peak","साहसिक युवक ने चोटी की ओर चढ़ाई की","0-1 1 1 4 5 2 6-7 7"),
 ("The release of the prisoners was ordered","क़ैदियों की रिहाई का आदेश मिला","0 1 2-3 4 5 6"),
 ("Lime is used in whitewash","सफ़ेदी में चूना काम आता है","1 2 0 3 4 5"),
 ("The architecture of the fort is amazing","किले का वास्तुशिल्प अद्भुत है","0 1 2-3 3 4 5"),
 ("Fungus grows in the rainy season","बरसात में कवक पनपते हैं","1 2 0 3 4"),
 ("The pictorial book delighted the children","सचित्र पुस्तक से बच्चे प्रसन्न हुए","0-1 2 4 5 3 6"),
 ("Drug trafficking is a serious crime","नशीली दवाओं का धंधा गंभीर अपराध है","0-1 1-2 2 3 4 5 6"),
 ("The arrangements were irregular","इंतज़ाम अनियमित थे","0 2 1 3"),
 ("The bird got entangled in the net","चिड़िया जाल में फँस गई","0 3 1 2 4 5"),
 ("The expectations from the meeting were dashed","बैठक से जुड़ी अवधारणाओं को धक्का लगा","0 2 3-4 4-5 5 6 7"),
 ("The disappointing result saddened everyone","निराशाजनक परिणाम से सब दुखी हुए","0 1 2 3 4 5 6"),
 ("Telephones reached every village in the old days","पुराने समय में दूरभाष गाँवों तक पहुँचा","0-1 1 3 2 4-5 5 6"),
 ("The disputed land was measured","विवादित भूमि की नापजोख हुई","0 1 2 3 4 5"),
 ("The accuracy of translation matters","अनुवाद की सटीकता महत्वपूर्ण है","0 1 2-3 3 4"),
 ("Metabolism keeps the body active","चयापचय शरीर को सक्रिय रखता है","0 3-4 4 1 2 5"),
 ("Infiltration on the border increased","सीमा पर घुसपैठ बढ़ गई","2 3 0 1 4 5"),
 ("The veteran player guided the team","दिग्गज खिलाड़ी ने टीम का मार्गदर्शन किया","0-1 1 1 4 5 2 6-7 7"),
 ("The science of mechanics fascinates students","यांत्रिकी का विज्ञान छात्रों को रोमांचित करता है","0 1 1 2 4-5 5 6 7"),
 ("The study of plants is botany","पादपों का अध्ययन वनस्पति विज्ञान है","0 1 1 2 3-4 4-5 5"),
 ("The disciple followed the guru","अनुयायी ने गुरु का अनुसरण किया","0-1 1 1 3-4 4 2 5"),
 ("The notorious dacoit was caught","कुख्यात डाकू पकड़ा गया","0-1 1 3 2 4"),
 ("The explanation of the verse is simple","श्लोक का स्पष्टीकरण सरल है","0 1 2 3 4 5"),
 ("The deaddiction center helps the addicted","नशे के इलाज के लिए प्रतिष्ठान सहायक है","0 1-2 2 3-4 5 6 7 8"),
 ("The rivalry of the two teams is old","दोनों टीमों की प्रतिद्वंद्विता पुरानी है","2-3 3 0-1 4 5 6"),
 ("Guns were seized from the smugglers","तस्करों से बंदूकें बरामद हुईं","0-1 1 2 4 5 3"),
 ("Naked truth is hard to face","नग्न सत्य का सामना कठिन है","0-1 0-1 2 3 4 5"),
 ("The availability of water is a problem","जल की उपलब्धता एक समस्या है","0 1 2-3 3 4 5 6"),
 ("Cognitive ability develops with age","संज्ञानात्मक क्षमता उम्र के साथ विकसित होती है","0 1 2 4 5-6 6 7 8"),
 ("The star of the film became famous","चलचित्र का सितारा प्रसिद्ध हुआ","0 1 2 3 4 5"),
 ("The printing of books is a big trade","पुस्तकों का मुद्रण बड़ा धंधा है","0 1 1-2 2 4 5 3"),
 ("The lord blessed the devotee","प्रभु ने भक्त को आशीर्वाद दिया","0-1 1 1 3-4 4 2 5"),
 ("The murders in the village shocked all","गाँव में हत्याओं ने सबको झकझोर दिया","0 1 2 3-4 4 5 6 7"),
 ("The playwright got the award","नाटककार को पुरस्कार मिला","0 1 3 2 4"),
 ("The bigot does not listen to anyone","कट्टर व्यक्ति किसी की नहीं सुनता","0 1 2 4 5 3 6"),
 ("The prose of the author flows like a river","लेखक का गद्य नदी की तरह बहता है","0 1 1 2 5-6 6-7 7 3-4 4"),
 ("Geometry is a branch of mathematics","ज्यामिति गणित की एक शाखा है","0 2 0-1 3 4 5 6"),
 ("The killer was punished","हत्यारे को दंड मिला","0 2 3 1 4"),
 ("The article on farming was informative","खेती पर आलेख सूचनाप्रद था","0 1 2 3 4 5"),
 ("The departed soul rests in peace","दिवंगत आत्मा को शांति मिले","0-1 1 2 4 5 3"),
 ("The communist spoke for the workers","साम्यवादी ने मज़दूरों के लिए बोला","0-1 1 1 4-5 5-6 6 2 7"),
 ("The front of the army moved ahead","सेना का मोर्चा आगे बढ़ा","0 1 1 2 5 3 4"),
 ("The new projects will employ many","नई परियोजनाएं अनेकों को रोज़गार देंगी","0 1 2 3 5-6 6 4 7"),
 ("Acid burns the skin","अम्ल त्वचा को जला देता है","0 2-3 3 1 4 5 6"),
 ("Repetition makes learning strong","पुनरावृत्ति से सीखना मज़बूत होता है","0 2 3 1 4 5 6"),
 ("The best player of the team retired","टीम का बेहतरीन खिलाड़ी संन्यास ले चुका","0 1 1-2 2 3 5 4 6"),
 ("The memoirs of the veteran are famous","वयोवृद्ध के संस्मरण प्रसिद्ध हैं","0-1 1 2-3 3 4 5"),
 ("A secular state treats all religions equally","धर्मनिरपेक्ष राज्य सभी धर्मों को समान मानता है","0-1 0-1 2 3 4-5 5 6-7 7 8 9"),
 ("Atomic energy is powerful","अणु ऊर्जा शक्तिशाली होती है","0 1 2 3 4"),
 ("The refugee camp was set up at the border","शरणार्थियों के लिए शिविर सीमा पर बना","0 1-2 2 3 5 6-7 7 4 8"),
 ("Indirect answers confuse the mind","अप्रत्यक्ष उत्तर मन को भ्रमित करते हैं","0 1 3 4 5-6 6 7"),
 ("The supply of ammunition was stopped","गोलाबारूद की पूर्ति रोक दी गई","0 1 1-2 2 4 5 6 7"),
 ("The displaced families returned home","विस्थापित परिवार घर लौट आए","0 1 3 2 4 5"),
 ("The certification of doctors is necessary","डॉक्टरों का प्रमाणन आवश्यक है","0 1 1-2 2 3 4"),
 ("Satire exposes the faults of society","व्यंग्य समाज के दोषों को उजागर करता है","0 2 1 3-4 4 5 6 7"),
 ("The musical program enthralled the audience","संगीतमय कार्यक्रम ने श्रोताओं को मंत्रमुग्ध किया","0-1 1 1 4-5 5 6-7 7 2 8"),
 ("The field is rectangular in shape","खेत आयताकार आकृति का है","0 2 1 4 3 5"),
 ("All the members attended the meeting","समस्त सदस्यों ने बैठक में भाग लिया","0 1-2 2 1 4 5 6-7 7"),
 ("The female writer won the prize","लेखिका को पुरस्कार मिला","0 1 3 2 4"),
 ("The colony became independent after struggle","उपनिवेश संघर्ष के बाद स्वतंत्र हुआ","0 4-5 5 2-3 3 6 1"),
 ("The membership of the club is open","संस्था की सदस्यता सबके लिए खुली है","0 1 1-2 2 5-6 6 3-4 4 7"),
 ("The triangular garden looks beautiful","त्रिकोणीय उपवन सुंदर लगता है","0 1 2 3 4 5"),
 ("The quantity of rice was measured","चावल का परिमाण नापा गया","0 1 1-2 2 3 4"),
 ("Mutation in genes causes disease","जीनों में उत्परिवर्तन से बीमारी होती है","1 2 0 4 5 6 7 8"),
 ("The ballot boxes were sealed","मतपत्र पेटियों को सील किया गया","0 1-2 2 4 5 3 6"),
 ("The famous singer gave a recital","विख्यात गायक ने गायन किया","0-1 1 1 4-5 5 2-3 3"),
 ("The delegation met the governor","प्रतिनिधिमंडल ने राज्यपाल से भेंट की","0-1 1 1 4 5 2-3 3 6"),
 ("The alphabet begins with the first letter","वर्णमाला का आरंभ पहले अक्षर से होता है","0 1 1 2 4 3 5-6 6-7 7 8"),
 ("The company of good people is music to ears","सत्संगत संगत कानों को मधुर लगती है","0-1 1 1 5-6 6 7 3-4 4-5 5 8"),
 ("A year and a half passed like that","ढाई वर्ष ऐसे ही बीत गए","0-1 1-2 2 4-5 5 3 6"),
 ("The manipulation of accounts was caught","हिसाबों में हेरफेर पकड़ा गया","0 1-2 2 3 4 5 6"),
 ("The nephew is like a son","भांजी बेटी के समान है","0 2-3 3 0-1 1 4"),
 ("The juice of sugarcane is sweet","गन्ने का निचोड़ना मीठा होता है","0 1 1 2 3 4 5"),
 ("Woolen socks protect from cold","ऊनी मोज़ा ठंड से बचाता है","0 1 3 4 2 5"),
 ("The myna mimics human speech","मैना मानव बोली की नकल करती है","0 2-3 3-4 4 1 5 6 7"),
 ("Pushing the cart the laborer climbed the slope","ठेलना में गाड़ी ढलानों पर चढ़ाई","0 1 1 2 4 5 3 6"),
 ("Oh what a beautiful sight","ओह कितना सुंद्र दृश्य है","0 2-3 3-4 4 1 5"),
 ("The nameless soldier sacrificed his life","अनाम सैनिक ने प्राण अर्पित किए","0 1 1 2 4 3 5 6"),
 ("Usually trains run on time","सामान्यतः रेलगाड़ी समय पर चलती है","0 1 3 2 4-5 5 6"),
 ("The poisonous snake hid in the bush","विषाक्त साँप झाड़ी में छिपा था","0-1 0-1 1 4 2 5 3 6"),
 ("The chief of the clan was old","कुलाधिपति वृद्ध हो गया था","0 1-2 2 5 3-4 4 6"),
 ("New systems are being tried","नई प्रणालियाँ आज़माई जा रही हैं","0 1 2 4 5-6 6 3 7"),
 ("The fish trade flourishes by the river","मत्स्य व्यापार नदी किनारे फलता है","0-1 0-1 1 4-5 5 3 6 7"),
 ("Explosive material was recovered","विस्फोटक सामग्री बरामद हुई","0 1-2 2 3 4 5"),
 ("The inland river is shallow","अंतर्देशीय नदी उथली होती है","0-1 0-1 1 3 2 4 5"),
 ("The attacker was arrested","हमलावर को गिरफ़्तार किया गया","0 2 3 1 4 5"),
 ("The dacoity took place at midnight","डकैती आधी रात को हुई","0 3-4 4 1 2 5"),
 ("The vice president addressed the gathering","उपराष्ट्रपति ने सभा को संबोधित किया","0-1 1 1 4-5 5 2 6 7"),
 ("The validity of the card expired","पहचान पत्र की वैधता समाप्त हो गई","0-1 1 1 4 2 5 6 7"),
 ("Competitions increase the talent of children","प्रतियोगिताएँ बच्चों की प्रतिभा बढ़ाती हैं","0 2-3 3 1 4 5 6"),
 ("The bounce of the ball surprised the fielder","गेंद का उछाल क्षेत्ररक्षक को चौंका गया","0 1 1 2 4 5-6 6 3 7 8"),
 ("The controller issued new instructions","नियंत्रक ने नए निर्देशों का संचार किया","0-1 1 1 3 4-5 5 2 6 7"),
 ("The integrated plan was praised","समेकित योजना की सराहना हुई","0 1 1-2 2 3 4"),
 ("The inclination of students towards science grew","छात्रों का विज्ञान की ओर झुकाव बढ़ा","0 1 1 2 5 4 6-7 7 8"),
 ("The councils of villages decided together","पालिकाओं ने मिलकर निर्णय लिया","0-1 1 1 2 3 4 5"),
 ("The supernatural tale scared the children","अलौकिक कहानी से बच्चे डर गए","0 1 2 3 4 5 6"),
 ("Institutional changes take time","संस्थागत परिवर्तनों में समय लगता है","0 1 1-2 2 3 4 5 6"),
 ("The prosecution presented evidence","अभियोजन ने सबूत पेश किए","0-1 1 1 3-4 4 2 5"),
 ("The revenge destroyed both families","प्रतिशोध ने दोनों परिवार बर्बाद कर दिए","0 1 1 2-3 3 4 5 6"),
 ("The elections are drawing near","चुनाव आसन्न हैं","0 3 1 2"),
 ("Erosion of the soil worries farmers","मिट्टी का क्षरण किसानों को चिंतित करता है","0 1 1 2 3 4-5 5 6 7"),
 ("The aforesaid rule applies here","उक्त नियम यहाँ लागू होता है","0 1 2 3 4-5 5 6"),
 ("Educationists demanded better schools","शिक्षाविदों ने बेहतर विद्यालय माँगे","0-1 1 1 3 2 4-5 5"),
 ("The inclusion of all players is necessary","सभी खिलाड़ियों का समावेश आवश्यक है","0 2-3 3 1 4 5 6"),
 ("The squad practiced till evening","टुकड़ी शाम तक अभ्यास करती रही","0 3-4 4 1 2 5 6"),
 ("Developing countries need support","विकासशील देशों को सहयोग चाहिए","0 1 2 4 5 3"),
 ("The miracle of science surprised everyone","विज्ञान का चमत्कार सबको चौंकाता है","0 1 1 2 4 3 5 6"),
 ("The orientation of the house is east facing","घर का अभिविन्यास पूर्व की ओर है","0 1 1-2 2 3 5-6 6 4 7"),
 ("The helpless could not defend","अक्षम व्यक्ति बचाव नहीं कर सका","0 1 2 3 4 5 6 7 8"),
 ("The elevation of the officer was announced","अधिकारी के उन्नयन की घोषणा हुई","0 1 1-2 2 3 4 5 6"),
 ("Documentation of the event was done","कार्यक्रम का दस्तावेजीकरण हुआ","0 1 1-2 2 3 4"),
 ("Geological survey found minerals","भूवैज्ञानिक सर्वेक्षण में खनिज मिले","0 1 1-2 2 3 4 5"),
 ("Nationwide celebrations were held","राष्ट्रव्यापी उत्सव मनाए गए","0 1 2 3 4"),
 ("The economist explained the budget","अर्थशास्त्री ने बजट समझाया","0-1 1 1 2 3 4"),
 ("The immovable property was registered","अचल संपत्ति पंजीकृत की गई","0-1 0-1 1 2 3 4 5"),
 ("The trainee learned the work","प्रशिक्षु ने काम सीखा","0 1 1 2 3"),
 ("The theatrical group staged a play","नाट्य मंडली ने नाटक खेला","0 1-2 2 1 4 3 5"),
 ("The spy was caught at the border","टोही सीमा पर पकड़ा गया","0 3 4 1-2 2 5"),
 ("Voluntary donations are accepted","स्वैच्छिक दान स्वीकार किए जाते हैं","0 1 2 3 4-5 5 6"),
 ("The aforesaid lines are quoted","उल्लिखित पंक्तियाँ उद्धृत की जाती हैं","0 1 2 3 4-5 5 6"),
 ("Shipping trade increased in coastal states","नौवहन व्यापार तटीय राज्यों में बढ़ा","0 1 1-2 2 5-6 6 3 4"),
 ("The date of the fair is fixed","मेले की दिनांक तय है","0 1 1-2 2 3 4"),
 ("The deodar trees of the mountains are tall","पर्वतों के देवदार ऊँचे होते हैं","1 2 0 3 5 4 6"),
 ("The proposal was canceled","प्रस्ताव निरस्त कर दिया गया","0 2 1 3 4 5"),
 ("The fairy blessed the child","परी ने बच्चे को आशीर्वाद दिया","0-1 1 1 3-4 4 2 5 6"),
 ("The skeleton was found in the ruins","कंकाल खंडहरों में मिला","0 4-5 5 1 2 3"),
 ("The lustful man fell in his own eyes","कामुक व्यक्ति अपनी दृष्टि में गिर गया","0 1 3 4-5 5-6 6 7 2 8"),
 ("The preface of the book is long","पुस्तक की प्रस्तावना लंबी है","0 1 1-2 2 3 4"),
 ("The cone of the pine fell down","शंकु पेड़ से नीचे गिरा","0 3-4 4 1 2 5"),
 ("The forecast of rain proved right","बारिश का पूर्वानुमान सही निकला","0 1 1-2 2 3 4 5"),
 ("Nationalism grew in the youth","युवाओं में राष्ट्रवाद जागा","0-1 1 2 3 4"),
 ("The praised dancer performed gracefully","प्रशंसित नर्तकी ने सुंदर नृत्य किया","0-1 1 1 3 2 4-5 5 6 7"),
 ("Polar regions remain frozen","ध्रुवीय क्षेत्र जमे रहते हैं","0 1 2 3-4 4 5"),
 ("Classification of animals is interesting","जीवों की श्रेणीकरण रोचक है","0 1 1-2 2 3 4"),
 ("The strong wind uprooted trees","प्रबल आँधी ने पेड़ उखाड़ दिए","0-1 0-1 1 1 3 4 2 5"),
 ("The coordinator called the meeting","समन्वयक ने बैठक बुलाई","0-1 1 1 2 3 4"),
 ("The religious school teaches scripture","मदरसा धर्मग्रंथ पढ़ाता है","0 2-3 3 1 4"),
 ("Transplant of the heart is complex","हृदय का प्रत्यारोपण जटिल होता है","0 1 1-2 2 3 4 5"),
 ("The release of water from the dam","बाँध से जल विमोचन की योजना है","0 1 2 3-4 4 5-6 6 7 8"),
 ("The consistent statements removed doubts","सुसंगत बयानों से शक दूर हुए","0 1 1-2 2 3 4-5 5 6"),
 ("Showing courage the soldier saved the child","सैनिक ने दिखाकर साहस बच्चे को बचाया","0-1 1 1 2-3 3 4 5-6 6 7 8"),
 ("The fifth boy won the race","पांचवां लड़का दौड़ जीत गया","0 1 3 2 4 5"),
 ("The oval field suits the game","अंडाकार मैदान खेल के लिए उपयुक्त है","0 1 2 3 5 4 6 7"),
 ("The famine forced people to migrate","दसवें वर्ष के अकाल ने पलायन कराया","0 1-2 2-3 3 4 5-6 6 7 8"),
 ("The galaxy shines in the night sky","रेखांकित आकाशगंगा रात में चमकती है","0 1 2 4 5 3 6"),
 ("The roots of the old tree are deep","पुराने पेड़ की जड़ें गहरी होती हैं","0-2 2 1 3-4 4 5 6 7"),
 ("Ore is extracted from mines","अयस्क खदानों से निकाला जाता है","0 2-3 3 1 4-5 5 6"),
 ("The riots disturbed the peace of the city","दंगों ने नगर की शांति भंग की","0-1 1 1 2 5 3-4 4 6"),
 ("Modernization changed the villages","आधुनिकीकरण ने गाँव बदल दिए","0 1 1 2 3 4"),
 ("The advocate argued the case well","अधिवक्ता ने मुकदमा अच्छी तरह लड़ा","0-1 1 1 3 2 4-5 5-6 6 7"),
 ("Sociology studies human society","समाजशास्त्र मानव समाज का अध्ययन करता है","0 2-3 3-4 4 1 5 6 7"),
 ("The unpublished diary of the poet surfaced","अप्रकाशित डायरी सामने आई","0-1 0-1 1 4 2 5 3"),
 ("Mammals feed their young","स्तनधारी अपने शावकों को दूध पिलाते हैं","0 3 3-4 4 1 2 5 6"),
 ("The ruling party won again","शासी दल फिर जीता","0-1 0-1 1 3 2 4"),
 ("Nationality unites the people","राष्ट्रीयता नागरिकों को जोड़ती है","0 3 1 2 4"),
 ("The master blessed the tenant","साहिब ने किसान को आशीर्वाद दिया","0-1 1 1 3 4 2 5 6"),
 ("The proximity of the river helps farming","नदी के समीप खेती लाभदायक है","0 1-2 2 4 3 5 6"),
 ("The employer paid the wages","नियोक्ता ने मज़दूरी दी","0-1 1 1 3 2 4"),
 ("The oppressed raised their voice","दलितों ने आवाज़ उठाई","0-1 1 1 2 3 4"),
 ("The unrest in universities worries all","विश्वविद्यालयों में अशांति सबको चिंतित करती है","0 1 2 3 5-6 6 4 7 8"),
 ("The parasite harms the host","परजीवी मेज़बान को हानि पहुँचाता है","0 2 3 1 4-5 5 6"),
 ("The cycle of seasons continues","ऋतुओं का आवर्ती चक्र चलता रहता है","0-1 1 1-2 2 3 4-5 5 6 7"),
 ("The mandate of people decides the government","जनादेश सरकार का निर्णय करता है","0 2 1-2 3 4 5 6"),
 ("The broadcaster aired the program","प्रसारक ने कार्यक्रम प्रसारित किया","0-1 1 1 2 3 4 5"),
 ("Humor lightens the mind","विनोद मन को हल्का करता है","0 3-4 4 1 2 5"),
 ("The stone in the kidney pains","पथरी की बीमारी दर्द देती है","0 1-2 2 3 5 4 6"),
 ("The tailor stitched the shirt","दर्ज़ी ने कपड़ा सिलना सीखा","0-1 1 1 3 2 4-5 5"),
 ("Turn the key to open the lock","ताला खोलने के लिए घुमाना पड़ता है","1 2 3-4 4 5 6 7 8 9"),
 ("The trio sang the song","तिकड़ी ने गीत गाया","0-1 1 1 2 3 4"),
 ("The sovereign king ruled justly","संप्रभु राजा ने न्याय किया","0-1 0-1 1 1 3 2 4"),
 ("The retired officer guides the youth","निवर्तमान अधिकारी युवाओं का मार्गदर्शन करते हैं","0 1 2 5 3 6-7 7 4 8"),
 ("The millennium saw great changes","सहस्राब्दी में विशाल परिवर्तन आए","0 1-2 2 3 4 5"),
 ("The sponsor funded the tournament","प्रायोजक ने प्रतियोगिता का प्रायोजन किया","0-1 1 1 3-4 4 2 5 6"),
 ("The general manager of the factory retired","कारखाने का महाप्रबंधक सेवानिवृत्त हुआ","0 1 1-2 2 3-4 4 5 6"),
 ("The restored temple looks grand","पुनर्स्थापित मंदिर भव्य लगता है","0 1 2 3 4 5 6"),
 ("The resulting confusion was unavoidable","परिणामी भ्रम अनिवार्य था","0 1 3 2 4"),
 ("The punished culprit repented","दंडित अपराधी ने पश्चाताप किया","0 1 1 3 2 4 5"),
 ("The step mother loved the child","सौतेले माँ ने बच्चे को गोद लिया","0-1 1-2 2 1 4 5 3 6 7"),
 ("The sponsorship of sports is increasing","खेलों का प्रायोजन बढ़ रहा है","0 1 1-2 2 3 4 5 6"),
 ("The ring was lost in the river","अंगूठी नदी में खो गई","0 3 1 2 4 5"),
 ("Unemployment troubles the youth","बेरोजगारी युवाओं को परेशान करती है","0 2-3 3 1 4-5 5 6"),
 ("The tomb of the king is in the city","राजा का मकबरा शहर में है","0 1 1 2 5 3 4 6"),
 ("The government school opened","राजकीय विद्यालय खुल गया","0-1 0-1 1 3 2 4"),
 ("The tremor of the earthquake was strong","भूकंप का झटका प्रबल था","0 1 1-2 2 3 4 5"),
 ("The sage meditated in the hills","योगी पहाड़ियों में ध्यान करता था","0 3-4 4 1-2 2 5 6"),
 ("The colleague helped in the work","सहकर्मी ने काम में सहायता की","0-1 1 1 3 4 2 5"),
 ("The communal riot hurt the town","सांप्रदायिक दंगों ने नगर को घायल किया","0-1 0-1 1 1 3 4 2 5 6"),
 ("The circumference of the field was measured","खेत की परिधि नापी गई","0 1 1-2 2 3 4 5"),
 ("The triangle has three sides","त्रिकोण में तीन भुजाएँ होती हैं","0 1 2 3-4 4 5 6"),
 ("The reunion of friends was joyful","पुराने मित्रों का पुनर्मिलन आनंददायक रहा","0-2 2 1 3 4 5 6"),
 ("The distracted driver met an accident","विचलित चालक दुर्घटना का शिकार हुआ","0 1 3 2 4 5 6 7"),
 ("The ambitious youth dreams big","महत्वाकांक्षी युवा बड़ा सपना देखता है","0-1 1 1 4 3 5-6 6 7"),
 ("The populist leader promised jobs","जनवादी नेता ने रोज़गार का वादा किया","0-1 1 1 3 5 4 2 6 7"),
 ("The abandoned house fell down","परित्यक्त मकान गिर गया","0 1 3 2 4 5"),
 ("Unequal wages cause resentment","असमान वेतन से असंतोष फैलता है","0 1 2 4 3 5 6 7"),
 ("The fleet of ships sailed at dawn","बेड़ा भोर में रवाना हुआ","0 3 1 2 4 5"),
 ("The judiciary is independent","न्यायपालिका स्वतंत्र होती है","0 3 1 2 4"),
 ("The casualties were shifted to hospital","हताहतों को अस्पताल ले जाया गया","0-1 1 1 4 5-6 6 2 3 7"),
 ("The concurrent events surprised all","समवर्ती घटनाओं ने सबको चौंकाया","0 1 1-2 2 3 4-5 5 6"),
 ("The proposal was accepted","स्वीकार्य प्रस्ताव पारित हुआ","0 1 3 2 4"),
 ("The processed goods were exported","संसाधित माल निर्यात हुआ","0 1-2 2 3 4 5"),
 ("Adolescence is a delicate age","किशोरावस्था नाज़ुक उम्र होती है","0 4 1-2 2 3 5 6"),
 ("Autonomy was given to institutions","संस्थाओं को स्वायत्तता दी गई","0 1 2 4 3 5 6"),
 ("The realist accepts the truth","यथार्थवादी सत्य स्वीकारता है","0 4 1 2-3 3 5"),
 ("Compliance of rules is required","नियमों का अनुपालन आवश्यक है","0 1 1-2 2 3 4 5"),
 ("The navel of the infant was cut","नवजात की नाभि काटी गई","0 1 1 2 3 4 5 6"),
 ("Insight comes with experience","अंतर्दृष्टि अनुभव से आती है","0 3 4 1-2 2 5"),
 ("The displacement of people pained all","जनता का विस्थापन सबको दुखी करता है","0 1 1-2 2 3 4-5 5 6 7"),
 ("Actually the fault was of the servant","दरअसल गलती नौकर की थी","0 2 1 4 3 5 6"),
 ("The noun names a thing","संज्ञा किसी वस्तु का नाम है","0 4 2-3 3 1 5 6"),
 ("The fasting devotee prayed","उपवास करते अनुयायियों ने प्रार्थना की","0 2 3 0-1 1 4-5 5 6 7"),
 ("The meter of poetry is musical","काव्य का छंद संगीतमय होता है","0 1 1-2 2 3 4 5"),
 ("The wrestler uprooted the opponent","पहलवान ने उखाड़ प्रतिद्वंद्वी को गिराया","0-1 1 1 2 4 3 5 6"),
 ("Salvation is the aim of life","मोक्ष जीवन का लक्ष्य है","0 3 0-1 1 2 4"),
 ("The trust takes care of property","न्यासी संपत्तियों की देखभाल करता है","0 2-3 3 4 5 6 7"),
 ("Strictness alone does not reform","सख्ती मात्र सुधार नहीं लाती","0 0 3-4 4 1-2 2 5"),
 ("The end of the story is strange","कहानी का अंजाम अजीब है","0 1 1-2 2 3 4 5"),
 ("The trio of gods is praised","त्रयी की महिमा गाई जाती है","0 1 1-2 2 3 4 5"),
 ("The map shows the terrain","भूभाग मानचित्रों में दिखता है","0 2-3 3 1 4 5"),
 ("Colloquial language is easy","बोलचाल की भाषा सरल होती है","0-1 0-1 1 2 4 3 5"),
 ("Every year the fair is held","प्रतिवर्ष मेला लगता है","1-2 0 3 1 4"),
 ("The play of the child is lovely","अंदर के कमरे में खिलौना रखा है","2 3-4 4 0-1 1 5 6 7"),
 ("The god of wealth is worshipped","लीला के रूप में देवताओं की पूजा होती है","2 3 0 5 1-2 2 6 7 8"),
 ("Firefighting teams worked hard","अग्निशमन दलों ने कड़ी मेहनत की","0 1 1-2 2 3 4 5 6"),
 ("Amendments were made in the law","कानून में संशोधनों का सुझाव आया","1 2 0 3 4 5 6 7"),
 ("Gender equality is a modern idea","लैंगिक समानता की बात होती है","0 1 2-3 3 4 5 6"),
 ("The puppet danced on strings","कठपुतली नाचती है धागों से","0 3 2 1 4 5"),
 ("The attackers fled in the dark","हमलावरों अंधेरे में भाग गए","0 3-4 4 1 2 5"),
 ("The empire lasted long","सल्तनत लंबे समय तक चली","0 4-5 5 1-2 2 3"),
 ("Reducing the wastage saved money","घटाकर बर्बादी रोकी गई","0 1-2 2 3 4 5 6"),
 ("The patriot sacrifices everything","देशभक्त सब कुछ अर्पित कर देता है","0 4-5 5 1-2 2 3 6 7"),
 ("Sandy soil drains quickly","बलुआ मिट्टी जल्दी सूख जाती है","0-1 0-1 1 3 2 4 5"),
 ("The specification was shared with firms","विनिर्देश फर्मों को भेजा गया","0 1 2 4-5 5 3 6"),
 ("The translated book sold well","अनुवादित पुस्तक अच्छी बिकी","0 1 2 3 4 5"),
 ("The analyst studied the data","विश्लेषक ने आँकड़े देखे","0-1 1 1 2-3 3 4"),
 ("The supply of grain was arranged","खाद्यान्न की पूर्ति की गई","0 1 1-2 2 3 4 5"),
 ("The foundation of the building is strong","नींव कायम रखने से इमारत टिकती है","0 3 4 1-2 2 5 6 7"),
 ("The unsafe bridge was closed","असुरक्षित पुल बंद कर दिया गया","0 1 3 2 4 5 6"),
 ("Raw material was arranged","सामग्रियों की खरीदी हुई","0 1-2 2 3 4 5"),
 ("Power lines were repaired","बिजली की लाइनें ठीक की गईं","0 1 1-2 2 4 5 3 6"),
 ("The assumptions of the study were wrong","मान्यताओं का आधार गलत था","0 1-2 2 3 4-5 5 6 7"),
 ("The museums of the city are famous","संग्रहालयों की मान्यता प्रसिद्ध है","0 1-2 2 3 4 5 6"),
 ("The inhibitor blocked the reaction","अवरोधक ने प्रतिक्रिया रोकी","0 1 1 2 3-4 4 5"),
 ("The plans were discussed","योजनाओं पर विचार हुआ","0 1-2 2 3 4 5"),
 ("Atoms combine to form molecules","अणुओं के जुड़ने से अणु बनते हैं","0 1-2 2 4 3 5 6 7"),
 ("The adjective qualifies the noun","विशेषण क्रिया की विशेषता बताता है","0 3 1-2 2 4 5 6"),
 ("Yes the work is complete","हां काम पूरा हो गया","0 3 1 2 4 5"),
 ("The councils of districts met","परिषदों की बैठक हुई","0 1-2 2 3 4 5"),
 ("Persuading him took time","दिलाने में समय लगा","0 2 1 3 4"),
 ("Monopoly harms consumers","एकाधिकार उपभोक्ताओं के लिए हानिकार है","0 2 2-3 3 4 5 6"),
 ("The slaying of the demon is legend","राक्षस का वध पौराणिक है","0 1 1 2 3 4 5"),
 ("The catalyst speeds the reaction","उत्प्रेरक प्रतिक्रिया तेज़ करता है","0 3-4 4 1 2 5"),
 ("Maps of the region were updated","मानचित्रों क्षेत्र का नक्शा बना","0 1-2 2 3 4 5 6"),
 ("The coral reef is fragile","प्रवाल भित्ति नाज़ुक होती है","0-1 0-1 1 3 2 4 5"),
 ("The compensation was announced","मुआवजे की घोषणा हुई","0 1-2 2 3 4"),
 ("The glory of the kingdom spread","महिमा की चर्चा दूर तक फैली","0 1-2 2 3 4-5 5 6 7"),
 ("The figures were counted again","संख्याएँ फिर गिनी गईं","0 3 2 1 4 5"),
 ("Saturn is a giant planet","शनि विशाल ग्रह है","0 2 1 3 4"),
 ("The mischiefs of children continue","छेड़ें बच्चों का शौक बना रहे","0 2 1 3 4 5 6"),
 ("Terror spread in the village","आतंक गाँव में फैल गया","0 2 1 3 4 5"),
 ("The thief sneaked in at night","चोर रात में घुस गया","0 4 1 2 5 3 6"),
 ("The churches of the coast are old","गिरजाघर तट के पुराने हैं","0 2-3 3 0-1 1 4 5"),
 ("The awakening spread among the youth","जागरण युवाओं में फैला","0 3 1 2 4 5"),
 ("The firms invested in technology","फर्मों ने तकनीक में निवेश किया","0-1 1 1 3-4 4 2 5 6"),
 ("The turn of duties rotates","बारीबारी से कर्तव्य निभाते हैं","0 2 1 3 4 5 6"),
 ("Mapping of resources was done","मानचित्रण विशेषज्ञों ने किया","0 2-3 3 1 4 5"),
 ("Geometric designs decorate the floor","ज्यामितीय आकृतियों फर्श सजाती हैं","0 1 1-2 2 3 4 5 6"),
 ("The obscene poster was removed","अश्लील पोस्टर हटाए गए","0 1 3 2 4 5"),
 ("Atmospheric pressure varies","वायुमंडलीय दबाव बदलता रहता है","0 1 2 3 4 5 6"),
 ("The prehistoric cave has paintings","प्रागैतिहासिक गुफा में चित्र हैं","0 1 2 4 3 5 6"),
 ("To grow the crop needs water","बढना हेतु फसल को जल चाहिए","0 3 1 4 2 5 6"),
 ("The urine test was clear","मूत्र परीक्षण साफ़ निकला","0 1 2 3 4 5"),
 ("Vaccination protected the children","टीकाकरण बच्चों को बचाता है","0 2-3 3 1 4 5"),
 ("The layers of earth tell history","परतों से पृथ्वी का इतिहास पता चलता है","0 1 1-2 2 3 4-5 5 6 7"),
 ("To draw a line use a scale","खींचने रेखा के लिए पैमाना चाहिए","0 2 1 3-4 4 5 6 7"),
 ("Constant practice improves skill","सतत अभ्यास कौशल बढ़ाता है","0 1 2 3 4 5"),
 ("To believe the truthful is wise","मानने में सच्चा बुद्धिमानी है","0 2-3 3 1 4 5 6 7"),
 ("Sexuality education is debated","कामुकता पर बहस होती है","0 2 1 3 4 5"),
 ("The obsolete custom ended","अप्रचलित रीति रिवाज बंद हुए","0 1-2 2 3 4 5"),
 ("The thorns hurt the feet","कांटे पैरों में चुभते हैं","0 3 1 2 4 5"),
 ("The tower collapsed suddenly","बुर्ज अचानक गिर गया","0 3 1-2 2 4 5"),
 ("The researcher published findings","खोजकर्ता ने निष्कर्ष प्रकाशित किए","0-1 1 1 2-3 3 4 5"),
 ("Dozens of boats sailed","दर्जनों नावें समुद्र में चलीं","0 1-2 2 4 3 5"),
 ("The graves are in the yard","कब्रों का प्रांगण पुराना है","0 1 1-2 2 3 4 5"),
 ("He performed the duty well","उसने निभाया कर्तव्य निष्ठा से","0 1 2 3 4-5 5 6 7"),
 ("The bankrupt trader left the town","दिवालिया व्यापारी नगर छोड़ गया","0 1 3 2 5 4 6 7"),
 ("To bury the dead is a duty","दफनाने मृतकों का धर्म है","0 2-3 3-4 4 1 5 6"),
 ("Moments of joy are rare","क्षणों की महत्त्वपूर्ण बेला है","0 1-2 2 3 4 5 6"),
 ("The ruling dynasty declined","सत्तारूढ़ वंश पतन को गया","0-1 0-1 1 3 4 2 5"),
 ("The foursome played well","चौकड़ी ने अच्छा प्रदर्शन किया","0 1 1 2-3 3 4 5"),
 ("The magic show amazed children","जादुई खेल से बच्चे हैरान रह गए","0 1 1 2 5 3 6 7 8"),
 ("The fool learns late","मूर्ख समझता देर से है","0 3 2 1 4 5"),
 ("The retrospective law was debated","पूर्वव्यापी कानून पर बहस हुई","0 1 1-2 2 3 4 5 6"),
 ("Lakes freeze in winter","झीलें सर्दियों में जम जाती हैं","0 3-4 4 1-2 2 5 6"),
 ("The varieties of mangoes were many","किस्मों का विवरण दिया गया","0 1 1-2 2 3 4 5"),
 ("The statements were recorded","बयानों का विघटित संग्रह हुआ","0 1-2 2 3 4 5 6"),
 ("Worldwide trade expanded","विश्वव्यापी व्यापार फैला","0 1 1-2 2 3 4"),
 ("The address on the letter faded","पते का लेख मिट गया","0 1 1-2 2 3 4 5"),
 ("The film won awards","चलचित्र को पुरस्कार मिले","0 1 3 2 4"),
 ("The widow bequeathed her property","वसीयत में संपत्ति दान की गई","0 1 1 2 4 3 5 6"),
 ("To order food call the kitchen","मंगवाना भोजन रसोई से कहिए","0 1 2 4 3 5 6"),
 ("Grumbling does no good","बडबडाना बेकार है","0 2 1 3 4"),
 ("The cockroach hid in a corner","तिलचट्टा कोने में छिप गया","0 4-5 5 1 2 3 6"),
 ("The moth circled the lamp","पतंगा दीपक के पास घूमता रहा","0 3-4 4 1 2 5 6 7"),
 ("The young man joined the army","तरुण युवक सेना में भर्ती हुआ","0 1 1 2-3 3 5 4 6 7"),
 ("The dog smelled the trail","कुत्ते ने सूँघना जाना मार्ग","0-1 1 1 2 4 3 5"),
 ("To push the cart needs strength","धकेलना गाड़ी के लिए शक्ति चाहिए","0 2 1 3-4 4 5 6 7"),
 ("To scatter seeds is sowing","बिखेरना बीज बोना कहलाता है","0 2-3 3 1 4 5 6 7"),
 ("The constellation guides sailors","तारामंडल नाविकों का मार्ग दिखाता है","0 2-3 3 1 4 5 6 7"),
 ("The monetary policy changed","मौद्रिक नीति में बदलाव आया","0 1-2 2 3 4 5 6"),
 ("The claimant filed a case","दावेदार ने मुकदमा दायर किया","0-1 1 1 2-3 3 4 5"),
 ("The future of children is bright","भावी पीढ़ी का भविष्य उज्ज्वल है","0 1 1-2 2 3 4 5 6"),
 ("The tablets were bitter","गोलियों का स्वाद कड़वा था","0 1 1 2 3 4 5"),
 ("The torso was injured","धड पर चोट आई थी","0 3 1-2 2 4 5 6"),
 ("The tremor of the phone broke silence","कंपन से मौन टूटा","0 3 2 1 4 5"),
 ("The effectiveness of the drug was proven","प्रभावशीलता परीक्षण सिद्ध हुई","0 2-3 3 1 4 5"),
 ("Competition improves quality","स्पर्धा गुणवत्ता बढ़ाती है","0 2 1 3 4"),
 ("The subcontinent is densely populated","उपमहाद्वीप घनी आबादी वाला है","0 4 2-3 3 1 5 6"),
 ("Eternal values endure","शाश्वत मूल्य कायम रहते हैं","0-1 0-1 1 2 3 4"),
 ("The complexities of law confuse people","जटिलताओं का ज्ञान कठिन है","0 1-2 2 1 3 4 5"),
 ("The boxer trained hard","मुक्केबाज ने कठोर अभ्यास किया","0 1 1 3-4 4 2 5 6"),
 ("Racism is condemnable","नस्लवाद निंदनीय है","0 3 1 2"),
 ("The district was reorganized","रूपांतरित जनपद बना","0 1-2 2 3 4"),
 ("The prophet preached peace","पैगंबर ने शांति का संदेश दिया","0 1 1 3 2 4 5 6"),
 ("The destruction of war is vast","विध्वंस युद्ध का परिणाम है","0 2 0-1 1 3 4 5"),
 ("The excitement of the crowd grew","उत्तेजना भीड़ में बढ़ती गई","0 2 1 3 4 5 6"),
 ("The waterfalls cascade from heights","झरनों का जल ऊँचाई से गिरता है","0 1 1-2 2 5 3 4 6"),
 ("The instructions were followed","निर्देशों प्राप्त हुए और पालन हुआ","0 1-2 2 3 4 5 6 7 8"),
 ("Socialism aims at equality","समाजवाद समानता चाहता है","0 3 1 2 4"),
 ("He sends letters every week","वह परम्परा से पत्र भेजता है","0 2-3 3 1 4 5 6"),
 ("The past cannot return","पिछला समय लौटता नहीं","0 1-2 2 3 4 5"),
 ("The ambiguity confused the court","अस्पष्टता ने न्यायालय को भ्रमित किया","0 1 1 2-3 3 4-5 5 6"),
 ("The broker settled the deal","मध्यस्थ ने सौदा तय किया","0 1 1 3 2 4 5"),
 ("The daughter is wise","पुत्री बुद्धिमान है","0 2-3 3 1"),
 ("The donor was honored","दाता का सम्मान हुआ","0 1 1-2 2 3 4"),
 ("The excited crowd cheered","उत्तेजित भीड़ ने नारे लगाए","0 1 2-3 3 1 4 5 6"),
 ("The warriors guarded the gate","सेनानियों द्वार की रखवाली करते थे","0 4-5 5 1-2 2 3 6 7"),
 ("The rooms of the palace are grand","कक्षों महल के भव्य हैं","0 1-2 2 0-1 1 3 4"),
 ("The bacteria caused illness","जीवाणु से बीमारी फैली","0 3 1 2 4 5"),
 ("The director general inspected the plant","महानिदेशक ने संयंत्र का निरीक्षण किया","0-1 1 1 2-3 3 4 5 6"),
 ("The junior clerk typed letters","कनिष्ठ लिपिक ने पत्र टाइप किए","0 1 1 3 2 4 5 6"),
 ("Bankruptcy ruined the trader","दिवालियापन व्यापारी का सर्वनाश है","0 3 1 2 4 5 6"),
 ("Circulation of blood is vital","परिसंचरण शरीर के लिए आवश्यक है","0 3 0-1 1 2 4 5"),
 ("Waste was recycled","कचरे से खाद बनाई गई","0 3 2 1 4 5"),
 ("Logical thinking solves problems","तार्किक विचार समस्याएँ सुलझाता है","0 1 2 4-5 5 3 6"),
 ("The tribunal gave the verdict","न्यायाधिकरण ने फैसला सुनाया","0 1 1 2-3 3 4 5"),
 ("The preacher addressed the gathering","प्रचारक ने सभा को संबोधित किया","0-1 1 1 3 4 2 5 6"),
 ("The beautiful valley attracted tourists","खूबसूरत घाटी पर्यटकों को लुभाती है","0 1 2 4 5 3 6"),
 ("The atmosphere of the village is calm","वायुमंडल का वातावरण शांत है","0 1 1-2 2 3 4 5"),
 ("The deviation from the path was small","विचलन मार्ग से थोड़ा था","0 3 1-2 2 4 5 6"),
 ("To catch the ball needs skill","पकडना गेंद के लिए कौशल चाहिए","0 2 1 3-4 4 5 6 7"),
 ("Because it rained the crop grew","चूँकि बारिश हुई फसल बढ़ी","0 2 1 3 4 5"),
 ("The blow was severe","प्रहार तेज़ था","0 2 1 3"),
 ("He said this yesterday","कहे गए शब्द वापस नहीं","0 1-2 2 3 4 5 6"),
 ("The wells dried in summer","कुओं का जल गर्मी में सूख गया","0 1 1-2 2 4-5 5 3 6"),
 ("The saw cut the plank","आरा ने तख्ता काटा","0 1 1 3 2 4"),
 ("Illegal construction was removed","गैरकानूनी निर्माण हटाया गया","0 1 3-4 4 2 5 6"),
 ("The terrestrial animals grazed","स्थलीय पशुओं ने चरना आरंभ किया","0 1-2 2 1 3 4 5 6 7"),
 ("The maiden won hearts","कुमारी ने सबका मन जीता","0-1 1 1 4 3 5 2 6"),
 ("The contributor was thanked","योगदानकर्ता का आभार व्यक्त हुआ","0 1 1-2 2 3 4 5 6"),
 ("The winners celebrated","जीतीं टीम ने जश्न मनाया","0 1-2 2 1 3 4 5"),
 ("Astrology claims to foretell","ज्योतिष भविष्य बताने का दावा करता है","0 3 4 5 6-7 7 1 8 9"),
 ("The dissatisfied workers struck work","असंतुष्ट मज़दूरों ने काम बंद किया","0 1 2-3 3 1 5 4 6 7"),
 ("Communism spread in that era","साम्यवाद उस युग में फैला","0 4-5 5 1-2 2 3 6"),
 ("Accordingly the plan was changed","तदनुसार योजना में बदलाव हुआ","0 1 1-2 2 3 4 5 6"),
 ("The tragedy moved everyone","त्रासदी से सब भावुक हुए","0 2 1 3 4 5"),
 ("Numerical data was analyzed","संख्यात्मक आँकड़े विश्लेषित किए गए","0 1-2 2 3 4 5 6"),
 ("The marginal farmer suffered loss","सीमांत किसान को घाटा हुआ","0 1 2 3 4 5 6"),
 ("The hole in the wall was patched","छिद्र दीवार में बंद किया गया","0 3 1 2 4 5 6 7"),
 ("The asteroid orbits the sun","क्षुद्रग्रह सूर्य की परिक्रमा करता है","0 2 1 3 4-5 5 6 7"),
 ("The councilors attended the meeting","पार्षदों की सूची बनाई गई","0 1-2 2 3 4 5 6"),
 ("Inflation hurts savings","मुद्रास्फीति से बचत घिसटती है","0 2 1 3 4 5 6"),
 ("The prosecutor examined witnesses","अभियोजक ने गवाहों की परीक्षा की","0-1 1 1 2-3 3 4-5 5 6"),
 ("The imaginary tale amused children","कल्पित कहानियों से बच्चे प्रसन्न हुए","0 1-2 2 3 4 5 6 7"),
 ("The assembly session began","विधानमंडल का अधिवेशन शुरू हुआ","0 1 1-2 2 3 4 5"),
 ("Venus shines at dusk","शुक्र संध्या में चमकता है","0 3-4 4 1 2 5"),
 ("The spear was sharp","भाला तेज़ धार वाला था","0 2 1 3 4 5 6"),
 ("The titles of nobles were hereditary","खिताबों का दायित्व विरासत चला","0 1-2 2 3 4 5 6 7"),
 ("The architects designed the palace","वास्तुकारों की टीम महल बनाने लगी","0 1-2 2 3 4 5 6 7 8"),
 ("The copies of documents were notarized","प्रतियाँ प्रमाणित होकर जमा की गईं","0 1 3 4 5 6 7 8"),
 ("The algae made the pond green","शैवाल ने तालाब हरा कर दिया","0 1 1 3 2 4 5"),
 ("The grace of the guru saved us","अनुग्रह की वर्षा हुई","0 1 1-2 2 3 4"),
 ("The recovery of the thief was slow","पुनर्प्राप्ति में देर हुई","0 1-2 2 3 4 5 6"),
 ("The lower berth was vacant","निचला बर्थ खाली था","0 1 2-3 3 4 5"),
 ("The costly treatment emptied savings","महंगा इलाज ने बचत खत्म की","0 1 1 3 2 4 5 6 7"),
 ("The conspiracy was exposed","कूटबद्ध षड्यंत्र खुल गया","0 1 1 2 3 4"),
 ("The expulsion of students was withdrawn","निष्कासन का आदेश वापस लिया गया","0 1 1-2 2 3 4-5 5 6 7"),
 ("To remove the tumor surgery was done","हटाना था अर्बुद शल्य चिकित्सा से","0 2 1 3 4 5 6 7"),
 ("The dialects vary by region","बोलियों में प्रदेश के अनुसार भिन्नता","0 1 3 4-5 5-6 6 7"),
 ("Humanities teach empathy","मानविकी मानवता सिखाती है","0 2-3 3 1 4"),
 ("The coin of old times is valuable","सिक्का पुराने ज़माने का कीमती है","0 2-3 3 1 4 5 6 7"),
 ("Complaints were registered","शिकायतों की सूची बनी","0 1-2 2 3 4 5"),
 ("The passages of the exam were tough","पारियों में परीक्षा कठिन थी","0 1-2 2 3 4 5 6"),
 ("The biennial fair drew crowds","द्विवार्षिक मेले में भीड़ उमड़ी","0 1 1-2 2 3 4 5"),
 ("Castes divide society","जातियोँ समाज बाँटती हैं","0 2 1 3 4 5"),
 ("The actor performed the role","निभा गया किरदार अभिनेता का","0 1 2 3-4 4 5 6"),
 ("The pure stream flowed","विशुद्ध जल रसद बहती रही","0 1 1 2 3 4 5"),
 ("Democracy needs participation","लोकतंत्रवादियों की भागीदारी चाहिए","0 2-3 3 1 4 5"),
 ("The surfaces were polished","सतहों पर संगोष्ठ हुई","0 2 1 3 4 5"),
 ("The manuscripts were digitized","पांडुलिपियों का अंकन हुआ","0 1-2 2 3 4 5"),
 ("The sculptor carved the idol","गढा मूर्तिकार ने अपनी कला","0 2 1 3 4 5 6"),
 ("The adjustment of salary was done","समायोजन वेतन का हो गया","0 2 1 3 4 5 6"),
 ("The plural denotes many","बहुवचन अनेकता जताता है","0 2 1 3 4 5"),
 ("The publishers released the catalog","प्रकाशकों ने सूची प्रकाशित की","0-1 1 1 2-3 3 4 5"),
 ("The spinal injury was serious","पृष्ठीय चोट गंभीर थी","0 1-2 2 3 4 5"),
 ("The contracts were signed","अनुबंधों का समापन हुआ","0 1-2 2 3 4 5"),
 ("The ruined city was deserted","तबाह नगर वीरान था","0 1 3 2 4 5"),
 ("The toxicity of chemicals varies","विषाक्तता रसायनों की अलग होती है","0 2-3 3 1 4-5 5 6 7"),
 ("The gym opens at dawn","व्यायामशाला भोर में खुलती है","0 3-4 4 1 2 5"),
 ("The livestock grazed in the meadow","पशुधन चरागाह में चरा","0 3-4 4 1 2 5"),
 ("The shapes of clouds change","आकृतियों का आकार बदलता रहता है","0 1-2 2 3 4-5 5 6 7"),
 ("The magnetic needle points north","चुम्बकीय सुई उत्तर दिखाती है","0 1 1-2 2 3 4 5"),
 ("The council decided unanimously","परिषद् का निर्णय सर्वसम्मत हुआ","0 1 1-2 2 3 4 5"),
 ("The stains did not go","धब्बे नहीं गए","0 2 1 3"),
 ("Dreams reflect desires","सपने मन की परछाईं हैं","0 3 1 2-3 3 4 5"),
 ("The coefficient was calculated","गुणांक निकाला गया","0 2 1 3 4"),
 ("The shrine echoes with hymns","आराधनालय में भजन गूँजते हैं","0 2 1 4 3 5 6"),
 ("The light of the lamp dispels dark","आलोक दीपक से अंधकार दूर होता है","0 1 2 3-4 4-5 5 6 7 8"),
 ("The patch on the cloth showed","पैच कपड़े पर अंकित था","0 2-3 3 1 4 5 6"),
 ("Aware of duty he acted","अवगत होकर कर्तव्य निभाया","0 1 3 2 4 5 6"),
 ("The style of expression was unique","अदा से कहने का तरीका अलग था","0 3 4 5 6 1-2 2 7 8"),
 ("The eager student asked questions","उन्मुख छात्र ने प्रश्न पूछे","0 1 2-3 3 1 4 5 6"),
 ("The spheres were arranged","गोलों की पंक्ति बनाई गई","0 1-2 2 3 4 5"),
 ("The nucleus controls the cell","नाभिक कोशिका का संचालन करता है","0 2-3 3 1 4 5 6"),
 ("The work was appreciated","सराहा गया कार्य समुचित","0 2 1 3 4 5"),
 ("The creation amazes all","सृष्टि का निर्माण अद्भुत है","0 1 1-2 2 3 4 5"),
 ("The vegetarian meal was simple","शाकाहारी भोजन सादा था","0 1 3 2 4 5"),
 ("Two and a half hours passed","ढाई घंटे बीत गए","0-1 1-2 2 3 4 5"),
 ("The hilly road is winding","पर्वतीय मार्ग घुमावदार है","0 1 1-2 2 3 4 5"),
 ("The beneficiaries thanked the donor","लाभान्वित लोगों ने धन्यवाद दिया","0 1-2 2 1 3 4 5 6"),
 ("The volcanic ash spread far","ज्वालामुखीय राख दूर तक फैली","0 1-2 2 3 4-5 5 6"),
 ("The pits were filled","गड्ढों मिट्टी से भर गए","0 2 1 3 4 5"),
 ("Rational decisions win trust","तर्कसंगत निर्णय पर विश्वास होता है","0 1 2 4-5 5 3 6"),
 ("Read the lesson carefully","पढें सबक ध्यान से","0 2 1 3-4 4"),
 ("The bats were out","बल्ले की मरम्मत हुई","0 1 1 2 3 4"),
 ("The absorption of nutrients occurs","अवशोषण खाद्य तत्वों का होता है","0 3 1-2 2 3 4 5 6"),
 ("The acquittal pleased the family","बरी होने पर परिवार प्रसन्न हुआ","0 1 2-3 3 0 4 5 6"),
 ("The intersection of lines is a point","प्रतिच्छेदन बिंदु पर होता है","0 1-2 2 3 4 5 6"),
 ("The evolutionary theory is accepted","विकासवादी सिद्धांत माना जाता है","0 1 1-2 2 3-4 4 5 6"),
 ("The scenic spot drew visitors","दर्शनीय स्थल दर्शकों को खींचता है","0 1 2 4-5 5 3 6"),
 ("The kick hurt the shin","लात पैर पर लगी","0 3 1-2 2 4 5"),
 ("Linguistics studies language","भाषाविज्ञान भाषा का अध्ययन है","0 2-3 3 0-1 1 4 5"),
 ("The arms of the wrestler were strong","बाहों में शक्ति भरी थी","0 1-2 2 3 4 5 6 7"),
 ("The integrity of the leader was praised","अखंडता के लिए सराहा गया","0 2 3 1 4 5 6 7"),
 ("The fifth chapter is long","पाँचवाँ अध्याय लंबा है","0 1 3 2 4 5"),
 ("The challenging climb tested all","चुनौतीपूर्ण चढ़ाई ने सबको परखा","0 1 1-2 2 3 4 5 6 7"),
 ("The warships sailed together","युद्धपोतों की काफिला रवाना","0 1-2 2 3 4 5 6"),
 ("Hydropower lights the villages","पनबिजली से गाँव जगमगाए","0 3 1 2 4 5 6"),
 ("She knows the whole story","जानती है वह पूरी बात","0 1 0 3 2 4"),
 ("In fact the fault was his","वस्तुतः दोष उसका था","0 2 1 4 3 5"),
 ("The rumor spread fast","अफवाह तेज़ी से फैली","0 3 1-2 2 4 5"),
 ("The affix changes the meaning","प्रत्यय अर्थ बदलता है","0 2 1 3 4 5"),
 ("The corpses were cremated","शवों का दाह संस्कार हुआ","0 1 1-2 2 3 4 5"),
 ("The corporations adopted new tech","निगमों ने तकनीक अपनाई","0-1 1 1 2-3 3 4 5"),
 ("The collections grew over years","संग्रहों में वृद्धि हुई","0 1 1 2 3 4 5"),
 ("Hostile forces gathered","शत्रुतापूर्ण सेनाएँ इकट्ठी हुईं","0 1 1 2 3 4"),
 ("The dams tamed the river","बंधे नदी को वश में किया","0 1 1 3 2 4 5 6"),
 ("The disorders were treated","विकारों का इलाज हुआ","0 1-2 2 3 4 5"),
 ("The riders raced ahead","सवारों ने दौड़ जारी रखी","0-1 1 1 3 2 4 5 6"),
 ("The rations reached the soldiers","रसद फौज तक पहुँची","0 4-5 5 1 2 3"),
 ("The collision injured many","टकरा जाने से अनेक घायल","0 2-3 3 1 4 5"),
 ("The pioneer was felicitated","प्रवर्तक को सम्मान मिला","0-1 1 1 3 2 4"),
 ("The uproar disturbed the class","हंगामा कक्षा में मचा","0 3 1 2 4 5"),
 ("The dominance of the empire ended","वर्चस्व का दौर बीत गया","0 1 1-2 2 3 4 5"),
 ("Where there is will there is way","कहाँ चाह वहीं राहा","4 5 6 0-2 2 3 7"),
 ("The troupe performed the play","मंडली ने नाटक प्रस्तुत किया","0 1 1 2 3-4 4 5"),
 ("Irrevocable decisions cannot change","अपरिवर्तनीय निर्णय बदले नहीं जाते","0 1 2 4 5 3 6"),
 ("The responsibilities were divided","जिम्मेदारियों का बँटवारा हुआ","0 1-2 2 3 4 5"),
 ("The infamous den was raided","बदनाम अड्डे पर छापा पड़ा","0 1 2-3 3 4-5 5 6 7"),
 ("The economical option was chosen","किफायती तरीका अपनाया गया","0 1 1 2 3 4 5"),
 ("The apprehension proved false","आशंका झूठी निकली","0 3 1 2 4"),
 ("The chapters were revised","अध्यायों में संशोधन हुआ","0 1-2 2 3 4 5"),
 ("The push started the swing","धक्का देकर झूला चलाया","0 2 1 3 4 5 6"),
 ("The inauguration was grand","शुभारंभ भव्य ढंग से हुआ","0 3 1-2 2 4 5 6"),
 ("The radius was measured","त्रिज्या नापी गई","0 2 1 3 4"),
 ("The lists were displayed","सूचियों पर चर्चा हुई","0 2-3 3 1 4 5"),
 ("The strong player led","सशक्त खिलाड़ी आगे रहा","0-1 1 1 3 4 2 5"),
 ("The foolish act was mocked","मूर्खतापूर्ण हरकत पर हँसी हुई","0 1 1-2 2 3 4 5 6 7"),
 ("Algebra uses symbols","बीजगणित संकेतों का विज्ञान है","0 2-3 3 1 4 5"),
 ("The Marxist wrote essays","मार्क्सवादी ने लेख लिखे","0-1 1 1 3 2 4 5"),
 ("The contradiction confused scholars","विरोधाभास विद्वानों को उलझाता है","0 2-3 3 1 4-5 5 6"),
 ("The rightist party protested","दक्षिणपंथी दल ने विरोध किया","0-1 1 1 3 2 4 5 6"),
 ("The deformity was corrected","विकृति शल्य चिकित्सा से ठीक हुई","0 3-4 4 1 2 5 6 7"),
 ("The editors met the author","संपादकों की बैठक लेखक से हुई","0 1-2 2 3 4 5 6"),
 ("The institutions celebrated the day","प्रतिष्ठानों में समारोह हुआ","0 1-2 2 3 4 5"),
 ("The herbs cured the ailment","जड़ीबूटियों से रोग दूर हुआ","0 2-3 3 1 4 5 6"),
 ("Accounting needs accuracy","लेखांकन सटीक तथ्य माँगता है","0 3-4 4 1 2 5"),
 ("The dolls adorned the shelf","गुडिया शैल्फ सजाती हैं","0 2-3 3 1 4 5 6"),
 ("The international summit concluded","अन्तरराष्ट्रीय सम्मेलन समाप्त हुआ","0 1 2 3 4 5"),
 ("To know oneself is wisdom","जानना स्वयं को ज्ञान है","0 3 4-5 5 1 6"),
 ("The redevelopment plan was drawn","पुनर्विकास की रूपरेखा बनी","0 1 1-2 2 3 4 5 6"),
 ("The merger was approved","संलयन का प्रस्ताव पारित हुआ","0 1-2 2 3 4 5 6"),
 ("The notes were melodious","स्वरों की धुन मधुर थी","0 1-2 2 3 4 5 6"),
 ("The begum donated jewels","बेगम ने आभूषण दान किए","0-1 1 1 4 2 5 3 6"),
 ("The projectile hit the target","प्रक्षेपित गोला निशाने पर लगा","0 1-2 2 1 5-6 6 3 4 7"),
 ("The estimates were revised","अनुमानों में संशोधन हुआ","0 1-2 2 3 4 5"),
 ("The theft was hushed","चुरा लिया गया माल चुपचाप","0 3 1 2 4-5 5 6"),
]
for e, h, a in V:
    add(e, h, a)

# ---------------- P. paana forms (thin row)
P = [
 ("Now it is hard to tolerate the heat","अब गर्मी झेल पाना कठिन है","3 4 5 0-1 2 6 7"),
 ("Everyone could not get food in the famine","अकाल में सबको भोजन नहीं मिल पाया","1 2 0 7 5 4-5 3-4 4"),
 ("He could not understand the nuance of the words","वह शब्दों की बारीकी समझ नहीं पाया","0 3 5 6 2 1 7 8"),
 ("The mother could not see her son again","माँ अपने बेटे को दोबारा नहीं देख पाई","0 1 3 3-4 2 5 6 7 8"),
 ("The farmer got the price of the grain in time","किसान को समय पर अनाज का दाम मिल पाया","0 1 3 4 5 6-7 6 8 9 10"),
 ("It is difficult to forget the past","अतीत को भूल पाना कठिन है","4-5 5 1 0-2 2 3"),
 ("Good books are rarely found now","अच्छी पुस्तकें अब दुर्लभ मिल पाती हैं","0-1 1-2 6 4-5 5 3 7"),
 ("The orphan could not get education","अनाथ को शिक्षा नहीं मिल पाई","0 1 5 3-4 4 2"),
 ("The letter could not reach in time","चिट्ठी समय पर पहुँच नहीं पाई","0 4 5 1-2 2 3 6"),
 ("Everyone does not get a true friend","सच्चा मित्र हर कोई नहीं पाता","0 1 6 3-5 5 2 4"),
 ("The beggar could not bear the insult","भिखारी अपमान झेल नहीं पाया","0 2 5 3-4 4 1 6"),
 ("The student could not pass the exam","छात्र परीक्षा पास नहीं कर पाया","0 5 1-2 2 6 3-4 4"),
 ("Slowly the pain became bearable","धीरे धीरे दर्द झेल पाना आसान हुआ","0 1 2-3 4 5-6 6 7 8"),
 ("The workers got their wages late","मज़दूरों को मज़दूरी देर से मिल पाई","0 1 5 6 3-4 4-5 5 2 7"),
 ("The patient could not sleep at night","रोगी रात में सो नहीं पाया","0 6 7 2-3 3 4-5 5 1"),
]
for e, h, a in P:
    add(e, h, a)

P2 = [
 ("Getting peace is rare in cities","शहरों में शांति पाना दुर्लभ है","1 2 0 4 5 3 6"),
 ("To find truth one must search","सत्य पाने के लिए खोज करनी पड़ती है","0 4-5 5-6 6 2-3 3 1 7"),
 ("He gets to eat fresh fruit daily","वह रोज़ ताज़े फल खाना पाता है","0 3 4-5 5 1 2 6 7"),
 ("Everyone does not get to study","हर कोई पढ़ना नहीं पाता","0 1-3 3 5-6 6 2 4"),
 ("The birds could not find grain in the drought","सूखे में पक्षी दाना नहीं पाते थे","1 2 0 6 4-5 5 3 7"),
 ("Where does one get nectar these days","आजकल अमृत कहाँ पाना संभव है","0 3 4-5 5 1 6 7"),
]
for e, h, a in P2:
    add(e, h, a)

print(f"total: {len(out)}")

# repair pass: any hand align that fails structural validation is replaced by
# the deterministic dictionary+position derivation from gen_align.py
import re as _re
import importlib.util as _ilu
_spec = _ilu.spec_from_file_location("ga", ROOT / "scripts" / "gen_align.py")
_ga = _ilu.module_from_spec(_spec); _spec.loader.exec_module(_ga)

def _ok(s):
    a = s.get("align")
    if not a:
        return False
    toks = a.split(); en = s["en"].split(); hi = s["hi"].split()
    if len(toks) != len(hi):
        return False
    return all(pp.isdigit() and int(pp) < len(en)
               for t in toks for pp in _re.split(r"[-,]", t))

for _s in out:
    if not _ok(_s):
        _s["align"] = _ga.derive(_s["en"], _s["hi"])
print(f"repaired to valid: {sum(_ok(s) for s in out)}/{len(out)}")

(ROOT / "data" / "phrases15.json").write_text(json.dumps(out, ensure_ascii=False, indent=2))
man = json.load(open(ROOT / "data" / "manifest.json"))
man["files"] = [f for f in man["files"] if f["file"] != "data/phrases15.json"] + [
    {"file": "data/phrases15.json", "count": len(out)}]
json.dump(man, open(ROOT / "data" / "manifest.json", "w"), ensure_ascii=False, indent=2)
print(f"wrote {len(out)} sentences")
