"""Generate data/phrases19.json — Batch 4 (missing1 tail, rank 5001+).
Skips (documented exceptions): फ़ाइलों दशाला अल्जेरिया मदन (proper/unclear),
एलर्जी रैंकों क्रेटर चिमनी कम्युनिस्टों फासीवादी (English-origin),
महा अनु (bound morphemes). Aligns hand-authored; derive fallback on failure.
"""
import json, re
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
N = [
    ("Fighting is his nature", "लड़ना उसका स्वभाव है", "0 3 2 2"),
    ("The king wore the sash", "राजा ने कमरबंद पहना", "1 2 4 2"),
    ("The granddaughter is dear", "नातिन सबको प्यारी है", "1 4 3 2"),
    ("The rust spoiled the iron", "रगड़ से लोहा खराब हुआ", "2 2 4 5 2 2"),
    ("The animals are kept in the shed", "पशुशाला में पशु रखे जाते हैं", "5 3 1 3 3 4"),
    ("The stairs go to the attic", "अट्टारी की सीढ़ियाँ ऊपर जाती हैं", "3 2 2 4 3 3"),
    ("The bus will go from the market", "बस बाज़ार से चलेगा", "1 3 3 3"),
    ("The disciple took initiation", "शिष्य ने दीक्षा ली", "1 2 3 2"),
    ("The feudal lord exploited the peasants", "सामंती शासकों ने किसानों का शोषण किया", "0 1 2 3 4 5 5 2"),
    ("The length of the cloth is short", "कपड़े की लम्बाई कम है", "2 2 3 4 2"),
    ("The insult of the teacher is a sin", "गुरु की अवज्ञा पाप है", "1 2 3 3 2"),
    ("The destinations of the journey are many", "यात्रा की मंजिलों में विविधता है", "2 2 3 5 5 2"),
    ("The stick of the guard is long", "चौकीदार की छड़ लंबी है", "1 2 3 4 2"),
    ("The wall got overgrown with moss", "दीवार पर काई पलीबढ़ी है", "1 3 4 5 2"),
    ("The principal of the school retired", "विद्यालय के कुलपिता सेवानिवृत्त हुए", "3 2 3 5 4 2"),
    ("The effort of the students paid off", "छात्रों के प्रयत्न रंग लाए", "1 2 3 4 5 2"),
    ("The plan is coordinated", "योजना समन्वित है", "1 2 2"),
    ("The police inspected the scene of crime", "पुलिस ने घटनास्थल देखा", "1 2 5 2"),
    ("The culture of the valley is unified", "घाटी की संस्कृति एकात्मक है", "2 2 3 4 2"),
    ("Genetics explains the traits", "आनुवंशिकी लक्षण समझाती है", "0 2 2 2 2"),
    ("Please consider this point", "इस बिंदु पर गौर कीजिए", "2 2 3 4 4"),
    ("The parameters of design were fixed", "रूप के मापदंडों की गणना हुई", "3 2 3 4 5 2"),
    ("The strings lost the tune", "तारों ने सुर हारे", "1 3 3 3"),
    ("The tours of the saint are famous", "संत के दौरों की चर्चा है", "1 2 3 4 4 2"),
    ("The foreigners liked the food", "विदेशियों को भोजन भाया", "1 2 3 3"),
    ("The terms of office were fixed", "कार्यकालों की अवधि तय हुई", "2 2 3 4 2 2"),
    ("The anti aircraft guns roared", "विमानरोधी तोपों ने गरजा", "0-1 1 2 3"),
    ("The fifth period is of sport", "पाँचवीं काल में खेल होता है", "0 1 3 3 4 4"),
    ("The sage meditated", "मुनि तपस्या करते थे", "1 2 2 2 2"),
    ("The travelers will return in the evening", "यात्री शाम को लौटेंगे", "1 4 4 2 2"),
    ("Abundance came with the rains", "बारिश से प्रचुरता आई", "2 2 1 3 2"),
    ("The scholar assimilated the ideas", "विद्वान ने विचार आत्मसात किए", "1 2 3 4 2 2"),
    ("The angels are depicted in the panel", "स्वर्गदूतों की आकृतियाँ बनी हैं", "3 2 2 3 2 2"),
    ("The races of horses are held yearly", "घोड़ों की दौड़ों में भीड़ लगती है", "2 2 3 4 5 4 2 2"),
    ("The dictionary is bilingual", "शब्दकोश द्विभाषी है", "1 2 2"),
    ("The paper is about grammar", "यह लेख व्याकरण सम्बन्धी है", "1 1 3 4 2"),
    ("The arguments of lawyers went long", "वकीलों के तर्कों पर बहस चली", "1 2 3 4 5 4 2"),
    ("The victory was undisputed", "जीत निर्विवाद रही", "1 3 2"),
    ("The village got electricity", "गाँव में विद्युतीकरण हुआ", "1 3 4 2"),
    ("The certificate was issued", "प्रमाणपत्र जारी हुआ", "1 3 2"),
    ("The patriots remember the martyrs", "देशभक्तों को शहीद याद हैं", "1 2 3 5 2"),
    ("The processes of law are slow", "कानून की प्रक्रियाएँ लंबी चलती हैं", "2 2 3 4 4 4 2"),
    ("The directory lists the officers", "निर्देशिका में अधिकारियों के नाम हैं", "1 3 4 2 5 2"),
    ("The minister looked after the treasury", "दीवान ने कोष संभाला", "1 2 3 2"),
    ("The trustees met the donors", "न्यासियों ने दानियों से भेंट की", "1 2 3 4 5 2 2"),
    ("The painter is famous", "चित्रकार प्रख्यात है", "1 2 2"),
    ("The foundation stone was laid", "आधारशिला रखी गई", "1 3 3 3"),
    ("Diving needs practice", "गोताखोरी में अभ्यास चाहिए", "1 3 4 3 2"),
    ("The steward managed the estate", "कारभारी ने जागीर संभाली", "1 2 3 2"),
    ("The designs of the temple are old", "मंदिर के रूपांकन प्राचीन हैं", "1 2 3 4 2"),
    ("The achievements of the students grew", "छात्रों की उपलब्धियाँ बढ़ीं", "1 2 3 4 4"),
    ("The coding of data was changed", "आँकड़ों का संकेतन बदला", "1 2 3 3 3"),
    ("The aggression of the army increased", "सेना की आक्रामकता बढ़ी", "1 2 3 4 4"),
    ("The racism is condemnable", "रंगभेद निंदनीय है", "0 2 2"),
    ("The train will go at night", "रेलगाड़ी रात को जायेगी", "1 4 4 3"),
    ("The goods were imported", "माल आयातित था", "2 3 2"),
    ("The rectum is part of the gut", "गुदा आँत का भाग है", "1 4 2 2 2"),
    ("The fort is fortified strongly", "किला किलेबंदी से मज़बूत है", "1 1 3 4 4 2"),
    ("The distillation of water purifies it", "पानी के आसवन से शुद्धता आती है", "2 2 3 2 5 4 3 3"),
    ("The accused were produced in the court", "आरोपियों को न्यायालय में पेश किया गया", "1 2 6 4 3 2 3"),
    ("The sequences of genes were mapped", "जीन के अनुक्रमों का नक्शा बना", "1 2 3 4 5 3"),
    ("The obstruction in the road was removed", "रास्ते का व्यवधान दूर हुआ", "1 2 3 5 3 2"),
    ("The forerunners of the movement are remembered", "आंदोलन के अग्रदूतों को याद किया जाता है", "1 2 3 5 5 2 4 2"),
    ("A flood came in the river", "नदी में बाढ़ आयी", "2 3 0 3"),
    ("The images of gods are bright", "देवताओं की छवियाँ उज्ज्वल हैं", "1 2 3 4 2"),
    ("The editions of the book sold out", "पुस्तक की आवृत्तियों की माँग रही", "2 2 3 4 5 4 2"),
    ("The breakup of the party happened", "दल का विखंडन हुआ", "1 2 3 2"),
    ("The men were present", "आदमियों की उपस्थिति थी", "1 2 3 2"),
    ("The child came eighth", "बच्चा आठवां आया", "1 2 2"),
    ("Smoking is prohibited here", "यहाँ धूम्रपान निषिद्ध है", "3 3 4 2"),
    ("Pneumonia weakened the patient", "निमोनिया ने रोगी कमज़ोर किया", "1 2 3 4 4 2"),
    ("The princes studied together", "राजकुमारों ने साथ विद्या पढ़ी", "1 2 5 4 4 2"),
    ("The matter is trivial", "बात तुच्छ है", "1 2 2"),
    ("The holders of permits were listed", "अनुमतियों के धारकों की सूची बनी", "2 2 3 4 4 5 2"),
    ("The butcher opened the shop", "कसाई ने दुकान खोली", "1 2 4 2"),
    ("The embankment was strengthened", "तटबंध प्रबलित किया गया", "1 3 2 3"),
    ("The intellectuals wrote letters", "बुद्धिजीवियों ने पत्र लिखे", "1 2 3 2"),
    ("The coffin was carried by four men", "ताबूत चार आदमियों ने उठाया", "1 4 3 3 2"),
    ("The minerals of the hills are many", "पहाड़ियों में खनिजों की भरमार है", "4 3 4 2 5 2"),
    ("The wrestlers came to the arena", "पहलवानों अखाड़े में आए", "1 5 4 3 2"),
    ("The investigators found the clue", "जांचकर्ताओं को सुराग मिला", "1 2 4 3 3"),
    ("The risks of business are many", "व्यापार के जोखिमों की सूची लंबी है", "1 2 3 4 5 6 4 2"),
    ("The sects of the town are many", "नगर के संप्रदायों में भेद हैं", "1 2 3 4 5 2"),
    ("The sketch shows the layout", "रेखाचित्र में नक्शा साफ़ है", "1 3 4 5 2 2"),
    ("The predecessors of the family are honored", "परिवार के पूर्ववर्तियों का सम्मान होता है", "1 2 3 4 4 2 4 2"),
    ("The priest chanted the hymns", "उपाध्याय ने मंत्र पढ़े", "1 2 3 2"),
    ("The manuscript is from the eighteenth era", "पांडुलिपि अठारहवीं सदी की है", "1 2 3 4 2 2"),
    ("The election was uncontested", "चुनाव निर्विरोध हुआ", "1 3 2"),
    ("Colonialism ruined the economy", "उपनिवेशवाद ने अर्थव्यवस्था बर्बाद की", "1 2 3 4 4 2"),
    ("The mutants differ from parents", "उत्परिवर्ती जनकों से भिन्न होते हैं", "1 4 3 5 4 4 2"),
    ("The destruction left the village ruined", "तबाही ने गाँव उजाड़ दिया", "1 2 3 4 4 2"),
    ("The anarchist spoke against the state", "अराजकतावादी ने राज्य के विरुद्ध बोला", "1 2 3 4 4 5 2"),
    ("The managerial skills were praised", "प्रबंधकीय कौशल की प्रशंसा हुई", "0 1 2 4 2 2"),
    ("The battalion changed sides", "पलटन ने पक्ष बदला", "1 2 3 3 3"),
    ("The work reached completeness", "कार्य की पूर्णता हुई", "1 2 3 2"),
    ("The body was incorporated", "संस्था निगमित हुई", "1 3 2"),
    ("The point is clear", "बिन्दु स्पष्ट है", "1 2 2"),
    ("The needs of the poor are many", "गरीबों की आवश्यकताएँ अनेक हैं", "1 2 3 4 2"),
    ("The lyric poem is melodious", "गीतात्मक कविता मधुर है", "0 1 3 2"),
    ("Diplomacy solved the crisis", "कूटनीति ने संकट सुलझाया", "1 2 3 2 2"),
    ("Redistribution of land was promised", "भूमि के पुनर्वितरण का वादा हुआ", "2 2 3 4 4 2 2"),
    ("Taxation burdens the middle class", "कराधान से मध्यवर्ग पर बोझ आता है", "1 3 2 4 5 4 4 2"),
    ("The two poems are comparable", "दोनों कविताएँ तुलनीय हैं", "0-1 1 2 2"),
    ("The mathematician solved the puzzle", "गणितशास्त्री ने पहेली सुलझाई", "1 2 3 2 2"),
    ("The rituals of the festival continued", "त्योहार के अनुष्ठानों की श्रृंखला चली", "1 2 3 4 5 5 2"),
    ("The policy matters were discussed", "नीतिगत बिंदुओं पर चर्चा हुई", "0 1 4 4 5 2"),
    ("The subgroup differs from the group", "उपसमूह समूह से भिन्न है", "1 3 3 5 2"),
    ("The mines were inspected", "खानों की जाँच हुई", "1 2 3 2"),
    ("The smoke is emitted from the chimney", "धुआँ निकासी से उत्सर्जित होता है", "1 6 2 4 4 4 4 2"),
    ("The exam has many options", "परीक्षा में बहुविकल्पी प्रश्न होते हैं", "4 3 0 1 5 5 2"),
    ("The echo resounded in the valley", "घाटी में शोर प्रतिध्वनित हुआ", "1 3 3 5 2"),
    ("The news of the storm spread", "तूफ़ान के समाचारों ने दुनिया जगाई", "2 2 3 4 5 4 2"),
    ("The germs cause disease", "कीटाणु रोगजनक होते हैं", "1 2 4 2"),
    ("The doctor advised rest", "चिकित्सक ने आराम अनुशंसित किया", "1 2 3 4 2 2"),
    ("The batsmen scored runs", "बल्लेबाजों ने रन बनाए", "1 2 4 3 3 3"),
    ("The child calls papa", "बच्चा पापा पुकारता है", "1 2 2 2 2"),
    ("He came seventeenth in line", "वह कतार में सत्रहवीं पर आया", "1 3 3 4 4 5 2"),
    ("The margin of victory was thin", "जीत का मार्जिन कम रहा", "1 2 3 4 4 4"),
    ("The priorities of the family changed", "परिवार की प्राथमिकताओं में बदलाव आया", "1 2 3 5 6 4 2"),
    ("The subset has fewer members", "उपसमुच्चय में सदस्य कम होते हैं", "1 3 3 4 4 4 2"),
    ("The study is based on experience", "अध्ययन अनुभवजन्य आधारों पर टिका है", "1 0 2 3 4 5 2 2"),
    ("The fair was a unique experience", "मेला अनुठा अनुभव रहा", "1 2 3 3 2"),
    ("The talks reached a deadlock", "बातचीत गतिरोध पर पहुंची", "0 1 3 2 2"),
    ("The circumstances worsened", "परिस्थिति बिगड़ गई", "1 2 3 3"),
    ("The writer stayed anonymous", "लेखक गुमनाम रहा", "1 3 2"),
    ("The two matters are unrelated", "दोनों बातें असंबंधित हैं", "0-1 1 2 2"),
    ("Put the flag on the roof", "छत पर झंडा डालें", "3 3 1 3 3"),
    ("The tsunami hit the coast", "सुनामी ने तट से टक्कर ली", "1 2 5 3 4 2"),
    ("The supplier sent the goods", "आपूर्तिकर्ता ने माल भेजा", "1 2 3 2"),
    ("Calculus is a branch of mathematics", "कलन गणित की एक शाखा है", "1 2 2 3 5 2"),
    ("The dream of the poet took shape", "कवि का सपना साकार हुआ", "1 2 3 4 2 2"),
    ("The noun is in singular", "संज्ञा एकवचन में है", "1 2 3 2"),
    ("The exposition of the theory is long", "सिद्धांत का प्रतिपादन लंबा है", "1 2 3 4 2"),
    ("The papers lay disordered", "काग़ज़ अव्यवस्थित पड़े थे", "1 2 3 3 2"),
    ("The stain of sin is deep", "पाप का दाग गहरा होता है", "1 2 1 3 4 4 2"),
    ("The guard of the area was alert", "क्षेत्ररक्षण में सैनिक सतर्क रहे", "1 3 4 5 2 2"),
    ("The new schemes were announced", "नई योजनाएँ घोषित हुईं", "1 1 3 2 2"),
    ("Knowing the truth he stayed quiet", "सच जानकर भी वह चुप रहा", "1 2 3 3 1 5 3"),
    ("The acceleration of the vehicle increased", "गाड़ी का त्वरण बढ़ा", "1 2 3 4 4"),
    ("The mother applies vermilion", "मौली माँग में लगाती है", "0 1 4 4 3 2"),
    ("The situations changed after rains", "बारिश के बाद स्थितियाँ बदलीं", "2 2 3 4 5 4 4"),
    ("The snow began melting", "बर्फ़ पिघलने लगी", "1 3 3 2"),
    ("The shop ran into loss", "दुकान घाटे में चली", "1 2 3 3 2"),
    ("The deception is widespread", "छल सर्वव्यापी है", "1 3 2"),
    ("The court ordered to stop the work", "न्यायालय ने काम ठहराने को कहा", "1 2 3 4 2 2 2"),
    ("The children played heartily", "बच्चों ने जमकर खेला", "1 2 3 2 2"),
    ("The essays of students were read", "छात्रों के निबंधों की चर्चा हुई", "1 2 3 4 5 2 2"),
    ("The desired book was found", "इच्छित पुस्तक मिल गई", "1 2 3 3 3"),
    ("Humidity is high in the rainy season", "सावन में आर्द्रता अधिक रहती है", "2 3 1 4 4 4 2"),
    ("The woman of the house decided", "नारी ने निर्णय लिया", "1 2 3 2 2"),
    ("The motif of the carpet is old", "क़ालीन का रूपांकन पुराना है", "1 2 3 4 2 2"),
    ("The comet appears rarely", "धूमकेतु कभी कभी दिखता है", "1 3 3 3 3 2"),
    ("The students will be able to come", "छात्र आ सकेंगे", "1 0 3"),
    ("The collection is selective", "संग्रह चयनात्मक है", "1 2 2"),
    ("The tribals got land rights", "आदिवासियों को भूमि का अधिकार मिला", "1 2 3 2 4 5 3 3"),
    ("The actor appeared as a king", "अभिनेता बतौर राजा नज़र आया", "1 2 3 5 4 3 2"),
    ("The father blessed the son", "जनक ने सुपुत्र को आशीर्वाद दिया", "1 2 3 4 5 2 2"),
    ("The word meanings are given", "शब्दार्थ नीचे दिए हैं", "0 4 3 3 2"),
    ("The request was submitted", "निवेदन पेश हुआ", "1 3 2"),
    ("Care was taken of cleanliness", "सफ़ाई का तत्वावधान रहा", "1 2 3 4 2 2"),
    ("The cellular structure is complex", "कोशिकीय ढाँचा जटिल होता है", "0 1 2 3 4 4 2"),
    ("The knowledge of self is true", "स्व का ज्ञान सच्चा है", "1 2 1 3 2 2"),
    ("The enterprise of the youth grew", "युवाओं का उपक्रम फैला", "1 2 3 4 3 3"),
    ("Rumors spread in the village", "गाँव में अफवाहें फैलीं", "2 3 1 2 2"),
    ("The hammer hit the nail", "हथौड़े ने कील मारी", "1 2 3 3 3"),
    ("The childbirth happened at home", "प्रसूति घर पर हुई", "1 2 3 2 2"),
    ("The hawks circled the field", "बाज़ों ने खेत का चक्कर लगाया", "1 2 3 2 3 3 2"),
    ("The armies stood face to face", "सेनाएँ आमनेसामने खड़ी हुईं", "1 4 4 2 2 2"),
    ("The circumstances are favorable", "परिस्थितियाँ अनुकूल हैं", "1 2 2"),
    ("The attitudes of people differ", "लोगों के रवैये अलग होते हैं", "1 2 3 4 4 4 2"),
    ("Beef is banned in states", "गोमांस कई राज्यों में वर्जित है", "1 3 3 4 5 4 2"),
    ("The location of the fort is high", "किले की अवस्थिति ऊँचाई पर है", "1 2 3 4 5 3 2"),
    ("The tunnels go under the mountain", "सुरंगों से रास्ता पहाड़ के नीचे जाता है", "3 3 1 4 2 5 5 4 4 4 2"),
    ("Tree plantation grew the greenery", "वृक्षारोपण से हरियाली बढ़ी", "1 3 3 3 4"),
    ("The wedding rites are elaborate", "वैवाहिक रीतियाँ भव्य होती हैं", "0 1 2 3 4 2"),
    ("The murderer was sentenced", "हत्यारा को सज़ा मिली", "1 3 2 3 3"),
    ("The planning of city improved", "नगर का नियोजन सुधरा", "1 2 3 4 4"),
    ("The employers met the union", "नियोक्ताओं ने संघ से बात की", "1 2 3 4 5 5 2"),
    ("The thermal plant produces power", "तापीय संयंत्र से बिजली बनती है", "0 1 2 3 4 3 3 2"),
    ("The firearms were seized", "आग्नेयास्त्र बरामद हुए", "1 3 3 2"),
    ("The sperm meets the egg", "शुक्राणु अंडे से मिलता है", "1 4 3 3 3 2"),
    ("The thinking of youth is changing", "युवाओं का चिंतन बदल रहा है", "1 2 3 5 4 4 2"),
    ("The propulsion of air gives motion", "वायु का प्रणोदन गति देता है", "1 2 3 4 4 4 2"),
    ("The frog took a leap", "मेंढक ने छलांग लगाई", "1 2 3 3 3"),
    ("The pull of the cart tired the bullocks", "गाड़ी का खिंचाव बैलों को पस्त करता है", "1 2 3 3 4 5 5 4 4 2"),
    ("The magazine is published quarterly", "पत्रिका आवधिक रूप से निकलती है", "1 0 2 2 2 4 4 2"),
    ("The expectation of good rain stayed", "अच्छी बारिश की प्रत्याशा बनी रही", "1 1 2 3 4 4 2 2"),
    ("The comments of readers improved the text", "पाठकों की टिप्पणियां लेखन सुधारती हैं", "1 2 3 4 5 5 2 2"),
    ("Keep the two piles separate", "दोनों ढेर पृथक रखें", "0-1 1 2 3 3 3"),
    ("The biologist studies cells", "जीवविज्ञानी कोशिकाएँ देखता है", "1 2 3 2 2 2"),
    ("The boatwoman rows the boat", "नाविक नाव निभाती है", "1 1 4 2 2 2"),
    ("The transverse beam holds the roof", "अनुप्रस्थ तीली छत को सहारा देती है", "0 1 1 3 2 4 5 5 2 2"),
    ("Sugar is soluble in water", "चीनी पानी में घुलनशील है", "1 4 3 2 2 2"),
    ("A poet was born in the village", "गाँव में कवि जन्मी", "2 3 0 3 3"),
    ("The length of the room is more", "कमरे की दैर्ध्य अधिक है", "2 2 3 4 2"),
    ("The trends of market changed", "बाज़ार के रुझानों में बदलाव आया", "1 2 3 5 6 4 2"),
    ("The writing is stylized", "लेखन शैलीबद्ध है", "1 2 2"),
    ("The saving of grain helps in famine", "अनाज के संचय से अकाल में काम आता है", "2 2 3 3 4 4 3 5 5 5 2"),
    ("The climate here is temperate", "यहाँ की जलवायु समशीतोष्ण है", "2 2 1 3 2 2"),
    ("The jagirdar collected the rent", "जागीरदार ने लगान वसूला", "1 2 4 3 3 3"),
    ("The chess moves were clever", "शतरंज की चालों में चतुराई थी", "1 2 2 3 4 5 2 2"),
    ("The virus spreads fast", "विषाणु तेज़ी से फैलता है", "1 2 3 4 3 3 2"),
    ("Grandmother tells stories", "दादी कहानियां सुनाती हैं", "0 2 3 2 2"),
    ("The rich of city came", "शहर के रईसों ने दौरा किया", "1 2 3 4 5 5 2"),
    ("The orchards bloomed in spring", "बसंत में बागानों में फूल आए", "4 3 3 3 4 2 2"),
    ("The family got divided", "परिवार खंडित हो गया", "1 2 3 3 3"),
    ("The study is quantitative", "अध्ययन मात्रात्मक है", "1 2 2"),
    ("The racist remark caused anger", "नस्लवादी टिप्पणी से रोष फैला", "0 1 2 3 4 5 3 2"),
    ("Air is compressed in the pump", "पंप में हवा संपीड़ित होती है", "2 3 3 1 4 4 4 2"),
    ("The vaccine is preventive", "टीका निवारक है", "1 2 2"),
    ("Capitalism grew with trade", "पूँजीवाद व्यापार के साथ बढ़ा", "1 3 2 3 3 3 3"),
    ("The inverse of the sum is taken", "योग का व्युत्क्रम निकाला जाता है", "1 2 3 4 5 5 2 2"),
    ("The airforce guarded the sky", "वायुसेना ने आकाश संभाला", "1 2 4 2"),
    ("The poetic language charms", "काव्यात्मक भाषा मोह लेती है", "0 1 3 3 2 2 2"),
    ("This sacrifice is the greatest", "यह त्याग महानतम है", "1 1 2 3 2"),
    ("The atheist questioned customs", "नास्तिक ने रीति पर प्रश्न उठाया", "1 2 4 3 5 2 3 3"),
    ("The verses are set to rhythm", "छंदों में लय बसती है", "1 3 3 4 2 2"),
    ("The intestine digests food", "आंत भोजन पचाती है", "1 3 4 2 2"),
    ("The rites were performed", "कृत्य संपन्न हुए", "1 3 2"),
    ("The dismissal of employees was ordered", "कर्मचारियों की बर्खास्तगी हुई", "1 2 3 4 2 2"),
    ("The emperors built the temples", "सम्राटों ने मंदिर बनवाए", "1 2 3 3 3 3"),
    ("The two designs are similar", "दोनों नमूने समरूप हैं", "0-1 1 2 2"),
    ("The fort is medieval", "किला मध्यकालीन है", "1 2 2"),
    ("He studies in eleventh grade", "वह ग्यारहवें में पढ़ता है", "1 2 3 4 4 2"),
    ("The youth are unemployed", "युवा बेरोजगार हैं", "1 2 2"),
    ("The maid swept the house", "नौकरानी ने घर बुहारा", "1 2 3 3 3"),
    ("The sanctity of the temple remains", "मंदिर की पवित्रता बनी रहती है", "1 2 3 4 2 4 4 2"),
    ("The archaeologist found coins", "पुरातत्वविद् ने सिक्के खोजे", "1 2 4 3 3"),
    ("The heroine danced well", "नायिका ने अच्छा नृत्य किया", "1 2 3 4 5 2"),
    ("The frenzy of crowd increased", "भीड़ का उन्माद बढ़ा", "1 2 3 4 4"),
    ("The arbitrary rules annoyed all", "मनमाने नियमों से सब नाराज़ हुए", "0 1 3 3 4 5 3 2 2"),
    ("The poetry of the saint is simple", "संत का पद्य सरल है", "1 2 3 2 2 2"),
    ("Rumors were quashed", "अफवाहों का खंडन हुआ", "1 2 3 2 2"),
    ("The vertebral column supports the body", "कशेरुकी धड़ को सहारा देती है", "1 2 2 3 4 5 5 5 2 2"),
    ("The tenants formed a union", "किरायेदारों ने संघ बनाया", "1 2 3 3 2 2"),
]
T = [
    ("The woodcutter has cut the wood", "लकड़हारे ने लकड़ी काटी है", "1 2 4 3 2 2"),
    ("The boys have swum the river", "लड़कों ने नदी पार की है", "1 2 4 5 3 2 2"),
    ("The girls had woven the mats", "लड़कियों ने चटाई बुनी थी", "1 2 5 3 2 2"),
    ("The shepherd had counted the sheep", "चरवाहा ने भेड़ें गिनी थीं", "1 2 5 3 2 2"),
    ("The cobbler had mended the shoes", "मोची ने जूते सिले थे", "1 2 5 3 2 2"),
    ("The women will be husking grain", "औरतें अनाज कूट रही होंगी", "1 3 3 3 2 2"),
    ("The ox will be drawing water", "बैल पानी खींच रहा होगा", "1 3 3 3 2 2"),
    ("The birds will have built nests", "पक्षियों ने घोंसले बना लिए होंगे", "1 2 5 3 3 3 2"),
    ("The farmer will have fed the cattle", "किसान ने पशु चारा दे दिया होगा", "1 2 5 3 3 3 3 2"),
]
out = []
def add(en, hi, align):
    out.append({"id": f"m{len(out)+1:03d}", "en": en, "hi": hi, "align": align})
for e, h, a in N:
    add(e, h, a)
for e, h, a in T:
    add(e, h, a)
import importlib.util
spec = importlib.util.spec_from_file_location("ga", ROOT / "scripts" / "gen_align.py")
ga = importlib.util.module_from_spec(spec); spec.loader.exec_module(ga)
def ok(s):
    a = s.get("align")
    if not a: return False
    toks = a.split(); en = s["en"].split(); hi = s["hi"].split()
    if len(toks) != len(hi): return False
    return all(pp.isdigit() and int(pp) < len(en) for t in toks for pp in re.split(r"[-,]", t))
bad = []
for s in out:
    if not ok(s):
        bad.append(s["id"]); s["align"] = ga.derive(s["en"], s["hi"])
print(f"valid: {sum(ok(s) for s in out)}/{len(out)} (derived: {' '.join(bad) or 'none'})")
(ROOT / "data" / "phrases19.json").write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n")
man = json.load(open(ROOT / "data" / "manifest.json"))
man["files"] = [f for f in man["files"] if f["file"] != "data/phrases19.json"] + [
    {"file": "data/phrases19.json", "count": len(out)}]
json.dump(man, open(ROOT / "data" / "manifest.json", "w"), ensure_ascii=False, indent=2)
print(f"wrote {len(out)} -> data/phrases19.json")
